### PR TITLE
Movement follow player

### LINKED ISSUE #9354: #7908 broke MOVEMENT_TYPE_COPY_PLAYER⁩
### Description

As per comment on #7908 
https://github.com/rh-hideout/pokeemerald-expansion/pull/7908#issuecomment-3940180633

### Reproduction Steps

_No response_

### Images / Video

_No response_

### Version

1.14.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
I created special COPY_MOVE for when you are colliding so that behaviors can be different for copy object events and follow object events.

I also had to find a way to avoid the double move for copy object event while you are colliding.
Because colliding trigger a walk in place slow animation (unless you are on bike) I made sure, the copy npc move slowly when you are colliding. I also had to reduce the walk in place slow animation duration by 1 frame.

## Media

https://github.com/user-attachments/assets/79c6da68-cbcf-4d52-9c14-a8b9fbf61f26

## Issue(s) that this PR fixes
Fixes #9354

## Discord contact info
Jamie

### CODE REVIEW

File: include/constants/event_object_movement.h [hunk 1]
```diff
@@ -365,16 +365,16 @@
...
+#define COPY_MOVE_FACE                  1
+#define COPY_MOVE_WALK                  2
+#define COPY_MOVE_WALK_FAST             3
+#define COPY_MOVE_WALK_FASTER           4
+#define COPY_MOVE_SLIDE                 5
+#define COPY_MOVE_JUMP_IN_PLACE         6
+#define COPY_MOVE_JUMP                  7
+#define COPY_MOVE_JUMP2                 8
+#define COPY_MOVE_WALK_COLLIDE          9
+#define COPY_MOVE_WALK_COLLIDE_SLOW    10
```
Comment (AlexOn1ine) [inline include/constants/event_object_movement.h]: I would make this an enum

Comment (FosterProgramming) [reply include/constants/event_object_movement.h]: enum added

**Review by AlexOn1ine — APPROVED** [review]

**Comment by AlexOn1ine** [comment]
All of those functions in the function table returning `TRUE` is probably just a vanilla quirk?
