### PR TITLE
Fixed Zygarde Complete disappearing upon catch

### LINKED ISSUE #7974: Catching a Zygarde Complete doesn't give you any mon
### Description

Currently, catching a Zygarde Complete will give you nothing, since the form change table is set up with no species data for the complete form. So it'll transform into `SPECIES_NONE` when caught.

It's not trivially fixable due to Zygarde complete having 2 precursor forms it can revert to. The fix is probably to make a Complete Zygarde species for each of the precursors.

### Reproduction Steps

1. Encounter a wild Zygarde with Power Construct
2. Damage the Zygarde to below half HP to activate Power Construct
3. Catch Zygarde Complete

### Images / Video

https://github.com/user-attachments/assets/78e1a9a1-15d7-4728-9ae7-60b2a841b237

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Media
mGBA_0qJCFtnzGJ

## Issue(s) that this PR fixes
Fixes #7974 

## Discord contact info
AsparagusEduardo

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -10161,17 +10161,22 @@ bool32 TryBattleFormChange(u32 battler, enum FormChanges method)
...
-
-        // Unlike Megas, Primal Reversion isn't canceled on fainting.
-        else if (IsBattlerPrimalReverted(battler) && (method == FORM_CHANGE_END_BATTLE))
-            restoreSpecies = TRUE;
-
-        // Gigantamax Pokemon have their forms reverted after fainting, switching, or ending the battle.
-        else if (IsGigantamaxed(battler) && (method == FORM_CHANGE_FAINT || method == FORM_CHANGE_BATTLE_SWITCH || method == FORM_CHANGE_END_BATTLE))
+        switch (method)
+        {
+        case FORM_CHANGE_END_BATTLE:
```
Comment (AlexOn1ine) [inline src/battle_util.c:10166]: Should Mimikyu revert back after a battle ends?

Comment (AsparagusEduardo) [reply src/battle_util.c:10166]: Yes, Disguise resets at the end of every battle in cartridge.
