### PR TITLE
Fix AI hazard move handling, minor AI tweaks

### LINKED ISSUE #5763: Quick Adjustment to AI_ShouldSetUpHazards
if (aiData->abilities[battlerDef] == ABILITY_MAGIC_BOUNCE
     || CountUsablePartyMons(battlerDef) == 0
     || (AI_DATA->speedStats[battlerAtk] > AI_DATA->speedStats[battlerDef] && HasMoveWithAdditionalEffect(battlerDef, MOVE_EFFECT_RAPID_SPIN))
     || HasMoveEffect(battlerDef, EFFECT_DEFOG)
     || HasMoveEffect(battlerDef, EFFECT_TIDY_UP))
        return FALSE;
Description:
Adds Tidy Up into the code for ShouldSetUpHazards code as well as making the AI check to see if it is slower than the player when setting hazards into Rapid Spin.
image
SShadowzLmao#3643

image
This just confirms that the partner is being targeted and changes the effect to good effect. Ideally should check if opponent has supereffective moves

### LINKED ISSUE #6126: All "errors" found by yours truly in src/battle_ai_util (no past issues are included here, to be updated)
Ping or DM me on discord to lmk when one or more of these have been PR'd so i can edit them out 
In case you're wondering about battle_ai_switch_items, that has already been looked through by me and battle_ai_main has been looked through and outside of the TODOs it is fine

Image
Steelsurge is not included in `IsHazardMoveEffect`

```
bool32 IsSemiInvulnerable(u32 battlerDef, u32 move)
{
    if (gBattleStruct->commandingDondozo & (1u << battlerDef))
        return TRUE;
    else if ((!gMovesInfo[move].damagesAirborne && gStatuses3[battlerDef] & STATUS3_ON_AIR)
            ||(!gMovesInfo[move].damagesUnderwater && gStatuses3[battlerDef] & STATUS3_UNDERWATER)
            ||(!gMovesInfo[move].damagesUnderground && gStatuses3[battlerDef] & STATUS3_UNDERGROUND)
            ||(gStatuses3[battlerDef] & STATUS3_PHANTOM_FORCE))
        return TRUE;
    else
        return FALSE;
}
```
Refactored IsSemiInvulnerable

Request: Change the ShouldSet[insert weather] functions to also check if a different weather is up and the opponent is using it
Also: Remove TYPE_STEEL and TYPE_GROUND from set sandstorm and TYPE_ICE from hail as they do not benefit from the weather

Why does HasThawingMove exist when you can just run CHECK_MOVE_FLAG(thawsUser)?

Make IsUngroundingEffect check for Skill Swap and Levitate on the opp

Image

Image

Added Sleep Talk in the sleep check in both functions

Image
Added a check for a special move if the user has quick feet (pointless to burn if it halves your damage, not worth speed), can be argued that in a double battle with support moves or just hazard moves the added code should be removed

```static const u16 sRecycleEncouragedItems[] =
{
    ITEM_CHESTO_BERRY,
    ITEM_LUM_BERRY,
    ITEM_STARF_BERRY,
    ITEM_SALAC_BERRY,
    ITEM_LIECHI_BERRY,
    ITEM_SITRUS_BERRY,
    ITEM_MICLE_BERRY,
    ITEM_CUSTAP_BERRY,
    ITEM_MENTAL_HERB,
    ITEM_FOCUS_SASH,
    ITEM_AGUAV_BERRY,
    ITEM_FIGY_BERRY,
    ITEM_IAPAPA_BERRY,
    ITEM_MAGO_BERRY,
    ITEM_WIKI_BERRY,
    ITEM_MENTAL_HERB,
    ITEM_POWER_HERB,
    ITEM_BERRY_JUICE,
    ITEM_WEAKNESS_POLICY,
    ITEM_BLUNDER_POLICY,
    ITEM_KEE_BERRY,
    ITEM_MARANGA_BERRY,
};
```
list expanded

Request: Have accuracy check if the user has any inaccurate moves in the image below

Image

For future reference: in the image below, only check for magic bounce
It has been changed to include magic coat

Image

Not tested, worth looking over: Added punching glove
```
s32 AI_WhichMoveBetter(u32 move1, u32 move2, u32 battlerAtk, u32 battlerDef, s32 noOfHitsToKo)
{
    bool32 effect1, effect2;
    u32 defAbility = AI_DATA->abilities[battlerDef];
    u32 atkAbility = AI_DATA->abilities[battlerAtk];

    // Check if physical moves hurt.
    if (AI_DATA->holdEffects[battlerAtk] != HOLD_EFFECT_PROTECTIVE_PADS && atkAbility != ABILITY_LONG_REACH
        && (AI_DATA->holdEffects[battlerDef] == HOLD_EFFECT_ROCKY_HELMET
        || defAbility == ABILITY_IRON_BARBS || defAbility == ABILITY_ROUGH_SKIN))
    { 
        if ((gMovesInfo[move1].makesContact && 
            (gMovesInfo[move2].punchingMove && AI_DATA->holdEffects[battlerAtk] == HOLD_EFFECT_PUNCHING_GLOVE))
            && !gMovesInfo[move2].makesContact)
            return -1;
        if ((gMovesInfo[move2].makesContact && 
            (gMovesInfo[move1].punchingMove && AI_DATA->holdEffects[battlerAtk] == HOLD_EFFECT_PUNCHING_GLOVE))
            && !gMovesInfo[move1].makesContact)
            return 1;
    }
```

ROM successfully compiles with all changes above
SShadowzLmao#3643

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
I went through everything in #6126 and added what I thought made sense.

Fixes:
- check all moves that can make hazards properly
- check all moves that can remove hazards properly
- `IsBattlerIncapacitated` considers Sleep Talk

Tweaks:
- Additional items added to `sRecycleEncouragedItems`
- Check for low accuracy move added when considering copying stat changes

This is to upcoming so I can rename `BLUNDER_POLICY_ACCURACY_THRESHOLD` to `LOW_ACCURACY_THRESHOLD` and reuse it.

## Issue(s) that this PR fixes
Closes #6126 
Closes #5763 

## **People who collaborated with me in this PR**
@ShadowzLmao2

## Feature(s) this PR does NOT handle:
Things I didn't think were good to add include:
- refactoring `IsSemiInvulnerable` (seems like unnecessary conflicts)
- Changing the ShouldSet[weather] functions to also check if a different weather is up and the opponent is using it (I don't fully understand what this means, we don't read the player's inputs)
- Make `IsUngroundingEffect` check for Skill Swap and Levitate on the opponent (this is just a move effect check function so it's inappropriate, it also isn't used anywhere atm to make changes there)

## **Discord contact info**
@Pawkkie

### CODE REVIEW

File: src/battle_ai_util.c [hunk 1]
```diff
@@ -4110,7 +4166,10 @@ bool32 AI_ShouldSetUpHazards(u32 battlerAtk, u32 battlerDef, struct AiLogicData
     if (aiData->abilities[battlerDef] == ABILITY_MAGIC_BOUNCE
      || CountUsablePartyMons(battlerDef) == 0
      || HasMoveEffect(battlerDef, EFFECT_RAPID_SPIN)
-     || HasMoveEffect(battlerDef, EFFECT_DEFOG))
+     || HasMoveEffect(battlerDef, EFFECT_TIDY_UP)
```
Comment (AlexOn1ine) [inline src/battle_ai_util.c:4169]: This wasn't blocking because it is a general issue but I think we should make a function `HasSideMoveEffect`. Otherwise in doubles the ai will not see this. Same goes for `SideHasMoveWithAdditionalEffect`
