### PR TITLE
Fix gba sprites trying load non existent female versions

### LINKED ISSUE #6242: Gender differences graphical issues when loading GBA-style sprites
### Description

`#if/#else`"s should do the trick.

Image
Image

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

860c2f6cbcc566cbd9890cb775e28bfba24f5ff5

### Discord contact info

AsparagusEduardo

### PR DESCRIPTION
**Pull request by FosterProgramming**
I used this script to the pokemon with problem then edited the pokemon data one by one with a replacement macro
```
import pathlib

def main():
    p = pathlib.Path("./graphics/pokemon")
    for x in sorted(p.iterdir()):
        if x.is_dir():
            images = x.iterdir()
            if (x / 'backf.png') in images and  (x / 'backf_gba.png') not in images:
                print(x)

if __name__ == "__main__":
    main()
```

## Issue(s) that this PR fixes
Fixes #6242

## Things to note in the release changelog:
- Fixes issues with pokemon getting gender differences in later gens when using gen3 sprite config 

## Discord contact info
Jamie

### CODE REVIEW

**Comment by Bassoonian** [comment]
I wonder if we couldn't just have ``P_GENDER_DIFFERENCES`` depend on the gen3 sprite config. Not that you should close this PR, I just think it's a discussion worth having on Discord before we decide how to approach this

**Comment by FosterProgramming** [comment]
> I wonder if we couldn't just have `P_GENDER_DIFFERENCES` depend on the gen3 sprite config. Not that you should close this PR, I just think it's a discussion worth having on Discord before we decide how to approach this

There are some mons in gen3 with gender differences but most of them were added later. If you check the files, there are a few gendered mons where I didn't add the P_GBA_STYLE_SPECIES_GFX tag

File: src/data/pokemon/species_info/gen_1_families.h [hunk 1]
```diff
@@ -201,10 +201,12 @@ const struct SpeciesInfo gSpeciesInfoGen1[] =
         .iconSprite = gMonIcon_Venusaur,
         .iconPalIndex = P_GBA_STYLE_SPECIES_ICONS ? 1 : 4,
 #if P_GENDER_DIFFERENCES
+#if !P_GBA_STYLE_SPECIES_GFX
```
Comment (AsparagusEduardo) [inline src/data/pokemon/species_info/gen_1_families.h]:
```suggestion
#if P_GENDER_DIFFERENCES && !P_GBA_STYLE_SPECIES_GFX
```

File: src/data/pokemon/species_info/gen_1_families.h [hunk 2]
```diff
@@ -201,10 +201,12 @@ const struct SpeciesInfo gSpeciesInfoGen1[] =
...
         .frontPicFemale = gMonFrontPic_VenusaurF,
         .frontPicSizeFemale = MON_COORDS_SIZE(64, 64),
         .backPicFemale = gMonBackPic_VenusaurF,
         .backPicSizeFemale = MON_COORDS_SIZE(64, 48),
+#endif
 #endif //P_GENDER_DIFFERENCES
```
Comment (AsparagusEduardo) [inline src/data/pokemon/species_info/gen_1_families.h]:
```suggestion
#endif //P_GENDER_DIFFERENCES && !P_GBA_STYLE_SPECIES_GFX
```

**Comment by FosterProgramming** [comment]
PR updated
