### PR TITLE
Fix duplicate Trick Room end message when used again

### LINKED ISSUE #9436: Trick Room potential errors
### Description

When using Trick Room while it is already active (to end it), the message "The twisted dimensions returned to normal!" appears twice.

### Reproduction Steps

See the video below.

### Images / Video

https://github.com/user-attachments/assets/2a7be3e8-db8f-45e6-bf2f-4fb7bf5169cd

### Version

1.15.0 (Latest release)

### Upcoming/master Version

master

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Issue(s) that this PR fixes
Fixes #9436

### CODE REVIEW

File: test/battle/move_effect/trick_room.c [hunk 1]
```diff
@@ -1,4 +1,28 @@
 #include "global.h"
 #include "test/battle.h"
 
-TO_DO_BATTLE_TEST("TODO: Write Trick Room (Move Effect) test titles")
+ASSUMPTIONS
```
Comment (Pawkkie) [inline test/battle/move_effect/trick_room.c:4]: Could you actually leave the `TO_DO_BATTLE_TEST("TODO: Write Trick Room (Move Effect) test titles")` comment? There are still gonna be a pile of Trick Room tests to write to check its basic functionality (ie. that it actually flips speeds etc.) which are not at all urgent and I'm not asking you to write them, but please leave that there so it gets flagged during project searches that those tests are still missing :)

File: test/battle/move_effect/trick_room.c [hunk 2]
```diff
@@ -1,4 +1,28 @@
...
+{
+    ASSUME(GetMoveEffect(MOVE_TRICK_ROOM) == EFFECT_TRICK_ROOM);
+}
+
+SINGLE_BATTLE_TEST("Trick Room doesn't print its ending message twice when used again")
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) { Speed(10); Moves(MOVE_TRICK_ROOM, MOVE_CELEBRATE); }
```
Comment (Pawkkie) [inline test/battle/move_effect/trick_room.c]: Also no need to explicitly define moves when not writing AI tests, so you can adjust it like so
```
PLAYER(SPECIES_WOBBUFFET) { Speed(10);  }
```
just to match the usual standard :)

**Comment by Cle-bit** [comment]
Done!
