### PR TITLE
[item, metronome] fix metronome damage multiplier

### LINKED ISSUE #3244: Held Item Metronome does not work as intended
### Description

The Held Item Metronome does not work as intended and instead seems to significantly lower damage output.
https://discord.com/channels/419213663107416084/774393519569502268/1143185746761617590

### Version

1.5.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

bassoonian

### PR DESCRIPTION
**Pull request by SBird1337**
Fixes metronome reducing damage instead of increasing it; Regression introduced by #3196 

## Description
Also adds ~~a test~~ tests for metronome. 2 of them are `KNOWN_FAILING` and have been assigned issues respectively.

## Issue(s) that this PR fixes
Fixes #3244 

## **Discord contact info**
karathan

### CODE REVIEW

File: test/battle/hold_effect/metronome.c [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+const uq4_12_t MetronomeMultipliers[] = {
+    UQ_4_12(1.2),
+    UQ_4_12(1.4),
+    UQ_4_12(1.6),
+    UQ_4_12(1.8),
+    UQ_4_12(2.0)
+};
+
+SINGLE_BATTLE_TEST("Metronome gradually boosts power by 20%")
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/metronome.c:19]:
```suggestion
SINGLE_BATTLE_TEST("Metronome Item gradually boosts power of consecutively used moves by 20%")
```

File: test/battle/hold_effect/metronome.c [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+        for (j = 0; j < METRONOME_TURNS; ++j) {
+            ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, player);
+            HP_BAR(opponent, captureDamage: &damage[j]);
+        }
+    } THEN {
+        for (j = 1; j < METRONOME_TURNS; ++j) {
+            EXPECT_MUL_EQ(damage[0], MetronomeMultipliers[j-1], damage[j]);
+        }
+    }
+}
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/metronome.c:40]:
```suggestion
}

TO_DO_BATTLE_TEST("Metronome Item's boost is reset if the attacker uses a different move")
TO_DO_BATTLE_TEST("Metronome Item's boost is reset if the move fails")
TO_DO_BATTLE_TEST("Metronome Item's boost maxes at 100%")
TO_DO_BATTLE_TEST("Metronome Item doesn't increase damage per hit of multi-hit moves")
TO_DO_BATTLE_TEST("Metronome Item counts called moves instead of the calling move")
TO_DO_BATTLE_TEST("Metronome Item counts charging turn of moves for its attacking turn")
```

File: test/battle/hold_effect/metronome.c [hunk 3]
```diff
@@ -0,0 +1,40 @@
+#include "global.h"
+#include "test/battle.h"
+
+#define METRONOME_TURNS 6
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/metronome.c:4]: I would use an `ARRAY_COUNT` of `MetronomeMultipliers`

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: test/battle/hold_effect/metronome.c (hunk 3 above)
Comment (SBird1337) [reply test/battle/hold_effect/metronome.c:4]: it's a bit weird, because that array actually has one less entry than turns.

Comment (AsparagusEduardo) [reply test/battle/hold_effect/metronome.c:4]: Then let's expand the array to have to also have the x1.0 multiplier :)

Comment (AsparagusEduardo) [reply test/battle/hold_effect/metronome.c:4]: (Alternatively, you can do ARRAY_COUNT - 1)

Comment (SBird1337) [reply test/battle/hold_effect/metronome.c]: 'aight, did that

File: test/battle/hold_effect/metronome.c (hunk 2 above)
Comment (SBird1337) [reply test/battle/hold_effect/metronome.c:44]: I added the remaining tests, some of which are `KNOWN_FAILING` :(

**Comment by SBird1337** [comment]
added missing tests and addressed the review comments, please squash :-)

File: test/battle/hold_effect/metronome.c [hunk 4]
```diff
@@ -33,8 +37,117 @@ SINGLE_BATTLE_TEST("Metronome gradually boosts power by 20%")
...
+SINGLE_BATTLE_TEST("Metronome Item's boost is reset if the attacker uses a different move")
+{
+    s16 damage[2];
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_METRONOME); }
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_TACKLE); }
+        TURN { MOVE(player, MOVE_QUICK_ATTACK); }
+        TURN { MOVE(player, MOVE_TACKLE); }
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/metronome.c:53]: I think we need to add another Tackle before Quick Attack to make sure that a boost would've theorically happened.

File: test/battle/hold_effect/metronome.c [hunk 5]
```diff
@@ -33,8 +37,117 @@ SINGLE_BATTLE_TEST("Metronome gradually boosts power by 20%")
...
+    PARAMETRIZE {item = ITEM_METRONOME; }
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_SOLAR_BEAM].effect == EFFECT_SOLAR_BEAM);
+        PLAYER(SPECIES_WOBBUFFET) { Item(item); }
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_SOLAR_BEAM); }
+        TURN { SKIP_TURN(player); }
+    } SCENE {
+        HP_BAR(opponent, captureDamage: &results[i].damage);
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/metronome.c:124]: How is it playing locally? I'm thinking maybe the test is capturing the "damage" of the charging turn, causing it to fail.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: test/battle/hold_effect/metronome.c (hunk 4 above)
Comment (SBird1337) [reply test/battle/hold_effect/metronome.c:53]: We already test for the boost happening in another test. The counter is 1 after the first Tackle, and gets reset only by using quick attack. (I.e. if quick attack was tackle, we would already see the boost applying)

File: test/battle/hold_effect/metronome.c (hunk 5 above)
Comment (SBird1337) [reply test/battle/hold_effect/metronome.c:129]: I added more verbose `MESSAGE` statements so it is clear that `HP_BAR` captures the damage turn. :)

If you look at the actual error message you can see that the damage is not `0`:
```
test/battle/hold_effect/metronome.c:131: EXPECT_MUL_EQ(51, 1.19:, 51) failed: 61 not in [50..52]
```
too :)

File: test/battle/hold_effect/metronome.c (hunk 4 above)
Comment (AsparagusEduardo) [reply test/battle/hold_effect/metronome.c:53]: Fair, carry on.

File: test/battle/hold_effect/metronome.c (hunk 5 above)
Comment (AsparagusEduardo) [reply test/battle/hold_effect/metronome.c:129]: Awesome, thank you!

**Review by AsparagusEduardo — APPROVED** [review]
