### PR TITLE
Fix screen select bar popping in too early for area screen in HGSS dex

### LINKED ISSUE #4070: HGSS Pokedex Area display bug
### Description

When using the HGSS pokedex in expansion, swapping to the Area tab loads in the top selection bar earlier than the actual map, and it happens without the appropriate fade-in effect. It then disappears again and loads in with the map with the appropriate fade-in effect. Does not seem to occur with other options in the HGSS pokedex.

Example in gif:
Desktop2024 01 26-11 32 49 18-ezgif com-crop

### Version

1.7.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

OnlyNeedJuan

### PR DESCRIPTION
**Pull request by ravepossum**
## Description
I've shifted around when the screen select bar gets drawn in the HGSS pokedex so it doesn't pop onscreen too early. 

I've moved the relevant asset and function to pokedex_area_screen.c from pokedex_plus_hgss.c because that's where the task that draws the rest of the screen is.

(also I removed an unused parameter that was left in)

## Images
fixed version

## Issue(s) that this PR fixes
Fixes #4070 

## **Discord contact info**
user: ravepossum

### CODE REVIEW

File: src/pokedex_area_screen.c [hunk 1]
```diff
@@ -806,3 +811,9 @@ static void CreateAreaUnknownSprites(void)
         }
     }
 }
+
+static void LoadHGSSScreenSelectBarSubmenu(void)
+{
+    CopyToBgTilemapBuffer(1, sPokedexPlusHGSS_ScreenSelectBarSubmenu_Tilemap, 0, 0);
```
Comment (Bassoonian) [inline src/pokedex_area_screen.c:817]: I would return early if `POKEDEX_PLUS_HGSS` is false to avoid building it into the rom if disabled

Comment (ravepossum) [reply src/pokedex_area_screen.c:820]: Added in a check just like the one in CB2_OpenPokedexPlusHGSS().

**Review by AlexOn1ine — APPROVED** [review]

File: src/pokedex_area_screen.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/pokedex_area_screen.c:820]: Hm, I think there is no need to return it early. because it is taken care of above
```
        if (POKEDEX_PLUS_HGSS)
            LoadHGSSScreenSelectBarSubmenu();
```

Comment (AsparagusEduardo) [reply src/pokedex_area_screen.c:820]: Check if by compiling with the dex off it includes any test exclusive to the HGSS Dex by using HMA

Comment (ravepossum) [reply src/pokedex_area_screen.c:817]: Per Edu's suggestion, I dug through the ROM in HMA and didn't find HGSS dex specific text present when the dex was turned off and there was no check to exit early in LoadHGSSScreenSelectBarSubmenu(). So I've removed it.

**Review by AlexOn1ine — APPROVED** [review]

File: src/pokedex_area_screen.c (hunk 1 above)
Comment (Bassoonian) [reply src/pokedex_area_screen.c:817]: Apologies, my bad then! Sorry for the unnecessary extra work :)
