### PR TITLE
Use battler arguments for SetMoveEffect

### LINKED ISSUE #7121: BattleScript_BerryConfuseHealEnd2_Anim corrups BS_SCRIPTING
### Description

The script `BattleScript_BerryConfuseHealEnd2_Anim` uses command `seteffectprimary` to confuse the berry user which calls `SetMoveEffect` and corrupts `BS_SCRIPTING`.

In doubles this causes the wrong mon to lose the berry.

### Reproduction Steps

Trigger the berry in a double battle on slot 2 or 3. The Berry has to confuse the user

### Images / Video

_No response_

### Version

1.12.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7121

The problem block was this:
```
    if (gBattleScripting.moveEffect & MOVE_EFFECT_AFFECTS_USER)
    {
        gEffectBattler = gBattlerAttacker; // battler that effects get applied on
        gBattleScripting.moveEffect &= ~MOVE_EFFECT_AFFECTS_USER;
        affectsUser = MOVE_EFFECT_AFFECTS_USER;
        gBattleScripting.battler = gBattlerTarget; // theoretically the attacker
    }
    else
    {
        gEffectBattler = gBattlerTarget;
        gBattleScripting.battler = gBattlerAttacker;
    }
```
If `gBattleScripting.battler` was set before there was a chance it would be overwritten by `gBattlerAttacker` / `gBattlerTarget` which was the case for `BattleScript_BerryConfuseHealEnd2`. The scripting battler was set in `HealConfuseBerry` but overwritten in the above mentioned block.

Using arguments future proofs it.

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Turns out I'm still stupid. Feel free to yell at my solution and I pass the instruction down as well.

**Comment by cfmnephrite** [comment]
So is this ready?

**Comment by AlexOn1ine** [comment]
> So is this ready?

yes

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -3275,20 +3286,11 @@ void SetMoveEffect(bool32 primary, bool32 certain)
...
-    {
-        gEffectBattler = gBattlerTarget;
-        gBattleScripting.battler = gBattlerAttacker;
-    }
-
+    gBattleScripting.battler = battler;
+    gEffectBattler = effectBattler;
     battlerAbility = GetBattlerAbility(gEffectBattler);
+    if (battler == effectBattler)
+        affectsUser = MOVE_EFFECT_AFFECTS_USER;
```
Comment (cfmnephrite) [inline src/battle_script_commands.c]: I would suggest that it's worth deleting the `MOVE_EFFECT_AFFECTS_USER` flag altogether to discourage its use and prevent downstream users from breaking this function (since you've removed the checks for it in some cases). I would then suggest changing affectsUser here to just be a boolean, and adding a new `STAT_CHANGE_AFFECTS_USER` flag to `battle_script_commands.h` to replace the flag when it's used for stat changes.

**Review by cfmnephrite — CHANGES_REQUESTED** [review]

File: src/battle_script_commands.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c]: I agree and think it is generally a bad type of flag and already attempted to remove it but all the mirror armor tests started failing and I wasn't able to figure why exactly. I can give it an other try though, tomorrow.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: done

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -12101,24 +12109,17 @@ static void TryPlayStatChangeAnimation(u32 battler, u32 ability, u32 stats, s32
...
-    bool32 affectsUser = (flags & MOVE_EFFECT_AFFECTS_USER);
     bool32 mirrorArmored = (flags & STAT_CHANGE_MIRROR_ARMOR);
     bool32 onlyChecking = (flags & STAT_CHANGE_ONLY_CHECKING);
-
-    if (affectsUser)
-        battler = gBattlerAttacker;
-    else
-        battler = gBattlerTarget;
-
+    bool32 checkStatDropPrevention = (flags & STAT_CHANGE_CHECK_PREVENTION || gBattlerAttacker != gBattlerTarget);
```
Comment (cfmnephrite) [inline src/battle_script_commands.c]: ~~Would `gBattlerAttacker != battler` not be more appropriate here? In every case this function is called, `battler` is the target but that might not necessarily always be the case in the future.~~
Forget this one, see below

File: data/battle_scripts_1.s [hunk 3]
```diff
@@ -235,7 +235,7 @@ BattleScript_SyrupBombEndTurn::
 	flushtextbox
 	playanimation BS_ATTACKER, B_ANIM_SYRUP_BOMB_SPEED_DROP
 	setstatchanger STAT_SPEED, 1, TRUE
-	statbuffchange STAT_CHANGE_ALLOW_PTR | STAT_CHANGE_NOT_PROTECT_AFFECTED, BattleScript_SyrupBombTurnDmgEnd
+	statbuffchange BS_ATTACKER, STAT_CHANGE_CHECK_PREVENTION | STAT_CHANGE_ALLOW_PTR | STAT_CHANGE_NOT_PROTECT_AFFECTED, BattleScript_SyrupBombTurnDmgEnd
```
Comment (cfmnephrite) [inline data/battle_scripts_1.s:238]: Maybe I'm being stupid but why is STAT_CHANGE_CHECK_PREVENTION necessary here? Doesn't that flag compensate for MOVE_EFFECT_AFFECTS_USER?

File: src/battle_script_commands.c [hunk 4]
```diff
@@ -1434,8 +1434,17 @@ static void JumpIfMoveFailed(u32 adder, u32 move, u32 moveType, const u8 *failIn
...
 {
+    CMD_ARGS();
+
+    if (!(gBattleMons[gBattlerAttacker].status2 & STATUS2_MULTIPLETURNS))
+    {
+        gBattleMons[gBattlerAttacker].status2 |= STATUS2_MULTIPLETURNS;
+        gLockedMoves[gBattlerAttacker] = gCurrentMove;
+        gProtectStructs[gBattlerAttacker].chargingTurn = TRUE;
+    }
+    gBattlescriptCurrInstr = cmd->nextInstr;
```
Comment (cfmnephrite) [inline src/battle_script_commands.c:1447]: Could you update this to use the volatile bitfield instead?

File: src/battle_script_commands.c [hunk 5]
```diff
@@ -12241,7 +12242,7 @@ static u32 ChangeStatBuffs(s8 statValue, u32 statId, u32 flags, u32 stats, const
             }
             return STAT_CHANGE_DIDNT_WORK;
         }
-        else if (battlerAbility == ABILITY_MIRROR_ARMOR && !affectsUser && !mirrorArmored && gBattlerAttacker != gBattlerTarget && battler == gBattlerTarget)
+        else if (battlerAbility == ABILITY_MIRROR_ARMOR && !mirrorArmored && gBattlerAttacker != gBattlerTarget && battler == gBattlerTarget)
```
Comment (cfmnephrite) [inline src/battle_script_commands.c]: This is changed behaviour - is this correct?

**Comment by cfmnephrite** [comment]
@AlexOn1ine Can I propose the following changes? Would make ChangeStatBuff easier to follow as well IMO: https://github.com/cfmnephrite/pokeemerald/commit/ee7e27e49961c9c0c01a1cb03ed913e38a442c06

**Comment by AlexOn1ine** [comment]
> @AlexOn1ine Can I propose the following changes? Would make ChangeStatBuff easier to follow as well IMO: [cfmnephrite@ee7e27e](https://github.com/cfmnephrite/pokeemerald/commit/ee7e27e49961c9c0c01a1cb03ed913e38a442c06)

Yeah, I like this minus the type def (we don't type def structs or enums)

I'll take care of the review comments tomorrow.

**Comment by cfmnephrite** [comment]
> > @AlexOn1ine Can I propose the following changes? Would make ChangeStatBuff easier to follow as well IMO: [cfmnephrite@ee7e27e](https://github.com/cfmnephrite/pokeemerald/commit/ee7e27e49961c9c0c01a1cb03ed913e38a442c06)
> 
> Yeah, I like this minus the type def (we don't type def structs or enums)
> 
> I'll take care of the review comments tomorrow.

Lovely! Here's the branch, feel free to pinch: https://github.com/cfmnephrite/pokeemerald/tree/seteffect_battler_args_tweaked

**Comment by AlexOn1ine** [comment]
@cfmnephrite wouldn't the following accomplish the same thing?
```diff
.macro setadditionaleffects
- 1:
.byte 0x15
- jumpifhalfword CMP_EQUAL, sMOVE_EFFECT, MOVE_EFFECT_CONTINUE, 1b
.endm

if (numAdditionalEffects > gBattleStruct->additionalEffectsCounter)
-	gBattleScripting.moveEffect = MOVE_EFFECT_CONTINUE;
+	return; 
```

**Comment by cfmnephrite** [comment]
> @cfmnephrite wouldn't the following accomplish the same thing?
> 
> ```diff
> .macro setadditionaleffects
> - 1:
> .byte 0x15
> - jumpifhalfword CMP_EQUAL, sMOVE_EFFECT, MOVE_EFFECT_CONTINUE, 1b
> .endm
> 
> if (numAdditionalEffects > gBattleStruct->additionalEffectsCounter)
> -	gBattleScripting.moveEffect = MOVE_EFFECT_CONTINUE;
> +	return; 
> ```

No, because a lot of move effects push the current instruction plus one, therefore preventing looping. You could just modify SetMoveEffect not to do that but that's a much more complex change and this works anyway.

File: src/battle_script_commands.c (hunk 5 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c]: no, the check was redundant because of `gBattlerAttacker != gBattlerTarget`

**Comment by AlexOn1ine** [comment]
> > > @AlexOn1ine Can I propose the following changes? Would make ChangeStatBuff easier to follow as well IMO: [cfmnephrite@ee7e27e](https://github.com/cfmnephrite/pokeemerald/commit/ee7e27e49961c9c0c01a1cb03ed913e38a442c06)
> > 
> > 
> > Yeah, I like this minus the type def (we don't type def structs or enums)
> > I'll take care of the review comments tomorrow.
> 
> Lovely! Here's the branch, feel free to pinch: https://github.com/cfmnephrite/pokeemerald/tree/seteffect_battler_args_tweaked

suggestion applied, rest tomorrow

File: include/battle_script_commands.h [hunk 6]
```diff
@@ -22,6 +22,24 @@ struct PickupItem
...
+    u8 raw_u8;
+    struct {
+        bool32 allowPtr:1; // STAT_CHANGE_ALLOW_PTR
+        bool32 mirrorArmored:1; // STAT_CHANGE_MIRROR_ARMOR
+        bool32 onlyChecking:1; // STAT_CHANGE_ONLY_CHECKING
+        bool32 notProtectAffected:1; // STAT_CHANGE_NOT_PROTECT_AFFECTED
+        bool32 updateMoveEffect:1; // STAT_CHANGE_UPDATE_MOVE_EFFECT
+        bool32 statDropPrevention:1; // STAT_CHANGE_CHECK_PREVENTION
+        bool32 certain:1; // STAT_CHANGE_CERTAIN
+        bool32 padding:8;
```
Comment (AlexOn1ine) [inline include/battle_script_commands.h]: why is the padding here at 8 instead of 25?

Comment (cfmnephrite) [reply include/battle_script_commands.h:39]: Should have clarified that I pushed an update to that to the branch I linked. I assumed you would just merge and squash it.

Comment (cfmnephrite) [reply include/battle_script_commands.h]: ? This is the change as you made it? It was 8 in my version because the MOVE_EFFECT_CERTAIN flag is at 1 << 14.

Comment (AlexOn1ine) [reply include/battle_script_commands.h]: Oh right, oops! I didn't understand it was at 1 << 14.

Comment (AlexOn1ine) [reply include/battle_script_commands.h]: ye, I replaced it with `STAT_CHANGE_CERTAIN`. It was otherwise irrelevant

File: data/battle_scripts_1.s (hunk 3 above)
Comment (AlexOn1ine) [reply data/battle_scripts_1.s:238]: Ye, it does slightly compensate but for Syrup Bomb and Sticky Web we don't know the value of `gBattlerTarget`. I feel like a flag in this case is better then trying to manipulate the value of `gBattlerTarget` (which is especially scary for sticky web because it can trigger during some battle action while a switch in is happening.)

File: src/battle_script_commands.c (hunk 4 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c:1447]: done. 

Should I do it for all `multiturn` instances?

Comment (cfmnephrite) [reply src/battle_script_commands.c:1447]: It's your PR so I'd say that's up to you.

**Comment by AlexOn1ine** [comment]
Conflicts solved, should be ready for a merge!
