### PR TITLE
Adds Generational config for Magic Guard (Fix for Gen4+)

### LINKED ISSUE #5862: Magic Guard ignores paralysis chance in Gen 4
### Description

image
In Gen 4, Magic Guard users are immune to the chance to not be able to move, but I still have a lowered speed stat. I would like to have this in the config so the creator can choose to use this niche Gen 4 interaction.

### Version

1.10.0 (Latest release)

### Upcoming/master Version

This goes for all branches

### Discord contact info

SShadowzLmao#3643

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #5862

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -3484,7 +3484,10 @@ u8 AtkCanceller_UnableToUseMove(u32 moveType)
             gBattleStruct->atkCancellerTracker++;
             break;
         case CANCELLER_PARALYSED: // paralysis
-            if (!gBattleStruct->isAtkCancelerForCalledMove && (gBattleMons[gBattlerAttacker].status1 & STATUS1_PARALYSIS) && !RandomPercentage(RNG_PARALYSIS, 75))
+            if (!gBattleStruct->isAtkCancelerForCalledMove
+             && gBattleMons[gBattlerAttacker].status1 & STATUS1_PARALYSIS
+             && !RandomPercentage(RNG_PARALYSIS, 75)
+             && (GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD && B_MAGIC_GUARD >= GEN_4))
```
Comment (hedara90) [inline src/battle_util.c:3490]: Magic Guard check should go before the random roll, so that the roll never happens if the Magic Guard would prevent the move prevention.

Comment (AlexOn1ine) [reply src/battle_util.c:3490]: I thought about this but isn't it more likely the random roll fails more often then a user having magic guard? You would basically do that Magic Guard check 75% of the time for nothing.

Comment (hedara90) [reply src/battle_util.c:3490]: Wouldn't a call to `RandomPercentage` be more expensive than checking the ability 3 times?
Or is it irrelevant?

Comment (AlexOn1ine) [reply src/battle_util.c:3490]: It is more expensive. My thought process is that the magic guard check will be true 99% of the time which means the random call will be executed regardless pretty much every time. But since the random call would fail 75% of the time we avoid running the magic guard check in those cases and run it only 25% of the time.

Comment (AlexOn1ine) [reply src/battle_util.c:3490]: Obviously this is only true if we assume that magic guard is a very rare ability which it is in vanilla.

Comment (AlexOn1ine) [reply src/battle_util.c:3490]: Maybe I'm wrong if the random call is really expensive and the ability check really cheap though

Comment (AlexOn1ine) [reply src/battle_util.c:3490]: let's just change the order since the ability check is cheap and I don't know how expensive the random call is

Comment (AlexOn1ine) [reply src/battle_util.c]: changed

**Review by hedara90 — DISMISSED** [review]

**Comment by hedara90** [comment]
Wait, why did it fail?

File: src/battle_util.c [hunk 2]
```diff
@@ -3484,7 +3484,10 @@ u8 AtkCanceller_UnableToUseMove(u32 moveType)
             gBattleStruct->atkCancellerTracker++;
             break;
         case CANCELLER_PARALYSED: // paralysis
-            if (!gBattleStruct->isAtkCancelerForCalledMove && (gBattleMons[gBattlerAttacker].status1 & STATUS1_PARALYSIS) && !RandomPercentage(RNG_PARALYSIS, 75))
+            if (!gBattleStruct->isAtkCancelerForCalledMove
+             && gBattleMons[gBattlerAttacker].status1 & STATUS1_PARALYSIS
+             && (GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD && B_MAGIC_GUARD >= GEN_4)
+             && RandomPercentage(RNG_PARALYSIS, 25))
```
Comment (AlexOn1ine) [inline src/battle_util.c:3490]:
```suggestion
             && !RandomPercentage(RNG_PARALYSIS, 75))
```

**Comment by AlexOn1ine** [comment]
> Wait, why did it fail?

I think it is because I reverted the random call. I don't understand it fails though but it wasn't the first time this happened.

**Review by hedara90 — APPROVED** [review]

**Comment by eatthepear** [comment]
This config seems to be implemented incorrectly. Magic Guard only prevents immobilization of paralysis in gen 4. In gens 5 onward, it does not prevent immobilization of paralysis. [bulbapedia link](https://bulbapedia.bulbagarden.net/wiki/Magic_Guard_(Ability))
