### PR TITLE
Fix UB when accessing move result flags

### LINKED ISSUE #6021: UB in certain scenarios
### Description
After some testing it seems to only cause issue, when the opposing mon use non-selfcast moves. Tested by giving every opposing mon only one move, 
Tackle, Tail Whip, Thunder Shock -> UB
Nasty Plot, Harden -> no UB?
First commit with this behaviour seem to be 97b30cb712a6a898f7b9760fd1c01b1274fb0c5a

Setup:
- FRLG asserts in FreeInternal;
```diff
+#define ABSPATH(x) (x)
...
void FreeInternal(void *heapStart, void *pointer)
{
    if (pointer)
    {
        struct MemBlock *head = (struct MemBlock *)heapStart;
        struct MemBlock *block = (struct MemBlock *)((u8 *)pointer - sizeof(struct MemBlock));
+       AGB_ASSERT_EX(block->magic == MALLOC_SYSTEM_ID, ABSPATH("gflib/malloc.c"), 204);
...
        if (block != head)
        {
            if (!block->prev->allocated)
            {
+               AGB_ASSERT_EX(block->prev->magic == MALLOC_SYSTEM_ID, ABSPATH("gflib/malloc.c"), 228);
...
```
- Lvl 15 Bulbasaur, with Tackle, Growl, Razor Leaf, Leech Seed
- edit trainer party to the following, e.g.:
```
=== TRAINER_HALEY_1 ===
Name: GREG
Class: Bug Catcher
Pic: Bug Catcher
Gender: Male
Music: Male
Double Battle: No
AI: Check Bad Move

Weedle
Level: 9
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe

Kakuna
Level: 9
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe

Caterpie
Level: 9
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe

Metapod
Level: 9
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
```
Execution:
- spam Tackle until the battle is won

Result:
ub

without asserts:
image

### Version

upcoming (Edge)

### Upcoming/master Version

ce40c3356cae7ab5d58d636a67626511515651d0

### Discord contact info

.cawt

### PR DESCRIPTION
**Pull request by cawtds**
## Description
`gBattleStruct->moveResultFlags` is accessed with species instead of battler.

## Issue(s) that this PR fixes
Fixes #6021

## **Discord contact info**
.cawt

### CODE REVIEW

File: include/battle_util.h [hunk 1]
```diff
@@ -248,6 +248,7 @@ uq4_12_t CalcTypeEffectivenessMultiplier(u32 move, u32 moveType, u32 battlerAtk,
 uq4_12_t CalcPartyMonTypeEffectivenessMultiplier(u16 move, u16 speciesDef, u16 abilityDef);
 uq4_12_t GetTypeModifier(u32 atkType, u32 defType);
 uq4_12_t GetOverworldTypeEffectiveness(struct Pokemon *mon, u8 moveType);
+void UpdateMoveResultFlags(uq4_12_t modifier, u16* flags);
```
Comment (AlexOn1ine) [inline include/battle_util.h:251]:
```suggestion
void UpdateMoveResultFlags(uq4_12_t modifier, u16 *resultFlags);
```

**Review by AlexOn1ine — APPROVED** [review]
