### PR TITLE
Fix Eviolite to use original species after Transform

### LINKED ISSUE #9275: Eviolite should check original species, not transformed species (also transformdataexecution should get rid of struct-order dependent copy)
### Description

https://bulbapedia.bulbagarden.net/wiki/Eviolite
> If held by a [transformed](https://bulbapedia.bulbagarden.net/wiki/Transform_(move)) Pokémon, the boost is based on its original species, not the species it is transformed into.

Not the case here.
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/src/battle_util.c#L7271-L7274

You can see in transformdataexecution that the target species is copied over to the user species. It's unclear because it uses a u8 copy to copy the data
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/src/battle_script_commands.c#L8536-L8540

species is the first field in the struct so it is copied:
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/include/pokemon.h#L337-L339

Apart from fixing transform, this copy should also just be modified to direct struct field copies, so that it isn't sensitive to struct order

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Issue(s) that this PR fixes
Partially fixes #9275

### CODE REVIEW

File: test/battle/hold_effect/eviolite.c [hunk 1]
```diff
@@ -1,4 +1,72 @@
 #include "global.h"
 #include "test/battle.h"
 
-TO_DO_BATTLE_TEST("TODO: Write Eviolite (Hold Effect) test titles")
```
Comment (AlexOn1ine) [inline test/battle/hold_effect/eviolite.c:4]: Maybe also an inverted test that tests that def isn't boosted for evolved mons?
