### PR TITLE
Fix Leppa Berry PP restore target under forced-consumption effects

### LINKED ISSUE #6538: Leppa Berry as consumed by Fling/Bug Bite might be inconsistent with vanilla behaviour
### Description

From Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Leppa_Berry

> If a Pokémon is forced to eat a Leppa Berry as a result of [Fling](https://bulbapedia.bulbagarden.net/wiki/Fling_(move)), [Bug Bite](https://bulbapedia.bulbagarden.net/wiki/Bug_Bite_(move)), [Pluck](https://bulbapedia.bulbagarden.net/wiki/Pluck_(move)), [Stuff Cheeks](https://bulbapedia.bulbagarden.net/wiki/Stuff_Cheeks_(move)), or [Teatime](https://bulbapedia.bulbagarden.net/wiki/Teatime_(move)), PP will be restored to the first move that has 0 PP left if such a move exists, or otherwise to the first move that has any PP missing.

But seems like when Fling/Bug Bite/presumably others try to consume a Leppa Berry, it checks for the first move that has missing PP: https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/battle_util.c#L7153-L7155

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description

> If a Pokémon is forced to eat a Leppa Berry as a result of Fling, Bug Bite, Pluck, Stuff Cheeks, or Teatime, PP will be restored to the first move that has 0 PP left if such a move exists, or otherwise to the first move that has any PP missing.

## Issue(s) that this PR fixes
Fixes #6538

### CODE REVIEW

File: src/battle_hold_effects.c [hunk 1]
```diff
@@ -891,43 +891,67 @@ static u32 ItemRestorePp(u32 battler, u32 itemId, ActivationTiming timing)
 {
     enum ItemEffect effect = ITEM_NO_EFFECT;
     struct Pokemon *mon = GetBattlerMon(battler);
-    u32 i, changedPP = 0;
+    u32 i;
```
Comment (hedara90) [inline src/battle_hold_effects.c]: Move this loop iterator declaration into the loop declaration.
(I know it's existing code, but since almost everything around it is being touched, it's good to get it done)

File: src/battle_hold_effects.c [hunk 2]
```diff
@@ -891,43 +891,66 @@ static u32 ItemRestorePp(u32 battler, u32 itemId, ActivationTiming timing)
...
 
-    for (i = 0; i < MAX_MON_MOVES; i++)
+    for (u32 i = 0; i < MAX_MON_MOVES; i++)
     {
         u32 move = GetMonData(mon, MON_DATA_MOVE1 + i);
         u32 currentPP = GetMonData(mon, MON_DATA_PP1 + i);
-        u32 ppBonuses = GetMonData(mon, MON_DATA_PP_BONUSES);
-        u32 maxPP = CalculatePPWithBonus(move, ppBonuses, i);
-        if (move && (currentPP == 0 || (gBattleScripting.overrideBerryRequirements && currentPP != maxPP)))
+        if (!move)
```
Comment (hedara90) [inline src/battle_hold_effects.c]:
```suggestion
        if (move == MOVE_NONE)
```
Non-boolean treated as a boolean

**Review by hedara90 — APPROVED** [review]
