### PR TITLE
Fixed Future Sight not being affected by Electrify

### LINKED ISSUE #4471: Electrify does not Change the Type of Foreseen Moves
### Description

Using Electrify on a Pokemon that has used Future Sight or Doom Desire does not change the type of the foreseen move to Electric.
Expected outcome is that the type of the foreseen move becomes Electric assuming that Electrify succeeded.
On cartridge Electrify changes foreseen moves to Electric, verified for Gen 7.
The incorrect behavior is also present on Showdown.

https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/ef3f8ea6-5d95-4976-85a3-81168490980a

### Version

1.8.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hedara#5073

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
I also updated Color Change tests to use Kecleon.

## Issue(s) that this PR fixes
Closes #4471

## People who collaborated with me in this PR
@AlexOn1ine, who provided a better fix + a fix for Instruct's dynamic move type

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
There is a more simple fix for this

**Comment by AsparagusEduardo** [comment]
> There is a more simple fix for this

Oh, weird, the commit that had the simpler fix wasn't included

**Comment by AsparagusEduardo** [comment]
Ah, I didn't push it lol

**Comment by AlexOn1ine** [comment]
Removing the resets of dynamic type means that it is never reset besides in ai calcs which seems like a footgun. Also according to this change if an -ate ability user uses a a normal type move, gets worry seeded before instructed, it will retain the type change before it got it's ability suppressed. 

Generally Instruct seems fundamentally broken. Here is one test that also fails but I think there are more because the instructed move doesn't got through the proper checks.
```
DOUBLE_BATTLE_TEST("Instructed move will be absorbed by Lightning Rod if it turns into an Electric Type move")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WYNAUT);
        OPPONENT(SPECIES_PIKACHU) { Ability(ABILITY_LIGHTNING_ROD); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN {
            MOVE(playerLeft, MOVE_TACKLE, target: opponentLeft);
            MOVE(opponentLeft, MOVE_PLASMA_FISTS, target: playerLeft);
            MOVE(playerRight, MOVE_INSTRUCT, target: playerLeft);
            MOVE(opponentRight, MOVE_CELEBRATE);
        }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerLeft);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_PLASMA_FISTS, opponentLeft);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_INSTRUCT, playerRight);
        ABILITY_POPUP(opponentLeft, ABILITY_LIGHTNING_ROD);
        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerLeft);
    }
}
```

For the Future Sight fix you could just move `gStatuses4[i] &= ~STATUS4_ELECTRIFIED` to the function `BattleTurnPassed` into this loop which just means it will always be removed after Future Sight is done. And `ENDTURN_ELECTRIFY` can be deprecated after this change.
```
    for (i = 0; i < gBattlersCount; i++)
    {
        gChosenActionByBattler[i] = B_ACTION_NONE;
        gChosenMoveByBattler[i] = MOVE_NONE;
        gBattleStruct->battlerState[i].absentBattlerFlags = gAbsentBattlerFlags & (1u << i);
        gBattleStruct->monToSwitchIntoId[i] = PARTY_SIZE;
        gStatuses4[i] &= ~STATUS4_ELECTRIFIED;
    }
```

**Comment by AsparagusEduardo** [comment]
> Generally Instruct seems fundamentally broken. Here is one test that also fails but I think there are more because the instructed move doesn't go through the proper checks.
> 
> ```
> DOUBLE_BATTLE_TEST("Instructed move will be absorbed by Lightning Rod if it turns into an Electric Type move")
> [...]

I'll be adding this as a `KNOWN_FAILING` test ^^;

> For the Future Sight fix you could just move `gStatuses4[i] &= ~STATUS4_ELECTRIFIED` to the function `BattleTurnPassed` into this loop which just means it will always be removed after Future Sight is done. And `ENDTURN_ELECTRIFY` can be deprecated after this change.
> 
> ```
>     for (i = 0; i < gBattlersCount; i++)
>     {
>         gChosenActionByBattler[i] = B_ACTION_NONE;
>         gChosenMoveByBattler[i] = MOVE_NONE;
>         gBattleStruct->battlerState[i].absentBattlerFlags = gAbsentBattlerFlags & (1u << i);
>         gBattleStruct->monToSwitchIntoId[i] = PARTY_SIZE;
>         gStatuses4[i] &= ~STATUS4_ELECTRIFIED;
>     }
> ```

This didn't do it undortunertly, but I get the idea.
image

> Removing the resets of dynamic type means that it is never reset besides ai calcs which seems like a footgun. Also according to this change if an -ate ability user uses a a normal type move, gets worry seeded before instructed, it will retain the type change before it got it's ability suppressed.

It still reset in `CheckChangingTurnOrderEffects`, which is called by `SetActionsAndBattlersTurnOrder`, which is called by `HandleTurnActionSelectionState`, which is also called by `BattleTurnPassed`.

**Comment by AsparagusEduardo** [comment]
Applied changes discussed on Discord

**Comment by AlexOn1ine** [comment]
Since I collaborated probably better if someone else finishes the review :sweat_smile:

File: test/battle/ability/color_change.c [hunk 1]
```diff
@@ -4,41 +4,46 @@
 SINGLE_BATTLE_TEST("Color Change changes the type of a Pokemon being hit by a move if the type of the move and the Pokemon are different")
 {
     GIVEN {
+        ASSUME(gSpeciesInfo[SPECIES_KECLEON].types[0] == TYPE_NORMAL || gSpeciesInfo[SPECIES_KECLEON].types[1] == TYPE_NORMAL);
```
Comment (Bassoonian) [inline test/battle/ability/color_change.c:7]: Isn't this assume technically wrong? If Kecleon would be a pure Ground type, the test would still be passing.

Comment (AsparagusEduardo) [reply test/battle/ability/color_change.c:7]: True. Will adjust to check that it's not Psychic type

**Review by Bassoonian — APPROVED** [review]
