### PR TITLE
Fixes Fling being usable with reusable TMs

### LINKED ISSUE #8902: Fling should not be able to throw reusable TMs
### Description

The current TM behaviour implemented in Fling, where it uses the data of the move it contains, only goes for TMs as items that are expendable (or TRs as they have been referred to lately).

### Reproduction Steps

Use Fling with a TM

### Images / Video

_No response_

### Version

1.14.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
Adds a check that prevents Fling working if holding a reusable TM.

Cleaned up some tests and removed duplicates.

## Issue(s) that this PR fixes
Fixes #8902

## Discord contact info
PhallenTree

### CODE REVIEW

File: test/battle/ability/corrosion.c [hunk 1]
```diff
@@ -66,34 +66,7 @@ SINGLE_BATTLE_TEST("Corrosion does not effect poison type damaging moves if the
     }
 }
 
-SINGLE_BATTLE_TEST("Corrosion can poison Poison- and Steel-type targets if it uses Fling while holding a Toxic Orb or a Poison Barb")
```
Comment (PhallenTree) [inline test/battle/ability/corrosion.c:69]: "Corrosion can poison Poison/Steel types if the Pokémon uses Fling while holding a Toxic Orb" and "Corrosion can poison Poison/Steel types if the Pokémon uses Fling while holding a Poison Barb" also check a Steel-type, so chose to keep those instead of this one

File: test/battle/move_effect/fling.c [hunk 2]
```diff
@@ -520,33 +520,17 @@ SINGLE_BATTLE_TEST("Fling deals damage based on a TM's move power")
...
-        ASSUME(!IsSpeciesOfType(SPECIES_WOBBUFFET, TYPE_DARK));
-        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_TM_EARTHQUAKE); }
-        OPPONENT(SPECIES_HIPPOWDON);
-    } WHEN {
-        TURN { MOVE(player, MOVE_FLING); }
-        TURN { MOVE(player, MOVE_EGG_BOMB); }
-    } SCENE {
-        ANIMATION(ANIM_TYPE_MOVE, MOVE_FLING, player);
-        HP_BAR(opponent, captureDamage: &damage[0]);
+        if (I_REUSABLE_TMS == FALSE) {
```
Comment (Bassoonian) [inline test/battle/move_effect/fling.c]: Shouldn't we be checking the importance of ``ITEM_TM_EARTHQUAKE`` here? Toggling that item's importance individually without touching the config will result in a test failure. Or maybe an assume that the TM being checked is indeed expendable? I get that you want to avoid a failing assume, but I do think we need to check the mechanic either way

Comment (PhallenTree) [reply test/battle/move_effect/fling.c]: Changed to check the Earthquake TM's importance
