### PR TITLE
Last fix for Sparkling Aria / Covert Cloak / Shield Dust interaction

### LINKED ISSUE #4636: Sparkling Aria interaction with burned Shield Dust Pokemon is not properly implemented
### Description

Shield Dust should prevent the secondary effect of Sparkling Aria from curing burns unless the Sparkling Aria hits multiple targets.
### Single battle

- Sparkling Aria **does not** cure burns from Pokemon with Shield Dust

### Double Battle

- If Sparkling Aria hits a burned Pokemon with Shield Dust and at least one more Pokemon, the burn **will** be cured.
- If multiple Pokemon with Shield Dust are hit with Sparkling Aria, any number of them that are burned **will** be cured.
- If only a Pokemon with Shield Dust is hit by Sparkling Aria due to other Pokemon either protecting, being semi-invulnerable due to Fly/Dive/Sky Drop etc., being immune due to ability or Sparkling Aria failing the accuracy check, the Pokemon with Shield Dust **will not** be cured of their burn.
- If the a Pokemon with Shield Dust if the only other live battler they **will not** be cured of their burn.
- If all other battlers faint from the Sparkling Aria, the Shield Dust user **will** be cured of their burn

### Version

1.8.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes  #4636

### CODE REVIEW

File: test/battle/ability/shield_dust.c [hunk 1]
```diff
@@ -147,6 +147,31 @@ DOUBLE_BATTLE_TEST("Shield Dust does or does not block Sparkling Aria depending
...
+        NONE_OF {
+            MESSAGE("The opposing Vivillon's burn was cured!");
+            STATUS_ICON(opponentLeft, none: TRUE);
+        }
+    }
+}
+
 DOUBLE_BATTLE_TEST("Shield Dust blocks Sparkling Aria if all other targets avoid getting hit by")
 {
     KNOWN_FAILING;  //  #4636
```
Comment (hedara90) [inline test/battle/ability/shield_dust.c:177]: Needs to be removed.

If the whole test is redundant due to "Shield Dust does block Sparkling Aria when only one mon is hit", the entire test can be removed.

Comment (AlexOn1ine) [reply test/battle/ability/shield_dust.c]: I kept this one. It covers all bases with fewer lines

File: src/battle_util.c [hunk 2]
```diff
@@ -12222,3 +12222,19 @@ bool32 IsMoveEffectBlockedByTarget(u32 ability)
...
+        return targetCount;
+
+    for (u32 battler = 0; battler < gBattlersCount; battler++)
+    {
+        if (MoveResultHasEffect(battler))
+            targetCount++;
+    }
+
+    return targetCount;
+}
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply src/battle_util.c]: added

File: src/battle_util.c [hunk 3]
```diff
@@ -12222,3 +12222,19 @@ bool32 IsMoveEffectBlockedByTarget(u32 ability)
...
 }
+
+u32 NumAffectedSpreadMoveTargets(void)
+{
+    u32 targetCount = 1;
+
+    if (!IsDoubleSpreadMove())
+        return targetCount;
+
+    for (u32 battler = 0; battler < gBattlersCount; battler++)
```
Comment (AlexOn1ine) [inline src/battle_util.c:12233]:
```suggestion
    u32 targetCount = 1;

    if (!IsDoubleSpreadMove())
        return targetCount;

    u32 targetCount = 0;
    for (u32 battler = 0; battler < gBattlersCount; battler++)
```

Comment (AlexOn1ine) [inline src/battle_util.c:12233]:
```suggestion
    u32 targetCount = 1;

    if (!IsDoubleSpreadMove())
        return targetCount;

    targetCount = 0;
    for (u32 battler = 0; battler < gBattlersCount; battler++)
```

**Review by hedara90 — APPROVED** [review]
