### PR TITLE
Fling Refactor

### LINKED ISSUE #9056: Fling will prevent ALL attempts at Symbiosis triggering via removeitem, not just for the removeitem for fling specifically
### Description

Cmd_removeitem calls TrySymbiosis
https://github.com/rh-hideout/pokeemerald-expansion/blob/c3b462a1397b9dea82882d336b1c77209c6d53bd/src/battle_script_commands.c#L6449-L6451
https://github.com/rh-hideout/pokeemerald-expansion/blob/c3b462a1397b9dea82882d336b1c77209c6d53bd/src/battle_script_commands.c#L6479-L6482

In TrySymbiosis, if the current move's effect is fling, symbiosis won't trigger
https://github.com/rh-hideout/pokeemerald-expansion/blob/c3b462a1397b9dea82882d336b1c77209c6d53bd/src/battle_util.c#L10236-L10244

This means that if a removeitem unrelated to fling happens (e.g., fling triggering a target's oran berry), symbiosis won't trigger.

One solution is to just have a flag to removeitem to specifically block symbiosis

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
## Description

Closes #9056 and Turns fling into a regular move effect that can be used on other damage moves without the modifier and failure parts. E.g. Tackle can have the fling effect but it's going to have it's own BP and doesn't check if the move fails 
due to not having and item or unable to fling the item (effect is prevented if item can't be flinged)

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Ready for review.

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -3124,6 +3124,67 @@ void SetMoveEffect(enum BattlerId battlerAtk, enum BattlerId effectBattler, enum
...
+                gBattlescriptCurrInstr = BattleScript_FlingBlockedByShieldDust;
+                break;
+            }
+
+            switch (holdEffect)
+            {
+            case HOLD_EFFECT_FLAME_ORB:
+                BattleScriptPush(battleScript);
+                SetMoveEffect(gBattlerAttacker, gBattlerTarget, MOVE_EFFECT_BURN, BattleScript_RemoveItem, NO_FLAGS);
+                break;
```
Comment (PhallenTree) [inline src/battle_script_commands.c:3212]:
```suggestion
            BattleScriptPush(battleScript);
            gBattlescriptCurrInstr = BattleScript_RemoveItem;
            switch (holdEffect)
            {
            case HOLD_EFFECT_FLAME_ORB:
                SetMoveEffect(gBattlerAttacker, gBattlerTarget, MOVE_EFFECT_BURN, gBattlescriptCurrInstr, NO_FLAGS);
                break;
```
Same for the others below

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -3124,6 +3124,67 @@ void SetMoveEffect(enum BattlerId battlerAtk, enum BattlerId effectBattler, enum
...
+                SetMoveEffect(gBattlerAttacker, gBattlerTarget, MOVE_EFFECT_FLINCH, BattleScript_RemoveItem, NO_FLAGS);
+                break;
+            case HOLD_EFFECT_MENTAL_HERB:
+                if (ItemBattleEffects(gBattlerTarget, 0, holdEffect, IsOnFlingActivation))
+                    BattleScriptPush(battleScript);
+                break;
+            case HOLD_EFFECT_WHITE_HERB:
+                if (ItemBattleEffects(gBattlerTarget, 0, holdEffect, IsOnFlingActivation))
+                    BattleScriptPush(battleScript);
+                break;
```
Comment (PhallenTree) [inline src/battle_script_commands.c:3229]: With the change above:

```suggestion
            case HOLD_EFFECT_MENTAL_HERB:
            case HOLD_EFFECT_WHITE_HERB:
                ItemBattleEffects(gBattlerTarget, 0, holdEffect, IsOnFlingActivation);
                break;
```
And remove the timing check on the activation functions

File: src/battle_script_commands.c [hunk 3]
```diff
@@ -3124,6 +3124,67 @@ void SetMoveEffect(enum BattlerId battlerAtk, enum BattlerId effectBattler, enum
...
+            default:
+                BattleScriptPush(battleScript);
+                gBattlescriptCurrInstr = BattleScript_RemoveItem;
+                break;
```
Comment (PhallenTree) [inline src/battle_script_commands.c:3231]:
```suggestion
            default:
                break;
```

File: src/battle_move_resolution.c [hunk 4]
```diff
@@ -1086,11 +1086,11 @@ static enum CancelerResult CancelerMoveFailure(struct BattleContext *ctx)
     switch (GetMoveEffect(ctx->move))
     {
     case EFFECT_FLING:
-        if (!CanFling(ctx->battlerAtk))
+        if (!CanFling(ctx->battlerAtk, ctx->abilityAtk))
             battleScript = BattleScript_ButItFailed;
         else // set fling item
-            gBattleStruct->flingItem = gLastUsedItem = gBattleMons[ctx->battlerAtk].item;
```
Comment (PhallenTree) [inline src/battle_move_resolution.c:1102]: This was specifically needed for spread Fling to apply the effect on all targets, up to you if you want to bring it back (and instead of pulling the attacker's item in `MOVE_EFFECT_FLING`, this would be pulled).

File: src/battle_script_commands.c (hunk 2 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c:3229]: Wouldn't the move just end, if the `IsOnFlingActivation` branches are removed in their respective functions?

File: src/battle_move_resolution.c (hunk 4 above)
Comment (AlexOn1ine) [reply src/battle_move_resolution.c:1102]: we can bring it back

File: src/battle_script_commands.c (hunk 2 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c:3229]: oh nevermind, they end in `return` not `end2`

**Comment by AlexOn1ine** [comment]
Review comments addressed.

File: src/battle_move_resolution.c [hunk 5]
```diff
@@ -1086,11 +1086,11 @@ static enum CancelerResult CancelerMoveFailure(struct BattleContext *ctx)
...
-        break;    
+         gBattleStruct->flingItem = gLastUsedItem = gBattleMons[ctx->battlerAtk].item;
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
            gBattleStruct->flingItem = gLastUsedItem = gBattleMons[ctx->battlerAtk].item;
```

**Comment by AlexOn1ine** [comment]
ready for re-review.

File: src/battle_script_commands.c [hunk 6]
```diff
@@ -6529,7 +6582,17 @@ static void Cmd_removeitem(void)
...
-    if (gBattleScripting.overrideBerryRequirements || itemId == ITEM_NONE)
+    if (gBattleStruct->flingItem != ITEM_NONE)
+    {
+        if (gBattleMons[gBattlerAttacker].item == ITEM_NONE) // Avoid the else branch
+        {
+            gBattlescriptCurrInstr = cmd->nextInstr;
+            return;
+        }
+        battler = gBattlerAttacker;
+        itemId = gBattleStruct->flingItem;
```
Comment (PhallenTree) [inline src/battle_script_commands.c]: We need to set `gBattleStruct->flingItem` to `ITEM_NONE` here, otherwise other battlers' items that activate in response to fling here never get removed.
This does break multi-target Fling functionality, but I'd rather Fling be correct and handle multi target Fling later.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Do we need the `flingItem` then since it wouldn't work on multi targets anyways in this case?

Comment (PhallenTree) [reply src/battle_script_commands.c]: At least a bit should be kept so that the item is removed from the correct battler.
Could you also have it only be set in `MOVE_EFFECT_FLING` to ensure that weakness berries are consumed properly?

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: ye, that's how it was handled prior to bringing back `flingItem`

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Actually, I think we can have the multi target behavior by having both a flag and storing the item.

This ensures the removal of the fling item at the right time and resets the flag
```C
    if (gBattleStruct->flungItem)
    {
        // skip if item already removed
        gBattleStruct->flungItem = FALSE;
        battler = gBattlerAttacker;
        itemId = gLastUsedItem;
    }
```
And this part only sets it when it can be flung
```C
    case MOVE_EFFECT_FLING:
        if (CanFling(gBattlerAttacker, abilities[gBattlerAttacker]))
        {
            gBattleStruct->flingItem = TRUE;
            u32 item = gLastUsedItem = gBattleStruct->flingItem;
```
Thoughts?

Comment (PhallenTree) [reply src/battle_script_commands.c]: The problem with that implementation is that an item can be passed by Symbiosis in between targets and then is removed on the next target. Maybe only set `gBattleStruct->flingItem` when the move effect will activate, along with `gBattleStruct->flungItem`, and if it has been set, instead use `overrideBerryRequirements` to skip item removal.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Used an enum to solve it so it's a bit cleaner. 

https://github.com/user-attachments/assets/f3bc15ac-a271-4cf5-8494-d849e6f1772d

File: src/battle_script_commands.c [hunk 7]
```diff
@@ -2124,7 +2124,12 @@ static void Cmd_printstring(void)
 {
     CMD_ARGS(u16 id);
 
-    if (gBattleControllerExecFlags == 0)
+    if (gBattleStruct->flungItem != FLUNG_ITEM_NONE)
```
Comment (PhallenTree) [inline src/battle_script_commands.c]: This should only skip specifically the Fling message: `STRINGID_PKMNFLUNG`

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: oh oops, fixed.

In hindsight we went the extra mile here to make it work for a fictional move. Maybe we shouldn't do this in the future for cases like this where a lot of extra handling is needed. But then again fling is also an exception. Usually moves aren't that complicated.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: I think I have a better for the message handling

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Changed it to skip the message when the animation was played. 

Also noticed that it didn't work on second target if there was no item so included a fix for that. Though at this point I wouldn't be opposed to just reverting it and handling a single mon :sweat_smile:
