### PR TITLE
Fix various stuff not working when hitting substitutes

### LINKED ISSUE #9482: Absorb effect on Substitute doesn't work
### Description

If you Giga Drain (or other absorb effect  moves) an opponent Pokemon with Substitute, you don't recover HP

### Reproduction Steps

Trivial

### Images / Video

_No response_

### Version

1.15.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by hedara90**
## Description

The target isn't damaged when a Substitute is hit, but it should be enough to verify that the move-damage is above 0 for the case of `EFFECT_ABSORB`.

## Issue(s) that this PR fixes
Fixes #9482 

## Discord contact info

hedara

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
This is a general issue because most moves just check for `IsBattlerTurnDamaged`. 

I think the general solution would be to add a boolean argument for `IsBattlerTurnDamage` and check the move damage there as well. Ignore it when we want to care about Substitute. Not sure, maybe there is a cleaner solution?

**Comment by hedara90** [comment]
Yea, it seems that currently recoil moves don't have recoil when hitting into substitutes.

**Comment by hedara90** [comment]
Newly added tests that don't work:
- Core Enforcer hitting a substitute, should still suppress ability of targets that have acted, verified by Linathan
- Z-Move Genesis Supernova, should set up Psychic terrain if hitting a substitute, JPwiki
- Plasma Fists should set up Ion Deluge if hitting a substitute, JPwiki
- Brick Break and similar, should break screens when hitting substitutes, JPwiki

File: test/battle/move_effect/ceaseless_edge.c [hunk 1]
```diff
@@ -94,3 +94,20 @@ SINGLE_BATTLE_TEST("Ceaseless Edge does not set up hazards if target was not hit
...
+        OPPONENT(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_WYNAUT);
+    } WHEN {
+        TURN { MOVE(player, MOVE_SUBSTITUTE); MOVE(opponent, MOVE_CEASELESS_EDGE); }
+        TURN { SWITCH(opponent, 1); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_SUBSTITUTE, player);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_CEASELESS_EDGE, opponent);
+        SUB_HIT(player);
+        NOT HP_BAR(opponent);
```
Comment (PhallenTree) [inline test/battle/move_effect/ceaseless_edge.c]: The spikes are set up on the player's side, why check if the opponent's side takes damage?

File: test/battle/move_effect/stone_axe.c [hunk 2]
```diff
@@ -92,3 +92,20 @@ SINGLE_BATTLE_TEST("Stone Axe fails to set up hazards if user faints")
...
+        OPPONENT(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_WYNAUT);
+    } WHEN {
+        TURN { MOVE(player, MOVE_SUBSTITUTE); MOVE(opponent, MOVE_STONE_AXE); }
+        TURN { SWITCH(opponent, 1); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_SUBSTITUTE, player);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_STONE_AXE, opponent);
+        SUB_HIT(player);
+        NOT HP_BAR(opponent);
```
Comment (PhallenTree) [inline test/battle/move_effect/stone_axe.c]: Same as Ceaseless Edge test

File: src/battle_move_resolution.c [hunk 3]
```diff
@@ -3156,7 +3156,7 @@ static enum MoveEndResult MoveEndMoveBlock(void)
         break;
     case EFFECT_CEASELESS_EDGE:
         if (gSideTimers[side].spikesAmount < 3
-         && IsBattlerTurnDamaged(gBattlerTarget)
+         && IsBattlerTurnDamaged(gBattlerTarget, FALSE)
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
         && IsBattlerTurnDamaged(gBattlerTarget, TRUE)
```

File: src/battle_move_resolution.c [hunk 4]
```diff
@@ -3145,7 +3145,7 @@ static enum MoveEndResult MoveEndMoveBlock(void)
         break;
     case EFFECT_STONE_AXE:
         if (!IsHazardOnSide(side, HAZARDS_STEALTH_ROCK)
-         && IsBattlerTurnDamaged(gBattlerTarget)
+         && IsBattlerTurnDamaged(gBattlerTarget, FALSE)
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
         && IsBattlerTurnDamaged(gBattlerTarget, TRUE)
```

File: test/battle/move_effect_secondary/break_screens.c [hunk 5]
```diff
@@ -159,3 +159,25 @@ DOUBLE_BATTLE_TEST("Brick Break and Psychic Fangs can remove Light Screen, Refle
...
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_REFLECT); }
+        TURN { MOVE(player, MOVE_SUBSTITUTE); MOVE(opponent, move); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_REFLECT, player);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_SUBSTITUTE, player);
+        ANIMATION(ANIM_TYPE_MOVE, move, opponent);
+        SUB_HIT(player);
+        MESSAGE("The wall shattered!");
```
Comment (PhallenTree) [inline test/battle/move_effect_secondary/break_screens.c]:
```suggestion
        MESSAGE("The wall shattered!");
        SUB_HIT(player);
```
Message happens before the damage is dealt

File: test/battle/move_effect/ceaseless_edge.c (hunk 1 above)
Comment (hedara90) [reply test/battle/move_effect/ceaseless_edge.c]: Because I'm a dumdum

**Comment by hedara90** [comment]
Review addressed.
Still failing tests:
- Plasma Fists turns normal moves into electric moves even if it hits a substitute
- (Z-MOVE) Genesis Supernova sets up psychic terrain when the target is behind a Substitute
- Core Enforcer suppresses the ability of targets that have already acted that are behind Substitutes
- Brick Break and Psychic Fangs can remove screens when the target is behind a Substitute

**Comment by hedara90** [comment]
`IsAnyTargetTurnDamaged` only used one of the path for `IsBattlerTurnDamaged, so I'm hard-coding it for now.

File: src/battle_script_commands.c [hunk 6]
```diff
@@ -2423,6 +2423,26 @@ static inline bool32 IgnoreTargetingForMoveEffect(enum MoveEffect moveEffect) //
...
+        return FALSE;
+
+    if (moveEffect != MOVE_EFFECT_BUG_BITE && IgnoreTargetingForMoveEffect(moveEffect))
+        return FALSE;
+
+    if (moveEffect == MOVE_EFFECT_CORE_ENFORCER)
+        return FALSE;
+
+    if (moveEffect == MOVE_EFFECT_BREAK_SCREEN)
+        return FALSE;
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:2438]: is the spectral thief pre attack blocked by substitute?

Comment (hedara90) [reply src/battle_script_commands.c:2438]: I don't know, it feels logical that it should be blocked, but Core Enforcer works with Substitute, so who knows.

Comment (PhallenTree) [reply src/battle_script_commands.c:2438]: Spectral Thief ignores Substitute to deal damage anyways so it also ignores it when stealing stats

File: src/battle_script_commands.c [hunk 7]
```diff
@@ -2824,7 +2844,7 @@ void SetMoveEffect(enum BattlerId battlerAtk, enum BattlerId effectBattler, enum
             if (gBattleMons[gEffectBattler].statStages[i] != DEFAULT_STAT_STAGE)
                 break;
         }
-        if (IsBattlerTurnDamaged(gEffectBattler) && i != NUM_BATTLE_STATS)
+        if (IsBattlerTurnDamaged(gEffectBattler, FALSE) && i != NUM_BATTLE_STATS)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: missing constant

File: src/battle_script_commands.c [hunk 8]
```diff
@@ -3713,7 +3733,7 @@ static void SetToxicChainPriority(void)
     if (abilityAtk == ABILITY_TOXIC_CHAIN
      && IsBattlerAlive(gBattlerTarget)
      && CanBePoisoned(gBattlerAttacker, gBattlerTarget, abilityAtk, GetBattlerAbility(gBattlerTarget))
-     && IsBattlerTurnDamaged(gBattlerTarget)
+     && IsBattlerTurnDamaged(gBattlerTarget, FALSE)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: missing constant

File: src/battle_util.c [hunk 9]
```diff
@@ -3958,7 +3958,7 @@ u32 AbilityBattleEffects(enum AbilityEffect caseID, enum BattlerId battler, enum
         case ABILITY_LINGERING_AROMA:
         case ABILITY_MUMMY:
             if (IsBattlerAlive(gBattlerAttacker)
-             && IsBattlerTurnDamaged(gBattlerTarget)
+             && IsBattlerTurnDamaged(gBattlerTarget, FALSE)
```
Comment (AlexOn1ine) [inline src/battle_util.c]: missing constant

**Comment by hedara90** [comment]
Review comments addressed

**Comment by AlexOn1ine** [comment]
@PhallenTree can be merged from my side. Feel free to merge
