### PR TITLE
Make movelist calculations happen during compilation instead of runtime

### LINKED ISSUE #7960: Accessing array out of bonds in HGSS dex movelist
### Description

```
#define MOVES_COUNT_TOTAL (EGG_MOVES_ARRAY_COUNT + MAX_LEVEL_UP_MOVES + NUM_ALL_MACHINES)
EWRAM_DATA static u16 sStatsMoves[MOVES_COUNT_TOTAL] = {0};
```
The size of the sStatsMoves array doesn't take into account tutor moves so if a pokemon move contain enough tutor moves for its movelist to be longer than EGG_MOVES_ARRAY_COUNT + MAX_LEVEL_UP_MOVES + NUM_ALL_MACHINES, it would start using the array out of bounds (In my testing, this doesn't cause any bug)

### Reproduction Steps

We can trigger the OOB with Mew by adding extra tutor moves to default expansion
These config need to be set up:
`POKEDEX_PLUS_HGSS` needs to be TRUE
`HGSS_SORT_TMS_BY_NUM` needs to be TRUE so that TMs are added to Mew move list
`P_TUTOR_MOVES_ARRAY` needs to be true so that Tutor moves are added to Mew move list

In a script, I add 
```
setvar VAR_0x8005, MOVE_MALIGNANT_CHAIN
setvar VAR_0x8005, MOVE_UPPER_HAND
setvar VAR_0x8005, MOVE_PSYCHIC_NOISE
setvar VAR_0x8005, MOVE_SUPERCELL_SLAM
setvar VAR_0x8005, MOVE_TEMPER_FLARE
setvar VAR_0x8005, MOVE_ALLURING_VOICE
setvar VAR_0x8005, MOVE_DRAGON_CHEER
setvar VAR_0x8005, MOVE_HARD_PRESS
setvar VAR_0x8005, MOVE_TACHYON_CUTTER
setvar VAR_0x8005, MOVE_MIGHTY_CLEAVE
setvar VAR_0x8005, MOVE_THUNDERCLAP
setvar VAR_0x8005, MOVE_BURNING_BULWARK
setvar VAR_0x8005, MOVE_FICKLE_BEAM
setvar VAR_0x8005, MOVE_IVY_CUDGEL
setvar VAR_0x8005, MOVE_SYRUP_BOMB
setvar VAR_0x8005, MOVE_MATCHA_GOTCHA
setvar VAR_0x8005, MOVE_BLOOD_MOON
setvar VAR_0x8005, MOVE_HYDRO_STEAM
setvar VAR_0x8005, MOVE_PSYBLADE
```
somewhere so that all these moves are added to the move tutor list

### Images / Video

I set up two debugprintf commands
`DebugPrintf("MOVES_COUNT_TOTAL: %d", MOVES_COUNT_TOTAL);` in  `static bool8 CalculateMoves(void)`
and 
`DebugPrintf("selected %d\nGetMoveName(sStatsMoves[selected]) %S", selected, GetMoveName(sStatsMoves[selected]));` in `static void PrintStatsScreen_Moves_Top(u8 taskId)`

This is what I did:

https://github.com/user-attachments/assets/fa570e7b-f936-4b91-b24a-c94c404028b3

and this is the log result:
```
[WARN] GBA Debug:	MOVES_COUNT_TOTAL: 97
[WARN] GBA Debug:	selected 0
GetMoveName(sStatsMoves[selected]) Pound
[WARN] GBA Debug:	selected 1
GetMoveName(sStatsMoves[selected]) Reflect Type
[WARN] GBA Debug:	selected 2
GetMoveName(sStatsMoves[selected]) Amnesia
[WARN] GBA Debug:	selected 3
GetMoveName(sStatsMoves[selected]) Baton Pass
[WARN] GBA Debug:	selected 4
...
[WARN] GBA Debug:	selected 95
GetMoveName(sStatsMoves[selected]) Mighty Cleave
[WARN] GBA Debug:	selected 96
GetMoveName(sStatsMoves[selected]) Mimic
[WARN] GBA Debug:	selected 97
GetMoveName(sStatsMoves[selected]) Mud-Slap
[WARN] GBA Debug:	selected 98
GetMoveName(sStatsMoves[selected]) Psyblade
[WARN] GBA Debug:	selected 99
GetMoveName(sStatsMoves[selected]) Psychic Noise
[WARN] GBA Debug:	selected 100
GetMoveName(sStatsMoves[selected]) Psych Up
[WARN] GBA Debug:	selected 101
GetMoveName(sStatsMoves[selected]) Rock Slide
[WARN] GBA Debug:	selected 102
GetMoveName(sStatsMoves[selected]) Rollout
[WARN] GBA Debug:	selected 103
GetMoveName(sStatsMoves[selected]) Sleep Talk
[WARN] GBA Debug:	selected 104
GetMoveName(sStatsMoves[selected]) Snore
[WARN] GBA Debug:	selected 105
GetMoveName(sStatsMoves[selected]) Soft-Boiled
[WARN] GBA Debug:	selected 106
GetMoveName(sStatsMoves[selected]) Substitute
[WARN] GBA Debug:	selected 107
GetMoveName(sStatsMoves[selected]) Supercell Slam
[WARN] GBA Debug:	selected 108
GetMoveName(sStatsMoves[selected]) Swagger
[WARN] GBA Debug:	selected 109
GetMoveName(sStatsMoves[selected]) Swift
[WARN] GBA Debug:	selected 110
GetMoveName(sStatsMoves[selected]) Swords Dance
[WARN] GBA Debug:	selected 111
GetMoveName(sStatsMoves[selected]) Syrup Bomb
[WARN] GBA Debug:	selected 112
GetMoveName(sStatsMoves[selected]) Tachyon Cutter
[WARN] GBA Debug:	selected 113
GetMoveName(sStatsMoves[selected]) Temper Flare
[WARN] GBA Debug:	selected 114
GetMoveName(sStatsMoves[selected]) Thunderclap
[WARN] GBA Debug:	selected 115
GetMoveName(sStatsMoves[selected]) Thunder Punch
[WARN] GBA Debug:	selected 116
GetMoveName(sStatsMoves[selected]) Thunder Wave
[WARN] GBA Debug:	selected 117
GetMoveName(sStatsMoves[selected]) Upper Hand
```

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Description
A lot of calculations used to happen to make sure a move was a valid part of a pokemon moveset and to properly order them when showing the movelist in the HGSS dex. With this PR, make_teachable.py generates the exact learnset for every pokemon in the order chosen by the config. 
This make the code checking if a move is available to learn a lot easier.
This allow the movelist to simply read the moves from the ROM in order instead of allocating memory to store an ordered list.
And it gives developers the possibility to change universal moves, to make a pokemon able to learn every etachable like Mew without touching stuff hardcoded in the pokemon.c file
I also added a new intermediate file in the learnset building process called make_tutors.py . make_teachables.py used to check every .inc files for added move tutors. This meant that every time a .inc filewould be changed, make_teachables would be run and pokemon.c would be recompiled. By separating the step checking for tutor moves. make_teachables will only run when a move tutor is added not just when a .inc file is changed

## Issue(s) that this PR fixes
This PR also fixes #7960

## Feature(s) this PR does NOT handle:
The new make_teachables.py could probably be optimised. Lhea did a great job making the previous version run very fast using python iterables. This is probably not as good

## Things to note in the release changelog:
- tmIlliterate flag in speciesInfo changed to teachingType. The options are `DEFAULT_LEARNING`, `TM_ILLITERATE` and `ALL_TEACHABLES`. The first two options match the tmIlliterate = false and tmIlliterate = true while the third one allow a pokemon to learn all teachables similarly to Mew
- Reduce EWRAM usage of HGSS dex
- Fix pokemon.c needing to be recompiled everytime a .inc file was changed
- P_TUTOR_MOVES_ARRAY has been removed (now always true when HGSS dex is enabled)
- Mew move teaching exception and univeral moves are now coded in the JSON file `src/data/pokemon/special_movesets.json` under the name signatureTeachables and universalMoves 

## Discord contact info
Jamie (foster_harmony)

### CODE REVIEW

File: src/pokedex_plus_hgss.c [hunk 1]
```diff
@@ -5289,12 +5293,16 @@ static void PrintStatsScreen_Moves_Description(u8 taskId)
...
+    #undef moves_x
+    #undef moves_y
 }
 
 static void PrintStatsScreen_Moves_BottomText(u8 taskId)
 {
-    u8 moves_x = 8;
-    u8 moves_y = 3;
+    #define moves_x 8
+    #define moves_y 3
```
Comment (rayrobdod) [inline src/pokedex_plus_hgss.c]: Under `-O2`, gcc is able to figure out when variables are effectively constant and that those variables can be constant-folded. <https://godbolt.org/z/c8szqvnG5>. Therefore, this replacing of effectively-constant variables with `#define`s is making the source code worse (with having to `#undef` to keep the values scopes limited to one method) while not improving the generated byte code at all.

**Comment by FosterProgramming** [comment]
I'm very happy with this iteration of the PR changing the HGSS dex movelist. Less unecessarry compile steps, simpler C code and less memory usage. Ready for review!

File: include/constants/teaching_types.h [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+Allow a pokemon to learn all universal moves
+*/
+
+#define TM_ILLITERATE       1
+/* TM_ILLITERATE
+Vanilla uses: pokemon with "gimmick" moveset (Ditto, Smeargle, Magikarp, ...)
+Pokemon can't learn any universal moves (unless it was added to their teachable learnset)
+*/
+
+#define ALL_TEACHABLES      1
```
Comment (AlexOn1ine) [inline include/constants/teaching_types.h]: shouldn't this be a 2?

Comment (AlexOn1ine) [reply include/constants/teaching_types.h]: also the comments should probably be above the define.

Comment (FosterProgramming) [reply include/constants/teaching_types.h]: It could be a 2 but that would mean using an additional bit for a parameter that is not used. Because the data is only used/read by the python script, we can make the actual text of the define be what matters. 
I don't know what happens if we try to assign something >= 2 to something with a bitfield of 1, (do bitfield 0 even work ?). So we could do in many ways: 
- use the text as an actual value
- assign more bits in case we change the implementation and want to use the value in ROM
- assign 1 (or maybe 0) bit but still put bigger numbers in the define (not sure if this works)

File: include/pokemon.h [hunk 3]
```diff
@@ -909,5 +908,7 @@ struct Pokemon *GetSavedPlayerPartyMon(u32 index);
 u8 *GetSavedPlayerPartyCount(void);
 void SavePlayerPartyMon(u32 index, struct Pokemon *mon);
 u32 IsSpeciesOfType(u32 species, u32 type);
+u32 GetUniversalMovesCount(void);
+u32 GetTutorMovesCount(void);
```
Comment (AlexOn1ine) [inline include/pokemon.h]: those don't seem to be used anywhere?

File: include/constants/teaching_types.h (hunk 2 above)
Comment (AlexOn1ine) [reply include/constants/teaching_types.h]: Ah I see. Yeah, if it's only used by the python script it makes sense to do it like that. 

It's not very obvious from reading that so we probably should add a comment explaining why we can have it set to 1 since I think someone else could make the same mistake as me. Especially if people want to add more "modes"

Comment (FosterProgramming) [reply include/constants/teaching_types.h]: There are comments already, what changes to them would you suggest?

Comment (AlexOn1ine) [reply include/constants/teaching_types.h]: Actually, it's probably fine like it is.

**Comment by FosterProgramming** [comment]
I updated the PR with Alex's suggested changes.
