### PR TITLE
Should switch refactor to facilitate switch prediction

### LINKED ISSUE #5119: Full Test Suite for ShouldSwitch Function
### Description

#5089 made me aware of the fact that while the "what mon should the AI send our" code has a pretty thorough testing suite, the "when should the AI switch" code doesn't. I'd like to have tests written similar to what I did for HasBadOdds for all of the sub functions in `ShouldSwitch` so we can make sure everything is working properly moving forward, as things could even be broken now and we wouldn't know it.

To be clear I am absolutely intending to work on addressing this myself, I'm just making an issue for it as I'm really crazy busy at the moment and I'm not certain when I'll get it finished. It's at the top of my hacking priority list :)

### Version

1.9.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

@pawkkie

### LINKED ISSUE #5217: AI takes advantage of "free" turns
### Description

When the AI sees that the enemy is locked into a [move with a charging turn](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_with_a_charging_turn), the AI should make decisions accordingly

### Discord contact info

Pawkkie

### LINKED ISSUE #5509: Improve Toxic Switch AI
### Description

As per discussion in #5462, "AI_FLAG_SMART_SWITCHING: AI will switch out if it has been Toxic'd for at least two turns 50% of the time with more than 1/3 HP remaining" is questionable behaviour at best and actively awful at worst as it just gives the player free damage on an incoming mon. Cases involving HP thresholds etc. should at this point be much better handled by other functions like `HasBadOdds`.

Was out of scope for that PR, is probably out of scope for #5466 but maybe. Leaving a note here so we don't forget.

### Discord contact info
@Pawkkie

### LINKED ISSUE #5534: AI calc speed dropped significantly
### Description

For some reason the AI delay got much worse since I last checked. It was at 49 frames previously and increased to 71. I haven't checked on master yet but this is something we have to fix in my view. 

image

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description

Refactoring `ShouldSwitch` in preparation for switch prediction. The AI will only be able to predict "Should I switch?" using this function, and not any specific cases where `ShouldSwitch` overrides the result of `GetMostSuitableMonToSwitchInto`, which is how it predicts which mon is coming in, which is why this refactor and its precursors are necessary. Should be able to address that in the future prediction PR though.

This fixes a significant amount of hypothetically-functional aspects of `ShouldSwitch` that weren't working as intended, as well as overhauling / simplifying a few functions to fully isolate `ShouldSwitch` from the move scoring code.

The majority of the new code is a full test suite for all of the `ShouldSwitch` functions, and tweaking existing functions to be compatible with `PASSES_RANDOMLY`.

## New KNOWN_FAILING Tests
`AI_FLAG_SMART_SWITCHING: AI will switch out if Encore'd into neutral move with good switchin 50% of the time`: Fails on clean upcoming before this PR as well, so the refactor is not the cause. This fails because the mon switches 100% of the time instead of 50% of the time, even if `ShouldSwitch` is adjusted such that it immediately returns false. This likely means that something somewhere else in the codebase is triggering switches, and I have not been able to find it.

`AI recognizes Volt Absorb received from Trace`: Fails due to mgriffin's [fix](https://github.com/Pawkkie/pokeemerald-expansion/pull/6) for AI tests being unable to handle two turn moves (Dive, Solar Beam, etc.) for an unknown reason. This is out of the scope of this PR, and if it's still failing by the time of merge, I'll make an issue so we don't forget.

## Issue(s) that this PR fixes
Closes #5217 
Closes #5119
Closes #5509 
Fixes #5534 

## **Discord contact info**
@Pawkkie

### CODE REVIEW

File: src/battle_ai_switch_items.c [hunk 1]
```diff
@@ -65,30 +65,16 @@ void GetAIPartyIndexes(u32 battler, s32 *firstId, s32 *lastId)
     }
 }
 
-bool32 IsSwitchinIdValid(u32 battler, u32 switchinId)
+bool32 SetSwitchinAndSwitch(u32 battler, u32 switchinId)
```
Comment (AlexOn1ine) [inline src/battle_ai_switch_items.c:68]: does this need to be a function? If you want it to keep it a function it should probably be a static inline

File: src/battle_main.c [hunk 2]
```diff
@@ -4202,14 +4202,21 @@ static void HandleTurnActionSelectionState(void)
...
+
+                // Setup battler data
+                sBattler_AI = battler;
+                BattleAI_SetupAIData(0xF, sBattler_AI);
+
+                // Setup switching data
                 if (AI_THINKING_STRUCT->aiFlags[battler] & AI_FLAG_RISKY) // Risky AI switches aggressively even mid battle
                     AI_DATA->mostSuitableMonId[battler] = GetMostSuitableMonToSwitchInto(battler, TRUE);
                 else
                     AI_DATA->mostSuitableMonId[battler] = GetMostSuitableMonToSwitchInto(battler, FALSE);
```
Comment (AlexOn1ine) [inline src/battle_main.c:4214]:
```
u32 isAiRisky = AI_THINKING_STRUCT->aiFlags[battler] & AI_FLAG_RISKY;                 

AI_DATA->mostSuitableMonId[battler] = GetMostSuitableMonToSwitchInto(battler, isAiRisky);
```
Evaluate isAiRisky at the top of `HandleTurnActionSelectionState` so it isn't checked in each iteration.

**Review by AlexOn1ine — COMMENTED** [review]
Just skimmed over. Will look closer into `HandleTurnActionSelectionState` later

File: src/battle_ai_switch_items.c (hunk 1 above)
Comment (Pawkkie) [reply src/battle_ai_switch_items.c:68]: It doesn't need to be after moving the bugfix, but I'd prefer we keep it one, cuz I like
```
return SetSwitchinAndSwitch(battler, PARTY_SIZE);
```
a lot better than
```
  {
      gBattleStruct->AI_monToSwitchIntoId[battler] = switchinId;
      return TRUE;
  }
```
cuz it's shorter and faster to write. If I get around to refactoring this into one big function instead of several little ones I'd remove it then but I'd prefer to keep it for now if that's cool :)

Comment (AlexOn1ine) [reply src/battle_ai_switch_items.c:68]: That's fair but I think it could be a simple static inline then, right? Also capitalize `i`

Comment (Pawkkie) [reply src/battle_ai_switch_items.c:68]: Yeah totally am in the middle of pushing that! :D 

You mean `SetSwitchInAndSwitch`? Most of the code I've written refers to the incoming mon as a "Switchin" so I'd prefer to keep it decapped if that's the `i` you're talking about, ie `switchinCandidate`

Comment (AlexOn1ine) [reply src/battle_ai_switch_items.c:68]: ah, okay

File: src/battle_main.c (hunk 2 above)
Comment (Pawkkie) [reply src/battle_main.c:4214]: Here, or above the for loop (I think that won't work cuz we don't have `battler` yet?)
```diff
static void HandleTurnActionSelectionState(void)
{
    s32 i, battler;

    gBattleCommunication[ACTIONS_CONFIRMED_COUNT] = 0;
    for (battler = 0; battler < gBattlersCount; battler++)
    {
        u32 position = GetBattlerPosition(battler);
+       u32 isAiRisky = AI_THINKING_STRUCT->aiFlags[battler] & AI_FLAG_RISKY; // Risky AI switches aggressively even mid battle
        switch (gBattleCommunication[battler])
        {
        case STATE_TURN_START_RECORD: // Recorded battle related action on start of every turn.
 ```

Comment (AlexOn1ine) [reply src/battle_main.c:4214]: oops, right. then keep it inside the actual case but I still think making the var is good because it makes then code more readable

Comment (Pawkkie) [reply src/battle_main.c:4214]: Yep super agree, pushing now :)

File: src/battle_main.c [hunk 3]
```diff
@@ -4191,6 +4191,7 @@ static void HandleTurnActionSelectionState(void)
     for (battler = 0; battler < gBattlersCount; battler++)
     {
         u32 position = GetBattlerPosition(battler);
+        u32 isAiRisky = AI_THINKING_STRUCT->aiFlags[battler] & AI_FLAG_RISKY; // Risky AI switches aggressively even mid battle
```
Comment (AlexOn1ine) [inline src/battle_main.c:4194]: Since we can't do it at function scope it makes more since to do it inside `STATE_TURN_START_RECORD` because otherwise it will assign the variable for each state

**Review by AlexOn1ine — APPROVED** [review]
