### PR TITLE
Fix match call regression

### LINKED ISSUE #8212: Trainers with Match Call rematches will notice the trainer and then get stuck in a loop
### Description

Any trainer with a rematch available will notice the player instead of waiting to be approached. Once the battle is over, the trainer will get stuck in a loop of repeatedly noticing the player and saying their post-battle text

### Reproduction Steps

_No response_

### Images / Video

Image

### Version

upcoming (Edge)

### Upcoming/master Version

2b48fc180186ba1a78f9aeb42e500c995e44f6c5

### Discord contact info

Frankfurter0

### PR DESCRIPTION
**Pull request by FosterProgramming**
Fixes regression introduced in #8156 because I only tested VS seeker but it broke match call

## Media
master

https://github.com/user-attachments/assets/29eb2d7f-589c-41a3-879c-0f374eea409f

this commit:

https://github.com/user-attachments/assets/67e74a49-6b04-4beb-b641-3cbd3925c831

## Issue(s) that this PR fixes
Fixes #8212

## Discord contact info
Jamie

### CODE REVIEW

File: src/trainer_see.c [hunk 1]
```diff
@@ -474,7 +474,7 @@ static u8 CheckTrainer(u8 objectEventId)
         if (GetTrainerFlagFromScriptPointer(trainerBattlePtr))
         {
             //If there is a rematch, we want to trigger the approach sequence
-            if (GetRematchFromScriptPointer(trainerBattlePtr))
+            if (GetRematchFromScriptPointer(trainerBattlePtr) && I_VS_SEEKER_CHARGING)
```
Comment (Bassoonian) [inline src/trainer_see.c]:
```suggestion
            if (I_VS_SEEKER_CHARGING && GetRematchFromScriptPointer(trainerBattlePtr))
```
Configs always go first so the compiler can optimise them out

**Review by Bassoonian — APPROVED** [review]
