### PR TITLE
Fix Shed Shell allowing fleeing/teleporting and Smoke Ball failing to guarantee escape

### LINKED ISSUE #7655: Shed Shell allows you to unconditionally flee/teleport from battles, and roamers can't always flee with smoke ball
### Description

From https://bulbapedia.bulbagarden.net/wiki/Shed_Shell
> Allows the holder to [switch out](https://bulbapedia.bulbagarden.net/wiki/Recall) (but not [flee](https://bulbapedia.bulbagarden.net/wiki/Escape) or [Teleport](https://bulbapedia.bulbagarden.net/wiki/Teleport_(move))) even if it is under the effect of a [trapping move](https://bulbapedia.bulbagarden.net/wiki/Category:Trapping_moves) or [Ability](https://bulbapedia.bulbagarden.net/wiki/Category:Trapping_Abilities).

Running from the Run option in the menu:
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_main.c#L4426-L4428

IsRunningFromBattleImpossible:
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_main.c#L4056-L4104

CanBattlerEscape:
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_util.c#L5515-L5520

So Shed Shell bypasses the impossibility check (but doesn't always guarantee running)

Also with Teleport
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/data/battle_scripts_1.s#L4224-L4239

Calls IsRunningFromBattleImpossible, which suffers from the Shed Shell check
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_script_commands.c#L16935-L16940

Also, for opponent pokemon that can flee (e.g. Roamers)
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_util.c#L744-L754

Calls CanBattlerEscape which checks for shed shell, but doesn't check for smoke ball

### Reproduction Steps

N/A, source code analysis

### Images / Video

_No response_

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by moostoet**
## Description
This PR fixes two related issues regarding escape mechanics and hold items:

1.  **Shed Shell**: Previously, Shed Shell allowed the holder to unconditionally flee or Teleport from battle, even when trapped (e.g., by Mean Look or Shadow Tag). This behavior was incorrect; Shed Shell should only guarantee the ability to **switch** out.
    *   Removed the `HOLD_EFFECT_SHED_SHELL` check from `CanBattlerEscape`.
    *   Added an explicit check for `HOLD_EFFECT_SHED_SHELL` in the "Switch" action handler (`HandleInputChooseAction` in `battle_main.c`) to allow manual switching when trapped.
    *   Added an explicit check for `HOLD_EFFECT_SHED_SHELL` in `Cmd_jumpifcantswitch` (`battle_script_commands.c`) to allow pivoting moves like U-turn and Baton Pass to work when trapped.

2.  **Smoke Ball / Run Away**: Opponents (such as Roaming Pokémon) could not always flee if they were considered "trapped" by `CanBattlerEscape`, even if they held a Smoke Ball or had the Run Away ability.
    *   Updated the opponent run logic (`HandleAction_Run` in `battle_util.c`) to explicitly check for `HOLD_EFFECT_CAN_ALWAYS_RUN` and `ABILITY_RUN_AWAY`, granting escape even if `CanBattlerEscape` returns `FALSE`.

## Issue(s) that this PR fixes
Fixes #7655.

## Discord contact info
viridian.

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
> Added an explicit check for HOLD_EFFECT_SHED_SHELL in Cmd_jumpifcantswitch (battle_script_commands.c) to allow pivoting moves like U-turn and Baton Pass to work when trapped.

Don't switch out moves bypass trapping without Shed Shell?

**Comment by moostoet** [comment]
@AlexOn1ine Yeah, they already do through the flag `SWITCH_IGNORE_ESCAPE_PREVENTION`, so what I said was basically a bit of a misnomer. I meant to say it in a more general manner because the check being moved there would also allow for other methods (like switch battle style) to work there, etc.

**Comment by AlexOn1ine** [comment]
> @AlexOn1ine Yeah, they already do through the flag `SWITCH_IGNORE_ESCAPE_PREVENTION`, so what I said was basically a bit of a misnomer. I meant to say it in a more general manner because the check being moved there would also allow for other methods (like switch battle style) to work there, etc.

Isn't the test `Shed Shell allows switching out via U-turn even when trapped` redundant then?

**Comment by moostoet** [comment]
> > @AlexOn1ine Yeah, they already do through the flag `SWITCH_IGNORE_ESCAPE_PREVENTION`, so what I said was basically a bit of a misnomer. I meant to say it in a more general manner because the check being moved there would also allow for other methods (like switch battle style) to work there, etc.
> 
> Isn't the test `Shed Shell allows switching out via U-turn even when trapped` redundant then?

Correct, will remove when home

**Comment by moostoet** [comment]
@AlexOn1ine Removed unnecessary tests

File: src/battle_util.c [hunk 1]
```diff
@@ -733,7 +733,9 @@ void HandleAction_Run(void)
         }
         else
         {
-            if (!CanBattlerEscape(gBattlerAttacker))
+            if (GetBattlerHoldEffect(gBattlerAttacker, TRUE) != HOLD_EFFECT_CAN_ALWAYS_RUN
```
Comment (AlexOn1ine) [inline src/battle_util.c:736]: does shed shell not work for roamers?

Comment (moostoet) [reply src/battle_util.c:736]: This is in `HandleAction_Run`, and I don't think Shed Shell allows for fleeing/running, but only allows switching out. as according to the issue description
