### PR TITLE
Fade background and sprites simulatneously

### LINKED ISSUE #9327: Minor graphical glitch when opening and closing menu in hotspring
### Description

The bottom part of player and npc sprites show this weird artifact when opening and closing the ststt menu

### Reproduction Steps

_No response_

### Images / Video

https://github.com/user-attachments/assets/4ef88991-6127-4a6c-b4ee-422ffd4503ac

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

HunarPG#2786

### PR DESCRIPTION
**Pull request by FosterProgramming**
Rework palette fade to fade background and sprites simulatneously instead of alternating background fade on one frame and sprite frame or another. It fixes some minor graphical error where a sprite supposed to blend with the background doesn't for one frame when fading.
This seems to work fine on emulators but the additional cycles requires may cause issues in some places in the code or on real hardware (this is why it's going to upcoming)

## Media

https://github.com/user-attachments/assets/fc80f244-2fb0-462d-bd35-fb843f2362e9

## Issue(s) that this PR fixes
Fixes #9327 

## Discord contact info
Jamie

### CODE REVIEW

File: src/palette.c [hunk 1]
```diff
@@ -330,87 +309,74 @@ static u8 UpdateTimeOfDayPaletteFade(void)
...
-                return PALETTE_FADE_STATUS_DELAY;
-            }
-            gPaletteFade.delayCounter = 0;
-        }
+        if (selectedPalettes & 1)
+            BlendPalette(
+                paletteOffset,
+                16,
+                gPaletteFade.y,
+                gPaletteFade.blendColor);
```
Comment (hedara90) [inline src/palette.c:344]:
```suggestion
        if (selectedPalettes & 1)
        {
            BlendPalette(
                paletteOffset,
                16,
                gPaletteFade.y,
                gPaletteFade.blendColor);
        }
```
I think this counts as multi-line statement (even if it's just an existing thing that's been moved)
Making it not multi-line also works

**Comment by FosterProgramming** [comment]
PR updated
