### PR TITLE
Fixes Charge effect not boosting and tests

### LINKED ISSUE #6101: Charge doesn't appear to be working
### Description

Image
An Electric type move seems to do the same amount of damage before and after using Charge. It looks like the Charged Up status isn't being set by Charge

### Version

upcoming (Edge)

### Upcoming/master Version

774e61e74a17b295ff62d8a0c088aec4566b8f2d

### Discord contact info

Frankfurter

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6101

The tests for charge didn't work so they didn't catch the bug. They didn't work because no damage was stored in the variables (See: #5977). Using an array fixes it.

### CODE REVIEW

File: test/battle/move_effect/charge.c [hunk 1]
```diff
@@ -125,24 +117,22 @@ SINGLE_BATTLE_TEST("Charge's effect is removed regardless if the next move is El
...
 
 SINGLE_BATTLE_TEST("Charge will not expire if it flinches twice in a row")
 {
-    s16 normalDamage = 0;
-    s16 chargedUpDamage = 0;
-
+    s16 damage[2];
     GIVEN {
         PLAYER(SPECIES_WOBBUFFET);
          OPPONENT(SPECIES_WOBBUFFET) { Item(ITEM_LUM_BERRY); }
```
Comment (hedara90) [inline test/battle/move_effect/charge.c:138]:
```suggestion
         ASSUME(gMovesInfo[MOVE_IRON_HEAD].additionalEffects[0].moveEffect == MOVE_EFFECT_FLINCH); 
         PLAYER(SPECIES_WOBBUFFET);
         OPPONENT(SPECIES_WOBBUFFET) { Item(ITEM_LUM_BERRY); }
```

**Review by hedara90 — APPROVED** [review]
