### PR TITLE
Fix destiny knot behavior and add tests

### LINKED ISSUE #8132: Destiny Knot doesn't check for infatuation eligiblity
### Description

https://github.com/rh-hideout/pokeemerald-expansion/blob/5325c275e60be69d94091dc2f9996d85f1967afa/data/battle_scripts_1.s#L3510-L3532

`infatuatewithbattler` only just calls a native function
https://github.com/rh-hideout/pokeemerald-expansion/blob/5325c275e60be69d94091dc2f9996d85f1967afa/asm/macros/battle_script.inc#L1941-L1945

`BS_InfatuateWithBattler` doesn't check for eligibility at all
https://github.com/rh-hideout/pokeemerald-expansion/blob/5325c275e60be69d94091dc2f9996d85f1967afa/src/battle_script_commands.c#L16577-L16584

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
Thanks to Linathan https://discord.com/channels/419213663107416084/1368163973366681712/1436532616395358278
We figured that infatuation from a destiny knot source seem to behave the same as from an Attract source so I removed the infatuatebattler macro/callnative to use tryinfatuate (the command used in Attract) instead
We also added Destiny Knot tests

## Media
Video of the tests:

https://github.com/user-attachments/assets/9e847b4d-21c9-4f46-a0b9-ec014a856809

## Issue(s) that this PR fixes
Fixes #8132

## Discord contact info
Jamie

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Instead of swapping targets with each other I would combine the scripts `BattleScript_TryDestinyKnotTarget` and `BattleScript_TryDestinyKnotAttacker` to `BattleScript_TryDestinyKnot` and use `BS_EFFECT_BATTLER` as the argument instead of `BS_ATTACKER / BS_TARGET`. To assign the battlers you can do `copyvar gEffectBattler, gBattlerAttacker/gBattlerTarget`

**Comment by FosterProgramming** [comment]
> Instead of swapping targets with each other I would combine the scripts `BattleScript_TryDestinyKnotTarget` and `BattleScript_TryDestinyKnotAttacker` to `BattleScript_TryDestinyKnot` and use `BS_EFFECT_BATTLER` as the argument instead of `BS_ATTACKER / BS_TARGET`. To assign the battlers you can do `copyvar gEffectBattler, gBattlerAttacker/gBattlerTarget`

But I need to save two battlers. If I put the destiny know holder in `BS_EFFECT_BATTLER`, where do I store the other one, just BS_TARGET?

**Comment by AlexOn1ine** [comment]
> > Instead of swapping targets with each other I would combine the scripts `BattleScript_TryDestinyKnotTarget` and `BattleScript_TryDestinyKnotAttacker` to `BattleScript_TryDestinyKnot` and use `BS_EFFECT_BATTLER` as the argument instead of `BS_ATTACKER / BS_TARGET`. To assign the battlers you can do `copyvar gEffectBattler, gBattlerAttacker/gBattlerTarget`
> 
> But I need to save two battlers. If I put the destiny know holder in `BS_EFFECT_BATTLER`, where do I store the other one, just BS_TARGET?

why do you need both battlers? nevermind for the message

it's all good then

File: test/battle/hold_effect/destiny_knot.c [hunk 1]
```diff
@@ -0,0 +1,61 @@
+#include "global.h"
+#include "test/battle.h"
+
```
Comment (AlexOn1ine) [inline test/battle/hold_effect/destiny_knot.c:3]: Could you add an assumption a the top for the destiny knot hold effect?
