### PR TITLE
Ai battle tests + ai logic fixes

### LINKED ISSUE #3130: Possible issue with AI move choice on killing rolls
### Description

Currently the AI picks a random move between all moves that see a kill, including moves with lower accuracy. (Somewhat discussed in PR #3109)
pokeemerald-8

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #3153: AI isn't picking the best move possible to faint the target
### Description

If both moves are super effective the AI picks one randomly without considering the damage the moves are doing. 

pokeemerald-20
pokeemerald-19

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by DizzyEggg**
The long awaited AI tests which should help get rid of all the popping issues related to AI, as well as improve it overall.

Replaces #2871
Fixes #3130 with tests
Fixes #3153 with tests

I implemented it differently than griffin(for example the log functionality or expected moves), but the general idea is the same. Having some way of making sure AI behaves the way we want it to behave.

The new `AI_BATTLE_TEST` and `AI_DOUBLE_BATTLE_TEST` follow the same rules as regular battle tests. The only difference is in `GIVEN` and `TURN`.
In `GIVEN`, using `AI_FLAGS`, we specify which flags AI has for the test.
In  `OPPONENT` we have to specify all moves the AI has.
`TURN` is different in that we don't control the opponent, but rather guess what it'll do. And if we guess correctly, that is AI does what we want, the test passes. Instead of `MOVE`, `SEND_OUT` and `SWITCH` there are `EXPECTED_MOVE`, `EXPECTED_SEND_OUT` and `EXPECTED_SWITCH`. These command work the same as their regular counterparts.

Note, for `EXPECTED_MOVE` there are 3 possible variants:
- `EXPECTED_MOVES` - same as `EXPECTED_MOVE` but allows more than one move. Useful when there are several valid moves for the AI to choose from.
- `NOT_EXPECTED_MOVE` - reverse of  `EXPECTED_MOVE`. Test fails if AI decides to use specified move. Useful when we want to make sure the objectively bad move in a certain situation is never gonna be used.
- `NOT_EXPECTED_MOVES` - same as above, but specifies that neither of the given moves are going to be used.

New `SCORE` commands. Apart from the above, there is another way of checking the correctness of AI's logic by comparing the AI scores. We can compare one move's score to another's or one move's score to a specific value. 
We compare the values using `EQ`, `LT`, `NE` and `GT` which correspond to equal, less than, not equal and greater than.
The 8 possible combinations are then:
```
SCORE_EQ
SCORE_NE
SCORE_GT
SCORE_LT
SCORE_EQ_VAL
SCORE_NE_VAL
SCORE_GT_VAL
SCORE_LT_VAL
```

I wrote a couple of tests already for this PR, so it'll hopefully be more clear with the examples.
I also fixed some fixes(xd) from #3199 with tests to confirm.

Note: Nothing in this PR is set for stone, so any feedback is greatly appreciated :)

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Everything passes now. I won't add anything new to this PR, so it should be ready to ~~merge~~  review.

File: include/test/battle.h [hunk 1]
```diff
@@ -864,6 +965,11 @@ struct ItemContext
 void OpenTurn(u32 sourceLine);
 void CloseTurn(u32 sourceLine);
 void Move(u32 sourceLine, struct BattlePokemon *, struct MoveContext);
+void ExpectedMove(u32 sourceLine, struct BattlePokemon *, struct MoveContext);
+void ExpectedMoves(u32 sourceLine, struct BattlePokemon *battler, bool32 notExpected, struct FourMoves moves);
+void ExpectedSendOut(u32 sourceLine, struct BattlePokemon *battler, u32 partyIndex);
+void ExpectedSwitch(u32 sourceLine, struct BattlePokemon *battler, u32 partyIndex);
+void Score(u32 sourceLine, struct BattlePokemon *battler, u32 cmp, bool32 toValue, struct TestAiScoreStruct cmpCtx);
```
Comment (mrgriffin) [inline include/test/battle.h:972]: Maybe consider calling this `ExpectScore` or `ExpectScoreCompare` or something?
```suggestion
void Score(u32 sourceLine, struct BattlePokemon *battler, u32 cmp, bool32 toValue, struct TestAIScoreStruct cmpCtx);
```

File: include/test/battle.h [hunk 2]
```diff
@@ -864,6 +965,11 @@ struct ItemContext
 void OpenTurn(u32 sourceLine);
 void CloseTurn(u32 sourceLine);
 void Move(u32 sourceLine, struct BattlePokemon *, struct MoveContext);
+void ExpectedMove(u32 sourceLine, struct BattlePokemon *, struct MoveContext);
+void ExpectedMoves(u32 sourceLine, struct BattlePokemon *battler, bool32 notExpected, struct FourMoves moves);
+void ExpectedSendOut(u32 sourceLine, struct BattlePokemon *battler, u32 partyIndex);
+void ExpectedSwitch(u32 sourceLine, struct BattlePokemon *battler, u32 partyIndex);
```
Comment (mrgriffin) [inline include/test/battle.h:971]: If you do change to `EXPECT_MOVE` etc, then I'd rename these too.

File: test/test_runner_battle.c [hunk 3]
```diff
@@ -711,6 +754,299 @@ void TestRunner_Battle_RecordHP(u32 battlerId, u32 oldHP, u32 newHP)
...
+            u32 moveId1 = gBattleMons[battlerId].moves[scoreCtx->moveSlot1];
+            s32 target = scoreCtx->target;
+            s32 *scores = gBattleStruct->aiFinalScore[battlerId][target];
+
+            //for (i = 0; i < MAX_MON_MOVES; i++)
+            //{
+                //MgbaPrintf_("Target = %d\n", target);
+                //MgbaPrintf_("Score %d: %d", i+1, scores[i]);
+            //}
+
```
Comment (mrgriffin) [inline test/test_runner_battle.c:1005]:
```suggestion
```

File: test/test_runner_battle.c [hunk 4]
```diff
@@ -812,6 +1148,7 @@ static s32 TryMessage(s32 i, s32 n, const u8 *string)
             continue;
 
         event = &DATA.queuedEvents[i].as.message;
+        // MgbaPrintf_("Looking for: %S Found: %S\n", event->pattern, string); // Useful for debugging.
```
Comment (mrgriffin) [inline test/test_runner_battle.c:1151]: Did you mean to keep this? I'm guessing so based on the comment... I wonder if it would be helpful to have a define which turns on test debug logging :thinking:
```suggestion
        // MgbaPrintf_("Looking for: %S Found: %S\n", event->pattern, string); // Useful for debugging.
```

File: test/test_runner_battle.c [hunk 5]
```diff
@@ -1672,13 +2052,157 @@ void ForcedMove(u32 sourceLine, struct BattlePokemon *battler)
     }
 }
 
+static void TryMarkExpectedMove(u32 sourceLine, struct BattlePokemon *battler, struct MoveContext *ctx)
+{
+    s32 battlerId = battler - gBattleMons;
+    u32 moveId, moveSlot, id;
+    s32 target;
+
+    INVALID_IF(DATA.turnState == TURN_CLOSED, "EXPECTED_MOVE outside TURN");
```
Comment (mrgriffin) [inline test/test_runner_battle.c:2061]: I'd add an `INVALID_IF(!IsAITest(), ...);` to this and the other AI-only expected functions.

File: test/test_runner_battle.c [hunk 6]
```diff
@@ -1994,3 +2543,64 @@ u32 TestRunner_Battle_GetForcedAbility(u32 side, u32 partyIndex)
...
+                DATA.aiLogLines[j] = DATA.aiLogLines[i];
+            j++;
+        }
+    }
+
+    if (j == ARRAY_COUNT(DATA.aiLogLines))
+        Test_ExitWithResult(TEST_RESULT_ERROR, "Too many AI log lines");
+
+    return &DATA.aiLogLines[j];
+    */
```
Comment (mrgriffin) [inline test/test_runner_battle.c:2581]:
```suggestion
```

File: include/test/battle.h [hunk 7]
```diff
@@ -199,6 +199,17 @@
  * - Instead of player and opponent there is playerLeft, playerRight,
  *   opponentLeft, and opponentRight.
  *
+ * AI_BATTLE_TEST(name, results...) and AI_DOUBLE_BATTLE_TEST(name, results...)
```
Comment (mrgriffin) [inline include/test/battle.h:202]: I'd call these `AI_SINGLE_BATTLE_TEST` and `AI_DOUBLE_BATTLE_TEST` for consistency with `SINGLE_BATTLE_TEST` and `DOUBLE_BATTLE_TEST`.

File: include/test/battle.h [hunk 8]
```diff
@@ -199,6 +199,17 @@
...
+ * Define battles where opponent mons are controlled by AI, the same that runs
+ * when battling regular Trainers. The flags for AI should be specified by
+ * the AI_FLAGS command.
+ * The rules remain the same as with the SINGLE and DOUBLE battle tests
+ * with some differences:
+ * - opponent's action is specified by the EXPECTED_MOVE(s) / EXPECTED_SEND_OUT / EXPECTED_SWITCH commands
```
Comment (mrgriffin) [inline include/test/battle.h:208]: I think I'd call these `EXPECT_MOVE`(s), `EXPECT_SEND_OUT`, and `EXPECT_SWITCH` for consistency with `EXPECT`/`EXPECT_EQ`/`EXPECT_FASTER`/etc.

File: include/test/battle.h [hunk 9]
```diff
@@ -483,8 +500,9 @@
 #define BATTLE_TEST_STACK_SIZE 1024
 #define MAX_TURNS 16
 #define MAX_QUEUED_EVENTS 25
+#define MAX_EXPECTED_ACTIONS 10
 
-enum { BATTLE_TEST_SINGLES, BATTLE_TEST_DOUBLES, BATTLE_TEST_WILD };
+enum { BATTLE_TEST_SINGLES, BATTLE_TEST_DOUBLES, BATTLE_TEST_WILD, BATTLE_TEST_AI, BATTLE_TEST_AI_DOUBLES };
```
Comment (mrgriffin) [inline include/test/battle.h:505]: I'd call these `BATTLE_TEST_AI_SINGLES` and `BATTLE_TEST_AI_DOUBLES` with consistency with `BATTLE_TEST_SINGLES` and `BATTLE_TEST_DOUBLES`.

File: include/test/battle.h [hunk 10]
```diff
@@ -584,6 +602,42 @@ struct BattlerTurn
     struct TurnRNG rng;
 };
 
+struct ExpectedAiAction
```
Comment (mrgriffin) [inline include/test/battle.h:605]: I'd call this `ExpectedAIAction` with a capital I. I think that's usually how we do our names (although admittedly it's not 100% consistent across the codebase). There's quite a few other examples of `Ai` instead of `AI`, I'd be happy to fix them all if it sounds like too boring to do :sweat_smile:

File: include/test/battle.h [hunk 11]
```diff
@@ -584,6 +602,42 @@ struct BattlerTurn
...
+    u8 toValue:1; // compare to value, not to move
+    u8 set:1;
+    u16 sourceLine;
+};
+
+struct AILogLine
+{
+    const char *file;
+    u16 line:15;
+    u16 set:1; // Weather score was set, or added/subtracted
```
Comment (mrgriffin) [inline include/test/battle.h:637]:
```suggestion
    u16 set:1; // Whether score was set, or added/subtracted
```

File: include/test/battle.h [hunk 12]
```diff
@@ -663,6 +725,17 @@ extern struct BattleTestRunnerState *gBattleTestRunnerState;
...
+#define APPEND_0()
+#define APPEND_1(a) a,
+#define APPEND_2(a, b) a,  b,
+#define APPEND_3(a, b, c) a,  b,  c,
+#define APPEND_4(a, b, c, d) a,  b,  c,  d,
+#define APPEND_5(a, b, c, d, e) a,  b,  c,  d,  e,
+#define APPEND_6(a, b, c, d, e, f) a,  b,  c,  d,  e,  f,
+#define APPEND_7(a, b, c, d, e, f, g) a,  b,  c,  d,  e,  f,  g,
+#define APPEND_8(a, b, c, d, e, f, g, h) a,  b,  c,  d,  e,  f,  g,  h,
+
```
Comment (mrgriffin) [inline include/test/battle.h:738]: It seems like `APPEND(...)` is equivalent to just `...`, so this shouldn't be needed.
```suggestion
```

File: test/battle/ai.c [hunk 13]
```diff
@@ -0,0 +1,413 @@
...
+
+        TURN { MOVE(player, MOVE_PROTECT);  EXPECTED_MOVE(opponent, MOVE_EARTHQUAKE); } // E-quake
+        TURN { SWITCH(player, 1);           EXPECTED_MOVE(opponent, MOVE_EARTHQUAKE); } // E-quake
+        TURN { MOVE(player, MOVE_PROTECT);  EXPECTED_MOVE(opponent, MOVE_THUNDERBOLT); } // T-Bolt
+        TURN { SWITCH(player, 0);           EXPECTED_MOVE(opponent, MOVE_THUNDERBOLT); } // T-Bolt
+        TURN { MOVE(player, MOVE_PROTECT);  EXPECTED_MOVE(opponent, MOVE_EARTHQUAKE); } // E-quake
+        TURN { SWITCH(player, 1);           EXPECTED_MOVE(opponent, MOVE_EARTHQUAKE);} // E-quake
+        TURN { MOVE(player, MOVE_PROTECT);  EXPECTED_MOVE(opponent, MOVE_THUNDERBOLT); } // T-Bolt
+    } SCENE {
+    }
```
Comment (mrgriffin) [inline test/battle/ai.c:23]: We don't have to write empty `SCENE`s, and I would expect most AI tests to not need them :)
```suggestion
    }
```

File: test/battle/ai.c [hunk 14]
```diff
@@ -0,0 +1,413 @@
...
+            TURN { EXPECTED_MOVE(opponent, MOVE_EARTHQUAKE); SEND_OUT(player, 1); }
+    } SCENE {
+        MESSAGE("Gravity intensified!");
+    }
+}
+
+AI_BATTLE_TEST("AI will not switch in a Pokemon which is slower and gets 1HKOed after fainting")
+{
+    bool8 alakazamFaster;
+    u16 speedAlakazm;
```
Comment (mrgriffin) [inline test/battle/ai.c:247]:
```suggestion
    bool32 alakazamFaster;
    u32 speedAlakazm;
```
When there aren't many locals, I'd personally default to using word-sized types.

**Review by mrgriffin — CHANGES_REQUESTED** [review]
AI tests!! :partying_face: 

I'm mostly nitpicking names and syntax here, the work itself looks really solid!

Would you feel up to rebasing and separating the non-test-related changes in, e.g. `battle_ai_util.c` from the test-related changes. If not, I was thinking I'd squash this PR?

File: test/test_runner_battle.c (hunk 4 above)
Comment (DizzyEggg) [reply test/test_runner_battle.c:1144]: Yeah, I'd like to keep it for now

File: include/test/battle.h [hunk 15]
```diff
@@ -819,6 +902,22 @@ enum { TURN_CLOSED, TURN_OPEN, TURN_CLOSING };
 #define TURN for (OpenTurn(__LINE__); gBattleTestRunnerState->data.turnState == TURN_OPEN; CloseTurn(__LINE__))
 
 #define MOVE(battler, ...) Move(__LINE__, battler, (struct MoveContext) { APPEND_TRUE(__VA_ARGS__) })
+
+#define EXPECTED_MOVE(battler, ...) ExpectedMove(__LINE__, battler, (struct MoveContext) { APPEND_TRUE(__VA_ARGS__) })
+#define NOT_EXPECTED_MOVE(battler, _move) ExpectedMove(__LINE__, battler, (struct MoveContext) { .move = _move, .explicitMove = TRUE, .notExpected = TRUE, .explicitNotExpected = TRUE, })
```
[the remark this answers is not in the document]
Comment (DizzyEggg) [reply include/test/battle.h]: I agree with what you said, though I had my reasons for using `MoveContext`. `allowed` is of no use, but I wanted to have an option for potential AI tests to specify things like critical hit, secondary effect and mega evolution. 

As for combining them, I couldn't really think of a way to do that without losing the ability to specify target(Since `EXPECT_MOVES` can't specify the target). I'm kinda blocked with what I have atm. 
Though if you have any ideas, maybe it could be changed 👀

**Comment by DizzyEggg** [comment]
Apart from the things in the previous comments, all of the other requested changes should be submitted.

**Review by mrgriffin — APPROVED** [review]
I'll keep thinking about merging `EXPECT_MOVE` and `EXPECT_MOVES`, but there's no need to hold up the PR waiting for that :)
