### PR TITLE
Shell Trap tests and Fix for Encore interaction

### LINKED ISSUE #5886: Shell Trap tests to verify the behavior
### Description

Source: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Shell_Trap_(move))

### Version

1.10.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Closes #5886

### CODE REVIEW

**Comment by hedara90** [comment]
CI failed

File: test/battle/move_effect/shell_trap.c [hunk 1]
```diff
@@ -214,3 +214,68 @@ SINGLE_BATTLE_TEST("Shell Trap activates if user is hit with a physical move but
         HP_BAR(opponent);
     }
 }
+
+SINGLE_BATTLE_TEST("Encore fails if target has active Shell Trap waiting")
+{
+    GIVEN {
+        ASSUME(GetMovePriority(MOVE_ENCORE) == EFFECT_ENCORE);
```
Comment (PhallenTree) [inline test/battle/move_effect/shell_trap.c]:
```suggestion
        ASSUME(GetMoveEffect(MOVE_ENCORE) == EFFECT_ENCORE);
```
