### PR TITLE
Fix Focus Energy boosting crit by the wrong amount with gen1 crit chance

### LINKED ISSUE #7654: Gen 1 Focus Energy boosts crit by the wrong amount with Gen 1 Crit Chance
### Description

Because with `GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO < GEN_3`, the Dragon Cheer bit is set instead of the Focus Energy bit.

Relevant code:
(`cmd_setfocusenergy`)
```
if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3)
    gBattleMons[battler].volatiles.focusEnergy = TRUE;
else
    gBattleMons[battler].volatiles.dragonCheer = TRUE;
```

(`CalcCritChanceStageGen1`)
```
if (gBattleMons[battlerAtk].volatiles.focusEnergy)
    critChance *= 4;
else if (gBattleMons[battlerAtk].volatiles.dragonCheer)
    critChance *= 2;
```

### Reproduction Steps

-

### Images / Video

_No response_

### Version

1.13.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Issue(s) that this PR fixes
Fixes #7654 

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -11161,7 +11161,8 @@ static void Cmd_setfocusenergy(void)
     }
     else
     {
-        if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3)
+        if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3
+            || GetGenConfig(GEN_CONFIG_CRIT_CHANCE) == GEN_1)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]:
```suggestion
        if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3
       || GetGenConfig(GEN_CONFIG_CRIT_CHANCE) == GEN_1)
```
That's our most common style

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -11161,7 +11161,8 @@ static void Cmd_setfocusenergy(void)
     }
     else
     {
-        if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3)
+        if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3
+       || GetGenConfig(GEN_CONFIG_CRIT_CHANCE) == GEN_1)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]:
```suggestion
        if (GetGenConfig(GEN_CONFIG_FOCUS_ENERGY_CRIT_RATIO) >= GEN_3
         || GetGenConfig(GEN_CONFIG_CRIT_CHANCE) == GEN_1)
```
