### PR TITLE
Fix Magic Coat reflecting hazard moves incorrectly when used by a partner

### LINKED ISSUE #8195: Magic Coat Not Properly Reflecting Hazard Moves
### Description

Magic guard should reflect all hazard types, as the move doesn't/isn't supposed to target. Attached video below to show this failing on latest master.

### Reproduction Steps

Spawned a bulbasaur with magic coat and nothing else, picked torchic, and used the following route 103 fight:

=== TRAINER_MAY_ROUTE_103_TORCHIC ===
Name: MAY
Class: Rival
Pic: May
Gender: Female
Music: Female
Double Battle: Yes
AI: Basic Trainer

Darkrai
Level: 10
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
- Spikes

Darkrai
Level: 10
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
- Stealth Rock

### Images / Video

https://github.com/user-attachments/assets/1bc5f4e4-e5fb-4475-849e-a24cb872a617

### Version

1.13.3 (Latest release)

### Upcoming/master Version

Latest Master as of 11/10/2025 morning Central Time

### Discord contact info

harbingerofruination

### PR DESCRIPTION
**Pull request by moostoet**
## Description
  

  - Updated `Cmd_attackcanceler` to detect active Magic Coat on an ally in doubles so hazard moves (and other bounceable
    moves) get redirected and reflected correctly even when the targeted Pokémon is already fainted.
  - Ensured the bounceability check now works for opponent-field targeting moves, covering hazards like Spikes and
    Stealth Rock.
  - Added a new double battle test verifying hazards are reflected when either player position uses Magic Coat,
    alongside new assumptions for hazard effects (based off hedara's original verification test)

  ## Media

  N/A

  ## Issue(s) that this PR fixes

  Fixes #8195
  
  
  
  
  

  ## Feature(s) this PR does NOT handle:

  None.

  ## Things to note in the release changelog:

  - Magic Coat now properly reflects hazard moves from either slot in double battles.

  ## Discord contact info

viridian.

### CODE REVIEW

File: test/battle/move_effect/magic_coat.c [hunk 1]
```diff
@@ -4,6 +4,8 @@
 ASSUMPTIONS
 {
     ASSUME(GetMoveEffect(MOVE_MAGIC_COAT) == EFFECT_MAGIC_COAT);
+    ASSUME(GetMoveEffect(MOVE_SPIKES) == EFFECT_SPIKES);
+    ASSUME(GetMoveEffect(MOVE_STEALTH_ROCK) == EFFECT_STEALTH_ROCK);
```
Comment (AlexOn1ine) [inline test/battle/move_effect/magic_coat.c]: Those should be added to the test because otherwise it would be an assumption fail for all tests in this file. Stuff that isn't used in all tests should only bind to the needed test.

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -1167,7 +1167,25 @@ static void Cmd_attackcanceler(void)
     }
 
     u32 isBounceable = MoveCanBeBouncedBack(gCurrentMove);
-    if (gProtectStructs[gBattlerTarget].bounceMove
+    bool32 bounceActive = (gProtectStructs[gBattlerTarget].bounceMove && IsBattlerAlive(gBattlerTarget));
+
+    if (!bounceActive
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:1172]: I would also add `!gBattleStruct->bouncedMoveIsUsed` as a check here

Comment (moostoet) [reply src/battle_script_commands.c:1172]: Added the check

File: test/battle/move_effect/magic_coat.c (hunk 1 above)
Comment (moostoet) [reply test/battle/move_effect/magic_coat.c]: Added to the test and removed from general assumptions
