### PR TITLE
Fixes weather abilities not activating when Cloud Nine user leaves th…

### LINKED ISSUE #5144: Forecast is not triggered when Cloud Nine ability user leaves the field
### Description

```
SINGLE_BATTLE_TEST("Forecast transforms Castform when Cloud Nine ability user leaves the field")
{
    GIVEN {
        PLAYER(SPECIES_CASTFORM) { Ability(ABILITY_FORECAST); }
        OPPONENT(SPECIES_GOLDUCK) { Ability(ABILITY_CLOUD_NINE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_SUNNY_DAY); MOVE(opponent, MOVE_CELEBRATE); }
        TURN { SWITCH(opponent, 1); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SUNNY_DAY, player);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponent);
        SEND_IN_MESSAGE("Wobbuffet");
        ABILITY_POPUP(player, ABILITY_FORECAST);
        MESSAGE("Castform transformed!");
    }
}
```

### Version

1.9.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #5144

### CODE REVIEW

File: test/battle/ability/forecast.c [hunk 1]
```diff
@@ -397,3 +397,21 @@ SINGLE_BATTLE_TEST("Forecast transforms Castform back when it uses a move that f
         EXPECT_EQ(GetMonData(&gPlayerParty[0], MON_DATA_SPECIES), SPECIES_CASTFORM);
     }
 }
+
+SINGLE_BATTLE_TEST("Forecast transforms Castform when Cloud Nine ability user leaves the field")
```
Comment (AsparagusEduardo) [inline test/battle/ability/forecast.c:401]: I recommend adding a `PARAMETRIZE` to also handle Air Lock here

Comment (AlexOn1ine) [reply test/battle/ability/forecast.c:401]: done

**Review by AsparagusEduardo — APPROVED** [review]
