### PR TITLE
Fixed Liquid Voice's dynamic type for normal moves 

### LINKED ISSUE #6091: Liquid Voice's dynamic types gives inconsistent results
### Description

Dynamic types don't seem to work with Liquid Voice and normal moves outside of battle
Image

### Version

upcoming (Edge)

### Upcoming/master Version

b109aa0c929907a81d5791dd6e3ed6ae40b2ac9c

### Discord contact info

Frankfurter

### PR DESCRIPTION
**Pull request by fdeblasio**
## Description
Reordered some steps in `GetDynamicMoveType` so that Normal-type sound moves would show the correct dynamic type outside of battle if affected by Liquid Voice

## Issue(s) that this PR fixes
Fixes #6091 

## **Discord contact info**
Frankfurter0

### CODE REVIEW

File: src/battle_main.c [hunk 1]
```diff
@@ -6006,31 +6006,31 @@ u32 GetDynamicMoveType(struct Pokemon *mon, u32 move, u32 battler, u8 *ateBoost)
...
     }
     else if (moveType != TYPE_NORMAL
-          && moveEffect != EFFECT_HIDDEN_POWER
-          && moveEffect != EFFECT_WEATHER_BALL
-          && ability == ABILITY_NORMALIZE
-          && GetActiveGimmick(battler) != GIMMICK_Z_MOVE)
+        && moveEffect != EFFECT_HIDDEN_POWER
+        && moveEffect != EFFECT_WEATHER_BALL
+        && ability == ABILITY_NORMALIZE
+        && GetActiveGimmick(battler) != GIMMICK_Z_MOVE)
```
Comment (AlexOn1ine) [inline src/battle_main.c:6028]: Most of the code base either uses
``` 
if (A
 && B)
or
if (A
    && B)
or 
if (A && B)
```
depending on the length of the line so please keep the old style used previously here

Comment (fdeblasio) [reply src/battle_main.c]: Done!

**Comment by AlexOn1ine** [comment]
Could you please add this test in a new liquid_voice.c file?
```
#include "global.h"
#include "test/battle.h"

ASSUMPTIONS
{
    ASSUME(GetMoveType(MOVE_HYPER_VOICE) == TYPE_NORMAL);
    ASSUME(GetMovePower(MOVE_HYPER_VOICE) > 0);
}

SINGLE_BATTLE_TEST("Liquid voice turns a sound move into a Water-type move")
{
    GIVEN {
        PLAYER(SPECIES_TYPHLOSION);
        OPPONENT(SPECIES_PRIMARINA) { Ability(ABILITY_LIQUID_VOICE); }
    } WHEN {
        TURN { MOVE(opponent, MOVE_HYPER_VOICE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HYPER_VOICE, opponent);
        MESSAGE("It's super effective!");
    }
}
```

**Comment by AlexOn1ine** [comment]
oh, since this is a bugfix it should go to master

**Comment by fdeblasio** [comment]
> Could you please add this test in a new liquid_voice.c file?
> 
> ```
> #include "global.h"
> #include "test/battle.h"
> 
> ASSUMPTIONS
> {
>     ASSUME(GetMoveType(MOVE_HYPER_VOICE) == TYPE_NORMAL);
>     ASSUME(GetMovePower(MOVE_HYPER_VOICE) > 0);
> }
> 
> SINGLE_BATTLE_TEST("Liquid voice turns a sound move into a Water-type move")
> {
>     GIVEN {
>         PLAYER(SPECIES_TYPHLOSION);
>         OPPONENT(SPECIES_PRIMARINA) { Ability(ABILITY_LIQUID_VOICE); }
>     } WHEN {
>         TURN { MOVE(opponent, MOVE_HYPER_VOICE); }
>     } SCENE {
>         ANIMATION(ANIM_TYPE_MOVE, MOVE_HYPER_VOICE, opponent);
>         MESSAGE("It's super effective!");
>     }
> }
> ```

> oh, since this is a bugfix it should go to master

Done and done

**Comment by AlexOn1ine** [comment]
thx

**Review by AlexOn1ine — APPROVED** [review]
