### PR TITLE
Fix nature power string and add support for evnvironment in tests

### LINKED ISSUE #8057: "Nature Power turned into Nature Power!"
### Description

When I use Nature Power, the message "Nature Power turned into [move]!" is wrong:
```
MON used Nature Power!
Nature Power turned into Nature Power!
MON used Swift!
```

### Reproduction Steps

Use Nature Power in a battle

### Images / Video

Image

### Version

upcoming (Edge)

### Upcoming/master Version

782c559a20e873ee0926eca3328ea23d28645c6b

### Discord contact info

purrfectdoodle

### PR DESCRIPTION
**Pull request by FosterProgramming**
Add Environment() test function that sets gBattleEnvironment and backgrounds.
If the environment chosen doesn't have a background (some were added just for secret power but have no visuals), a default background will be picked to avoid crashes
Add Nature Power test to make sure on all background (does not include test for when terrain effect is active)

## Issue(s) that this PR fixes
Fixes #8057

## Things to note in the release changelog:
- Add option to choose an environment when setting up a battle test

## Discord contact info
Jamie

### CODE REVIEW

File: include/test_runner.h [hunk 1]
```diff
@@ -28,6 +28,7 @@ void TestRunner_Battle_CheckBattleRecordActionType(u32 battlerId, u32 recordInde
 
 u32 TestRunner_Battle_GetForcedAbility(u32 side, u32 partyIndex);
 u32 TestRunner_Battle_GetChosenGimmick(u32 side, u32 partyIndex);
+u8 TestRunner_Battle_GetForcedEnvironment(void);
```
Comment (AlexOn1ine) [inline include/test_runner.h]:
```suggestion
u32 TestRunner_Battle_GetForcedEnvironment(void);
```

File: test/test_runner_battle.c [hunk 2]
```diff
@@ -3104,6 +3111,11 @@ u32 TestRunner_Battle_GetForcedAbility(u32 side, u32 partyIndex)
     return DATA.forcedAbilities[side][partyIndex];
 }
 
+u8 TestRunner_Battle_GetForcedEnvironment(void)
```
Comment (AlexOn1ine) [inline test/test_runner_battle.c]:
```suggestion
u32 TestRunner_Battle_GetForcedEnvironment(void)
```

File: src/battle_bg.c [hunk 3]
```diff
@@ -650,7 +651,13 @@ static u8 GetBattleEnvironmentOverride(void)
 {
     u8 battleScene = GetCurrentMapBattleScene();
 
-    if (gBattleTypeFlags & (BATTLE_TYPE_FRONTIER | BATTLE_TYPE_LINK | BATTLE_TYPE_RECORDED_LINK | BATTLE_TYPE_EREADER_TRAINER))
+    if (TestRunner_Battle_GetForcedEnvironment()
+    && gBattleEnvironmentInfo[gBattleEnvironment].background.tilemap
+    && gBattleEnvironmentInfo[gBattleEnvironment].background.tileset)
```
Comment (AlexOn1ine) [inline src/battle_bg.c]:
```suggestion
    if (TestRunner_Battle_GetForcedEnvironment()
     && gBattleEnvironmentInfo[gBattleEnvironment].background.tilemap
     && gBattleEnvironmentInfo[gBattleEnvironment].background.tileset)
```

File: src/battle_bg.c [hunk 4]
```diff
@@ -1022,7 +1029,13 @@ void DrawBattleEntryBackground(void)
     }
     else if (gBattleTypeFlags & (BATTLE_TYPE_FRONTIER | BATTLE_TYPE_LINK | BATTLE_TYPE_RECORDED_LINK | BATTLE_TYPE_EREADER_TRAINER))
     {
-        if (!(gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER) || gPartnerTrainerId > TRAINER_PARTNER(PARTNER_NONE))
+        if (TestRunner_Battle_GetForcedEnvironment()
+        && gBattleEnvironmentInfo[gBattleEnvironment].background.tilemap
+        && gBattleEnvironmentInfo[gBattleEnvironment].background.tileset)
```
Comment (AlexOn1ine) [inline src/battle_bg.c]:
```suggestion
        if (TestRunner_Battle_GetForcedEnvironment()
         && gBattleEnvironmentInfo[gBattleEnvironment].background.tilemap
         && gBattleEnvironmentInfo[gBattleEnvironment].background.tileset)
```
