### PR TITLE
Fix Sucker Punch to succeed against Me First targets

### LINKED ISSUE #9274: Sucker Punch should work vs a battler using Me First
### Description

Didn't realize this but Sucker Punch needs a Me First check as well
https://bulbapedia.bulbagarden.net/wiki/Sucker_Punch_(move)
> Sucker Punch will now succeed if the opponent is using [Me First](https://bulbapedia.bulbagarden.net/wiki/Me_First_(move))

However, no such check
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/src/battle_move_resolution.c#L1283-L1294

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Issue(s) that this PR fixes
Fixes #9274

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -2732,10 +2732,13 @@ static enum MoveCanceler CancelerMoveFailure(struct BattleContext *ctx)
             battleScript = BattleScript_InsomniaProtects;
         break;
     case EFFECT_SUCKER_PUNCH:
+    {
+        u32 defMove = GetChosenMoveFromPosition(ctx->battlerDef);
         if (HasBattlerActedThisTurn(ctx->battlerDef)
-         || (IsBattleMoveStatus(GetChosenMoveFromPosition(ctx->battlerDef)) && !gProtectStructs[ctx->battlerDef].noValidMoves))
+         || (IsBattleMoveStatus(defMove) && !gProtectStructs[ctx->battlerDef].noValidMoves && defMove != MOVE_ME_FIRST))
```
Comment (AlexOn1ine) [inline src/battle_util.c]: Should check `EFFECT_ME_FIRST`
