### PR TITLE
Fixed Parental Bond

### LINKED ISSUE #3407: Parental Bond is nonfunctional
### Description

brokenpbond

As title says, Parental Bond is currently broken and does nothing. Issue seems to lie somewhere in the IsMoveAffectedByParentalBond function, as forcing it to return TRUE makes it work.

### Version

1.6.1 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Fixes Parental Bond after #2952.

TODO: the rest of the tests.

## Issue(s) that this PR fixes
#3407 

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Making the executive decision to merge this PR. Will make an issue to make the missing tests.

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -15765,7 +15765,7 @@ bool32 IsMoveAffectedByParentalBond(u32 move, u32 battler)
 {
     if (move != MOVE_NONE && move != MOVE_STRUGGLE
         && gBattleMoves[move].split != SPLIT_STATUS
-        && !gBattleMoves[move].strikeCount > 2)
```
Comment (ghoulslash) [inline src/battle_script_commands.c:15768]: on upcoming this is `gBattleMoves[move].strikeCount <= 2` from 3412 (iirc). Which is correct?

Comment (AsparagusEduardo) [reply src/battle_script_commands.c:15768]: It shouldn't, because it Parental Bond doesn't affect Multi-hit moves, and the `<= 2` means that it would affect moves that hit twice.

Comment (ghoulslash) [reply src/battle_script_commands.c:15768]: might be worth fixing on upcoming too, then

Comment (AsparagusEduardo) [reply src/battle_script_commands.c:15768]: Will do once I merge master into upcoming.
