### PR TITLE
Fixes ability Corrosion

### LINKED ISSUE #4035: Corrosion Bug
### Description

Corrosion doesn't work on damaging moves with poison chance against Poison-types.

### Version

1.7.2 (Latest release)

### Upcoming/master Version

58102e6

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4035

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Ready for re-review.

File: src/battle_ai_util.c [hunk 1]
```diff
@@ -2752,8 +2752,18 @@ bool32 AI_CanPutToSleep(u32 battlerAtk, u32 battlerDef, u32 defAbility, u32 move
 
 static bool32 AI_CanPoisonType(u32 battlerAttacker, u32 battlerTarget, u32 move)
 {
-    return ((AI_DATA->abilities[battlerAttacker] == ABILITY_CORROSION && gBattleMoves[move].split == SPLIT_STATUS)
-            || !(IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON) || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL)));
+    if (GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION)
+    {
+        if ((IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL) && (gBattleMoves[gCurrentMove].split == SPLIT_STATUS))
```
Comment (Skeli789) [inline src/battle_ai_util.c:2757]: First off:
```suggestion
        if ((IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL) && (gBattleMoves[move].split == SPLIT_STATUS))
```

Second, this isn't a good way to handle it. The AI should think it can poison a Steel type or Poison type with any move. If the engine is coded correctly, the effectiveness check will take over and the move won't even be considered because it doesn't affect the target (for damaging Poison-type moves on Steel-types). Additionally, if Inverse battles are ever added to the expansion, this kind of logic (of only status moves) will cause AI judgment errors because it won't think it could poison a Steel-type even though it could.

Third, AI_CanPoisonType should be just calling `CanPoisonType`. Or better yet, remove the function altogether and just call `CanPoisonType`.

**Review by Skeli789 — CHANGES_REQUESTED** [review]

File: src/battle_ai_util.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_ai_util.c]: > Third, AI_CanPoisonType should be just calling CanPoisonType. Or better yet, remove the function altogether and just call CanPoisonType.

I don't know why but the expansion doesn't pass a move argument in the battle_script_command functions so since I can't tell why the decision was made to make additional AI functions I don't want to make a change. As suggested for now I will just change it to call `CanPoisonType` since the argument is not needed anymore.

> The AI should think it can poison a Steel type or Poison type with any move. If the engine is coded correctly, the effectiveness check will take over and the move won't even be considered because it doesn't affect the target

I see.

> Additionally, if Inverse battles are ever added to the expansion, this kind of logic (of only status moves) will cause AI judgment errors because it won't think it could poison a Steel-type even though it could.

Inverse battles are already a feature. 

Pushed a change.

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -8121,18 +8121,13 @@ static bool32 HasAttackerFaintedTarget(void)
...
 bool32 CanPoisonType(u8 battlerAttacker, u8 battlerTarget)
 {
-    if (GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION)
-    {
-        if ((IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL) && (gBattleMoves[gCurrentMove].split == SPLIT_STATUS))
-        || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON))
-            return TRUE;
-    }
+    if (GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION
+    && (IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL) || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON)))
```
Comment (LOuroboros) [inline src/battle_script_commands.c:8125]:
```suggestion
    if (GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION
        && (IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL) || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON)))
```

*I prefer to stack the conditions personally, but most of the contributors tend to drop 4 full spaces and there's no real consistency in this regard (at least not yet), so.*

File: src/battle_script_commands.c [hunk 3]
```diff
@@ -8121,8 +8121,13 @@ static bool32 HasAttackerFaintedTarget(void)
 
 bool32 CanPoisonType(u8 battlerAttacker, u8 battlerTarget)
 {
-    return ((GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION && gBattleMoves[gCurrentMove].split == SPLIT_STATUS)
-            || !(IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON) || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL)));
+    if (GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION
```
Comment (Skeli789) [inline src/battle_script_commands.c:8124]: This is extraneous. You can just skip the check for returning FALSE on Poison or Steel types if the attacker's Ability is Corrosion. Something like "ability != corrosion && (type == poison || type == steel) then return false"

Comment (AlexOn1ine) [reply src/battle_script_commands.c:8124]: Oh damn, right.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: pushed a change, thx

File: src/battle_script_commands.c (hunk 2 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c:8125]: I agree with stacking and I don't see a reason in this case to drop 4 spaces. I don't mind non stacking conditions if brackets are used but without it looks weird.

File: src/battle_script_commands.c [hunk 4]
```diff
@@ -8121,8 +8121,10 @@ static bool32 HasAttackerFaintedTarget(void)
 
 bool32 CanPoisonType(u8 battlerAttacker, u8 battlerTarget)
 {
-    return ((GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION && gBattleMoves[gCurrentMove].split == SPLIT_STATUS)
-            || !(IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON) || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL)));
+    if (GetBattlerAbility(battlerAttacker) != ABILITY_CORROSION
```
Comment (Skeli789) [inline src/battle_script_commands.c:8124]: Last change, I promise haha. Use de morgan on this and just return the statement directly like it was originally:
```
    return GetBattlerAbility(battlerAttacker) == ABILITY_CORROSION
        || (!IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL) && !IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON))
```

Comment (AlexOn1ine) [reply src/battle_script_commands.c:8124]: it's fine. Hope you aren't getting tired by my coding abilities 😅

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: pushed the change.

File: src/battle_script_commands.c (hunk 2 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Since only a return is used now I added 4 spaces.

File: src/battle_ai_util.c [hunk 5]
```diff
@@ -2752,8 +2752,7 @@ bool32 AI_CanPutToSleep(u32 battlerAtk, u32 battlerDef, u32 defAbility, u32 move
 
 static bool32 AI_CanPoisonType(u32 battlerAttacker, u32 battlerTarget, u32 move)
 {
-    return ((AI_DATA->abilities[battlerAttacker] == ABILITY_CORROSION && gBattleMoves[move].split == SPLIT_STATUS)
-            || !(IS_BATTLER_OF_TYPE(battlerTarget, TYPE_POISON) || IS_BATTLER_OF_TYPE(battlerTarget, TYPE_STEEL)));
+    return CanPoisonType(battlerAttacker, battlerTarget);
```
Comment (Bassoonian) [inline src/battle_ai_util.c:2755]: If we're outright ignoring the move argument, shouldn't we be removing it then?

Comment (AlexOn1ine) [reply src/battle_ai_util.c:2755]: Maybe I just remove the func then.

Comment (AlexOn1ine) [reply src/battle_ai_util.c]: removed

**Review by Bassoonian — APPROVED** [review]
