### PR TITLE
Fixes Knock Off still activating when there is no Item

### LINKED ISSUE #7387: Issues related to move knock off.
### Description

When a Pokemon carries a weakness policy, if it is hit by move knock off, the weakness policy is triggered, but it displays :_A knocked off B's ????????!_

After testing, I found that the **weakness policy**, **sticky barb**, and **focus sash** have similar issues.

### Reproduction Steps

A Pokemon carries a weakness policy, sticky barb or focus sash. Then it is hit by move knock off. Pay attention to the information output of the battle.

### Images / Video

Image

### Version

1.12.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #7418: The Eject Pack / Life Orb test has a spelling mistake in the not message
### Description

If the spelling mistake is corrected the test fails. 

### Reproduction Steps

corrected test:
```
SINGLE_BATTLE_TEST("Eject Pack does not cause the new Pokémon to lose HP due to it's held Life Orb")
{
    GIVEN {
        ASSUME(gItemsInfo[ITEM_LIFE_ORB].holdEffect == HOLD_EFFECT_LIFE_ORB);
        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_EJECT_PACK); }
        PLAYER(SPECIES_WYNAUT) { Item(ITEM_LIFE_ORB); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_OVERHEAT); SEND_OUT(player, 1); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_OVERHEAT, player);
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, player);
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, player);
        MESSAGE("Wobbuffet is switched out with the Eject Pack!");
        SEND_IN_MESSAGE("Wynaut");
        NOT MESSAGE("Wynaut was hurt by the Life Orb!");
        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponent);
    }
}
```

### Images / Video

_No response_

### Version

1.12.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7387
Fixes #7418

### CODE REVIEW

File: test/battle/hold_effect/red_card.c [hunk 1]
```diff
@@ -455,7 +455,7 @@ SINGLE_BATTLE_TEST("Red Card does not cause the dragged out mon to lose hp due t
         ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, opponent);
         MESSAGE("The opposing Wobbuffet held up its Red Card against Wobbuffet!");
         MESSAGE("Wynaut was dragged out!");
-        NOT MESSAGE("Wynaut was hurt by its Life Orb!");
+        NOT MESSAGE("Wynaut was hurt by the Life Orb!");
```
Comment (hedara90) [inline test/battle/hold_effect/red_card.c]: Can this be a `HP_BAR` check instead?

Comment (AlexOn1ine) [reply test/battle/hold_effect/red_card.c]: done

Comment (hedara90) [reply test/battle/hold_effect/red_card.c]: It was only changed in the Eject Pack test

Comment (AlexOn1ine) [reply test/battle/hold_effect/red_card.c]: should be fixed

File: src/data/debug_trainers.h
Comment (hedara90) [inline src/data/debug_trainers.h:1]: This file shouldn't be here

Comment (AlexOn1ine) [reply src/data/debug_trainers.h:1]: removed

**Review by hedara90 — APPROVED** [review]
