### PR TITLE
Fix transform tint applying to every from change on reload

### LINKED ISSUE #8412: Visual Morpeko Transfrom bug (applies to all forms)
### Description

When Morpeko changes form, a white film is created on the sprite if the battle menu is exited briefly. 

Report and video from Kevin on the pret discord channel 

https://github.com/user-attachments/assets/da62b7eb-e847-4cca-807a-d98a8baa3575

### Reproduction Steps

See video

### Images / Video

_No response_

### Version

1.14.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Media

https://github.com/user-attachments/assets/50f1b3f6-da15-4625-af6e-5ffe2851f4cc

## Issue(s) that this PR fixes
Fixes #8412

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_gfx_sfx_util.c [hunk 1]
```diff
@@ -655,7 +655,7 @@ void BattleLoadMonSpriteGfx(struct Pokemon *mon, u32 battler)
     LoadPalette(paletteData, BG_PLTT_ID(8) + BG_PLTT_ID(battler), PLTT_SIZE_4BPP);
 
     // transform's pink color
-    if (gBattleSpritesDataPtr->battlerData[battler].transformSpecies != SPECIES_NONE)
```
Comment (AlexOn1ine) [inline src/battle_gfx_sfx_util.c:658]: was this set to `NONE` when laving the battle interface? If yes, do you know why?

Comment (AlexOn1ine) [reply src/battle_gfx_sfx_util.c:658]: oh nevermind, I understand now

**Comment by AsparagusEduardo** [comment]
There should probably be a check for instances of transformedSpecies, as it seems like the animation is setting this value for instances besides transform

**Comment by FosterProgramming** [comment]
> There should probably be a check for instances of transformedSpecies, as it seems like the animation is setting this value for instances besides transform

It's setting this value for all form changes which I thought was intentional
