### PR TITLE
Fixed indentation for various files.

### LINKED ISSUE #517: [Reminder] Check and correct indentation in several files
Ex: `src/data/text/move_descriptions.h`, `data/battle_scripts_1.s` and possibly a few others like `src/battle_script_commands.c` and `src/battle_util.c`.

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Fixes #517, except for `data/battle_scripts_1.s` which is handled by #13 .

## **Discord contact info**
AsparagusEduardo#6051

### CODE REVIEW

**Review by ExpoSeed — APPROVED** [review]

**Review by Pyredrid — DISMISSED** [review]

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -337,262 +337,262 @@ static void Cmd_metalburstdamagecalculator(void);
...
-	Cmd_finishturn, // 0xF7
-	Cmd_trainerslideout, // 0xF8
-	Cmd_settelekinesis, // 0xF9
-	Cmd_swapstatstages, // 0xFA
-	Cmd_averagestats, // 0xFB
-	Cmd_jumpifoppositegenders, // 0xFC
-	Cmd_trygetbaddreamstarget, // 0xFD
-	Cmd_tryworryseed, // 0xFE
-	Cmd_metalburstdamagecalculator, // 0xFF
+    Cmd_attackcanceler, // 0x0
```
Comment (ultima-soul) [inline src/battle_script_commands.c:340]: Can you align the number comments all to the right so they're in the same column? Upstream seems to do that so we should match that.

**Review by ultima-soul — CHANGES_REQUESTED** [review]

**Review by ghoulslash — APPROVED** [review]

**Review by ExpoSeed — APPROVED** [review]

**Review by ultima-soul — APPROVED** [review]
