### PR TITLE
Fixes terrain not failing on duplicate

### LINKED ISSUE #7937: The same terrain can be set up on top
### Description

The same terrain can be set up on top which means the timer will also reset

### Reproduction Steps

code.

### Images / Video

_No response_

### Version

1.13.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7937

### CODE REVIEW

File: test/battle/move_effect/misty_terrain.c [hunk 1]
```diff
@@ -87,3 +87,16 @@ SINGLE_BATTLE_TEST("Misty Terrain lasts for 5 turns")
...
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_MISTY_TERRAIN); MOVE(opponent, MOVE_MISTY_TERRAIN); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_MISTY_TERRAIN, player);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_MISTY_TERRAIN, opponent);
+    }
+}
```
Comment (PhallenTree) [inline test/battle/move_effect/misty_terrain.c]:
```suggestion
}

```
