### PR TITLE
Fixes various Dynamax HP conversions/calculations

### LINKED ISSUE #4538: Dynamax Mons gain HP incorrectly when leveling up
### Description

In the following example, my Sneasler was Dynamaxed for three turns, during it which it took no damage. When Dynamax reverted, it lost 1 HP. I presume this is a rounding error.

image

EDIT: I reproduced the issue, except this time Sneasler lost 3 HP at the end of a round while still Dynamaxed.

image

EDIT 2: I realized the issue is caused by leveling up while Dynamaxed. The Max HP increases, but not all of the effective HP does to match it, just a portion, which I believe is the incorrect behavior.

EDIT 3: I've also now experienced twice where my Pokemon had taken damage while Dynamaxed, then leveled up and was essentially fully healed. Bizarrely, in one of these instances, it even took a hit and received no damage.

### Version

upcoming (Edge)

### Upcoming/master Version

0aad2a9ba7b358f559c50ecc07a8752400f1d64f

### Discord contact info

Special K#8400

### PR DESCRIPTION
**Pull request by PhallenTree**
- Fixes Dynamaxed mons having the Dynamax HP multiplier applied again when changing form while Dynamaxed, causing HP to be restored when changing forms and potential overflow;
- Fixes Dynamaxed mons not properly following the interaction described below when changing form: (from Power Construct on Bulbapedia)

> Since Zygarde Complete Forme has a higher base HP stat, Zygarde's maximum HP will increase and its current HP will be revised to its new maximum HP minus the amount of HP it had lost before changing form.

- Fixes Dynamaxed mons gaining HP when leveling up based on the amount of HP gained on the previous level up;
- Fixes Dynamaxed mons gaining too much HP when leveling up after a Dynamaxed mon was the last to level up (caused an HP overflow);

Fixed level up interaction (tested with Dynamax Level 0):

https://github.com/user-attachments/assets/4f3c7ab9-9f08-49b5-a5ef-bb67307ccbc5

- Fixes Dynamaxed mons not reverting their HP/maxHP correctly according to their Dynamax Level;
- Fixes various effects on Dynamaxed mons (that use `GetNonDynamaxHP` and `GetNonDynamaxMaxHP`) ignoring the mon's Dynamax Level when calculating HP/maxHP;

`CalculateMonStats` uses the Dynamaxed max HP for `oldMaxHP` and non-Dynamaxed max HP for `newMaxHP` which caused issues 2 and 4.

Removed `gBattleScripting->dynamax.levelUpHP` and the `battler` argument for `ApplyDynamaxHPMultiplier` since they are unused.

## Issue(s) that this PR fixes
Fixes #4538, fixes the mechanical issue mentioned in #4651

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: src/battle_controller_player.c [hunk 1]
```diff
@@ -1502,30 +1504,32 @@ static void Task_GiveExpWithExpBar(u8 taskId)
...
                 if (GetActiveGimmick(battler) == GIMMICK_DYNAMAX && monId == gBattlerPartyIndexes[battler])
                 {
-                    ApplyDynamaxHPMultiplier(battler, &gPlayerParty[monId]);
-                    gBattleMons[battler].hp = gBattleStruct->dynamax.levelUpHP;
-                    SetMonData(&gPlayerParty[monId], MON_DATA_HP, &gBattleMons[battler].hp);
+                    ApplyDynamaxHPMultiplier(mon);
+                    // overwrite levelUpHP since it overflows
+                    gBattleScripting.levelUpHP = GetMonData(mon, MON_DATA_MAX_HP) - oldMaxHP;
+                    gBattleMons[battler].hp += gBattleScripting.levelUpHP;
+                    SetMonData(mon, MON_DATA_HP, &gBattleMons[battler].hp);
```
Comment (AlexOn1ine) [inline src/battle_controller_player.c:1532]: correct me if I'm wrong but this seems to be identical to the above code block. If this is true could you use a function to remove the duplicate code?

File: src/battle_dynamax.c [hunk 2]
```diff
@@ -151,8 +151,9 @@ u16 GetNonDynamaxHP(u32 battler)
         return gBattleMons[battler].hp;
     else
     {
-        u16 mult = UQ_4_12(1.0/1.5); // placeholder
-        u16 hp = UQ_4_12_TO_INT((gBattleMons[battler].hp * mult) + UQ_4_12_ROUND);
+        struct Pokemon *mon = &GetSideParty(GetBattlerSide(battler))[gBattlerPartyIndexes[battler]];
```
Comment (AlexOn1ine) [inline src/battle_dynamax.c:154]: The code has a bunch of those. I believe there is an inline function in `inlcude/battle.h` that can clean up the call a bit.

**Review by AlexOn1ine — APPROVED** [review]
