### PR TITLE
Fixes Effects activating when move wasn't successful 

### LINKED ISSUE #7801: Throat Spray triggers even when mon is flinched
### Description

Throat spray should only trigger after a successful sound move is used. If a mon flinches, it currently still triggers (tested on latest master with doubles).

### Reproduction Steps

1.) Use a sound based move while an opposing mon can only fake you out or smt
2.) Observe it activates even though you are flinched

### Images / Video

_No response_

### Version

1.13.1 (Latest release)

### Upcoming/master Version

master

### Discord contact info

Jordan

### LINKED ISSUE #7805: Hazard-Setting Attacking Moves Set Hazards Even When Missing Or HItting Protected Mon
### Description

Currently, stone axe, ceaseless edge, etc set their hazards even if they don't hit the target, be it via protect or by missing.

### Reproduction Steps

Use one of the above moves against a mon with protect/brightpowder.

### Images / Video

_No response_

### Version

1.13.1 (Latest release)

### Upcoming/master Version

Latest Master

### Discord contact info

Jordan

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7801
Fixes #7805

### CODE REVIEW

File: test/battle/hold_effect/throat_spray.c [hunk 1]
```diff
@@ -88,3 +88,20 @@ SINGLE_BATTLE_TEST("Throat Spray does not activate if move fails")
         }
     }
 }
+
+
+SINGLE_BATTLE_TEST("Throat Spray does not activate if user flinches")
```
Comment (Bassoonian) [inline test/battle/hold_effect/throat_spray.c]:
```suggestion
SINGLE_BATTLE_TEST("Throat Spray does not activate if user flinches")
```
