### PR TITLE
Fix toxic debris setting hazards on the wrong side when hit by an ally

### LINKED ISSUE #7981: Using bear up on an ally with toxic debris sets up toxic spikes on your side of the field
### Description

Per bulbapedia and scarlet and violet testing, hitting your own glimmora with a given move (like beat up) should only set up hazards on the opposing side of the field.

### Reproduction Steps

1.) Have a pokemon with toxic debris and an ally pokemon with a physical move in a double battle

2.) Use fake out, beat up, or any other physical move on your toxic debris mon

3.) Observe spikes getting set up on your side of the field rather then opposing side of the field.

### Images / Video

_No response_

### Version

1.13.2 (Latest release)

### Upcoming/master Version

Master

### Discord contact info

Harbingerofruination

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Issue(s) that this PR fixes
Fixes #7981

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -4959,7 +4959,8 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
              && IsBattlerTurnDamaged(gBattlerTarget)
              && (gSideTimers[GetBattlerSide(gBattlerAttacker)].toxicSpikesAmount != 2))
             {
-                SWAP(gBattlerAttacker, gBattlerTarget, i);
+                gBattlerAttacker = gBattlerTarget;
+                gBattlerTarget = BATTLE_OPPOSITE(gBattlerAttacker);
```
Comment (AlexOn1ine) [inline src/battle_util.c:4965]: This will mutate `gBattlerAttacker` to the opposite mon after toxic debris is resolved in `BattleScript_ToxicDebrisRet`.

You can get around this by storing attacker and target with 
```
SaveBattlerTarget(gBattlerTarget); 
SaveBattlerAttacker(gBattlerAttacker);
```
With those script adjustments
```diff
BattleScript_ToxicDebrisRet:
-	copybyte sBATTLER, gBattlerTarget
-	copybyte gBattlerTarget, gBattlerAttacker
-	copybyte gBattlerAttacker, sBATTLER
+	restoretarget
+	restoreattacker
	return
```

Comment (FosterProgramming) [reply src/battle_util.c:4965]: Oh i saw the swap code and I was wondering where the swap back happened but didn't check the battle script. I'm fixing this.

**Review by AlexOn1ine — APPROVED** [review]
