### PR TITLE
Prevent double Dynamax for single-trainer 2v1 multi battles

### LINKED ISSUE #7608: AI can Dynamax both lead mons in a 2v1 multibattle
### Description

AI in 2v1 multi will Dynamax both leads. Cause: `HasTrainerUsedGimmick` runs for all battlers before `gBattleStruct->gimmick.toActivate |= 1u << battler` is executed in `HandleTurnActionSelectionState`. This results in battler 3 passing `HasTrainerUsedGimmick` because `gBattleStruct->gimmick.toActivate & (1u << BATTLE_PARTNER(battler)` does not pass, which would prevent the second dynamax.

Also, `IsPartnerMonFromSameTrainer` returns false if `BATTLE_TYPE_MULTI` is set, which is incorrect for 2v1 multibattle opponents.

### Reproduction Steps

Change the Steven Multi to `2_vs_1` against Maxie only.

Party:
```
=== TRAINER_MAXIE_MOSSDEEP ===
Name: MAXIE
Class: Magma Leader
Pic: Magma Leader Maxie
Gender: Male
Music: Magma
Double Battle: No
AI: Basic Trainer

Camerupt @ Focus Sash
Level: 46
Dynamax Level: 10
IVs: 18 HP / 18 Atk / 18 Def / 18 SpA / 18 SpD / 18 Spe
- Splash

Camerupt @ Focus Sash
Level: 46
Dynamax Level: 10
IVs: 18 HP / 18 Atk / 18 Def / 18 SpA / 18 SpD / 18 Spe
- Wicked Blow

Houndoom @ Focus Sash
Level: 46
IVs: 18 HP / 18 Atk / 18 Def / 18 SpA / 18 SpD / 18 Spe
- Splash

Houndoom @ Focus Sash
Level: 46
IVs: 18 HP / 18 Atk / 18 Def / 18 SpA / 18 SpD / 18 Spe
- Splash
```

### Images / Video

https://github.com/user-attachments/assets/0bfcf4a6-507b-4b31-9345-5929d4989a1e

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

grintoul

### PR DESCRIPTION
**Pull request by moostoet**
## Description
This fixes AI-controlled 2v1 multibattles where both opponent leads would Dynamax. The root cause was that `HasTrainerUsedGimmick` was evaluated before `gimmick.toActivate` was set, so the second battler saw the gimmick as unused and queued a second Dynamax. Additionally, partner detection treated both opposing battlers as separate trainers in 2v1 multi, allowing two gimmicks.

Key changes:
- Treat only true single-trainer pairs as blocking partners, but allow player+partner to remain independent (no regression to player/partner battles).
- When an AI chooses to use a gimmick, set `gBattleStruct->gimmick.toActivate` immediately and skip if that trainer already has a gimmick queued/used:
  ```c
  enum Gimmick gimmick = gBattleStruct->gimmick.usableGimmick[battler];
  if (gimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
  {
      gBattleStruct->gimmick.toActivate |= 1u << battler;
      BtlController_EmitTwoReturnValues(... | RET_GIMMICK | ...);
  }
  ```
- Simplify `HasTrainerUsedGimmick` to look only at activation flags and whether the same-trainer partner is already queued/active which eliminates reliance on AI intent bits:
  ```c
  if (IsDoubleBattle() && IsPartnerMonFromSameTrainer(battler))
      if (gimmickIsQueuedOrActivatedForPartner)
          return TRUE;
  return gBattleStruct->gimmick.activated[battler][gimmick];
  ```
- Add regression test:
  - `AI only Dynamaxes once per trainer in 2v1 multi battles`

## Media
Not applicable.

## Issue(s) that this PR fixes
Fixes #7608

## Feature(s) this PR does NOT handle:
None.

## Things to note in the release changelog:
- Fixed AI 2v1 multibattles incorrectly allowing both opponent leads to Dynamax in the same turn.

## Discord contact info
viridian.

### CODE REVIEW

File: src/battle_main.c [hunk 1]
```diff
@@ -3940,6 +3940,8 @@ static void TryDoEventsBeforeFirstTurn(void)
         memset(&gSpecialStatuses, 0, sizeof(gSpecialStatuses));
         BattlePutTextOnWindow(gText_EmptyString3, B_WIN_MSG);
         AssignUsableGimmicks();
+        if (gAiBattleData != NULL)
+            gAiBattleData->aiUsingGimmick = 0;
```
Comment (AlexOn1ine) [inline src/battle_main.c]: don't need to check for null at this stage

File: src/battle_main.c [hunk 2]
```diff
@@ -4053,6 +4055,8 @@ void BattleTurnPassed(void)
 
     BattlePutTextOnWindow(gText_EmptyString3, B_WIN_MSG);
     AssignUsableGimmicks();
+    if (gAiBattleData != NULL)
+        gAiBattleData->aiUsingGimmick = 0;
```
Comment (AlexOn1ine) [inline src/battle_main.c]: don't need to check for null at this stage

File: src/battle_main.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_main.c]: actually you shouldn't need this one here? The struct is zeroed out at the start of the battle so you shouldn't need to set it to zero again

Comment (moostoet) [reply src/battle_main.c]: Removed the null check

File: src/battle_main.c (hunk 2 above)
Comment (moostoet) [reply src/battle_main.c]: Removed the null check

File: src/battle_controller_player_partner.c [hunk 3]
```diff
@@ -269,12 +269,16 @@ static void PlayerPartnerHandleChooseMove(u32 battler)
...
+    enum Gimmick gimmick = gBattleStruct->gimmick.usableGimmick[battler];
+    if (gimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
     {
+        gBattleStruct->gimmick.toActivate |= 1u << battler;
         BtlController_EmitTwoReturnValues(battler, B_COMM_TO_ENGINE, B_ACTION_EXEC_SCRIPT, (chosenMoveIndex) | (RET_GIMMICK) | (gBattlerTarget << 8));
     }
     else
     {
+        if (IsAIUsingGimmick(battler))
+            SetAIUsingGimmick(battler, NO_GIMMICK);
```
Comment (AlexOn1ine) [inline src/battle_controller_player_partner.c]: Any reason you check before setting to 0

File: src/battle_controller_opponent.c [hunk 4]
```diff
@@ -464,12 +464,16 @@ static void OpponentHandleChooseMove(u32 battler)
...
+            enum Gimmick gimmick = gBattleStruct->gimmick.usableGimmick[battler];
+            if (gimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
             {
+                gBattleStruct->gimmick.toActivate |= 1u << battler;
                 BtlController_EmitTwoReturnValues(battler, B_COMM_TO_ENGINE, B_ACTION_EXEC_SCRIPT, (chosenMoveIndex) | (RET_GIMMICK) | (gBattlerTarget << 8));
             }
             else
             {
+                if (IsAIUsingGimmick(battler))
+                    SetAIUsingGimmick(battler, NO_GIMMICK);
```
Comment (AlexOn1ine) [inline src/battle_controller_opponent.c]: same here

File: src/battle_controller_player_partner.c [hunk 5]
```diff
@@ -269,12 +269,16 @@ static void PlayerPartnerHandleChooseMove(u32 battler)
             gBattlerTarget = GetBattlerAtPosition(B_POSITION_OPPONENT_RIGHT);
     }
     // If partner can and should use a gimmick (considering trainer data), do it
-    if (gBattleStruct->gimmick.usableGimmick[battler] != GIMMICK_NONE && IsAIUsingGimmick(battler))
+    enum Gimmick gimmick = gBattleStruct->gimmick.usableGimmick[battler];
+    if (gimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
```
Comment (AlexOn1ine) [inline src/battle_controller_player_partner.c]:
```suggestion
    enum Gimmick usableGimmick = gBattleStruct->gimmick.usableGimmick[battler];
    if (usableGimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
```

File: src/battle_controller_opponent.c [hunk 6]
```diff
@@ -464,12 +464,16 @@ static void OpponentHandleChooseMove(u32 battler)
                     gBattlerTarget = GetBattlerAtPosition(B_POSITION_PLAYER_RIGHT);
             }
             // If opponent can and should use a gimmick (considering trainer data), do it
-            if (gBattleStruct->gimmick.usableGimmick[battler] != GIMMICK_NONE && IsAIUsingGimmick(battler))
+            enum Gimmick gimmick = gBattleStruct->gimmick.usableGimmick[battler];
+            if (gimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
```
Comment (AlexOn1ine) [inline src/battle_controller_opponent.c]:
```suggestion
            enum Gimmick usableGimmick = gBattleStruct->gimmick.usableGimmick[battler];
            if (usableGimmick != GIMMICK_NONE && IsAIUsingGimmick(battler) && !HasTrainerUsedGimmick(battler, gimmick))
```

**Review by AlexOn1ine — COMMENTED** [review]
Instead of setting `SetAiUsingGemmick` in several places I would include it in the function `SetAiLogicDataForTurn`. That should cover everything.

**Comment by AlexOn1ine** [comment]
> Instead of setting `SetAiUsingGemmick` in several places I would include it in the function `SetAiLogicDataForTurn`. That should cover everything.

actually this might be cap by me so please ignore lol

File: src/battle_controller_opponent.c (hunk 6 above)
Comment (moostoet) [reply src/battle_controller_opponent.c]: added this

File: src/battle_controller_player_partner.c (hunk 5 above)
Comment (moostoet) [reply src/battle_controller_player_partner.c]: added this

File: src/battle_controller_player_partner.c (hunk 3 above)
Comment (moostoet) [reply src/battle_controller_player_partner.c]: Removed the check, agree that it is probably not necessary

File: src/battle_gimmick.c [hunk 7]
```diff
@@ -91,20 +91,16 @@ bool32 ShouldTrainerBattlerUseGimmick(u32 battler, enum Gimmick gimmick)
...
-    }
-    // Otherwise, return whether current battler has used gimmick.
-    else
+    if (IsDoubleBattle() && IsPartnerMonFromSameTrainer(battler))
     {
-        return gBattleStruct->gimmick.activated[battler][gimmick];
+        u32 partner = BATTLE_PARTNER(battler);
+        if (gBattleStruct->gimmick.activated[partner][gimmick]
+            || ((gBattleStruct->gimmick.toActivate & (1u << partner))
+                && gBattleStruct->gimmick.usableGimmick[partner] == gimmick))
```
Comment (AlexOn1ine) [inline src/battle_gimmick.c]:
```suggestion
        if (gBattleStruct->gimmick.activated[partner][gimmick]
         || ((gBattleStruct->gimmick.toActivate & (1u << partner)) && gBattleStruct->gimmick.usableGimmick[partner] == gimmick))
```

File: src/battle_util.c [hunk 8]
```diff
@@ -8770,14 +8770,14 @@ s32 GetStealthHazardDamage(enum TypeSideHazard hazardType, u32 battler)
...
-    if (!IsOnPlayerSide(battler) && gBattleTypeFlags & BATTLE_TYPE_TWO_OPPONENTS)
-        return FALSE;
-    else if (IsOnPlayerSide(battler) && gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER)
-        return FALSE;
-    else if (gBattleTypeFlags & BATTLE_TYPE_MULTI)
-        return FALSE;
+    if (!IsOnPlayerSide(battler))
+    {
+        return !(gBattleTypeFlags & BATTLE_TYPE_TWO_OPPONENTS);
+    }
```
Comment (AlexOn1ine) [inline src/battle_util.c]:
```suggestion
        return !(gBattleTypeFlags & BATTLE_TYPE_TWO_OPPONENTS);
```

File: src/battle_util.c [hunk 9]
```diff
@@ -8770,14 +8770,12 @@ s32 GetStealthHazardDamage(enum TypeSideHazard hazardType, u32 battler)
...
-        return FALSE;
-    else if (gBattleTypeFlags & BATTLE_TYPE_MULTI)
-        return FALSE;
+    if (!IsOnPlayerSide(battler))
+        return !(gBattleTypeFlags & BATTLE_TYPE_TWO_OPPONENTS);
     else
-        return TRUE;
+    {
+        return !(gBattleTypeFlags & BATTLE_TYPE_MULTI);
+    }
```
Comment (AlexOn1ine) [inline src/battle_util.c]:
```suggestion
        return !(gBattleTypeFlags & BATTLE_TYPE_MULTI);
```
