### PR TITLE
Counter/Mirror Coat/Metal Burst refactor

### LINKED ISSUE #8562: Metal Burst prioritizes physical damage taken (+ some comments on redirection)
### Description

From Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Metal_Burst

> In battles involving multiple Pokémon, Metal Burst will hit the last opponent that dealt damage to the user, even if that opponent is not adjacent to the user.

The logic checks physical damage first, then special damage. So even if the physical damage was received earlier, it'll base the target and damage on that
https://github.com/rh-hideout/pokeemerald-expansion/blob/38519b66e3a266f2aeb95d33a104817d601149fb/src/battle_script_commands.c#L14031-L14068

The solution would be to have a third damage variable that tracks both physical and special damage

Another thing from bulbapedia which I haven't investigated, but probably should be looked into:
> However, if the last Pokémon to hit the user faints before the user moves, the remaining enemy Pokémon will be hit instead, like with a regular single-target damaging move (using the damage taken from the move of the now-fainted Pokémon that had hit the user).

Currently, a target isn't counted if it's fainted, but bulbapedia suggests that it should consider damage from fainted mons anyway

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
Refactors Counter, Mirror Coat, Metal Burst and Comeuppance to use a new effect, `EFFECT_REFLECT_DAMAGE`, that allows for moves that reflect a certain percentage of the damage taken by the last move of a specified category.

Simplified `gSpecialStatuses` members `physicalDmg`, `specialDmg`, `enduredDamage` to `damagedByAttack`.

Adds 2 `EFFECT_REFLECT_DAMAGE` relevant configs for the following interactions:

- `COUNTER_MIRROR_COAT_ALLY`

> In the fourth generation, if the last move taken was from an ally, it will fail even if the Pokemon has been hit by a move from an enemy that turn. From the fifth generation onwards, allies' attacks have no effect, and the Pokemon will counterattack against the enemy that last dealt damage with a move. If the Pokemon has not been hit by a move from an enemy that turn, it will fail.

- `COUNTER_TRY_HIT_PARTNER` (According to the test file, this was different in Gen4- and Gen5+)

> If the opponent that used the last move has already fainted and is no longer in play, such as when it has received damage from Explosion, it will counterattack against the other Pokémon remaining in the opponent's field. If the opponent has no Pokémon in play, it will fail.

Added many Metal Burst, Mirror Coat and Counter tests.

## Issue(s) that this PR fixes
Fixes #8562

## Things to note in the release changelog:
- `EFFECT_COUNTER`, `EFFECT_MIRROR_COAT` and `EFFECT_METAL_BURST` have been combined into `EFFECT_REFLECT_DAMAGE`
- These now use `BattleScript_EffectHit` and their damage is calculated in `DoFixedDamageMoveCalc`

## Discord contact info
PhallenTree

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -8727,6 +8765,25 @@ s32 DoFixedDamageMoveCalc(struct BattleContext *ctx)
...
+                baseDamage = gProtectStructs[ctx->battlerAtk].physicalDmg;
+            else
+                baseDamage = gProtectStructs[ctx->battlerAtk].specialDmg;
+        
+            dmg = (baseDamage - 1) * percentMultiplier / 100;
+        }
+        else
+        {
+            return INT32_MAX;
+        }
```
Comment (AlexOn1ine) [inline src/battle_util.c]: maybe we should assign `INT32_MAX` on initialization so we don't need the else branch?

Comment (PhallenTree) [reply src/battle_util.c]: Done, also had to do an early return otherwise it would clear effectiveness flags from any non-fixed damage move.

Comment (AlexOn1ine) [reply src/battle_util.c]: Right, looks better anyways then the previous implementation
