### PR TITLE
Fix FindMonThatAbsorbsOpponentsMove not seeing Mold Breaker or choice items

### LINKED ISSUE #6854: FindMonThatAbsorbsOpponentsMove doesn't check for Mold Breaker
### Description

Title, this is easy I just need to remember to do it, hence making an issue

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

Pawkkie

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
AI currently doesn't consider the player's Mold Breaker ability when sending in a mon with an absorbing ability. This is rather exploitable.

While fixing this, noticed that it also ran a damage calc without considering choice locked items. This has already been addressed in the other switching functions, must forgotten this one had one.

This PR fixes both of these issues.

## Issue(s) that this PR fixes
#6854 

## **Discord contact info**
@Pawkkie

### CODE REVIEW

File: src/battle_ai_switch_items.c [hunk 1]
```diff
@@ -462,6 +462,8 @@ static bool32 FindMonThatAbsorbsOpponentsMove(u32 battler)
         return FALSE;
     if (AreStatsRaised(battler))
         return FALSE;
+    if (IsMoldBreakerTypeAbility(opposingBattler, GetBattlerAbility(opposingBattler)))
+        return FALSE;
```
Comment (AlexOn1ine) [inline src/battle_ai_switch_items.c:466]: This retrieves the non stored ability

Comment (Pawkkie) [reply src/battle_ai_switch_items.c:466]: Heck this should be `AI_GetBattlerAbility` then right, I always forget there are discrepancies between these

Comment (Pawkkie) [reply src/battle_ai_switch_items.c]: Fixed :)

**Review by AlexOn1ine — APPROVED** [review]
