### PR TITLE
Fix namebox bug when reloading the map mid-script

### LINKED ISSUE #8049: PokeNav overworld calls get glitched if last message has a namebox
### Description

Title. I saw it happening when trying to set a namebox to Mr. Briney's text when sailing to Dewford with him: afterwards, the scripted call from Norman becomes glitched (you can still press A and proceed, though). This one is the easiest to see; probably happens with other scripted calls or random ones too, might investigate later...

### Reproduction Steps

In file data/maps/Route104_MrBrineysHouse/scripts.inc, go at Route104_MrBrineysHouse_EventScript_SailToDewford and add a namebox using the setspeaker command (right before msgbox Route104_MrBrineysHouse_Text_SetSailForDewford, MSGBOX_DEFAULT).

### Images / Video

Image

### Version

upcoming (Edge)

### Upcoming/master Version

3260d2a42ad9d61b94a352aef9b287de15148bf7

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Description
When the game waps, the overworld is reloaded and all windows are deeleted/freed but because sNameboxWindowId is not cleared, the namebox code will bug and delete or modify already existing windows. We add a function to reset sNameboxWindowId that is called when loading a new map at the same times windows are freed

## Media
I used the same setup described in #8049

https://github.com/user-attachments/assets/2f73ac21-b28d-4261-b04c-6fbd1c670e0b

## Issue(s) that this PR fixes
Fixes #8049

## Discord contact info
Jamie

### CODE REVIEW

File: src/overworld.c [hunk 1]
```diff
@@ -1495,6 +1496,7 @@ static void InitOverworldBgs(void)
     SetBgTilemapBuffer(1, gOverworldTilemapBuffer_Bg1);
     SetBgTilemapBuffer(2, gOverworldTilemapBuffer_Bg2);
     SetBgTilemapBuffer(3, gOverworldTilemapBuffer_Bg3);
+    ResetNameboxId();
```
Comment (mudskipper13) [inline src/overworld.c]: This should be within the `InitStandardTextBoxWindows();` function below instead of being alone here, as that's where all Overworld Window IDs (e.g. Start Menu) are usually being initialized. It doesn't have much difference in-game, but it's good for consistency

File: src/field_name_box.c [hunk 2]
```diff
@@ -94,6 +94,11 @@ u32 GetNameboxWindowId(void)
     return sNameboxWindowId;
 }
 
+void ResetNameboxId(void)
+{
+    sNameboxWindowId = WINDOW_NONE;
+}
+
```
Comment (mudskipper13) [inline src/field_name_box.c]: I'd add resetting `gSpeakerName` as well to ensure there's no leftover namebox spawned when transitioning onto a new map (and then rename the function to accomodate it).
```suggestion
void ResetNameboxData(void)
{
    sNameboxWindowId = WINDOW_NONE;
    gSpeakerName = NULL;
}
```
