### PR TITLE
Fix most failed and assume fail tests with `GEN_LATEST` = `GEN_6`

### LINKED ISSUE #6081: Some sleep clause tests fail with P_LVL_UP_LEARNSETS set to Gen 6
### Description

Delibird only learns 1 move in these generations, which breaks the tests. Wasn't aware this was a limitation when I wrote them.

I used Delibird because it's the only mon with both Insomnia and Vital Spirit, so it was really convenient. Will need to rewrite these using another mon.

### Version

1.10.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

Pawkkie

### LINKED ISSUE #6600: Test Runner Move PP on Slot 2+
### Description

From original PR #5525:

Failsafe check on assigned move PP. If a mon has a moveset with a single move, PP in move slot 2+ will be 0, so some tests will fail with a hard-to-track issue

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Follow up to #7688

Tests with added `ASSUME`s due to data changes:
- `AI_FLAG_RISKY: Mid-battle switches prioritize offensive options`.
  - Swellow's 50 Sp.Atk in Gen 6 instead of the current 75 causes the AI to switch to Electrode.
- `Trainer Class Balls apply to the entire party`

## Issue(s) that this PR fixes
Closes #6081, closes #6600.

## Discord contact info
AsparagusEduardo

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Ready for review!

File: test/test_runner_battle.c [hunk 1]
```diff
@@ -1564,9 +1564,14 @@ void OpenPokemon(u32 sourceLine, u32 side, u32 species)
     (*partySize)++;
 
     CreateMon(DATA.currentMon, species, 100, 0, TRUE, 0, OT_ID_PRESET, 0);
-    data = MOVE_NONE;
+    // Reset move IDs, but force PP to be non-zero. This is a safeguard against test species that only learn 1 move having test moves with 0 PP
     for (i = 0; i < MAX_MON_MOVES; i++)
+    {
+        data = MOVE_NONE;
         SetMonData(DATA.currentMon, MON_DATA_MOVE1 + i, &data);
+        data = 0x7F;
```
Comment (AlexOn1ine) [inline test/test_runner_battle.c]: Maybe add a comment that this is max pp? Without looking into `struct PokemonSubstruct1` it isn't obvious why it is set to `0x7F`

File: test/battle/move_effect/role_play.c [hunk 2]
```diff
@@ -93,7 +93,8 @@ SINGLE_BATTLE_TEST("Role Play fails if user's ability can't be suppressed")
     u32 species, ability;
 
     PARAMETRIZE { species = SPECIES_ARCEUS; ability = ABILITY_MULTITYPE; }
-    PARAMETRIZE { species = SPECIES_DARMANITAN; ability = ABILITY_ZEN_MODE; }
+    if (B_UPDATED_ABILITY_DATA >= GEN_7)
+        PARAMETRIZE { species = SPECIES_DARMANITAN; ability = ABILITY_ZEN_MODE; }
```
Comment (AlexOn1ine) [inline test/battle/move_effect/role_play.c:97]: what is the config for?

File: test/battle/move_effect/focus_punch.c [hunk 3]
```diff
@@ -114,12 +114,13 @@ AI_SINGLE_BATTLE_TEST("AI will Incapacitate -> Substitute -> Focus Punch if able
 
 AI_SINGLE_BATTLE_TEST("AI won't use status moves if the player's best attacking move is Focus Punch")
 {
+    //AI_LOG;
```
Comment (AlexOn1ine) [inline test/battle/move_effect/focus_punch.c]:
```suggestion
```

File: test/battle/gimmick/zmove.c [hunk 4]
```diff
@@ -6,9 +6,10 @@
 SINGLE_BATTLE_TEST("(Z-MOVE) Z-Moves do not retain priority")
 {
     GIVEN {
+        WITH_CONFIG(GEN_CONFIG_MEGA_EVO_TURN_ORDER, GEN_7); // TODO: Decouple this config from other gimmicks
```
Comment (AlexOn1ine) [inline test/battle/gimmick/zmove.c:9]: > // TODO: Decouple this config from other gimmicks

What's the issue here?

Comment (AsparagusEduardo) [reply test/battle/gimmick/zmove.c:9]: > > // TODO: Decouple this config from other gimmicks
> 
> What's the issue here?

When setting this config to Gen 6 or lower, Z-Moves retain the original move's priority. This is because it relies on TryChangeTurnOrder handled by it.

File: test/battle/move_effect/role_play.c (hunk 2 above)
Comment (AsparagusEduardo) [reply test/battle/move_effect/role_play.c:97]: > what is the config for?

Apparently, Zen Mode was updated in Gen 7 so that it can't be overridden, and this test didn't account for that, making it fail.

**Comment by AsparagusEduardo** [comment]
Addressed the other comments
