### PR TITLE
Fixes Status overwrites and Effect Spore wrong func args

### LINKED ISSUE #7323: effect spore can sleep already statused mons
### Description

paralysed mons can be put to sleep by contacting mon with effect spore. maybe other statuses too, this is the situation I encountered however. 

### Reproduction Steps

attack an effcet spore mon with a contact move while paralysed until effect spore triggers a sleep. when sleep ends, para returns.

### Images / Video

https://github.com/user-attachments/assets/7d8df219-fe22-4cbf-b8ba-9c91fac7986b

### Version

upcoming (Edge)

### Upcoming/master Version

424c127b8bab529ef7b8834e3d8b74c9281bb672

### Discord contact info

mrleaky666

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7323

### CODE REVIEW

File: test/battle/move_effect/protect.c [hunk 1]
```diff
@@ -194,6 +194,27 @@ SINGLE_BATTLE_TEST("Protect: Baneful Bunker poisons pokemon for moves making con
     }
 }
 
+SINGLE_BATTLE_TEST("Protect: Baneful Bunker can't poison pokemon if they are already statused")
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET);
+        PLAYER(SPECIES_WOBBUFFET);
```
Comment (Bassoonian) [inline test/battle/move_effect/protect.c]: Why does the player have two Pokémon?

File: test/battle/move_effect/protect.c [hunk 2]
```diff
@@ -226,6 +247,27 @@ SINGLE_BATTLE_TEST("Protect: Burning Bulwark burns pokemon for moves making cont
     }
 }
 
+SINGLE_BATTLE_TEST("Protect: Burning Bulwark can't burn pokemon if they are already statused")
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET);
+        PLAYER(SPECIES_WOBBUFFET);
```
Comment (Bassoonian) [inline test/battle/move_effect/protect.c]: Why does the player have two Pokémon?

Comment (AlexOn1ine) [reply test/battle/move_effect/protect.c]: removed

File: test/battle/move_effect/protect.c (hunk 1 above)
Comment (AlexOn1ine) [reply test/battle/move_effect/protect.c]: removed
