### PR TITLE
Fix stats defined in tests being  overwritteng by stat change

### LINKED ISSUE #4550: In Tests, some form changes override the HP stat defined to the test when triggered.
### Description

Some form changing effects that change stats when activated behave strangely in tests.
HP is recalculated when the form changes and the new MaxHP is calculated using the species Base HP with 0 IVs and EVs. Then damage taken is applied in different ways depending on how the new Max/current HP compares to the Test defined ones. I haven't analyzed the relationship properly, just noticed that differences exist.
Transform is not affected by this presumably because it's specifically coded to not change the HP stat.
Most of the effects could be coded to ignore the HP stat too, since most forms with different stats never have different HP, the only outlier is Zygarde-Complete which changes its HP stat.

https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/270b691f-8d5e-4360-9072-762387cbcdac

https://github.com/rh-hideout/pokeemerald-expansion/assets/149414898/a18864cf-e1b5-4688-a113-e73bd625c976

### Version

1.8.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Description
I thought the best way to fix both #4550 and #4743 would be to change CalculateMonStats to not update some stats based on a flag set by the testing system. The hyper training flags seemed like good candidate for that because they do not matter for battle test and thus can be used without having to modify the test structure. It worked at fixing both issues but broke the HyperTraining tests in `test/pokemon.c`. Adding a inBattle check make the changes work for form changes and does not break hyper training tests but it doesn't work for level change because they happen before the battle start. 
So I made sure the stat recalcs for level changes happen at the beginning of battle instead of the test set-up phase.
I also added a short CalculateMonStats test to make sure the refactor didn't break functionality. The test passed both commits of this PR: before and after the refactor
Some tests broke functionality because they expected the speed to change when changing forms so I had to modify them

## Issue(s) that this PR fixes
Fixes #4550 and #4743

## Discord contact info
Jamie

### CODE REVIEW

File: src/pokemon.c [hunk 1]
```diff
@@ -3567,6 +3572,26 @@ u32 GetSpeciesBaseSpeed(u16 species)
...
+            return GetSpeciesBaseAttack(species);
+        case STAT_DEF:
+            return GetSpeciesBaseDefense(species);
+        case STAT_SPEED:
+            return GetSpeciesBaseSpeed(species);
+        case STAT_SPATK:
+            return GetSpeciesBaseSpAttack(species);
+        case STAT_SPDEF:
+            return GetSpeciesBaseSpDefense(species);
+    }
```
Comment (AlexOn1ine) [inline src/pokemon.c:3591]:
```suggestion
    {
    case STAT_HP:
        return GetSpeciesBaseHP(species);
    case STAT_ATK:
        return GetSpeciesBaseAttack(species);
    case STAT_DEF:
        return GetSpeciesBaseDefense(species);
    case STAT_SPEED:
        return GetSpeciesBaseSpeed(species);
    case STAT_SPATK:
        return GetSpeciesBaseSpAttack(species);
    case STAT_SPDEF:
        return GetSpeciesBaseSpDefense(species);
    }
```

File: test/battle/form_change/mega_evolution.c [hunk 2]
```diff
@@ -75,10 +75,10 @@ SINGLE_BATTLE_TEST("Mega Evolution doesn't affect turn order (Gen6)")
 {
     GIVEN {
         WITH_CONFIG(GEN_CONFIG_MEGA_EVO_TURN_ORDER, GEN_6);
-        PLAYER(SPECIES_GARDEVOIR) { Item(ITEM_GARDEVOIRITE); Speed(105); }
-        OPPONENT(SPECIES_WOBBUFFET) { Speed(106); }
+        PLAYER(SPECIES_GARDEVOIR) { Item(ITEM_GARDEVOIRITE); }
+        OPPONENT(SPECIES_WOBBUFFET) {}
```
Comment (AlexOn1ine) [inline test/battle/form_change/mega_evolution.c:79]: I think the test modifications make the test case invalid. Same applies to the other turn order tests

Comment (FosterProgramming) [reply test/battle/form_change/mega_evolution.c:79]: Ok, I spent hours testing this. The test is valid because when no explicit speed is given to the battler, the test engine will fix the speed for the battlers based on the order of their commands in the turn list. The first move will make the batttler act at speed 12 and the second one at speed 11 but this rigging doesn't prevent stat changing from from change. So by putting opponent first in the turn commands, it create a similar effect at what was achieved before with fixing the speed

Comment (AlexOn1ine) [reply test/battle/form_change/mega_evolution.c:79]: I see

File: test/test_runner_battle.c [hunk 3]
```diff
@@ -1681,14 +1681,18 @@ void Level_(u32 sourceLine, u32 level)
     INVALID_IF(level == 0 || level > MAX_LEVEL, "Illegal level: %d", level);
     SetMonData(DATA.currentMon, MON_DATA_LEVEL, &level);
     SetMonData(DATA.currentMon, MON_DATA_EXP, &gExperienceTables[gSpeciesInfo[species].growthRate][level]);
+    gMain.inBattle = TRUE;
     CalculateMonStats(DATA.currentMon);
+    gMain.inBattle = FALSE;
```
Comment (AlexOn1ine) [inline test/test_runner_battle.c:1686]: Out of scope for the PR but maybe it's better to pass down an `arg` instead of checking `gMain.inBattle`
