### PR TITLE
Fixes Dynamic Moves types in SumScreen while in Battle

### LINKED ISSUE #6034: Dynamic Hidden Power Type not Working for Mons not in Battle
### Description

The dynamic hidden power type is not showing correctly during a battle, but only when viewing the summary screen on a mon that is not currently on the field.
I know i have Rave's BW summary screen and i apologize that i was too lazy to go capture this on clean master, but i looked at the relevant code and id bet $1 the same thing will happen there.

https://github.com/user-attachments/assets/a3eca9ca-4712-4463-9556-89a395adc75d

note my omastar has hidden power flying, which shows correctly when hes the battler on the field, but does not show correctly when hes off the field.
the relevant code is in the `GetDynamicMoveType` function. 
i changed the `if (gMain.inBattle)` -> `if (gMain.inBattle && gBattleMons[battler].species == GetMonData(mon, MON_DATA_SPECIES))` in the case for hidden power and it resolved my issue in my own proj, but something similar may need to be done for other moves that use this function, which i havent verified yet.

### Version

1.10.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

iriv24

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6034

### CODE REVIEW

File: src/battle_main.c [hunk 1]
```diff
@@ -5844,11 +5844,13 @@ u32 GetDynamicMoveType(struct Pokemon *mon, u32 move, u32 battler, u8 *ateBoost)
     u32 moveType = gMovesInfo[move].type;
     u32 moveEffect = gMovesInfo[move].effect;
     u32 species, heldItem, holdEffect, ability, type1, type2, type3;
+    bool32 monInBattle = gMain.inBattle && gPartyMenu.menuType != PARTY_MENU_TYPE_IN_BATTLE;
 
     if (move == MOVE_STRUGGLE)
         return TYPE_NORMAL;
 
-    if (gMain.inBattle)
+
```
Comment (AlexOn1ine) [inline src/battle_main.c:5852]:
```suggestion
```

**Review by Bassoonian — APPROVED** [review]
