### PR TITLE
Fixes Trace turn order

### LINKED ISSUE #2432: Reminder: make Trace and Intimidate into normal switch in abilities
Currently, these run in a separate loop from other switch in abilities. This means they don't activate in the correct order - they should activate based on turn order like all other switch in abilities (except Neutralizing Gas).

### LINKED ISSUE #4292: Trace turn order is wrong
### Description

```
DOUBLE_BATTLE_TEST("Wrong Trace activation order")
{
    GIVEN {
        PLAYER(SPECIES_DEOXYS_SPEED) { Speed(40); Ability(ABILITY_PRESSURE); }
        PLAYER(SPECIES_GARDEVOIR) { Speed(20); Ability(ABILITY_TRACE); }
        OPPONENT(SPECIES_HIPPOWDON) { Speed(10); Ability(ABILITY_SAND_STREAM); }
        OPPONENT(SPECIES_DEOXYS_SPEED) { Speed(30); Ability(ABILITY_PRESSURE); }
    } WHEN {
        TURN { }
    } SCENE {
        ABILITY_POPUP(playerLeft, ABILITY_PRESSURE);
        ABILITY_POPUP(opponentRight, ABILITY_PRESSURE);
        ABILITY_POPUP(playerRight, ABILITY_TRACE);
        ABILITY_POPUP(playerRight, ABILITY_PRESSURE);
        ABILITY_POPUP(opponentLeft, ABILITY_SAND_STREAM);
    }
}
```
Trace is supposed to activate before Sand Stream.

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/56a63eb6-8bcf-42b6-acd2-a7fed2f86aba

Works fine with a different ability so I assume it is a problem with Trace

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/5e0defde-18bc-461c-aea9-914667e49ff3

master/upcoming

### Version

1.8.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes  #4292
Fixes #2432

### CODE REVIEW

File: test/battle/ability/trace.c [hunk 1]
```diff
@@ -79,3 +79,20 @@ SINGLE_BATTLE_TEST("Trace will copy an opponent's ability whenever it has the ch
         MESSAGE("Ralts TRACED Foe Torchic's Blaze!");
     }
 }
+
+DOUBLE_BATTLE_TEST("Trace respect the turn order")
```
Comment (Bassoonian) [inline test/battle/ability/trace.c:83]:
```suggestion
DOUBLE_BATTLE_TEST("Trace respects the turn order")
```

**Review by Bassoonian — APPROVED** [review]
