### PR TITLE
Bugfixes Batch

### LINKED ISSUE #5676: Primal Weather not being cleared immediately after fainting
### Description

Primal weather should be cleared immediately after the mon faints as opposed to the instant before you send out a new mon.

https://github.com/user-attachments/assets/b0be8666-38a6-4576-bdec-5b7347edf192

I think the issue is the location of the calls to `trytoclearprimalweather` within `BattleScript_FaintedMonTryChoose` in `battle_scripts_1.s`, but im not 100% sure where they are supposed to go otherwise i woulda just made the PR myself :( 

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

iriv24

### LINKED ISSUE #7396: Entrainment Not Clearing Primal Weather
### Description

If a Pokemon uses Entrainment to change the ability of one of the Primal Legendaries, the Primal Weather does not get cleared.

My local branches are in a kind of jank state or else i would open a PR myself but i added this code

Image

which is whats called in gastro acid and worry seed and it seemed to fix the issue, but i did not do more extensive testing than one manual case

### Reproduction Steps

Have a pokemon with entrainment and an ability other than a primal-weather setting ability
be against a primal legendary (primal groudon for example)
use entrainment, see primal legendary's ability change, but the weather remains

### Images / Video

https://github.com/user-attachments/assets/c2c317b2-6b71-4d81-b442-9eedbebd166a

### Version

1.12.1 (Latest release)

### Upcoming/master Version

master

### Discord contact info

iriv24

### LINKED ISSUE #7450: It's Super Effective string being printed after non-damage dealing moves.
### Description

In battle using a non-damage dealing move that would be considered 'Super Effective' by type still displays the 'It's Super Effective' string. Intended behavior is (I believe) for that message to only be displayed for damage dealing moves.
The responsible function is likely ``static void Cmd_resultmessage(void)`` defined in ``src/battle_script_commands.c``
Confirmed on a clean 1.12.2 repo.

### Reproduction Steps

1) Create a battle with an obedient level 20 Jolteon and an enemy Pidgey (any user pokemon with thunder wave and any enemy flying type mon will do fine)
1a) You can use this script to set it up. Call the script however you prefer -
`
LittlerootTown_Script_TestSign::
	setflag (FLAG_BADGE05_GET)
	givemon SPECIES_JOLTEON, 20
	setwildbattle SPECIES_PIDGEY, 3
	dowildbattle
	end
`
2) Use thunderwave
3) Observe

### Images / Video

Image

Image

### Version

1.12.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #7607: Since Gen5 Synchronize can badly poison
### Description

> When a Pokémon with Synchronize is [badly poisoned](https://bulbapedia.bulbagarden.net/wiki/Poison_(status_condition)) by another Pokémon, that Pokémon will now be inflicted with the bad poison condition, rather than the regular poison condition.

Source: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Synchronize_(Ability))

### Reproduction Steps

The code snippet has to be adjusted:
```
if (gBattleStruct->synchronizeMoveEffect == MOVE_EFFECT_TOXIC)
    gBattleStruct->synchronizeMoveEffect = MOVE_EFFECT_POISON;
```

### Images / Video

_No response_

### Version

1.12.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #7657: Forewarn can corrupt gBattlerTarget
### Description

Refer to #6648 for more information

Apparently, I completely missed forewarn having issues
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_util.c#L3734-L3743
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/src/battle_util.c#L2906-L2908

No target saved at all. Neither in the script, which I double checked for good measure
https://github.com/rh-hideout/pokeemerald-expansion/blob/7302de4209491ed30d214f3d1ed2182b2f58bb47/data/battle_scripts_1.s#L8048-L8052

Really, STRINGID_FOREWARNACTIVATES should just use another battler index instead of B_DEF_NAME_WITH_PREFIX

### Reproduction Steps

N/A, source code analysis

### Images / Video

_No response_

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #7736: BS_ActivateItemEffects uses the wrong case id
### Description

`ITEMEFFECT_NORMAL` ends with `end2` which is incorrect. The callnative is used to trigger stolen Picketpocket items. 

### Reproduction Steps

Needs to be tested 

### Images / Video

_No response_

### Version

1.13.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #5676
Fixes #7396
Fixes #7607
Fixes #7657
Fixes #7736
Fixes #7450

### CODE REVIEW

File: test/battle/ability/desolate_land.c [hunk 1]
```diff
@@ -83,3 +83,17 @@ SINGLE_BATTLE_TEST("Desolate Land will not create a softlock when move in semi i
         ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, player);
     }
 }
+
+SINGLE_BATTLE_TEST("Desolate Land is removed immediately if user faints")
```
Comment (hedara90) [inline test/battle/ability/desolate_land.c:87]: This test currently passes on `master`.
A check for the end of turn sunshine animation should make it have different pass/fail compared to master
pokeemerald-test-0

Comment (AlexOn1ine) [reply test/battle/ability/desolate_land.c:87]: Fixed

File: src/data/pokemon/teachable_learnsets.h
Comment (hedara90) [inline src/data/pokemon/teachable_learnsets.h:1]: Are these changes supposed to be here?

Comment (AlexOn1ine) [reply src/data/pokemon/teachable_learnsets.h:1]: I think it's because of  #7672

**Comment by AlexOn1ine** [comment]
also fixed #7736 just now

File: src/data/pokemon/teachable_learnsets.h
Comment (hedara90) [reply src/data/pokemon/teachable_learnsets.h:1]: Why are the changes only showing up now though?
They were added as part of `fix test` 2cb22d9.

Comment (AlexOn1ine) [reply src/data/pokemon/teachable_learnsets.h:1]: not sure. I can revert them

Comment (AlexOn1ine) [reply src/data/pokemon/teachable_learnsets.h:1]: Actually, maybe we shouldn't revert? Hydrapple can learn those moves and they would be added by a different PR regardless.

Comment (hedara90) [reply src/data/pokemon/teachable_learnsets.h:1]: Yea, I checked `master` just now, the file is changed there too.
It apparently wasn't done as part of the PR that added the moves.

**Comment by AlexOn1ine** [comment]
also fixed #7450

**Review by hedara90 — APPROVED** [review]
