### PR TITLE
Fixed Mega Evolved Pokémon being able to get Friendship effects in battle

### LINKED ISSUE #2261: Reminder: re-review Affection mechanics PR

### PR DESCRIPTION
**Pull request by LOuroboros**
## Description
Fixes #2261.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

File: include/battle.h [hunk 1]
```diff
@@ -456,6 +456,7 @@ struct MegaEvolutionData
     bool8 playerSelect;
     u8 triggerSpriteId;
     bool8 isWishMegaEvo;
+    bool32 didMegaEvo[PARTY_SIZE][2]; // For each party member and side.
```
Comment (AsparagusEduardo) [inline include/battle.h:459]: Why a bool32? That looks wasteful. Plus, there should be an easier way to keep track if a mon is a Mega. I'm thinking a species flag should suffice.
Another thought that I've had is that now that we have form change handling, Mega Evolution and Primal Reversion handling could be refactored to work like them, saving resources in BattleStruct.

Comment (LOuroboros) [reply include/battle.h:459]: > Why a bool32? That looks wasteful.

I thought it would let the GBA's CPU process it faster because it's better suited to handle that data type :eyes:

> Plus, there should be an easier way to keep track if a mon is a Mega. I'm thinking a species flag should suffice.

Sounds like a better idea, as soon as #2293 is merged, I'll update this PR accordingly :eyes:

> Another thought that I've had is that now that we have form change handling, Mega Evolution and Primal Reversion handling could be refactored to work like them, saving resources in BattleStruct.

I thought that was eventually going to happen ever since we talked about eventually moving all the form changes there in the Discord server. I think it's a bit above what I'm personally capable of though since the Mega Evolution code touches some scary parts of the battle engine's code, so if you wanted to handle that... :eyes:

Comment (AsparagusEduardo) [reply include/battle.h:459]: > I thought it would let the GBA's CPU process it faster because it's better suited to handle that data type eyes
While true, it's not a big enough of an improvement

image

> Sounds like a better idea, as soon as #2293 is merged, I'll update this PR accordingly eyes

:+1: 

> I thought that was eventually going to happen ever since we talked about eventually moving all the form changes there in the Discord server. I think it's a bit above what I'm personally capable of though since the Mega Evolution code touches some scary parts of the battle engine's code, so if you wanted to handle that... eyes

Yes, that change would be out of the scope of this PR, so this will be handled later.

I'll mark this PR as a draft for now until #2293 is merged

**Comment by LOuroboros** [comment]
Should be ready for a re-review :eyes:

File: src/battle_util.c [hunk 2]
```diff
@@ -2105,24 +2105,24 @@ void TryToRevertMimicry(void)
     }
 }
 
-u32 GetMonFriendshipScore(struct Pokemon *pokemon)
+u32 GetBattlerFriendshipScore(u8 battlerId)
 {
-    u32 friendshipScore = GetMonData(pokemon, MON_DATA_FRIENDSHIP);
+    struct MegaEvolutionData *mega = &(((struct ChooseMoveStruct *)(&gBattleResources->bufferA[battlerId][4]))->mega);
```
[the remark this answers is not in the document]
Comment (LOuroboros) [reply src/battle_util.c]: Oopsie. Done.

**Review by AsparagusEduardo — APPROVED** [review]
Just in time!
