### PR TITLE
Fix various Toxic Spikes interactions

### LINKED ISSUE #6682: Comatose Pokemon can be poisoned by Toxic Spikeson switch-in
### Description

Pokemon with Comatose aren't supposed to be poisoned on switchin into Toxic Spikes, verified on cart.

https://github.com/user-attachments/assets/06f21881-ff3a-42c0-967e-bbd656588a6f

Test to verify behaviour.
```C
SINGLE_BATTLE_TEST("Comatose pokemon doesn't get poisoned by Toxic Spikes on switch-in")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_KOMALA) { Ability(ABILITY_COMATOSE); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(opponent, MOVE_TOXIC_SPIKES); }
        TURN { SWITCH(player, 1); }
    } SCENE {
        NOT STATUS_ICON(player, STATUS1_POISON);
        ABILITY_POPUP(player, ABILITY_COMATOSE);
        NOT HP_BAR(player);
    }
}
```

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Toxic Spikes handling wasn't taking into account Comatose.
Added tests for Mold Breaker + Phazing interactions with Toxic Spikes and immunity Abilities.

## Issue(s) that this PR fixes

Fixes #6682 

## Feature(s) this PR does NOT handle:

Pastel Veil interactions not handled, needs investigation.

## **Discord contact info**

hedara

### CODE REVIEW

File: test/battle/ability/comatose.c [hunk 1]
```diff
@@ -55,3 +55,35 @@ SINGLE_BATTLE_TEST("Comatose may be suppressed if pokemon transformed into a pok
...
+        ABILITY_POPUP(player, ABILITY_COMATOSE);
+        NOT HP_BAR(player);
+    }
+}
+
+SINGLE_BATTLE_TEST("Comatose pokemon don't get poisoned by Toxic Spikes on switch-in if forced in by phazing with Mold Breaker")
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET);
+        PLAYER(SPECIES_SNORLAX) { Ability(ABILITY_IMMUNITY); }
```
Comment (PhallenTree) [inline test/battle/ability/comatose.c:79]:
```suggestion
        PLAYER(SPECIES_KOMALA) { Ability(ABILITY_COMATOSE); }
```

**Comment by hedara90** [comment]
Fixed, it was me being stupid when testing more interactions.

**Comment by AlexOn1ine** [comment]
@PhallenTree once you reviewed something can you push the approve button? :sweat_smile: I know you can't merge but I think every other maintainer will trust you enough to merge after your approval.

**Review by PhallenTree — APPROVED** [review]

**Review by AlexOn1ine — APPROVED** [review]
