### PR TITLE
Fix Defog and Prevent Escape effects

### LINKED ISSUE #3664: Pain Split can be Mirror Coated
### Description

Damage done by Pain Split can be reflected by Mirror Coat.

### Version

upcoming (Edge)

### Upcoming Version

77ae9e3

### Discord contact info

._.terra._.

### LINKED ISSUE #3665: Some Trapping Moves like Spirit Shackle do not Trap the Player
### Description

I have tested this behaviour with Spirit Shackle and Anchor Shot. There might be other moves I cannot think of right now.

If the foe's Pokemon uses one of these moves, the player can still switch out. However, these moves are supposed to trap the player.

### Version

upcoming (Edge)

### Upcoming Version

77ae9e3

### Discord contact info

._.terra._.

### LINKED ISSUE #3666: Defog PP issue
### Description

If the foe's Pokemon's evasion is -6, Defog does not get its PP drained, making for a basically infinitely usable move.

### Version

1.6.2 (Default)

### Upcoming Version

77ae9e3

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #3665
Fixes #3666
Fixes #3664

I changed `EFFECT_HIT_PREVENT_ESCAPE` to a primary effect and for Defog `gBattlerAttacker` was overwritten inside the loop in `TryDefogClear` so I restored it at the end of the function. Also changed cleardefog to a callnative.

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -2390,7 +2390,7 @@ static void Cmd_datahpupdate(void)
                         gSpecialStatuses[battler].physicalBattlerId = gBattlerTarget;
                     }
                 }
-                else if (!IS_MOVE_PHYSICAL(gCurrentMove) && !(gHitMarker & HITMARKER_PASSIVE_DAMAGE))
+                else if (!IS_MOVE_PHYSICAL(gCurrentMove) && !(gHitMarker & HITMARKER_PASSIVE_DAMAGE) && gCurrentMove != MOVE_PAIN_SPLIT)
```
Comment (Bassoonian) [inline src/battle_script_commands.c:2393]: Shouldn't we check for `EFFECT_PAIN_SPLIT` instead?

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Yes. Fixed.

**Review by Bassoonian — APPROVED** [review]
