### PR TITLE
Fix Minior start of battle form

### LINKED ISSUE #6473: Minior Formchange Bug
### Description

Intended: Minior starts in its broken form pre battle. When it is sent out, it instantly transforms into its shielded form. 

Currently: Minior always starts in its shielded form.

Example: https://youtu.be/VZrnsWYrQRQ?t=677

### Version

1.11.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Minior is supposed to start battles in Core form, then immediately change to Meteor form when sent out if above 50% HP

## Media

https://github.com/user-attachments/assets/4971e93b-320f-4e57-9da3-01f77e071d77

## Issue(s) that this PR fixes

Fixes #6473 

## Discord contact info

hedara

### CODE REVIEW

File: test/battle/ability/shields_down.c [hunk 1]
```diff
@@ -1,23 +1,25 @@
...
+            ABILITY_POPUP(opponent, ABILITY_SHIELDS_DOWN);
+            ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_FORM_CHANGE, opponent);
+        }
     } THEN {
         EXPECT_EQ(opponent->species, SPECIES_MINIOR_CORE);
     }
 }
 
-SINGLE_BATTLE_TEST("Minior Core transforms into Minior Meteor on switch-in if it more then 1/2 health")
+SINGLE_BATTLE_TEST("Minior Core transforms into Minior Meteor on switch-in if has it more then 1/2 health")
```
Comment (Bassoonian) [inline test/battle/ability/shields_down.c]:
```suggestion
SINGLE_BATTLE_TEST("Minior Core transforms into Minior Meteor on switch-in if it has more than 1/2 health")
```

File: test/battle/ability/shields_down.c [hunk 2]
```diff
@@ -33,6 +35,21 @@ SINGLE_BATTLE_TEST("Minior Core transforms into Minior Meteor on switch-in if it
     }
 }
 
+SINGLE_BATTLE_TEST("Minior Core transforms into Minior Meteor on battle start if it has more then 1/2 health")
```
Comment (Bassoonian) [inline test/battle/ability/shields_down.c]:
```suggestion
SINGLE_BATTLE_TEST("Minior Core transforms into Minior Meteor on battle start if it has more than 1/2 health")
```

Also, >1/2 or >=1/2?

Comment (hedara90) [reply test/battle/ability/shields_down.c]: From testing on cart.
At 10 out of 20 HP Minior stays in Core form when sent out.

Comment (Bassoonian) [reply test/battle/ability/shields_down.c]: Shouldn't we test for that too then instead of just assuming full HP?

Comment (hedara90) [reply test/battle/ability/shields_down.c]: Tests updated
