### PR TITLE
Version specific tweaks of post whiteout script

### LINKED ISSUE #9315: Nursejoy doesn't look towards healing machine after whiteout in FRLG
### Description

Nursejoy doesn't look towards healing machine after whiteout in FRLG
Fine if you heal only doesn't when you white out

### Reproduction Steps

_No response_

### Images / Video

Vanilla
https://github.com/user-attachments/assets/39711dde-b39c-4db6-b74b-a76b32b34315

Expansion
https://github.com/user-attachments/assets/48c5e80d-9e0d-4eeb-9f4b-ae8b270aa9f0

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

Hunar#2786

### PR DESCRIPTION
**Pull request by FosterProgramming**
In vanilla emerald, you are simply teleported in front of the pokecenter 
In #4967, Cawt added a new config that copied the FRLG system where a little cutscene play when you whiteout
This was turned into a gen config on by default in a later commit
This feature was slightly bugged because it used VAR_LAST_TALKED to store the last nurse id (the way it is in frlg) but the emerald script expect it to be stored in VAR_0x800B

With the addition of FRLG into expansion, there were a few additional issues specific to FRLG mode:
- the script mom says after whiteout would reference Professor Birch
- the nurse would use the emerad healing text instead of the firered healing during a whiteout cutscene

This PR should fix all these issues

## Issue(s) that this PR fixes
Fixes #9315

## Discord contact info
Jamie

### CODE REVIEW

File: src/field_screen_effect.c [hunk 1]
```diff
@@ -1454,7 +1454,15 @@ static void Task_RushInjuredPokemonToCenter(u8 taskId)
...
+                if (IS_FRLG)
+                    StringCopy(gStringVar1, COMPOUND_STRING("PROF. OAK"));
+                else
+                    StringCopy(gStringVar1, COMPOUND_STRING("PROF. BIRCH"));
                 ScriptContext_SetupScript(EventScript_AfterWhiteOutMomHeal);
+            }
+            else if (IS_FRLG)
+                ScriptContext_SetupScript(EventScript_AfterWhiteOutHeal_Frlg);
             else
                 ScriptContext_SetupScript(EventScript_AfterWhiteOutHeal);
```
Comment (Bassoonian) [inline src/field_screen_effect.c:1470]:
```suggestion
            else if (IS_FRLG)
            {
                ScriptContext_SetupScript(EventScript_AfterWhiteOutHeal_Frlg);
            }
            else
            {
                ScriptContext_SetupScript(EventScript_AfterWhiteOutHeal);
            }
```
