### PR TITLE
Fling fixes and tests

### LINKED ISSUE #3001: Fling doesn't check if move is successful before consuming item.
When using Fling in battle, the item will always be consumed, even if the move isn't actually successfully used. For example, if a Pokémon is asleep and uses Fling, then it will sleep for the turn and the item will have been consumed erroneously. Another consequence of this is that if the Pokémon is not holding an item and uses Fling, the textbox that states how the move has failed will always print even when it's not supposed to.

The problem stems from `BattleScript_EffectFling` in **data/battle_scripts_1.s**

```
BattleScript_EffectFling:
    jumpifcantfling BS_ATTACKER, BattleScript_ButItFailedAtkStringPpReduce
    jumpifstatus3 BS_ATTACKER, STATUS3_EMBARGO, BattleScript_ButItFailedAtkStringPpReduce
    jumpifword CMP_COMMON_BITS, gFieldStatuses, STATUS_FIELD_MAGIC_ROOM, BattleScript_ButItFailedAtkStringPpReduce
    setlastuseditem BS_ATTACKER
    removeitem BS_ATTACKER
    attackcanceler
    accuracycheck BattleScript_PrintMoveMissed, ACC_CURR_MOVE
    attackstring
    pause B_WAIT_TIME_SHORT
    printstring STRINGID_PKMNFLUNG
    waitmessage B_WAIT_TIME_SHORT
    ppreduce
    critcalc
    damagecalc
    ...
```
`attackcanceler` is used too late here and needs to be moved to the first line like so:

```
BattleScript_EffectFling:
    attackcanceler
    jumpifcantfling BS_ATTACKER, BattleScript_ButItFailedAtkStringPpReduce
    jumpifstatus3 BS_ATTACKER, STATUS3_EMBARGO, BattleScript_ButItFailedAtkStringPpReduce
    jumpifword CMP_COMMON_BITS, gFieldStatuses, STATUS_FIELD_MAGIC_ROOM, BattleScript_ButItFailedAtkStringPpReduce
    setlastuseditem BS_ATTACKER
    removeitem BS_ATTACKER
    accuracycheck BattleScript_PrintMoveMissed, ACC_CURR_MOVE
    attackstring
    pause B_WAIT_TIME_SHORT
    printstring STRINGID_PKMNFLUNG
    waitmessage B_WAIT_TIME_SHORT
    ppreduce
    critcalc
    damagecalc
    ...
```

That's pretty much it.

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3001

- Tests for Fling
- Changed the Fling various to a call native
- removed unnecessary lines from the Fling battlescript
- made kee berry and maranga berry be affected by fling

### CODE REVIEW

File: test/move_effect_fling.c [hunk 1]
```diff
@@ -0,0 +1,336 @@
...
+
+SINGLE_BATTLE_TEST("Fling fails if pokemon holds no item")
+{
+    u16 item;
+
+    PARAMETRIZE {item = ITEM_NONE; }
+    PARAMETRIZE {item = ITEM_RAZOR_CLAW; }
+
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) {Item(item); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:17]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(item); }
```

File: test/move_effect_fling.c [hunk 2]
```diff
@@ -0,0 +1,336 @@
...
+    u16 move;
+
+    PARAMETRIZE {move = MOVE_CELEBRATE; }
+    PARAMETRIZE {move = MOVE_EMBARGO; }
+    PARAMETRIZE {move = MOVE_MAGIC_ROOM; }
+
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_EMBARGO].effect == EFFECT_EMBARGO);
+        ASSUME(gBattleMoves[MOVE_MAGIC_ROOM].effect == EFFECT_MAGIC_ROOM);
+        PLAYER(SPECIES_WOBBUFFET) {Item(ITEM_RAZOR_CLAW); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:43]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_RAZOR_CLAW); }
```

File: test/move_effect_fling.c [hunk 3]
```diff
@@ -0,0 +1,336 @@
...
+    PARAMETRIZE {item = ITEM_RAZOR_CLAW; }
+
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) {Item(item); }
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_FLING);}
+    } SCENE {
+        MESSAGE("Wobbuffet used Fling!");
+        if (item != ITEM_NONE) {
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:23]:
```suggestion
        if (item != ITEM_NONE)
        {
```

File: test/move_effect_fling.c [hunk 4]
```diff
@@ -0,0 +1,336 @@
...
+            ANIMATION(ANIM_TYPE_MOVE, MOVE_FLING, player);
+            HP_BAR(opponent);
+        } else {
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:26]:
```suggestion
        }
        else
        {
```

File: test/move_effect_fling.c [hunk 5]
```diff
@@ -0,0 +1,336 @@
...
+    PARAMETRIZE {move = MOVE_MAGIC_ROOM; }
+
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_EMBARGO].effect == EFFECT_EMBARGO);
+        ASSUME(gBattleMoves[MOVE_MAGIC_ROOM].effect == EFFECT_MAGIC_ROOM);
+        PLAYER(SPECIES_WOBBUFFET) {Item(ITEM_RAZOR_CLAW); }
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(opponent, move);}
+        TURN { MOVE(player, MOVE_FLING);}
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:47]:
```suggestion
        TURN { MOVE(opponent, move); }
        TURN { MOVE(player, MOVE_FLING); }
```

File: test/move_effect_fling.c [hunk 6]
```diff
@@ -0,0 +1,336 @@
...
+{
+    u16 ability;
+
+    PARAMETRIZE {ability = ABILITY_KLUTZ; }
+    PARAMETRIZE {ability = ABILITY_RUN_AWAY; }
+
+    GIVEN {
+        ASSUME(P_GEN_4_POKEMON == TRUE);
+        ASSUME(B_KLUTZ_FLING_INTERACTION >= GEN_5);
+        PLAYER(SPECIES_BUNEARY) {Item(ITEM_RAZOR_CLAW); Ability(ability); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:69]:
```suggestion
        PLAYER(SPECIES_BUNEARY) { Item(ITEM_RAZOR_CLAW); Ability(ability); }
```

File: test/move_effect_fling.c [hunk 7]
```diff
@@ -0,0 +1,336 @@
...
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_FLING);}
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:72]:
```suggestion
        TURN { MOVE(player, MOVE_FLING); }
```

File: test/move_effect_fling.c [hunk 8]
```diff
@@ -0,0 +1,336 @@
...
+            MESSAGE("But it failed!");
+        }
+    }
+}
+
+SINGLE_BATTLE_TEST("Fling's thrown item can be regained with Recycle")
+{
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_RECYCLE].effect == EFFECT_RECYCLE);
+        PLAYER(SPECIES_WOBBUFFET) {Item(ITEM_RAZOR_CLAW); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:88]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_RAZOR_CLAW); }
```

File: test/move_effect_fling.c [hunk 9]
```diff
@@ -0,0 +1,336 @@
...
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_FLING);}
+        TURN { MOVE(player, MOVE_RECYCLE);}
+        TURN { MOVE(player, MOVE_FLING);}
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:93]:
```suggestion
        TURN { MOVE(player, MOVE_FLING); }
        TURN { MOVE(player, MOVE_RECYCLE); }
        TURN { MOVE(player, MOVE_FLING); }
```

File: test/move_effect_fling.c [hunk 10]
```diff
@@ -0,0 +1,336 @@
...
+    }
+}
+
+SINGLE_BATTLE_TEST("Fling - Item is lost even when there is no target")
+{
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_SELF_DESTRUCT].effect == EFFECT_EXPLOSION);
+        PLAYER(SPECIES_WOBBUFFET) {Item(ITEM_RAZOR_CLAW); Speed(2); }
+        OPPONENT(SPECIES_WOBBUFFET) {Speed(5); }
+        OPPONENT(SPECIES_WOBBUFFET) {Speed(5); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:113]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_RAZOR_CLAW); Speed(2); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(5); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(5); }
```

File: test/move_effect_fling.c [hunk 11]
```diff
@@ -0,0 +1,336 @@
...
+        TURN { MOVE(opponent, MOVE_SELF_DESTRUCT); MOVE(player, MOVE_FLING); SEND_OUT(opponent, 1); }
+        TURN { MOVE(player, MOVE_FLING); }
+    } SCENE {
+        MESSAGE("Foe Wobbuffet used SelfDestruct!");
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_SELF_DESTRUCT, opponent);
+        HP_BAR(player);
+        MESSAGE("Foe Wobbuffet fainted!");
+        MESSAGE("Wobbuffet used Fling!");
+        MESSAGE("But it failed!");
+
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:124]: I think it needs the "sent out" message here

File: test/move_effect_fling.c [hunk 12]
```diff
@@ -0,0 +1,336 @@
...
+    } THEN {
+        EXPECT_EQ(player->item, ITEM_NONE);
+    }
+}
+
+SINGLE_BATTLE_TEST("Fling - Item is lost when target protects itself")
+{
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_PROTECT].effect == EFFECT_PROTECT);
+        PLAYER(SPECIES_WOBBUFFET) {Item(ITEM_RAZOR_CLAW); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:136]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_RAZOR_CLAW); }
```

File: test/move_effect_fling.c [hunk 13]
```diff
@@ -0,0 +1,336 @@
...
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_PROTECT); MOVE(player, MOVE_FLING);}
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:139]:
```suggestion
        TURN { MOVE(opponent, MOVE_PROTECT); MOVE(player, MOVE_FLING); }
```

File: test/move_effect_fling.c [hunk 14]
```diff
@@ -0,0 +1,336 @@
...
+{
+    u32 status;
+    u16 item;
+
+    PARAMETRIZE {status = STATUS1_SLEEP_TURN(2); item = ITEM_RAZOR_CLAW; }
+    PARAMETRIZE {status = STATUS1_PARALYSIS; item = ITEM_RAZOR_CLAW; }
+    PARAMETRIZE {status = STATUS1_FREEZE; item = ITEM_RAZOR_CLAW; }
+    PARAMETRIZE {status = STATUS1_SLEEP_TURN(2); item = ITEM_NONE; }
+    PARAMETRIZE {status = STATUS1_PARALYSIS; item = ITEM_NONE; }
+    PARAMETRIZE {status = STATUS1_FREEZE; item = ITEM_NONE; }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:164]: I think the `item` field here is unneeded, since you already made a test for failing when the item is `ITEM_NONE`
```suggestion
    PARAMETRIZE { status = STATUS1_SLEEP_TURN(2); item = ITEM_RAZOR_CLAW; }
    PARAMETRIZE { status = STATUS1_PARALYSIS; item = ITEM_RAZOR_CLAW; }
    PARAMETRIZE { status = STATUS1_FREEZE; item = ITEM_RAZOR_CLAW; }
    PARAMETRIZE { status = STATUS1_SLEEP_TURN(2); item = ITEM_NONE; }
    PARAMETRIZE { status = STATUS1_PARALYSIS; item = ITEM_NONE; }
    PARAMETRIZE { status = STATUS1_FREEZE; item = ITEM_NONE; }
```

File: test/move_effect_fling.c [hunk 15]
```diff
@@ -0,0 +1,336 @@
...
+SINGLE_BATTLE_TEST("Fling applies special effects when throwing specific Items")
+{
+    u16 item, effect;
+
+    PARAMETRIZE {item = ITEM_FLAME_ORB; effect = EFFECT_WILL_O_WISP; }
+    PARAMETRIZE {item = ITEM_TOXIC_ORB; effect = EFFECT_TOXIC; }
+    PARAMETRIZE {item = ITEM_POISON_BARB; effect = EFFECT_POISON; }
+    PARAMETRIZE {item = ITEM_LIGHT_BALL; effect = EFFECT_PARALYZE; }
+    PARAMETRIZE {item = ITEM_RAZOR_FANG; effect = EFFECT_FLINCH_HIT; }
+    PARAMETRIZE {item = ITEM_KINGS_ROCK; effect = EFFECT_FLINCH_HIT; }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:214]: Doesn't matter much, but using the `MOVE_EFFECT_x` might make more sense here
```suggestion
    PARAMETRIZE { item = ITEM_FLAME_ORB; effect = EFFECT_WILL_O_WISP; }
    PARAMETRIZE { item = ITEM_TOXIC_ORB; effect = EFFECT_TOXIC; }
    PARAMETRIZE { item = ITEM_POISON_BARB; effect = EFFECT_POISON; }
    PARAMETRIZE { item = ITEM_LIGHT_BALL; effect = EFFECT_PARALYZE; }
    PARAMETRIZE { item = ITEM_RAZOR_FANG; effect = EFFECT_FLINCH_HIT; }
    PARAMETRIZE { item = ITEM_KINGS_ROCK; effect = EFFECT_FLINCH_HIT; }
```

File: test/move_effect_fling.c [hunk 16]
```diff
@@ -0,0 +1,336 @@
...
+
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) {Item(item); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:217]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(item); }
```

File: test/move_effect_fling.c [hunk 17]
```diff
@@ -0,0 +1,336 @@
...
+    PARAMETRIZE {item = ITEM_PECHA_BERRY; effect = HOLD_EFFECT_CURE_PSN; status1 = STATUS1_TOXIC_POISON; }
+    PARAMETRIZE {item = ITEM_RAWST_BERRY; effect = HOLD_EFFECT_CURE_BRN; status1 = STATUS1_BURN; }
+    PARAMETRIZE {item = ITEM_ASPEAR_BERRY; effect = HOLD_EFFECT_CURE_FRZ; status1 = STATUS1_FREEZE; }
+    PARAMETRIZE {item = ITEM_APICOT_BERRY; effect = HOLD_EFFECT_SP_DEFENSE_UP; statId = STAT_SPDEF; }
+    PARAMETRIZE {item = ITEM_MARANGA_BERRY; effect = HOLD_EFFECT_MARANGA_BERRY; statId = STAT_SPDEF; }
+    PARAMETRIZE {item = ITEM_GANLON_BERRY; effect = HOLD_EFFECT_DEFENSE_UP; statId = STAT_DEF; }
+    PARAMETRIZE {item = ITEM_KEE_BERRY; effect = HOLD_EFFECT_KEE_BERRY; statId = STAT_DEF; }
+    PARAMETRIZE {item = ITEM_LIECHI_BERRY; effect = HOLD_EFFECT_ATTACK_UP; statId = STAT_ATK; }
+    PARAMETRIZE {item = ITEM_PETAYA_BERRY; effect = HOLD_EFFECT_SP_ATTACK_UP; statId = STAT_SPATK; }
+    PARAMETRIZE {item = ITEM_SALAC_BERRY; effect = HOLD_EFFECT_SPEED_UP; statId = STAT_SPEED; }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:270]:
```suggestion
    PARAMETRIZE { item = ITEM_ORAN_BERRY; effect = HOLD_EFFECT_RESTORE_HP; }
    PARAMETRIZE { item = ITEM_SITRUS_BERRY; effect = HOLD_EFFECT_RESTORE_HP; }
    PARAMETRIZE { item = ITEM_CHESTO_BERRY; effect = HOLD_EFFECT_CURE_SLP; status1 = STATUS1_SLEEP; }
    PARAMETRIZE { item = ITEM_CHERI_BERRY; effect = HOLD_EFFECT_CURE_PAR; status1 = STATUS1_PARALYSIS; }
    PARAMETRIZE { item = ITEM_PECHA_BERRY; effect = HOLD_EFFECT_CURE_PSN; status1 = STATUS1_POISON; }
    PARAMETRIZE { item = ITEM_PECHA_BERRY; effect = HOLD_EFFECT_CURE_PSN; status1 = STATUS1_TOXIC_POISON; }
    PARAMETRIZE { item = ITEM_RAWST_BERRY; effect = HOLD_EFFECT_CURE_BRN; status1 = STATUS1_BURN; }
    PARAMETRIZE { item = ITEM_ASPEAR_BERRY; effect = HOLD_EFFECT_CURE_FRZ; status1 = STATUS1_FREEZE; }
    PARAMETRIZE { item = ITEM_APICOT_BERRY; effect = HOLD_EFFECT_SP_DEFENSE_UP; statId = STAT_SPDEF; }
    PARAMETRIZE { item = ITEM_MARANGA_BERRY; effect = HOLD_EFFECT_MARANGA_BERRY; statId = STAT_SPDEF; }
    PARAMETRIZE { item = ITEM_GANLON_BERRY; effect = HOLD_EFFECT_DEFENSE_UP; statId = STAT_DEF; }
    PARAMETRIZE { item = ITEM_KEE_BERRY; effect = HOLD_EFFECT_KEE_BERRY; statId = STAT_DEF; }
    PARAMETRIZE { item = ITEM_LIECHI_BERRY; effect = HOLD_EFFECT_ATTACK_UP; statId = STAT_ATK; }
    PARAMETRIZE { item = ITEM_PETAYA_BERRY; effect = HOLD_EFFECT_SP_ATTACK_UP; statId = STAT_SPATK; }
    PARAMETRIZE { item = ITEM_SALAC_BERRY; effect = HOLD_EFFECT_SPEED_UP; statId = STAT_SPEED; }
```

File: test/move_effect_fling.c [hunk 18]
```diff
@@ -0,0 +1,336 @@
...
+
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) {Item(item); }
+        OPPONENT(SPECIES_WOBBUFFET) {Status1(status1); HP(399); MaxHP(400); }
```
Comment (AsparagusEduardo) [inline test/move_effect_fling.c:274]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Item(item); }
        OPPONENT(SPECIES_WOBBUFFET) { Status1(status1); HP(399); MaxHP(400); }
```

File: include/battle_scripts.h [hunk 19]
```diff
@@ -10,6 +10,7 @@ extern const u8 BattleScript_MakeMoveMissed[];
 extern const u8 BattleScript_PrintMoveMissed[];
 extern const u8 BattleScript_MoveMissedPause[];
 extern const u8 BattleScript_MoveMissed[];
+extern const u8 BattleScript_RemoveItemButItFailedAtkStringPpReduce[];
```
Comment (AsparagusEduardo) [inline include/battle_scripts.h:13]: I want to see if I can rename `BattleScript_ButItFailedAtkStringPpReduce` to `BattleScript_ButItFailedPpReduceAtkString` and if so, then it could be...
```suggestion
extern const u8 BattleScript_ButItFailedPpReduceAtkStringRemoveItem[];
```

File: src/battle_script_commands.c [hunk 20]
```diff
@@ -16150,11 +16147,22 @@ void BS_CalcMetalBurstDmg(void)
...
+{
+    NATIVE_ARGS(u8 battler, const u8 *jumpInstr);
+
+    u32 battler = GetBattlerForBattleScript(cmd->battler);
+    if (!CanFling(battler))
+        gBattlescriptCurrInstr = cmd->jumpInstr;
+    else
+        gBattlescriptCurrInstr = cmd->nextInstr;
+}
+
```
Comment (AsparagusEduardo) [inline src/battle_script_commands.c:16160]: You're already receiving the battler from `NATIVE_ARGS` here, so there shouldn't be a need to call `GetBattlerForBattleScript`, and the data type change for `CanFling`.

I think some natives have that issue, so that's something to clean up. (eg, compare `BS_GetBattlerSide` vs `BS_CanTeleport`)

```suggestion
void BS_JumpIfCantFling(void)
{
    NATIVE_ARGS(u8 battler, const u8 *jumpInstr);

    if (!CanFling(cmd->battler))
        gBattlescriptCurrInstr = cmd->jumpInstr;
    else
        gBattlescriptCurrInstr = cmd->nextInstr;
}
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: src/battle_script_commands.c (hunk 20 above)
Comment (AsparagusEduardo) [reply src/battle_script_commands.c:16160]: Actually, no, I'm wrong! `BS_CanTeleport` is literally the only one that ISN'T using that, so that's a problem there.

Comment (DizzyEggg) [reply src/battle_script_commands.c:16160]: Nope, this is needed. The battler in the args tells which battler to use.

Comment (AsparagusEduardo) [reply src/battle_script_commands.c:16160]: I know, that I said in my second comment ^^
Though `GetBattlerForBattleScript` returns `u8`, so there was still no need to change `CanFling`'s argument data type.

File: data/battle_scripts_1.s [hunk 21]
```diff
@@ -5567,11 +5565,13 @@ BattleScript_AlreadyAtFullHp::
...
-	jumpifnotfirstturn BattleScript_ButItFailedAtkStringPpReduce
+	jumpifnotfirstturn BattleScript_ButItFailedPpReduceAtkString
 	setmoveeffect MOVE_EFFECT_FLINCH
 	goto BattleScript_EffectHit
-
-BattleScript_ButItFailedAtkStringPpReduce::
+	
+BattleScript_ButItFailedPpReduceAtkStringRemoveItem::
+	removeitem BS_ATTACKER
+BattleScript_ButItFailedPpReduceAtkString::
```
Comment (ghoulslash) [inline data/battle_scripts_1.s:5574]: Why the change from ButItFailedAtkStringPpReduce? Seems unrcessary

File: include/constants/battle_script_commands.h [hunk 22]
```diff
@@ -230,7 +230,6 @@
 #define VARIOUS_SET_SKY_DROP                         138
 #define VARIOUS_CLEAR_SKY_DROP                       139
 #define VARIOUS_SKY_DROP_YAWN                        140
-#define VARIOUS_JUMP_IF_CANT_FLING                   141
```
Comment (ghoulslash) [inline include/constants/battle_script_commands.h:233]: Instead of deleting can you relabel to VARIOUS_UNUSED_141 or similar?

**Review by ghoulslash — CHANGES_REQUESTED** [review]

File: data/battle_scripts_1.s (hunk 21 above)
Comment (AsparagusEduardo) [reply data/battle_scripts_1.s:5574]: Because I felt that for the sake of consistency, each additional action would be added as a suffix. Forgot to PR that to pret.

Comment (ghoulslash) [reply data/battle_scripts_1.s:5574]: Then wouldn't it make more sense to change the other labels to read in the order the cmds happen?

Comment (AsparagusEduardo) [reply data/battle_scripts_1.s:5574]: I'm thinking that the primary action should go first (`ButItFailed`)

File: include/constants/battle_script_commands.h (hunk 22 above)
Comment (AsparagusEduardo) [reply include/constants/battle_script_commands.h:233]: I think we wanted to remove them entirely (and we should've stopped people from PRing them once we got the callnative stuff but we didn't xD), so no point on renaming them to a variable that we won't use imo.

Comment (AsparagusEduardo) [reply include/constants/battle_script_commands.h:233]: Since we want to replace them completely for callnatives, I don't see the usefulness of replacing it with an unused value that we're not gonna use ever.

**Comment by DizzyEggg** [comment]
What is blocking this PR from getting merged?

File: include/constants/battle_script_commands.h (hunk 22 above)
Comment (AsparagusEduardo) [reply include/constants/battle_script_commands.h:233]: (why did this get commented twice?) I thought the first time didn't go, so I had to rewrite my comment

**Comment by AsparagusEduardo** [comment]
PR opened over at pret: https://github.com/pret/pokeemerald/pull/1906 👀

**Comment by AsparagusEduardo** [comment]
@ghoulslash how about pret's current labels?

**Comment by ghoulslash** [comment]
> @ghoulslash how about pret's current labels?

Seems fine to me

**Comment by DizzyEggg** [comment]
Anything left to change here? 👀

**Comment by AsparagusEduardo** [comment]
> Anything left to change here? 👀

Applying pret's current labels.
Also, I think that the "removing item and then fail" should have a goto and be next to the other fling scripts

**Comment by DizzyEggg** [comment]
Sorry, I'm kinda lost here. Which labels should be changed to what exactly? 
BattleScript_ButItFailedPpReduceAtkString back to BattleScript_ButItFailedAtkStringPpReduce? BattleScript_ButItFailedPpReduceAtkStringRemoveItem to BattleScript_ButItFailedAtkStringPpReduceRemoveItem?

**Comment by AsparagusEduardo** [comment]
> Sorry, I'm kinda lost here. Which labels should be changed to what exactly? BattleScript_ButItFailedPpReduceAtkString back to BattleScript_ButItFailedAtkStringPpReduce? BattleScript_ButItFailedPpReduceAtkStringRemoveItem to BattleScript_ButItFailedAtkStringPpReduceRemoveItem?

- `BattleScript_ButItFailedPpReduce` -> `BattleScript_FailedFromPpReduce` (current label)
- `BattleScript_ButItFailedPpReduceAtkString` -> `BattleScript_FailedFromAtkString` (current label)
- Move `BattleScript_ButItFailedPpReduceAtkStringRemoveItem` to be below  `BattleScript_FlingEnd`
```diff
BattleScript_FlingEnd:
	tryfaintmon BS_TARGET
	trysymbiosis
	goto BattleScript_MoveEnd

+BattleScript_FlingFailConsumeItem
+	removeitem BS_ATTACKER
+	goto BattleScript_FailedFromAtkString

BattleScript_FlingFlameOrb:
```

**Review by AsparagusEduardo — APPROVED** [review]
