### PR TITLE
Avoid doubling up on status moves in double battles.

### LINKED ISSUE #7451: Double Battle Check Bad Move AI Not Functioning Properly
### Description

Both foes in a double battle will use moves such as stealth rock, sticky web, etc despite the second foe's attack doing nothing. 

### Reproduction Steps

Create a double battle with the check bad move AI flag and two mons that know stealth rock and an attacking move. Both foes will use stealth rock.

### Images / Video

https://github.com/user-attachments/assets/b6ce8902-8db4-474e-a118-eb34c9f338a1

### Version

1.12.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

ChrispyChris27

### PR DESCRIPTION
**Pull request by surskitty**
Tests for CheckBadMove and improved logic to avoid both pokemon redundantly doing the same thing.

Teatime and Court Change still need a lot more CheckBadMove handling.  And CheckViability.

## Issue(s) that this PR fixes
Fixes #7451

## Feature(s) this PR does NOT handle:
Teatime and Court Change still lack any other logic beyond "don't have both pokemon use them on the same turn."

## Discord contact info
wildvenonat

### CODE REVIEW

File: src/battle_ai_main.c [hunk 1]
```diff
@@ -2547,7 +2557,7 @@ static s32 AI_CheckBadMove(u32 battlerAtk, u32 battlerDef, u32 move, s32 score)
             {
                 // This only happens if the ally already rolled on double trick room on final turn.
                 // Both Pokemon use Trick Room on the final turn of Trick Room to anticipate both opponents Protecting to stall out.
-                if (gFieldTimers.trickRoomTimer == gBattleTurnCounter)
+                if (gFieldStatuses & STATUS_FIELD_TRICK_ROOM && gFieldTimers.trickRoomTimer == gBattleTurnCounter)
```
Comment (AlexOn1ine) [inline src/battle_ai_main.c:2560]: what's the status flag check for? Technically the counter should be enough

Comment (surskitty) [reply src/battle_ai_main.c:2560]: Testing says otherwise; it double trick rooms for no reason without the status check.

Comment (surskitty) [reply src/battle_ai_main.c:2560]: Thinking about it, I suspect the reason the status check is required is that the turn at the beginning of the fight is 0, and so the trick room timer is also 0. Which would mean it only happens on the first turn and so is not actively bad behavior on account of Fake Out existing, but it's still a bug. 

Regardless it isn't _intentional_ behavior for it to double trick room on first turn.

Comment (AlexOn1ine) [reply src/battle_ai_main.c:2560]: right, you have a point. let me think about that.
