### PR TITLE
Fixed Hoenn dex off by 1 issues

### LINKED ISSUE #6103: Hoenn Dex's owned number is off by 1
### Description

The "Own" value in the Hoenn Dex is 1 greater than the actual number
Image

This applies to the HGSS Dex as well
Image

### Version

upcoming (Edge)

### Upcoming/master Version

c4b838587bdaf6a44bd47c22bd72bf412190bb48

### Discord contact info

Frankfurter

### PR DESCRIPTION
**Pull request by fdeblasio**
## Description
Changed two for loops to end at `HOENN_DEX_COUNT - 1` instead of `HOENN_DEX_COUNT`

One of these fixes the Hoenn Dex's owned off by 1 error, the other allows HasAllHoennMons to work correctly

## Issue(s) that this PR fixes
Fixes #6103 

## **Discord contact info**
Frankfurter

### CODE REVIEW

File: src/pokedex.c [hunk 1]
```diff
@@ -4539,7 +4539,7 @@ u16 GetHoennPokedexCount(u8 caseID)
     u16 count = 0;
     u16 i;
 
-    for (i = 0; i < HOENN_DEX_COUNT; i++)
+    for (i = 0; i < HOENN_DEX_COUNT -1; i++)
```
Comment (Bassoonian) [inline src/pokedex.c:4542]:
```suggestion
    for (i = 0; i < HOENN_DEX_COUNT - 1; i++)
```

**Comment by Bassoonian** [comment]
As a bugfix, this should target master

**Comment by fdeblasio** [comment]
> As a bugfix, this should target master

Done!

**Review by Bassoonian — APPROVED** [review]
