### PR TITLE
Fixes Red Card / Eject Pack interaction

### LINKED ISSUE #5716: Red Card + Eject Pack interaction
### Description

If an Eject Pack Pokemon uses a move like Superpower, Overheat etc against a Pokemon holding Red Card (and not fainting it), the Eject Pack activates first, then the Red Card activates later:

Visualization: https://www.twitch.tv/moxi/clip/ResoluteGentleDinosaurNerfBlueBlaster-Wi00HWD9sO2Ae3pF (Based on Pokemon Lucid, but I checked it in the current Expansion version and it's still present)
Intended interaction: Red Card cancells Eject Pack,  ~~the latter still gets consumed~~ apparently Showdown got this part wrong, tested it on Cardridge and the Pokemon should keep its Eject Pack. https://replay.pokemonshowdown.com/gen9customgame-2245743669

https://github.com/user-attachments/assets/051a45a5-6847-4486-9bfb-1754b6f446bd

Furthermore, I want to bring attention to this smogon thread: https://www.smogon.com/forums/threads/various-eject-pack-bugs.3733517/
While I haven't tested any of the interactions described in there (yet), I think this could be a good baseline for writing Tests.

### Version

1.9.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes  #5716

### CODE REVIEW

**Comment by Pawkkie** [comment]
Thoughts on this comment https://github.com/rh-hideout/pokeemerald-expansion/issues/5716#issuecomment-2501723238 pertaining to #5657? Not saying it needs to be checked / addressed in this PR but if it's something we *should* check we should make a new issue for it so don't lose it by closing the issue.

File: test/battle/hold_effect/red_card.c [hunk 1]
```diff
@@ -467,4 +467,25 @@ SINGLE_BATTLE_TEST("Red Card prevents Emergency Exit activation when triggered")
     }
 }
 
+SINGLE_BATTLE_TEST("Red Card activates before Eject Pack")
+{
+    GIVEN {
```
Comment (Pawkkie) [inline test/battle/hold_effect/red_card.c:472]: Need an `ASSUME` for Overheat's self stat lowering

**Review by Pawkkie — CHANGES_REQUESTED** [review]
Bonus points for how fast you fixed this!

**Review by Pawkkie — APPROVED** [review]
