### PR TITLE
Fix protect recoil issue and add tests for protect

### LINKED ISSUE #3304: Recoil moves cause recoil damage against Protect like moves
### Description

Recoil moves and moves with `EFFECT_PROTECT` not named Protect cause the user to still take recoil damage (and any additional effects). For a weird reason it only applies after a different move was previously used. For doubles it can happen the same turn the partner moves first, in singles it's on the second turn.

Simple test:
```
SINGLE_BATTLE_TEST("Protect like moves cause recoil effect")
{
    GIVEN {
        PLAYER(SPECIES_RAPIDASH);
        OPPONENT(SPECIES_BEAUTIFLY);
    } WHEN {
        TURN { MOVE(opponent, MOVE_TACKLE);
               MOVE(player, MOVE_TACKLE);
        }
        TURN { MOVE(opponent, MOVE_SILK_TRAP);
               MOVE(player, MOVE_DOUBLE_EDGE);
        }
        TURN {}
    } SCENE {
        NOT MESSAGE("Rapidash is hit with recoil!");
    }
}
```
Recording:

https://github.com/rh-hideout/pokeemerald-expansion/assets/93446519/291d86d6-afb5-4236-b037-41c2b31482d4

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #3312: Multi-hit moves damage pokemon using silk-trap
### Description

When using a multi-hit move against a pokemon using silk-trap, the first attack is protected, but subsequent attacks deal damage. The speed-lowering effect happens for every hit.

### Version

1.5.3 (Default)

### Upcoming Version

_No response_

### Discord contact info

MarinePez

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3304 
Fixes #3312

Adds tests for all protect moves.

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Note for the reviewer: also check #3312

**Comment by DizzyEggg** [comment]
@AsparagusEduardo 

The answer was: yes, it also fixed #3312. BUT good thing I wrote a test for all protect moves, because baneful bunker needed the same fix as the other two. Which is now fixed too

File: test/battle/move_effect/protect.c [hunk 1]
```diff
@@ -0,0 +1,369 @@
...
+    static const u16 protectMoves[][3] = {{MOVE_KINGS_SHIELD, STAT_ATK, 1}, {MOVE_SILK_TRAP, STAT_SPEED, 1}, {MOVE_OBSTRUCT, STAT_DEF, 2}};
+    u16 protectMove = MOVE_NONE;
+    u16 usedMove = MOVE_NONE;
+    u16 statId = 0, lowersBy = 0;
+
+    for (j = 0; j < ARRAY_COUNT(protectMoves); j++)
+    {
+        PARAMETRIZE {protectMove = protectMoves[j][0]; statId = protectMoves[j][1]; lowersBy = protectMoves[j][2]; usedMove = MOVE_TACKLE; }
+        PARAMETRIZE {protectMove = protectMoves[j][0]; usedMove = MOVE_LEER; }
+        PARAMETRIZE {protectMove = protectMoves[j][0]; usedMove = MOVE_WATER_GUN; }
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:67]:
```suggestion
        PARAMETRIZE { usedMove = MOVE_TACKLE; protectMove = protectMoves[j][0]; statId = protectMoves[j][1]; lowersBy = protectMoves[j][2]; }
        PARAMETRIZE { usedMove = MOVE_LEER; protectMove = protectMoves[j][0]; statId = 0; lowersBy = 0; }
        PARAMETRIZE { usedMove = MOVE_WATER_GUN; protectMove = protectMoves[j][0]; statId = 0; lowersBy = 0; }
```

File: test/battle/move_effect/protect.c [hunk 2]
```diff
@@ -0,0 +1,369 @@
...
+            }
+        }
+    } THEN {
+        if (usedMove == MOVE_TACKLE) {
+            EXPECT_EQ(player->statStages[statId], DEFAULT_STAT_STAGE - lowersBy);
+        }
+    }
+}
+
+// Also checks if it can faint the mon.
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:107]: I would make a separate test for it.

File: test/battle/move_effect/protect.c [hunk 3]
```diff
@@ -0,0 +1,369 @@
...
+        NOT HP_BAR(opponent);
+        if (usedMove == MOVE_TACKLE) {
+            STATUS_ICON(player, STATUS1_POISON);
+        } else {
+            NOT STATUS_ICON(player, STATUS1_POISON);
+        }
+    }
+}
+
+SINGLE_BATTLE_TEST("Recoil is not applied if battler was protected") // #3319
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:174]:
```suggestion
SINGLE_BATTLE_TEST("Recoil damage is not applied if target was protected")
```

File: test/battle/move_effect/protect.c [hunk 4]
```diff
@@ -0,0 +1,369 @@
...
+    PARAMETRIZE {move = MOVE_PROTECT; }
+    PARAMETRIZE {move = MOVE_DETECT; }
+    PARAMETRIZE {move = MOVE_KINGS_SHIELD; }
+    PARAMETRIZE {move = MOVE_BANEFUL_BUNKER; }
+    PARAMETRIZE {move = MOVE_SILK_TRAP; }
+    PARAMETRIZE {move = MOVE_OBSTRUCT; }
+    PARAMETRIZE {move = MOVE_SPIKY_SHIELD; }
+
+    GIVEN {
+        ASSUME(gBattleMoves[MOVE_DOUBLE_EDGE].effect == EFFECT_RECOIL_33);
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:187]: Let's add the other `EFFECT_RECOIL_x`s here

File: test/battle/move_effect/protect.c [hunk 5]
```diff
@@ -0,0 +1,369 @@
...
+        // 2nd turn
+        ANIMATION(ANIM_TYPE_MOVE, move, opponent);
+        MESSAGE("Foe Beautifly protected itself!");
+        MESSAGE("Rapidash used Double-Edge!");
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_DOUBLE_EDGE, player);
+        NOT MESSAGE("Rapidash is hit with recoil!");
+    }
+}
+
+SINGLE_BATTLE_TEST("Multi-hit moves don't hit a protected target and fail only once") // #3312
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:207]:
```suggestion
SINGLE_BATTLE_TEST("Multi-hit moves don't hit a protected target and fail only once")
```

File: test/battle/move_effect/protect.c [hunk 6]
```diff
@@ -0,0 +1,369 @@
...
+
+DOUBLE_BATTLE_TEST("Crafty Shield protects self and ally from status moves")
+{
+    u16 move = MOVE_NONE;
+    struct BattlePokemon *targetOpponent = NULL;
+
+    PARAMETRIZE {move = MOVE_HYPER_VOICE; }
+    PARAMETRIZE {move = MOVE_LEER; }
+    PARAMETRIZE {move = MOVE_TACKLE; targetOpponent = opponentLeft; }
+    PARAMETRIZE {move = MOVE_TACKLE; targetOpponent = opponentRight; }
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:338]:
```suggestion
    PARAMETRIZE { move = MOVE_HYPER_VOICE; }
    PARAMETRIZE { move = MOVE_LEER; }
    PARAMETRIZE { move = MOVE_TACKLE; targetOpponent = opponentLeft; }
    PARAMETRIZE { move = MOVE_TACKLE; targetOpponent = opponentRight; }
```

File: test/battle/move_effect/protect.c [hunk 7]
```diff
@@ -0,0 +1,369 @@
...
+
+DOUBLE_BATTLE_TEST("Quick Guard protects self and ally from priority moves")
+{
+    u16 move = MOVE_NONE;
+    struct BattlePokemon *targetOpponent = NULL;
+
+    PARAMETRIZE {move = MOVE_TACKLE; targetOpponent = opponentLeft; }
+    PARAMETRIZE {move = MOVE_TACKLE; targetOpponent = opponentRight; }
+    PARAMETRIZE {move = MOVE_QUICK_ATTACK; targetOpponent = opponentLeft; }
+    PARAMETRIZE {move = MOVE_QUICK_ATTACK; targetOpponent = opponentRight; }
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:303]:
```suggestion
    PARAMETRIZE { move = MOVE_TACKLE; targetOpponent = opponentLeft; }
    PARAMETRIZE { move = MOVE_TACKLE; targetOpponent = opponentRight; }
    PARAMETRIZE { move = MOVE_QUICK_ATTACK; targetOpponent = opponentLeft; }
    PARAMETRIZE { move = MOVE_QUICK_ATTACK; targetOpponent = opponentRight; }
```

File: test/battle/move_effect/protect.c [hunk 8]
```diff
@@ -0,0 +1,369 @@
...
+    }
+}
+
+DOUBLE_BATTLE_TEST("Wide Guard protects self and ally from multi-target moves")
+{
+    u16 move = MOVE_NONE;
+
+    PARAMETRIZE {move = MOVE_TACKLE; }
+    PARAMETRIZE {move = MOVE_SURF; } // All targets
+    PARAMETRIZE {move = MOVE_HYPER_VOICE; } // 2 foes
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:259]:
```suggestion
    PARAMETRIZE { move = MOVE_TACKLE; }      // Single target
    PARAMETRIZE { move = MOVE_SURF; }        // All targets
    PARAMETRIZE { move = MOVE_HYPER_VOICE; } // 2 foes
```

File: test/battle/move_effect/protect.c [hunk 9]
```diff
@@ -0,0 +1,369 @@
...
+{
+    u16 move = MOVE_NONE;
+
+    PARAMETRIZE {move = MOVE_PROTECT; }
+    PARAMETRIZE {move = MOVE_DETECT; }
+    PARAMETRIZE {move = MOVE_KINGS_SHIELD; }
+    PARAMETRIZE {move = MOVE_BANEFUL_BUNKER; }
+    PARAMETRIZE {move = MOVE_SILK_TRAP; }
+    PARAMETRIZE {move = MOVE_OBSTRUCT; }
+    PARAMETRIZE {move = MOVE_SPIKY_SHIELD; }
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:217]:
```suggestion
    PARAMETRIZE { move = MOVE_PROTECT; }
    PARAMETRIZE { move = MOVE_DETECT; }
    PARAMETRIZE { move = MOVE_KINGS_SHIELD; }
    PARAMETRIZE { move = MOVE_BANEFUL_BUNKER; }
    PARAMETRIZE { move = MOVE_SILK_TRAP; }
    PARAMETRIZE { move = MOVE_OBSTRUCT; }
    PARAMETRIZE { move = MOVE_SPIKY_SHIELD; }
```

File: test/battle/move_effect/protect.c [hunk 10]
```diff
@@ -0,0 +1,369 @@
...
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:184]:
```suggestion
    PARAMETRIZE { move = MOVE_PROTECT; }
    PARAMETRIZE { move = MOVE_DETECT; }
    PARAMETRIZE { move = MOVE_KINGS_SHIELD; }
    PARAMETRIZE { move = MOVE_BANEFUL_BUNKER; }
    PARAMETRIZE { move = MOVE_SILK_TRAP; }
    PARAMETRIZE { move = MOVE_OBSTRUCT; }
    PARAMETRIZE { move = MOVE_SPIKY_SHIELD; }
```

File: test/battle/move_effect/protect.c [hunk 11]
```diff
@@ -0,0 +1,369 @@
...
+// Also checks if it can faint the mon.
+SINGLE_BATTLE_TEST("Spiky Shield does 1/8 dmg of max hp for moves making contact")
+{
+    u16 usedMove = MOVE_NONE;
+    u16 hp = 400, maxHp = 400;
+
+    PARAMETRIZE {usedMove = MOVE_TACKLE; hp = 1;}
+    PARAMETRIZE {usedMove = MOVE_TACKLE;}
+    PARAMETRIZE {usedMove = MOVE_LEER;}
+    PARAMETRIZE {usedMove = MOVE_WATER_GUN;}
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:116]:
```suggestion
    PARAMETRIZE { usedMove = MOVE_TACKLE; hp = 1;}
    PARAMETRIZE { usedMove = MOVE_TACKLE;}
    PARAMETRIZE { usedMove = MOVE_LEER;}
    PARAMETRIZE { usedMove = MOVE_WATER_GUN;}
```

File: test/battle/move_effect/protect.c [hunk 12]
```diff
@@ -0,0 +1,369 @@
...
+    u32 j;
+    static const u16 protectMoves[] = {MOVE_PROTECT, MOVE_DETECT, MOVE_SPIKY_SHIELD, MOVE_BANEFUL_BUNKER};
+    u16 protectMove = MOVE_NONE;
+    u16 usedMove = MOVE_NONE;
+
+    for (j = 0; j < ARRAY_COUNT(protectMoves); j++)
+    {
+        PARAMETRIZE {protectMove = protectMoves[j]; usedMove = MOVE_TACKLE; }
+        PARAMETRIZE {protectMove = protectMoves[j]; usedMove = MOVE_LEER; }
+        PARAMETRIZE {protectMove = protectMoves[j]; usedMove = MOVE_WATER_GUN; }
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/protect.c:33]:
```suggestion
        PARAMETRIZE { protectMove = protectMoves[j]; usedMove = MOVE_TACKLE; }
        PARAMETRIZE { protectMove = protectMoves[j]; usedMove = MOVE_LEER; }
        PARAMETRIZE { protectMove = protectMoves[j]; usedMove = MOVE_WATER_GUN; }
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: test/battle/move_effect/protect.c (hunk 5 above)
Comment (DizzyEggg) [reply test/battle/move_effect/protect.c:221]: Why removing the comment? I added it intentionally that this test is written because of a submitted issue

File: test/battle/move_effect/protect.c (hunk 2 above)
Comment (DizzyEggg) [reply test/battle/move_effect/protect.c:121]: Personally not a fan of this since the test would be pretty much the same and I'd rather not duplicate code, especially if tests allow us to parametrize.

File: test/battle/move_effect/protect.c (hunk 4 above)
Comment (DizzyEggg) [reply test/battle/move_effect/protect.c:207]: Done

**Comment by DizzyEggg** [comment]
I removed the comment to the issue's github number, this should be ready to merge now.

**Comment by DizzyEggg** [comment]
@AsparagusEduardo Should be ready to merge 👀

**Review by AsparagusEduardo — APPROVED** [review]
