### PR TITLE
Fix Forecast and Flower Gift corruption

### LINKED ISSUE #7795: Weather-Transforming Pokemon Corpses Remain After Death And Transform Again In Doubles
### Description

Castform and Cherrim specifically, on death, have their corpses remain on screen, followed by an additional transformation message, and don't disappear until the screen is somehow reloaded. Tested on latest master branch.

### Reproduction Steps

To reproduce:

1.) Create a double battle with a non-sand weather setter/drought user and castform/cherrim. 
2.) Kill the transformed mon
3.) Observe the issue

### Images / Video

_No response_

### Version

1.13.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

Jordan

### PR DESCRIPTION
**Pull request by Bassoonian**
Also corrects an existing test that was faulty and marks it as known failing

## Issue(s) that this PR fixes
Fixes #7795

## Discord contact info
bassoonian

### CODE REVIEW

File: test/battle/form_change/faint.c [hunk 1]
```diff
@@ -16,3 +17,26 @@ SINGLE_BATTLE_TEST("Aegislash reverts to Shield Form upon fainting")
...
 }
+
+DOUBLE_BATTLE_TEST("Causing a Forecast or Flower Gift Pokémon to faint should not cause a message") // issue 7795
+{
+    u32 species;
+    PARAMETRIZE { species = SPECIES_CASTFORM; }
+    PARAMETRIZE { species = SPECIES_CHERRIM; }
+    GIVEN {
+        PLAYER(SPECIES_TORCHIC);
+        PLAYER(SPECIES_MAGEARNA);
```
Comment (hedara90) [inline test/battle/form_change/faint.c]: I think we should use a different mon here.
Magearna has an ability that triggers when any battlers faints, which causes unnecessary noise in the test.
The standard Wobbuffet + Scratch should suffice.

**Comment by Bassoonian** [comment]
Changes applied

**Review by hedara90 — APPROVED** [review]
