### PR TITLE
Fix order of messages in gen6 exp share

### LINKED ISSUE #3318: The order of key items Exp. Share messages is wrong
### Description

Pokémon level up before the "The rest of your team gained Exp. Points" message appears. Context in Discord: https://discord.com/channels/419213663107416084/1148047834583679056/1152881573289533512

### Version

1.5.3 (Default)

### Upcoming Version

_No response_

### Discord contact info

bassoonian

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3318 

Changes the order of messages when mons obtain exp, so that it's first the mons via sent-out, and then via exp-share(with the 'The rest of your team got Exp Points' msg).

Also does some clean-up.

### CODE REVIEW

File: include/config/item.h [hunk 1]
```diff
@@ -18,7 +18,7 @@
 #define I_REUSABLE_TMS          FALSE       // In Gen5-8, TMs are reusable. Setting this to TRUE will make all vanilla TMs reusable, though they can also be cherry-picked by setting their importance to 1.
 
 // Exp. Share config
-#define I_EXP_SHARE_FLAG        0           // If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
+#define I_EXP_SHARE_FLAG        0 // If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
```
Comment (LOuroboros) [inline include/config/item.h:21]: Was there a reason to misalign the comment like this? :eyes:

Comment (DizzyEggg) [reply include/config/item.h:21]: Nope, it's from me testing it. I can change it back

Comment (AsparagusEduardo) [inline include/config/item.h:21]:
```suggestion
#define I_EXP_SHARE_FLAG                  0 // If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
```

File: include/config/item.h [hunk 2]
```diff
@@ -18,7 +18,7 @@
 #define I_REUSABLE_TMS          FALSE       // In Gen5-8, TMs are reusable. Setting this to TRUE will make all vanilla TMs reusable, though they can also be cherry-picked by setting their importance to 1.
 
 // Exp. Share config
-#define I_EXP_SHARE_FLAG        0           // If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
+#define I_EXP_SHARE_FLAG                  0 // If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
```
Comment (AsparagusEduardo) [inline include/config/item.h:21]:
```suggestion
#define I_EXP_SHARE_FLAG        0           // If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
```

**Review by AsparagusEduardo — APPROVED** [review]
