### PR TITLE
fixed-damage-move-ai-calc-fix

### LINKED ISSUE #7381: AI considering type chart and damage modifier for fixed-damage moves
### Description

AI appears to be factoring in type chart and the 85-100% damage modifier when considering the damage moves will do to targets, despite the moves still dealing fixed damage in-game

### Reproduction Steps

Put Sonic Boom / Dragon Rage on any enemy mon, send in a mon with a type resistance, then open the battle debug menu and view the AI damage/score page

### Images / Video

https://github.com/user-attachments/assets/ec05bc1e-83c7-4c26-8db0-f9fe3d92d187

### Version

upcoming (Edge)

### Upcoming/master Version

249b4d1574be1cd8a3b5271858bc17470864085b

### Discord contact info

grintoul

### PR DESCRIPTION
**Pull request by grintoul1**
AI for switch in and move decisions is factoring in type effectiveness and damage rolls for fixed-damage moves. This PR fixes. 

## Media
before
https://cdn.discordapp.com/attachments/1077168246555430962/1396601926958714980/image.png?ex=687fffe6&is=687eae66&hm=585890cbcd7c41031de8a197f6d14a049eb925a3d133712d61d0db096c58f847&
after
https://cdn.discordapp.com/attachments/1077168246555430962/1396866813987655751/image.png?ex=687fa518&is=687e5398&hm=ee898cd3f53e2af3589db8f12b8eb21694ab075982e0b161a8fefe0b926f9062&
## Issue(s) that this PR fixes
#7381

## Discord contact info
grintoul

## Credit
@AlexOn1ine for advising a more intelligent solution

### CODE REVIEW

File: src/battle_ai_util.c [hunk 1]
```diff
@@ -903,16 +903,33 @@ struct SimulatedDamage AI_CalcDamage(u32 move, u32 battlerAtk, u32 battlerDef, u
         }
         else
         {
-            u32 damage = CalculateMoveDamageVars(&ctx);
+            u32 damage;
 
-            simDamage.minimum = GetDamageByRollType(damage, DMG_ROLL_LOWEST);
-            simDamage.minimum = ApplyModifiersAfterDmgRoll(&ctx, simDamage.minimum);
+            if (moveEffect == EFFECT_LEVEL_DAMAGE || moveEffect == EFFECT_PSYWAVE || moveEffect == EFFECT_FIXED_HP_DAMAGE 
+                || moveEffect == EFFECT_FIXED_PERCENT_DAMAGE || moveEffect == EFFECT_FINAL_GAMBIT)
```
Comment (AlexOn1ine) [inline src/battle_ai_util.c]:
```suggestion
            if (ctx.fixedBasePower)
```

Comment (AlexOn1ine) [reply src/battle_ai_util.c]: actually `ctx.fixedBasePower != 0` is better in this case

Comment (grintoul1) [reply src/battle_ai_util.c]: fixedBasePower is for Rollout and Fury Cutter? Or does it cover these also?

Comment (AlexOn1ine) [reply src/battle_ai_util.c]: oh wait, no this doesn't work. never mind

Comment (AlexOn1ine) [reply src/battle_ai_util.c]: then I would check for `movePower == 1`. I think this should work

Comment (AlexOn1ine) [reply src/battle_ai_util.c]: For context why I think avoiding a move effect check is better, is because it can easily break when users add a custom move that is a fixed damage move or a new move is released. In cases like those it's usually better to have a more general check that doesn't break in the future.

Comment (grintoul1) [reply src/battle_ai_util.c]: just had a look and this would include moves like Guillotine

Comment (AlexOn1ine) [reply src/battle_ai_util.c]: right...

That's a bit annoying

Comment (grintoul1) [reply src/battle_ai_util.c]: Return/Frustration also. More than happy to make a change, but will need to take another look tomorrow as have to be up early for work - thanks for looking so quickly!

**Comment by grintoul1** [comment]
Sorry if you all just got a bunch of pings; I did something stupid :)

**Comment by grintoul1** [comment]
@AlexOn1ine your idea appears to be working :)

image

**Review by AlexOn1ine — APPROVED** [review]
