### PR TITLE
Fixes ability Embody Aspect triggering multiple times

### LINKED ISSUE #6248: Embody Aspect lack a intrepid sword-like field to not activate multiple times per battle
### Description

I think the title explains it all, there need to be an additionnal check for Embody aspect, and a field created as it was done for intrepid sword. In its current state it will activate multiple times per battle (every time it switches in) instead of just the first time it terastalizes.

### Version

1.10.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6248

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -5107,7 +5107,8 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
         case ABILITY_EMBODY_ASPECT_HEARTHFLAME_MASK:
         case ABILITY_EMBODY_ASPECT_WELLSPRING_MASK:
         case ABILITY_EMBODY_ASPECT_CORNERSTONE_MASK:
-            if (!gSpecialStatuses[battler].switchInAbilityDone)
+            if (!gSpecialStatuses[battler].switchInAbilityDone
+                 && !(gBattleStruct->embodyAspectBoost[GetBattlerSide(battler)] & (1u << gBattlerPartyIndexes[battler])))
```
Comment (Bassoonian) [inline src/battle_util.c:5111]:
```suggestion
            if (!gSpecialStatuses[battler].switchInAbilityDone
             && !(gBattleStruct->embodyAspectBoost[GetBattlerSide(battler)] & (1u << gBattlerPartyIndexes[battler])))
```

**Review by Bassoonian — APPROVED** [review]
