### PR TITLE
Fixed ace switching bugs

### LINKED ISSUE #5697: Forcing a mon to switch to their ace mon early with the ACE flag set causes weird behavior
### Description

So i discovered this in my own project with the following scenario:
Opponent with ACE flage set has Garganacl alive (not ace mon) and Kingambit alive (is ace mon). I trapped the Garganacl into using the move Recover by using Encore on it. Rather than remaining in and spamming Recover, the AI switched to Kingambit, but instead it threw out a Bad Egg and my game froze.

I tried to reproduce on upcoming and while i didn't get a bad egg, i did get arguably stranger behavior... the AI threw out a new copy of the Garganacl.

https://github.com/user-attachments/assets/c6c07190-125b-416d-bfe7-efb51e78aa93

AI's Party:
image

And i know the Kingambit is there because after the events of this video, I KOed the Garganacl and the AI threw out Kingambit.
I also quadruple checked and the AI only has 2 Pokemon in their party.

Also I am not even sure where this one is coming from, I tried debugging in `OpponentHandleChoosePokemon` again but i wasnt even seeing a `chosenMonId` get printed where we were checking before.

### Version

master
upcoming (Edge)

current for both

### Discord contact info

iriv24

### LINKED ISSUE #5919: AI switch into switched out Mon
### Description

Seems like an interaction between Ace flag and smart switching behavior.

Situation: Trainer has three mons:
- first is defeated
- second got yawned
- third is the Ace and should come out last

https://github.com/user-attachments/assets/13525fb8-6b56-48fd-b913-f9612060e3c4

Due to yawning it seems that a switch was triggered, but the Ace couldn't be chosen so it switched in the same Pokémon again.

### Version

1.9.4

### Upcoming/master Version

_No response_

### Discord contact info

wiz1989

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
There's a section of code in `ShoudSwitch` that's decently old and has been refactored out of relevance that was allowing correct switching behaviour with hit escape moves (ie. U-Turn) and is no longer necessary, and in the current setup is actively allowing switching into illegal mons. This was removed, which fixed #5919. Turns out that *is* a duplicate of #5697, which fixes that also.

I noticed we didn't have a switching test for the #2591, which the code I was removing was initially intended to fix, and discovered that it wasn't working correctly anymore anyways, even with the code lol. For both smart switching and regular switching. I fixed this also and added a generic case for both switching behaviours to make sure we don't regress this again.

## Issue(s) that this PR fixes
Fixes #5919 
Fixes #5697 

## **People who collaborated with me in this PR**
@iriv24 for their diligent testing and debugging support

## Feature(s) this PR does NOT handle:
Full hedara-approved sleep-clause-thoroughness testing suite for ace mon behaviour in general

## **Discord contact info**
@Pawkkie

### CODE REVIEW

File: src/battle_ai_switch_items.c [hunk 1]
```diff
@@ -966,20 +965,14 @@ bool32 ShouldSwitch(u32 battler)
             continue;
         if (IsAceMon(battler, i))
         {
-            hasAceMon = TRUE;
             continue;
         }
```
Comment (Bassoonian) [inline src/battle_ai_switch_items.c:969]: Braces no longer needed

**Review by AlexOn1ine — APPROVED** [review]

File: src/battle_ai_switch_items.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_ai_switch_items.c:969]: I didn't see this comment, sorry
