### PR TITLE
Follower female fix

### LINKED ISSUE #5470: Some followerd change sprites when reloading the game or changing a move in their learnset.
### Description

When reloading the game or changing the move using a tm/hm or move relerner some pokemon's OW sprites change to a  different one, as seen in the videos below. currently i have tested terapagos and ogerpon. terapagos changes to woobat and ogerpon to simisage. Footage is from a fresh clone on the repo

[terapagos reload save.webm](https://github.com/user-attachments/assets/9ed976ae-0ed0-4c05-99c2-38a511049279)

[terapagos teach hm surf.webm](https://github.com/user-attachments/assets/7cd70ab1-9452-448d-bbdc-cf986369c896)

### Version

upcoming (Edge)

### Upcoming/master Version

Latest Commit (4th october)

### Discord contact info

Liamjd14

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Fixes followers breaking for females with high species numbers.
Removed vestigial shiny handler not present in the expansion version of the followers branch since it's handled with a bitfield instead.
Updated a `graphicsId` comment to represent current expansion status.
Fixed this fix breaking followers in the sprite visualizer.

Changed a follower form extraction to use updated expansion values (maybe, I don't know if that function actually does that, hopefully someone who knows more can verify)

## Images

https://github.com/user-attachments/assets/04f66642-2eae-479a-85e2-37c667b99b96

## Issue(s) that this PR fixes

Fixes #5470 

## Feature(s) this PR does NOT handle:

Hisuan Sneasel brokeness in sprite visualizer

## **Discord contact info**

hedara

### CODE REVIEW

File: src/event_object_movement.c [hunk 1]
```diff
@@ -1734,7 +1734,8 @@ static u16 PackGraphicsId(const struct ObjectEventTemplate *template)
         if (template->script && template->script[0] == 0x7d)
         {
             form = T1_READ_16(&template->script[2]);
-            form = (form >> 10) & 0x1F;
+            //form = (form >> 10) & 0x1F;
```
Comment (AlexOn1ine) [inline src/event_object_movement.c:1737]: any reason this isn't just removed?

Comment (hedara90) [reply src/event_object_movement.c:1737]: Showing the previous state of the code.
I'm not sure if this part of the code does what I think it does.

Comment (AlexOn1ine) [reply src/event_object_movement.c:1737]: Can we not check the previous state through git or this pull request?

Comment (hedara90) [reply src/event_object_movement.c:1737]: Yes, but it's also the code that's meant to stick out because I'm not sure about it.
It can be removed on Github when someone who knows more agrees that the new line is correct.

Comment (mrgriffin) [reply src/event_object_movement.c:1737]: Huh. `0x7d` is [`bufferspeciesname`](https://github.com/pret/pokeemerald/blob/master/asm/macros/event.inc#L1042), and `T1_READ_16(&template->script[2])` corresponds to the [`species` argument](https://github.com/pret/pokeemerald/blob/master/asm/macros/event.inc#L1044).

So I suppose what we're saying here is that if the script starts with `bufferspeciesname _, X` then `form` will be stored in the top 5 bits of `X`.

Ah, there's a comment just above which explains what I said, lol!:
```c
    // set form based on template's script,
    // if first command is bufferspeciesname
```
I think this change is needed because our species have 12 bits. I think for sanity's sake `form = template->trainerRange_berryTreeId & 0x1F;` should probably also use a `0x0F` mask because there's only 4 bits available for `form` in the graphics ID. There should probably be a constant for that mask to make it easier to understand what's going on? `OBJ_EVENT_GFX_FORM_MASK` or something.

I have to say I'm quite confused about the purpose of this code. Is the idea that maybe you'd have an Unown's graphics ID set to the base form, but then in the script you could specify a specific Unown form for it to be displayed as (I guess there's a macro somewhere that does `(species) | ((form) << 10)`?)

Comment (mrgriffin) [reply src/event_object_movement.c:1737]: Ah, also the shift in this should be by `OBJ_EVENT_GFX_SPECIES_BITS` rather than by `10` (again because of our species having 12 bits).

**Comment by hedara90** [comment]
Apparently followers can't be shiny with the PR as it is now in the Sprite Visualizer.
I'll look more into resolving that. And whatever the final state of the `PackGraphics` part turns out to be. Initial short testing didn't show any change between 12 and 11 bits of shifting.

**Comment by kittenchilly** [comment]
> Apparently followers can't be shiny with the PR as it is now in the Sprite Visualizer. I'll look more into resolving that. And whatever the final state of the `PackGraphics` part turns out to be. Initial short testing didn't show any change between 12 and 11 bits of shifting.

That might have been what the SPECIES_SHINY_TAG was for

**Comment by hedara90** [comment]
Marking as draft, going to give fixing both overworld and sprite visualizer at the same time.

**Comment by hedara90** [comment]
Fixed both the Sprite Visualizer and Followers at the same time, as well as Sneasel-H turning into Onix in Visualizer.
Looks horrible, but it works.
pokeemerald-2
pokeemerald-1
pokeemerald-0

**Comment by kittenchilly** [comment]
If not packing graphics doesn't cause performance or size issues then it should be fine, right?

**Comment by hedara90** [comment]
As far as I can tell, we weren't actually using that function.

**Comment by kittenchilly** [comment]
Then it looks fine to me, really.

**Review by AsparagusEduardo — APPROVED** [review]
