### PR TITLE
Fix some ai action check happening before the logic was computed

### LINKED ISSUE #7118: Roamers don't flee on the first turn
### Description

It looks like the roamer does not flee on the first turn, but they do on the second.

My very quick, totally incomplete digging so far:
- Initially setting roamerCanFlee to TRUE in AI_Roaming does not change anything.

### Reproduction Steps

1- set & do a wild battle in a debug script:
Debug_EventScript_Script_1::
	setwildbattle SPECIES_LATIAS, 50, ITEM_NONE
	dowildbattle
	release
	end

2- Set the Roamer battle type in void BattleSetup_StartScriptedWildBattle(void):
gBattleTypeFlags = BATTLE_TYPE_ROAMER;

3- Witness

### Images / Video

Image
Image
Image

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

Nopinou

### PR DESCRIPTION
**Pull request by FosterProgramming**
To limit AI computation the check for flee and watch actions was put early but compltely bypass computing the logic for fleeing or watching, resulting in those happening a turn later.
I made sure run only the AI computations regarding fleeing and watching before checking thus fixing the issue of roamer not fleeing in the first turn.

## Media

https://github.com/user-attachments/assets/520fc072-b9a6-4d17-9ccc-da20a96a7288

## Issue(s) that this PR fixes
Fixes #7118 

## Things to note in the release changelog:
- Roamers will now flee in the first turn of battle

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_ai_main.c [hunk 1]
```diff
@@ -362,7 +375,7 @@ void ComputeBattlerDecisions(u32 battler)
     if (isAiBattler || CanAiPredictMove())
     {
         // If ai is about to flee or chosen to watch player, no need to calc anything
-        if (isAiBattler && BattlerChoseNonMoveAction())
+        if (isAiBattler && BattlerChooseNonMoveAction(battler))
```
Comment (AlexOn1ine) [inline src/battle_ai_main.c]: Would moving `BattlerChoseNonMoveAction` to the end of the function also solve the issue? Right before the end of `ComputeBattlerDecisions`

Comment (FosterProgramming) [reply src/battle_ai_main.c]: Yes, it works and that was my first naive solution but the comment seem to indicate, we want to avoid compute all AI flag functions if possible so I went for a solution that preserve that idea

Comment (AlexOn1ine) [reply src/battle_ai_main.c]: That was just a logical error on my part because I haven't considered that the fleeing is actually computed later. Meaning the correct fix would be to move this code block to the end of the function.

Comment (AlexOn1ine) [reply src/battle_ai_main.c]: you can also remove the comment.

**Comment by FosterProgramming** [comment]
The PR has been updated

File: src/battle_ai_main.c [hunk 2]
```diff
@@ -319,7 +319,7 @@ void BattleAI_SetupAIData(u8 defaultScoreMoves, u32 battler)
     gAiBattleData->chosenTarget[battler] = gBattlerTarget;
 }
 
-bool32 BattlerChoseNonMoveAction(void)
+bool32 BattlerChooseNonMoveAction()
```
Comment (AlexOn1ine) [inline src/battle_ai_main.c]:
```suggestion
bool32 BattlerChooseNonMoveAction(void)
```
