### PR TITLE
Fix hgss pokedex when catching mon with terrain

### LINKED ISSUE #7874: Catching an uncaught Pokemon with Terrain active still is glitchy for the HGSS Pokedex
### Description

The same issue as #7695 except with the HGSS Pokedex active (it's fixed in the regular Pokedex)

### Reproduction Steps

_No response_

### Images / Video

Image

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

89d045f68e21d7c5bd66fde39a9897c7d697ae0a

### Discord contact info

Frankfurter0

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #7874

### CODE REVIEW

File: include/pokedex.h [hunk 1]
```diff
@@ -8,6 +8,7 @@ void ResetPokedex(void);
 u16 GetNationalPokedexCount(u8 caseID);
 u16 GetHoennPokedexCount(u8 caseID);
 u8 DisplayCaughtMonDexPage(u16 species, bool32 isShiny, u32 personality);
+u32 Pokedex_CreateCatchedMonSprite(u32 species, s32 x, s32 y);
```
Comment (Bassoonian) [inline include/pokedex.h]:
```suggestion
u32 Pokedex_CreateCaughtMonSprite(u32 species, s32 x, s32 y);
```
Sorry :) this throughout the commit

File: src/pokedex_plus_hgss.c [hunk 2]
```diff
@@ -4147,14 +4147,18 @@ void Task_DisplayCaughtMonDexPageHGSS(u8 taskId)
         CopyBgTilemapBufferToVram(3);
         gTasks[taskId].tState++;
         break;
-    case 4:
-        spriteId = CreateMonSpriteFromNationalDexNumberHGSS(dexNum, MON_PAGE_X, MON_PAGE_Y, 0);
-        gSprites[spriteId].oam.priority = 0;
+    case 4: {
+        u32 personality = ((u16)gTasks[taskId].tPersonalityHi << 16) | (u16)gTasks[taskId].tPersonalityLo;
```
Comment (Bassoonian) [inline src/pokedex_plus_hgss.c]:
```suggestion
    case 4:
    {
        u32 personality = ((u16)gTasks[taskId].tPersonalityHi << 16) | (u16)gTasks[taskId].tPersonalityLo;
```

File: include/pokedex.h (hunk 1 above)
Comment (DizzyEggg) [reply include/pokedex.h]: OOF, please squash this lmao

**Review by Bassoonian — APPROVED** [review]
