### PR TITLE
Fix switch-in abilities not triggering on revive

### LINKED ISSUE #5176: Inconsistency with reviving with a fainted player mon on the right
### Description

Video: https://discord.com/channels/419213663107416084/774393519569502268/1273462654882549842
> if you revive the mon in index 1, then it gets sent out immediately. but if you revive any other mon, it's sent out at the end of turn
and I don't even know if switch in abilities are triggered
or if that's purely a visual effect

### Version

1.9.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

luckytyphlosion

### PR DESCRIPTION
**Pull request by FosterProgramming**
Remove abilities (and item) disable on faint

## Issue(s) that this PR fixes
Fixes #5176 (kind of, #5176 mentions abilities not triggering on revive but the major complaint inconsistent switch-in which I think has been fixed, the Hedara tests failing are just test engine quirks, I use the same setup, you just need a skip_turn action for the revived mon)

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -4224,7 +4224,6 @@ static void Cmd_tryfaintmon(void)
          && !(gAbsentBattlerFlags & (1u << battler))
          && !IsBattlerAlive(battler))
         {
-            gBattleMons[battler].ability = ABILITY_NONE;
```
Comment (PhallenTree) [inline src/battle_script_commands.c]: Neutralizing Gas tests timeout because this is always reached (the battler's ability is always Neutralizing Gas).
Consider using `gDisableStructs[battler].neutralizingGas` and setting it to `FALSE` here.

Comment (FosterProgramming) [reply src/battle_script_commands.c]: I tried and it doesn't work

Comment (PhallenTree) [reply src/battle_script_commands.c]: #8318 should cleanup Neutralizing Gas activation so these tests don't timeout anymore.
As for the other test that fails, those abilities might need a `IsBattlerAlive(battler)` check before trying to change forms.

**Comment by FosterProgramming** [comment]
Pr rebased on top on master and I finally got it to pass all the tests.

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -16194,7 +16194,8 @@ void BS_ActivateWeatherChangeAbilities(void)
 
     u32 battler = GetBattlerForBattleScript(cmd->battler);
     gBattlescriptCurrInstr = cmd->nextInstr;
-    AbilityBattleEffects(ABILITYEFFECT_ON_WEATHER, battler, 0, 0, 0);
+    if (IsBattlerAlive(battler))
```
Comment (PhallenTree) [inline src/battle_script_commands.c]: It would be better if this check was instead in `AbilityBattleEffects`, since it can still activate terrain abilities (Mimicry) or if another mon switches in after this mon faints during the same turn. I'd recommend instead adding:
```
if (!IsBattlerAlive(battler))
    return effect;
```
after `case ABILITYEFFECT_ON_WEATHER` and `case ABILITYEFFECT_ON_TERRAIN` in `AbilityBattleEffects`.
