### PR TITLE
Fixes Emergency Exit when hp is restored over tag out range

### LINKED ISSUE #4029: Emergency Exit Issues
### Description

The HP value at which Golisopod with odd maximum HP values gets his Emergency Exit activated is wrong by 1.

Example: Golisopod at a maximum HP of 263 takes a hit with puts him into 131 HP (Super Fang for testing if Golispod took 1 damage beforehand). 
**Expected situation**: 131 is under half and therefore it is expected for Golispods Emergency Exit to activate.
Ho
**Actual situation**: Emergency Exit does not activate, as for some reason, it considers 130 as the Emergency Exit range. (Rounding problem?).

On even HP, Emergency Exit behaves as expected.

Added to that, there is another bug where Golispod gets ejected while getting a Sitrus Heal, which should be impossinble. In the same example, if you give Golispod a Sitrus Berry, it will Eject Out, despite Sitrus Berry healing it out of Emergency Exit range.

### Version

upcoming (Edge)

### Upcoming/master Version

58102e6

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4029

Second part.

### CODE REVIEW

File: test/battle/ability/emergency_exit.c [hunk 1]
```diff
@@ -5,16 +5,34 @@ SINGLE_BATTLE_TEST("Emergency Exit switches out when taking 50% max-hp damage")
 {
     GIVEN {
         PLAYER(SPECIES_WOBBUFFET) { Attack(1314); }; // will deal exactly 132 damage, putting GOLISOPOD just under half hp
```
Comment (Bassoonian) [inline test/battle/ability/emergency_exit.c:7]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET);
```

**Review by Bassoonian — APPROVED** [review]

File: src/battle_util.c [hunk 2]
```diff
@@ -6793,6 +6793,10 @@ static u8 ItemHealHp(u32 battler, u32 itemId, bool32 end2, bool32 percentHeal)
             BattleScriptPushCursor();
             gBattlescriptCurrInstr = BattleScript_ItemHealHP_RemoveItemRet;
         }
+        if (gBattleResources->flags->flags[battler] & RESOURCE_FLAG_EMERGENCY_EXIT
+         && GetNonDynamaxMaxHP(battler) > gBattleMons[battler].maxHP / 2)
```
Comment (ghoulslash) [inline src/battle_util.c:6797]: why are we comparing two maxHp values here? Shouldnt this be `GetNonDynamaxHP(battler) > gBattleMons[battler].maxHP/2`?

Comment (AlexOn1ine) [reply src/battle_util.c:6797]: i messed up. Fixed in  #4041 follow up.
