### PR TITLE
Fix U-Turn With Ace Mon (#4748)

### LINKED ISSUE #4748: U-Turn With Ace Mon
### Description

The Ai used U-Turn on Farigiraf and with only that Farigiraf and the ace mon, it went back into Farigiraf which should have been illegal. You can't U-Turn into whoever is already out. The Ace Pokemon Flag was messing with the U-Turn

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

not 100% sure. updated it like 3 days ago

### Discord contact info

SShadowzLmao#3643

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
This turned out to just be a conditional block error that we missed in both the initial `GetBestMonIntegrated` implementation *and* its minor refactor in #4849 lol. I've also written a corresponding test.

## Issue(s) that this PR fixes
Fixes #4748

## **Discord contact info**
@Pawkkie

### CODE REVIEW

File: test/battle/ai.c [hunk 1]
```diff
@@ -699,6 +699,19 @@ AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_MON_CHOICES: Post-KO switches prioritize of
     }
 }
 
+AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_MON_CHOICES: U-Turn will send out Ace Mon if it's the only one remaining")
```
Comment (AlexOn1ine) [inline test/battle/ai.c:702]: Does this test prove the fix? It is just one move with one mon in the back

Comment (Pawkkie) [reply test/battle/ai.c:702]: Yeah actually, with the bug present it tries to switch in index -1 lol

**Review by AlexOn1ine — APPROVED** [review]
