### PR TITLE
Battle bond tests and small fix

### LINKED ISSUE #2431: Battle Bond doesn't transform when fainting ally
Found by akimoto#5337 on RHH's discord

player

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #2431

Adds tests for Battle Bond

### CODE REVIEW

File: test/battle/ability/battle_bond.c [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+{
+    ASSUME(P_GEN_6_POKEMON == TRUE);
+    ASSUME(gBattleMoves[MOVE_WATER_GUN].power != 0);
+}
+
+SINGLE_BATTLE_TEST("Battle Bond does not transform species other than Greninja")
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) {Ability(ABILITY_BATTLE_BOND); }
+        OPPONENT(SPECIES_WOBBUFFET) {HP(1); }
```
Comment (AsparagusEduardo) [inline test/battle/ability/battle_bond.c:14]:
```suggestion
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_BATTLE_BOND); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(1); }
```

File: test/battle/ability/battle_bond.c [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+    PARAMETRIZE {monsCountPlayer = 3; monsCountOpponent = 2; }
+    PARAMETRIZE {monsCountPlayer = 3; monsCountOpponent = 3; }
+
+    GIVEN {
+        PLAYER(SPECIES_GRENINJA_BATTLE_BOND);
+        PLAYER(SPECIES_WOBBUFFET) {HP(1); }
+        if (monsCountPlayer == 3) {
+            PLAYER(SPECIES_WOBBUFFET);
+        }
+        OPPONENT(SPECIES_WOBBUFFET) {HP(1); }
```
Comment (AsparagusEduardo) [inline test/battle/ability/battle_bond.c:140]:
```suggestion
        OPPONENT(SPECIES_WOBBUFFET) { HP(1); }
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

**Review by AsparagusEduardo — APPROVED** [review]
