### PR TITLE
Fixes plasma fists and several let's go and max move effects which should occur even when fainting a foe

### LINKED ISSUE #9263: Several max moves, let's go moves, and plasma fists do not occur when fainting the target
### Description

in battle_script_commands.c, the following clause:
```
    else if (!IsBattlerAlive(gEffectBattler) && !activateAfterFaint)
        moveEffect = MOVE_EFFECT_NONE;
```
is removing any effect that doesn't have Self=TRUE defined in moves_info, whenever the move causes the target to faint. 

I believe this includes the following incorrect cases. Please review :)

    case MOVE_EFFECT_SUN:
    case MOVE_EFFECT_RAIN:
    case MOVE_EFFECT_SANDSTORM:
    case MOVE_EFFECT_HAIL:
    case MOVE_EFFECT_MISTY_TERRAIN:
    case MOVE_EFFECT_GRASSY_TERRAIN: 
    case MOVE_EFFECT_ELECTRIC_TERRAIN:
    case MOVE_EFFECT_PSYCHIC_TERRAIN:
    case MOVE_EFFECT_RAISE_TEAM_ATTACK:
    case MOVE_EFFECT_RAISE_TEAM_DEFENSE:
    case MOVE_EFFECT_RAISE_TEAM_SPEED:
    case MOVE_EFFECT_RAISE_TEAM_SP_ATK:
    case MOVE_EFFECT_RAISE_TEAM_SP_DEF:
    case MOVE_EFFECT_CRIT_PLUS_SIDE:
    case MOVE_EFFECT_DEFOG:
    case MOVE_EFFECT_REFLECT:
    case MOVE_EFFECT_LIGHT_SCREEN:
    case MOVE_EFFECT_AURORA_VEIL:
    case MOVE_EFFECT_GRAVITY:
    case MOVE_EFFECT_HEAL_TEAM:
    case MOVE_EFFECT_AROMATHERAPY:
    case MOVE_EFFECT_RECYCLE_BERRIES:
    case MOVE_EFFECT_ION_DELUGE:
    case MOVE_EFFECT_HAZE:

### Reproduction Steps

Tests in PR:
```


DOUBLE_BATTLE_TEST("Dynamax: G-Max Finale heals allies by 1/6 of their health, even if it faints the foe")
{
    s16 damage1, damage2;
    GIVEN {
        ASSUME(MoveHasAdditionalEffect(MOVE_G_MAX_FINALE, MOVE_EFFECT_HEAL_TEAM));
        PLAYER(SPECIES_ALCREMIE) { HP(1); GigantamaxFactor(TRUE); }
        PLAYER(SPECIES_MILCERY) { HP(1); }
        OPPONENT(SPECIES_WOBBUFFET)  { HP(1); }
        OPPONENT(SPECIES_WOBBUFFET)  { HP(1); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(playerLeft, MOVE_MOONBLAST, target: opponentLeft, gimmick: GIMMICK_DYNAMAX); SEND_OUT(opponentLeft, 2); }
    } SCENE {
        MESSAGE("Alcremie used G-Max Finale!");
        HP_BAR(playerLeft, captureDamage: &damage1);
        HP_BAR(playerRight, captureDamage: &damage2);
    } THEN {
        EXPECT_MUL_EQ(-damage1, Q_4_12(6), playerLeft->maxHP); // heals based on Dynamax HP. Appears to have a problem with milcery in this case!?
    }
}

DOUBLE_BATTLE_TEST("Dynamax: G-Max Replenish recycles allies' berries 50\% of the time, even if it faints the foe")
{
    PASSES_RANDOMLY(1, 2, RNG_G_MAX_REPLENISH);
    GIVEN {
        ASSUME(MoveHasAdditionalEffect(MOVE_G_MAX_REPLENISH, MOVE_EFFECT_RECYCLE_BERRIES));
        PLAYER(SPECIES_SNORLAX) { Item(ITEM_APICOT_BERRY); GigantamaxFactor(TRUE); }
        PLAYER(SPECIES_MUNCHLAX) { Item(ITEM_APICOT_BERRY); Ability(ABILITY_THICK_FAT); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(1); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(1); }
        OPPONENT(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(playerLeft, MOVE_STUFF_CHEEKS); \
               MOVE(playerRight, MOVE_STUFF_CHEEKS); \
               MOVE(opponentLeft, MOVE_CELEBRATE); \
               MOVE(opponentRight, MOVE_CELEBRATE); }
        TURN { MOVE(playerLeft, MOVE_SCRATCH, target: opponentLeft, gimmick: GIMMICK_DYNAMAX); SEND_OUT(opponentLeft, 2);}
    } SCENE {
        // turn 1
        MESSAGE("Using Apicot Berry, the Sp. Def of Snorlax rose!");
        MESSAGE("Using Apicot Berry, the Sp. Def of Munchlax rose!");
        // turn 2
        MESSAGE("Snorlax used G-Max Replenish!");
        MESSAGE("Snorlax found one Apicot Berry!");
        MESSAGE("Munchlax found one Apicot Berry!");
    }
}

```

### Images / Video

_No response_

### Version

1.14.3 (Latest release)

### Upcoming/master Version

Master

### Discord contact info

luuma

### PR DESCRIPTION
**Pull request by luuma**
## Description
Several move effects do not target self but do still target pokemon other than the foe. These are getting overwritten when activateAfterFaint is not set

## Issue(s) that this PR fixes
Fixes #9263 

## Feature(s) this PR does NOT handle:
The exact behaviour of these moves are **not something I've tested in game**. I have not reviewed all move effects extensively, and I assume this should be done before merge. 

When reviewing this behaviour, it might be worth checking what happens when the target is the final mon in the foe's party, perhaps adding:

```
    else if (NoAliveMonsForBattlerSide(gBattlerTarget))
        moveEffect = MOVE_EFFECT_NONE;
```

## Discord contact info
luuma

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -3066,12 +3066,37 @@ void SetMoveEffect(u32 battler, u32 effectBattler, enum MoveEffect moveEffect, c
         return;
     }
 
-    switch (moveEffect) // Set move effects which happen later on
+    switch (moveEffect) // Set move effects which happen even if the move's defined effectbattler is fainted
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: could you make a function with this switch instead? Maybe something like `ShouldIgnoreTargetForMoveEffect` and directly inline it into the check.

Comment (luuma) [reply src/battle_script_commands.c]: Sure, all done

File: test/battle/gimmick/dynamax.c [hunk 2]
```diff
@@ -1710,5 +1710,77 @@ DOUBLE_BATTLE_TEST("Dynamax stat raising moves don't make stat-changing abilitie
...
+        ASSUME(MoveHasAdditionalEffect(MOVE_G_MAX_FINALE, MOVE_EFFECT_HEAL_TEAM));
+        PLAYER(SPECIES_ALCREMIE) { HP(1); GigantamaxFactor(TRUE); }
+        PLAYER(SPECIES_MILCERY) { HP(1); }
+        OPPONENT(SPECIES_WOBBUFFET)  { HP(1); }
+        OPPONENT(SPECIES_WOBBUFFET)  { HP(1); }
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(playerLeft, MOVE_MOONBLAST, target: opponentLeft, gimmick: GIMMICK_DYNAMAX); SEND_OUT(opponentLeft, 2); }
+    } SCENE {
+        MESSAGE("Alcremie used G-Max Finale!");
```
Comment (AlexOn1ine) [inline test/battle/gimmick/dynamax.c:1731]: We usually use animation checks for whether the move hits or not.

File: test/battle/gimmick/dynamax.c [hunk 3]
```diff
@@ -1710,5 +1710,77 @@ DOUBLE_BATTLE_TEST("Dynamax stat raising moves don't make stat-changing abilitie
...
+    }
+}
+
+DOUBLE_BATTLE_TEST("Dynamax: G-Max Replenish recycles allies' berries 50\% of the time, even if it faints the foe")
+{
+    PASSES_RANDOMLY(1, 2, RNG_G_MAX_REPLENISH);
+    GIVEN {
+        ASSUME(MoveHasAdditionalEffect(MOVE_G_MAX_REPLENISH, MOVE_EFFECT_RECYCLE_BERRIES));
+        PLAYER(SPECIES_SNORLAX) { Item(ITEM_APICOT_BERRY); GigantamaxFactor(TRUE); }
+        PLAYER(SPECIES_MUNCHLAX) { Item(ITEM_APICOT_BERRY); Ability(ABILITY_THICK_FAT); }
```
Comment (AlexOn1ine) [inline test/battle/gimmick/dynamax.c:1747]: missing assume for the berry

**Comment by luuma** [comment]
Bugfix ready for another review
