### PR TITLE
Fix substitute/defog interactions

### LINKED ISSUE #5386: Defog lowers evasion on mon behind Substitutes
### Description

With `GEN_LATEST` settings for Defog, using it against a pokemon behind a Substitute while it has something that Defog can remove should not lower their Evasion.

Follow up on #5381

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by FosterProgramming**
on master Defog was lowering evasion behind substitute if there was stuff on field regardless on gen and I'm fixing that, it will never reduce evasion behind sub in gen5+
Then from my reading of bulbapedia/jp wiki, it seems that it always lowers evasion in gen4 regardless of if there is stuff to remove so I'm going with that for now, it should be easy to change if it's different anyway

I added tests for min stage evasion because I was confused about some stuff but it may not be needed 

## Issue(s) that this PR fixes
Fixes #5386

## Discord contact info
Jamie

### CODE REVIEW

**Comment by FosterProgramming** [comment]
PR updated with #8416 changes

**Comment by FosterProgramming** [comment]
I added helper functions for swapping substitute in  #8423 so I could, to the discretion of the review, rewrite this PR using those

File: include/constants/battle_anim.h [hunk 1]
```diff
@@ -538,62 +538,62 @@
...
+#define B_ANIM_TRICK_ROOM                     45
+#define B_ANIM_WONDER_ROOM                    46
+#define B_ANIM_MAGIC_ROOM                     47
+#define B_ANIM_TAILWIND                       48
+#define B_ANIM_FOG_CONTINUES                  49
+#define B_ANIM_TERA_CHARGE                    50
+#define B_ANIM_TERA_ACTIVATE                  51
+#define B_ANIM_SIMPLE_HEAL                    52
+#define B_ANIM_POWER_CONSTRUCT                53
+#define B_ANIM_STATS_CHANGE_IGNORE_SUBSTITUTE 54
```
Comment (AlexOn1ine) [inline include/constants/battle_anim.h]: why does there need to be a new anim?

Comment (FosterProgramming) [reply include/constants/battle_anim.h]: It felt easier to make a new anim that include the substitute swap. Mostly it made sure other stat change anim call would not bypass the substitute. But I could rewrite using the helper functions I made for #8243 and it would likely be cleaner and without the new anim

Comment (AlexOn1ine) [reply include/constants/battle_anim.h]: ye, this would be better.

Comment (FosterProgramming) [reply include/constants/battle_anim.h]: I will rewrite it tomorrow. Can you merge #8243 first?

**Comment by FosterProgramming** [comment]
PR updated

**Review by AlexOn1ine — APPROVED** [review]
