### PR TITLE
Fix shiny stars being freed before shiny animation was played

### LINKED ISSUE #5348: Shiny sparkles glitch out when opponent animation is too long with followers
### Description
Sometimes, if an opponent has a long enough animation it seems that the graphics for the shiny sparkles don't get loaded correctly.

### Video
When encountering Wingull and spamming the A button to get through the dialogue as fast as possible, the bug can be triggered.

https://github.com/user-attachments/assets/3d26e2d6-6148-4313-8109-82bb64fc85e3

When encountering Zigzagoon, bug is not triggered.

https://github.com/user-attachments/assets/bde1f406-73a7-4c62-83b7-cded71198763

### Notes

- Bug only happens when using OW Followers.
- Seems to be related to opponent animation length.

### Version

1.9.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

sarnnn

### PR DESCRIPTION
**Pull request by FosterProgramming**
Sometimes a battler would free the shiny stars even tho an another battler still needs it. This PR fixes that.

## Description
Here is an overview of the shiny sparks in battle:
All battler call TryShinyAnimation and wait for it to set a flag that tell them the animation is over.
Once that flag is set, the battler would free the shiny sparks (or try to free if the tag is not used). This would cause issues if another battler wanted to use it. This is not an issue if the animations are properly played sequentially because the battler would just allocate the stars again but when various speed-ups are applied to the game, this happen more often.

So instead of freeing directly, I made sure it calls a function called FreeShinyStars that only frees if every battler has ended their shiny animation. (I'm not sure if I should use a more explicit name for the function like TryFreeingShinyStars or FreeShinyStarsIfSomething but I couldn't find one I really like)

Phantonomy found a consistent setup in his hack Transform, which I used to understand the issue and make the example videos.

## Media
Before:

https://github.com/user-attachments/assets/8d1ad0cc-b0e1-497b-915a-211242d24d74

After:

https://github.com/user-attachments/assets/cbfc3f04-99a4-429f-9e69-c713255a91f3

## Issue(s) that this PR fixes
Fixes #5348 

## Things to note in the release changelog:
- Fixes shiny sparks in battle not appearing properly in rare circumstances (more common with various speedup options)

## Discord contact info
Jamie(foster_harmony)

### CODE REVIEW

File: src/battle_controllers.c [hunk 1]
```diff
@@ -3124,3 +3121,14 @@ void UpdateFriendshipFromXItem(u32 battler)
         SetBattlerMonData(battler, GetBattlerParty(battler), gBattlerPartyIndexes[battler]);
     }
 }
+
+void FreeShinyStars(void)
+{
+    for (u32 battler = 0; battler < MAX_BATTLERS_COUNT; battler++)
```
Comment (AlexOn1ine) [inline src/battle_controllers.c]:
```suggestion
    for (u32 battler = 0; battler < gBattlersCount; battler++)
```
