### PR TITLE
Fix Red Card / Eject Button interaction

### LINKED ISSUE #8738: Eject Button and Red Card need to be in a single case
### Description

Title

### Reproduction Steps

see code

### Images / Video

_No response_

### Version

1.14.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #8771: Red Card moveend should probably initialize gBattlerTarget to the red card holder
### Description

When red card activates, it runs a script, which swaps the attacker and target (to be compatible with forcerandomswitch)
https://github.com/rh-hideout/pokeemerald-expansion/blob/cded31fa7f492a443627f9b64676b1090e58a93a/data/battle_scripts_1.s#L7997-L8004

However, the target is never actually set in the Red Card moveend, so the temporary attacker will just be whatever was last in gBattlerTarget, which is unpredictable for spread moves
https://github.com/rh-hideout/pokeemerald-expansion/blob/cded31fa7f492a443627f9b64676b1090e58a93a/src/battle_move_resolution.c#L1179-L1192

It's unknown if this actually affects anything (mold breaker won't work anyway because it's not the target's turn), but the target should probably be set to a known value (red card holder makes the most sense here)

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #8738
Fixes  #8771

To upcoming because I feel this is out of scope for master

### CODE REVIEW

File: src/battle_move_resolution.c [hunk 1]
```diff
@@ -1140,129 +1140,92 @@ static enum MoveEndResult MoveEnd_KeeMarangaHpThresholdItemTarget(void)
...
 
-    for (u32 i = 0; i < gBattlersCount; i++)
+    for (u32 battlerDef = 0; battlerDef < gBattlersCount; battlerDef++)
     {
-        u32 battler = battlers[i];
+        u32 battler = battlers[battlerDef];
 
-        if (!(ejectButtonBattlers & 1u << battler))
-            continue;
+        // Only fastest red card or eject pack activates
```
Comment (grintoul1) [inline src/battle_move_resolution.c]: Should this read Eject Button?

File: include/constants/battle_move_resolution.h [hunk 2]
```diff
@@ -41,8 +41,7 @@ enum MoveEndState
     MOVEEND_SHEER_FORCE, // If move is Sheer Force affected, skip to Hit Escape + One
     MOVEEND_COLOR_CHANGE, // Color Change / Berserk / Anger Shell
     MOVEEND_KEE_MARANGA_HP_THRESHOLD_ITEM_TARGET,
-    MOVEEND_RED_CARD,
-    MOVEEND_EJECT_BUTTON,
+    MOVEEND_EJECT_ITEMS, // Red Card, Eject Button
```
Comment (grintoul1) [inline include/constants/battle_move_resolution.h]: Given Eject Pack is handled separately further down, while there is a comment present here using "Eject Items" could perhaps cause confusion else where? 

Perhaps something along the lines of `MOVEEND_CARD_AND_BUTTON`? Though that also doesn't feel the best

Comment (AlexOn1ine) [reply include/constants/battle_move_resolution.h]: that works, ye

**Comment by AlexOn1ine** [comment]
changes applied, also fixes  #8771

File: src/battle_move_resolution.c [hunk 3]
```diff
@@ -1740,7 +1740,7 @@ static enum MoveEndResult (*const sMoveEndHandlers[])(void) =
     [MOVEEND_SHEER_FORCE] = MoveEnd_SheerForce,
     [MOVEEND_COLOR_CHANGE] = MoveEnd_ColorChange,
     [MOVEEND_KEE_MARANGA_HP_THRESHOLD_ITEM_TARGET] = MoveEnd_KeeMarangaHpThresholdItemTarget,
-    [MOVEEND_EJECT_ITEMS] = MoveEnd_EjectItems,
+    [MOVEEND_CARD_BUTTON] = MoveEnd_EjectItems,
```
Comment (grintoul1) [inline src/battle_move_resolution.c]: Sorry, being picky, do we want to rename the `MoveEnd_EjectItems` function to reflect this change also? Could cause similar confusion

Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: oops, forgot to change it alongside. fixed.

**Review by grintoul1 — APPROVED** [review]
