### PR TITLE
Banned species list

### LINKED ISSUE #6760: Too many seen frontier banned species causes a crash
### Description

Image

### Version

upcoming (Edge)

### Upcoming/master Version

1a2cd5645af10263c852ade80dd349a7989889ca

### Discord contact info

AsparagusEduardo

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Description
The PR is large but the changes are relatively straightforward. I updated the function printing the string and added a task that can display a window with the list of banned species.
The Battle Frontier lobby scripts have been updated to match the changes.
The thing a bit out of ordinary is that I updated the list_menu code to allow to show things without allocating a ListMenuItems array. Here I use it to allocate a u16 array instead (3 times smaller) but I have plans to use this new feature reduce the memory usage of the move relearner as well.

## Media

https://github.com/user-attachments/assets/300ee531-368d-4fc4-8cb6-c29407d42dc0

https://github.com/user-attachments/assets/de44351c-2c80-4689-aae1-7036366a6634

https://github.com/user-attachments/assets/02f371d8-a695-41cc-899b-d10797513c61

https://github.com/user-attachments/assets/f72be367-e83e-4619-b23f-6aa876bce79c

https://github.com/user-attachments/assets/7ef15c93-b7aa-4876-bc74-8842dad5711c

## Issue(s) that this PR fixes
Fixes #6760

## Feature(s) this PR does NOT handle:
 The window is basic so the UI/UX could be improved

## Things to note in the release changelog:
- Add a window displaying caught banned species list in the Battle Frontier instead of the string detailing all the is 

## Discord contact info
Jamie (foster_harmony)

### CODE REVIEW

File: include/list_menu.h [hunk 1]
```diff
@@ -76,8 +76,9 @@ struct ListMenuTemplate
     u8 lettersSpacing:3;
     u8 itemVerticalPadding:3;
     u8 scrollMultiple:2; // x40, x80 = xC0
-    u8 fontId:6; // x1, x2, x4, x8, x10, x20 = x3F
-    u8 cursorKind:2; // x40, x80
+    u8 fontId:5; // x1, x2, x4, x8, x10 = x1F
+    u8 cursorKind:2; // x20, x40
+    u8 isDynamic:1; //Dynamic list doesn't store all items in memory but load them from ROM when necessary
```
Comment (AlexOn1ine) [inline include/list_menu.h:81]: Is there a reason it isn't always dynamic?

Comment (FosterProgramming) [reply include/list_menu.h:81]: Dynamic might be better and work for every list in the game or it might not, but every case would need to be looked at one by one and refactoring every use of listItem felt like a big increase in scope.

**Comment by AlexOn1ine** [comment]
image

is it normal that I can scroll through the list? Which conditions need to be fulfilled so I can see all banned species?

**Comment by FosterProgramming** [comment]
Scrolling through the list is intended behavior tho it may not be good design as discussed in the thread. A species will show /be counted when given the number if it's "caught" in your pokedex. In my examples, I used the debug menu to set all mons to "caught". 
Is there a mismatch between the number of mons they tell you are banned and the number you can see/scroll through?

**Comment by AlexOn1ine** [comment]
> show /be counted when given the number if it's "caught" in your pokedex. In my examples, I used the debug menu to set all mons to "caught".

That was the problem. All good then.
