### PR TITLE
Add Battle Anim cmds for dynamic Task, Sprite creation + Misc. Anim Fixes

### LINKED ISSUE #2650: Heal Block only targets a single battler
should have MOVE_TARGET_BOTH

### PR DESCRIPTION
**Pull request by ghoulslash**
Cmds to create tasks and sprites that affect a dynamic number of targets

Animation Fixes:
- fiery wrath
- electroweb 
-  heal block targeting/anim --> Another cmd was needed, createspriteontargets_onpos, because AnimSpriteOnMonPos is weird
- Venom Drench to take average target positions into account

fixes #2650

These can eventually be used for triple battles, so rather than editing all MOVE_TARGET_BOTH anim tasks/sprite callbacks we can use these cmds in the battle anim scripts

electroweb:
electroweb

### CODE REVIEW

File: src/battle_anim.c [hunk 1]
```diff
@@ -479,6 +484,126 @@ static void Cmd_createsprite(void)
...
+    int ntargets;
+    s16 subpriority;
+    
+    for (i = 0; i < argsCount; i++)
+    {
+        gBattleAnimArgs[i] = T1_READ_16(sBattleAnimScriptPtr);
+        sBattleAnimScriptPtr += 2;
+    }
+
+    if (argVar & 0x80)
```
Comment (DizzyEggg) [inline src/battle_anim.c:500]: Since getting subpriority is the same here as in the Cmd_createsprite function, I think it's worth seperating these two duplicates of code into a function like 'GetSubpriorityForMoveAnim'.

File: src/battle_anim.c [hunk 2]
```diff
@@ -509,6 +634,68 @@ static void Cmd_createvisualtask(void)
     gAnimVisualTaskCount++;
 }
 
+extern u32 GetBattlerMoveTargetType(u8 battlerId, u16 move);
```
Comment (DizzyEggg) [inline src/battle_anim.c:637]: I think it would be better to just include the needed header at the top instead of extern.

**Review by DizzyEggg — CHANGES_REQUESTED** [review]

**Comment by ghoulslash** [comment]
implemented suggestions

File: data/battle_anim_scripts.s [hunk 3]
```diff
@@ -1492,22 +1492,22 @@ Move_HEAL_BLOCK:
 	loadspritegfx ANIM_TAG_BLUE_STAR
 	monbg ANIM_TARGET
 	createsoundtask SoundTask_PlaySeChangingVolume, SE_M_ABSORB_2, SOUND_PAN_TARGET, 256, -16, 0, 2
-	createsprite gHealingBlueStarSpriteTemplate, ANIM_TARGET, 2, 0, -5, 1, 0
+	createspriteontargets_onpos gHealingBlueStarSpriteTemplate, ANIM_TARGET, 2, 2, 0, -5, ANIM_TARGET, 0
```
Comment (DizzyEggg) [inline data/battle_anim_scripts.s:1495]: Heal Block animation is a bit broken in singles, it plays as if there were two targets.

**Review by DizzyEggg — CHANGES_REQUESTED** [review]

File: data/battle_anim_scripts.s (hunk 3 above)
Comment (ghoulslash) [reply data/battle_anim_scripts.s:1495]: > Heal Block animation is a bit broken in singles, it plays as if there were two targets.

Added IsBattlerAlive checks for each target, consolidated checks to new function, `GetBattleAnimMoveTargets`

**Review by DizzyEggg — APPROVED** [review]
