### PR TITLE
Bugfixes batch

### LINKED ISSUE #6661: White herb descriptive bugs in double battles.
### Description

1.**Double** match 
2.Pokemon the **right** holds White herb 
3.Pokemon the **right** uses moves that lower their status (such as Superpower). 

Bug appears: "pokemon returned its status to normal using it's xxx".

Here xxx refers to the item carried by the Pokemon on the **left**. The above bug will **only** appear when the white herb is carried by the **right** side Pokemon.

Image

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #6689: U-turn is supposed to trigger before eject pack if user holds it
### Description

```
SINGLE_BATTLE_TEST("Hit Escape: U-turn triggers before Eject Pack")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_EJECT_PACK); };
        PLAYER(SPECIES_WYNAUT);
        OPPONENT(SPECIES_GOODRA_HISUI) { Ability(ABILITY_GOOEY); };
    } WHEN {
        TURN { MOVE(player, MOVE_U_TURN); SEND_OUT(player, 1); }
    } SCENE {
        NOT ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, player);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_U_TURN, player);
        HP_BAR(opponent);
        SEND_IN_MESSAGE("Wynaut");
    }
}
```

[Source](<https://www.youtube.com/watch?v=H1b7FKQDG6U&t=7315s>)

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #6721: Dragon Darts: Both darts do not target a user of redirection
### Description

(Disclaimer: I can provide a video of the interaction. Figured I'd write this up to report on it for now)

There's a bug with Dragon Darts which when a redirection move (such as Follow Me and Rage Powder) is used, both darts are unaffected.

The intended behavior is both targets go into the redirection user.

Extra Test Cases:
- If the target faints from the first dart, the second dart should be ignored entirely.
- If the target redirects to a user that's immune to Dragon Darts, both darts should go into that target, thus causing the move to fail entirely.

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

linathan

### LINKED ISSUE #6723: Rowap/Jaboca Berry activating on death
### Description

Rowap and Jaboca Berry should activate even if the holder faints. Currently, it does not.

Showdown proof: https://replay.pokemonshowdown.com/gen9customgame-2353270286-ylaxua52gyrd496qkb1xsxc7623v72mpw
Gen 4 Cardridge proof if the Showdown Proof isn't considered good enough: https://www.youtube.com/watch?v=RJkvhpnbj-0&feature=youtu.be

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #6732: Beast Boost triggers even if user is fainted due to Destony Bond
### Description

If a Pokemon with beast Boost knocks something out that has Destiny Bond active, the Beast Boost currently triggers despite the battler being fainted.

Test to verify the behaviour.
```C
SINGLE_BATTLE_TEST("Beast Boost doesn't trigger if user is fainted")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_DESTINY_BOND) == EFFECT_DESTINY_BOND);
        ASSUME(GetMovePower(MOVE_SCRATCH) > 0);
        PLAYER(SPECIES_WOBBUFFET) { HP(1); }
        PLAYER(SPECIES_WYNAUT);
        OPPONENT(SPECIES_KARTANA) { Ability(ABILITY_BEAST_BOOST); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_DESTINY_BOND); MOVE(opponent, MOVE_SCRATCH); SEND_OUT(player, 1); SEND_OUT(opponent, 1); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_DESTINY_BOND, player);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SCRATCH, opponent);
        NOT ABILITY_POPUP(opponent, ABILITY_BEAST_BOOST);
        SEND_IN_MESSAGE("Wynaut");
        MESSAGE("2 sent out Wobbuffet!");
    }
}
```

https://github.com/user-attachments/assets/81adba7c-b8a4-45e4-b757-2c8aa5f23c84

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### LINKED ISSUE #6740: Desolate Land makes Dive unable to execute the 2nd turn
### Description

The second turn keeps trying to execute and fail, essentially locking the game.

https://github.com/user-attachments/assets/fa25846f-2cc0-403b-ba0a-bd534103b8be

Test to check the behaviour
```C
SINGLE_BATTLE_TEST("Desolate Land does not break Dive")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_GROUDON) {Item(ITEM_RED_ORB);}
    } WHEN {
        TURN { MOVE(player, MOVE_DIVE); }
        TURN { SWITCH(opponent, 1); SKIP_TURN(player); }
        TURN { }
    } SCENE {
    }
}
```

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### LINKED ISSUE #6745: gBattleScripting.savedDmg is used for recoil and shell bell calculation in moveend but can be corrupted along the way
### Description

Look at move end constants
Notice MOVEEND_SUM_DAMAGE is the very first one
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf4721571683420734e64b73c6eaefde079636/include/constants/battle_script_commands.h#L258-L291

Writes to `gBattleScripting.savedDmg`
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/src/battle_script_commands.c#L6291-L6294

MOVEEND_RECOIL uses that value for the recoil calculation
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/src/battle_script_commands.c#L6469-L6502

So does shell bell
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/src/battle_util.c#L8171-L8183

Too bad it can get overwritten. Cheek pouch can overwrite `gBattleScripting.savedDmg` and that one is called before recoil and shell bell
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/src/battle_script_commands.c#L9042-L9062

`tryactivatesoulheart` might overwrite it
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/data/battle_scripts_1.s#L5405-L5435
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/src/battle_script_commands.c#L10679-L10696
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/data/battle_scripts_1.s#L8399-L8411

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #6747: Strange triggering behaviour with lifeorb
### Description

This will check for `IsBattlerTurnDamaged(gBattlerTarget)` or `gBattleStruct->moveDamage[gBattlerTarget]`
https://github.com/rh-hideout/pokeemerald-expansion/blob/fadf472/src/battle_util.c#L8191-L8193

If you do a ctrl+F of `gBattleStruct->moveDamage` in battle_util, you can notice that a ton of stuff will modify its value (such as most held item effects that modify damage).

Also other instances in battle_script_commands, e.g. cheek pouch, recoil

Thus, it seems like that check doesn't actually check for what it intends to

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6747
Fixes #6745
Fixes #6661
Fixes #6723
Fixes #6732
Fixes #6721
Fixes #6740
Fixes #6689

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
ready for review.

File: test/battle/ability/desolate_land.c [hunk 1]
```diff
@@ -65,3 +65,19 @@ SINGLE_BATTLE_TEST("Desolate Land does not block a move if pokemon is asleep and
...
+        PLAYER(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_GROUDON) {Item(ITEM_RED_ORB);}
+    } WHEN {
+        TURN { MOVE(player, MOVE_DIVE); }
+        TURN { SWITCH(opponent, 1); SKIP_TURN(player); }
+        TURN { MOVE(player, MOVE_CELEBRATE); }
+    } SCENE {
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_DIVE, opponent);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponent);
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply test/battle/ability/desolate_land.c]: I've not fixed this one correctly.

File: src/battle_util.c [hunk 2]
```diff
@@ -3577,6 +3590,11 @@ static void CancellerWeatherPrimal(u32 *effect)
         }
         if (*effect == 1)
         {
+            if (gStatuses3[gBattlerAttacker] & STATUS3_SEMI_INVULNERABLE_NO_COMMANDER)
+            {
+                gStatuses3[gBattlerAttacker] = 0;
+                gProtectStructs[gBattlerAttacker].chargingTurn = FALSE;
+            }
```
Comment (PhallenTree) [inline src/battle_util.c:3597]: Does `CancelMultiTurnMoves(gBattlerAttacker)` not work in this case?
Also hedara's requested change got reverted on the force push, so the test is wrong

Comment (AlexOn1ine) [reply src/battle_util.c:3597]: Oh, right this exists. This should be used, I just forgot about it lol

**Comment by AlexOn1ine** [comment]
ready for re-review

**Review by hedara90 — APPROVED** [review]
