### PR TITLE
Show floor number in map popup

### LINKED ISSUE #9316: No Silph Co Floor data shown in FRLG
### Description

In Vanilla FRLG Silph co map popup shows it's floor too

### Reproduction Steps

_No response_

### Images / Video

Vanilla

Image

Expansion

Image

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

HunarPG#2786

### PR DESCRIPTION
**Pull request by FosterProgramming**
Added support for the floor number feature from FRLG
Added a test that to verify map names fit into the default pop up
(I don't test gen 5 pop up because they cover the whole screen)

## Media

https://github.com/user-attachments/assets/5b6e76b1-521b-492a-941f-d272f4a48899

## Issue(s) that this PR fixes
Fixes #9316

## Feature(s) this PR does NOT handle:
Makefile update to make the test work with firered maps

## Things to note in the release changelog:
- The floor number feature from FRLG is now available in Emerald and working in FireRed. You can add a "floor_number" argument to you map json and when a popup for the map will appear, it will add 1F, 2F, B1. You can also use the value "FLOOR_ROOFTOP" (or 127) to show "ROOFTOP" like in the celadon mall

## Discord contact info
Jamie

### CODE REVIEW

File: test/text.c [hunk 1]
```diff
@@ -557,6 +560,28 @@ TEST("Type names fit on Pokedex Search Screen")
     EXPECT_LE(GetStringWidth(fontId, gTypesInfo[type].name, 0), widthPx);
 }
 
+
+TEST("Map names fit in popup")
+{
+    ASSUME(OW_POPUP_GENERATION == GEN_3);
+    u32 i, j;
```
Comment (hedara90) [inline test/text.c]: Loop iterator declared outside of loop declaration.

File: tools/mapjson/mapjson.cpp [hunk 2]
```diff
@@ -169,8 +169,13 @@ string generate_map_header_text(Json map_data, Json layouts_data) {
...
 
-    if (version != "firered")
-        text << "\t.2byte 0\n";
+    string floor_number = json_to_string(map_data, "floor_number", true);
+    if (floor_number.empty())
+        text << "\t.byte 0\n";
+    else
+        text << "\t.byte " << floor_number << "\n";
+
+    text << "\t.byte 0\n";
```
Comment (hedara90) [inline tools/mapjson/mapjson.cpp:178]: Doesn't this cause 2 `.byte 0` to be emitted if floor number is empty

File: src/map_name_popup.c [hunk 3]
```diff
@@ -518,9 +520,60 @@ static void UpdateSecondaryPopUpWindow(u8 secondaryPopUpWindowId)
...
+        return FALSE;
+    if (mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_1F
+     && mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_2F
+     && mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_3F
+     && mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_4F
+     && mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_5F
+     && mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_ROOF
+     && mapHeader->mapLayoutId != LAYOUT_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR)
+        return FALSE;
+    return TRUE;
```
Comment (hedara90) [inline src/map_name_popup.c:560]:
```suggestion
    {
        return FALSE;
    }
    return TRUE;
```

File: src/map_name_popup.c [hunk 4]
```diff
@@ -518,9 +520,60 @@ static void UpdateSecondaryPopUpWindow(u8 secondaryPopUpWindowId)
...
+}
+
+u8 *GetPopUpMapName(u8 *dest, const struct MapHeader *mapHeader)
```
Comment (hedara90) [inline src/map_name_popup.c:563]: The `IsCeladonDeptStore` part of this feels very clunky.
~~Couldn't it just be handled by giving the department store its own name?~~ Not without adding a new mapsec.
I think that, the `if (mapHeader->floorNumber != 0)` check should happen first, most maps doesn't need the floor handling, so it's better to check if it can just do an early return with the result of `GetMapName`.

File: tools/mapjson/mapjson.cpp (hunk 2 above)
Comment (FosterProgramming) [reply tools/mapjson/mapjson.cpp:178]: Yes, why is that a problem?
2 `.byte 0` and `.2byte 0` result in the same bytecode

File: src/map_name_popup.c (hunk 4 above)
Comment (FosterProgramming) [reply src/map_name_popup.c:563]: I made some changes but I'm not sure if that's what you want

File: tools/mapjson/mapjson.cpp (hunk 2 above)
Comment (hedara90) [reply tools/mapjson/mapjson.cpp:178]: Yea, I just missed that the previous code was `.2byte`

**Review by hedara90 — APPROVED** [review]
