### PR TITLE
Fix wrong gimmick spite showing when inputting too fast

### LINKED ISSUE #7078: Incorrect gimmick icon can show in double battles
### Description

When selecting "Battle" on the second mon while the gimmick icon is still on screen for the first mon the icon does not update to the correct sprite and just repeats from the first mon. This is just visual, the correct gimmick still activates for each mon.
I believe this issue is similar to #4652 / #6384 and the sprite is now not being destroyed in time.

### Reproduction Steps

Select "Battle" on the second mon in a double battle while the gimmick sprite for the first mon is still visible.

### Images / Video

https://github.com/user-attachments/assets/0fd0e98a-db0b-4922-896c-0e6ecd516e71

### Version

1.12.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

moo66

### PR DESCRIPTION
**Pull request by FosterProgramming**
If the gimmick sprite doesn't match the current battler when opening the move window, I delete the sprite early instead of waiting for the animation to finish

## Media
master:

https://github.com/user-attachments/assets/243c520f-72cc-4f52-bfdc-dceeadeda272

this commit:

https://github.com/user-attachments/assets/67b56018-a899-495c-a931-67b18715d60c

## Issue(s) that this PR fixes
Fixes #7078

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_controller_player.c [hunk 1]
```diff
@@ -2090,6 +2090,8 @@ void PlayerHandleChooseMove(u32 battler)
 
         if (!IsGimmickTriggerSpriteActive())
             gBattleStruct->gimmick.triggerSpriteId = 0xFF;
+        else if (!IsGimmickTriggerSpriteMatchingBattler(battler))
+            DestroyGimmickTriggerSprite();
```
Comment (AlexOn1ine) [inline src/battle_controller_player.c:2094]: A bit confused. Why do we delete it when it is matching?

Comment (FosterProgramming) [reply src/battle_controller_player.c:2094]: There is a ! / not, we destroy when it's not matching

Comment (AlexOn1ine) [reply src/battle_controller_player.c:2094]: ah fuck, I'm sorry...

**Review by AlexOn1ine — APPROVED** [review]
