### PR TITLE
Fix crashing tests looping

### LINKED ISSUE #7255: Tests can loop infinitely
### Description

```
TEST("LOOP")
{
  void (*f)(void) = NULL;
  f();
}
```
When the above test is run it will never stop / crash. 
Suspect from MGriffin 

> it's possible that sCurrentTest got broken by something else

### Reproduction Steps

_No response_

### Images / Video

_No response_

### Version

1.12.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by mrgriffin**
`.persistent` was incorrectly positioned in the linker script which meant that the `RegisterRamReset(RESET_ALL)` in `src/crt0.s` zeroed `sCurrentTest`, causing the crashing test to re-run.

## Issue(s) that this PR fixes
Fixes #7255

### CODE REVIEW

File: test/test_runner.c [hunk 1]
```diff
@@ -770,3 +779,10 @@ u32 SourceLineOffset(u32 sourceLine)
     else
         return sourceLine - test->sourceLine;
 }
+
+TEST("Tests resume after CRASH")
```
Comment (hedara90) [inline test/test_runner.c]: I think this test should be moved to it's own file.
A `test/test_test_runner.c` or something where we can add other tests for the actual test runner.
We can add tests for other test behaviour like `KNOWN_FAILING` and so on there later

**Comment by mrgriffin** [comment]
Ready for re-review!
