### PR TITLE
Move tutors makefile

### LINKED ISSUE #9052: Makefile dependencies for learnsets aren't fully foolproof
### Description

#8803's new changes aren't fully foolproof and may error after making clean

```
AssertionError: SOURCE_TEACHING_TYPES_JSON=PosixPath('tools/learnset_helpers/build/all_teaching_types.json') does not exist
```

### Reproduction Steps

_No response_

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
Fix build errors with `move_tutors.h`

## Issue(s) that this PR fixes
Fixes #9052

## Discord contact info
Jamie

### CODE REVIEW

File: src/event_object_movement.c [hunk 1]
```diff
@@ -2111,7 +2111,7 @@ u8 CreateVirtualObject(u16 graphicsId, u8 virtualObjId, s16 x, s16 y, u8 elevati
 struct Pokemon *GetFirstLiveMon(void)
 {
     u32 i;
-    for (i = 0; i < PARTY_SIZE; i++)
+    for (i = 0; i < gPlayerPartyCount; i++)
```
Comment (grintoul1) [inline src/event_object_movement.c]:
```suggestion
    for (i = 0; i < CalculatePlayerPartyCount(); i++)
```
Not 100% certain, but I don't think `gPlayerPartyCount` is continuously up to date. Would it be safer to use `CalculatePlayerPartyCount()` here either in the loop or the line above?

Comment (FosterProgramming) [reply src/event_object_movement.c]: I think this got changed while I was switching branches when it shouldn't. I just reverted it

**Comment by FosterProgramming** [comment]
PR updated
