### PR TITLE
Fix Psych Up wrong battler message and Gen 6+ crit ratio copying

### LINKED ISSUE #8949: Psych Up has not been updated to Gen 6+
### Description

per Bulbapedia: Psych Up now also copies the target's critical hit ratio. (e.g. If the target has the effect of Focus Energy, the user also gains that effect; if the user has the effect of Focus Energy but the target does not, the user loses that effect.)

### Reproduction Steps

code, debug battle

### Images / Video

_No response_

### Version

upcoming

### Upcoming/master Version

bcae4e2110

### Discord contact info

amiosi

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description

- Correct the battler text when Psych Up is used.
- Implement Gen 6+ behavior to copy the target’s critical hit ratio.
- Preserves Psych Up ignoring other Protect-like effects while allowing Crafty Shield to block it.

## Issue(s) that this PR fixes
Fix #8949 and #8950

### CODE REVIEW

File: test/battle/move_effect/psych_up.c [hunk 1]
```diff
@@ -1,4 +1,119 @@
...
+SINGLE_BATTLE_TEST("Psych Up displays the correct battlers when used by the player")
+{
+    GIVEN {
+        PLAYER(SPECIES_TORNADUS) { Speed(66); }
+        OPPONENT(SPECIES_LANDORUS) { Speed(99); }
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_SWORDS_DANCE); MOVE(player, MOVE_CELEBRATE); }
+        TURN { MOVE(player, MOVE_PSYCH_UP); MOVE(opponent, MOVE_CELEBRATE); }
+    } SCENE {
+        MESSAGE("The opposing Landorus used Swords Dance!");
```
Comment (AlexOn1ine) [inline test/battle/move_effect/psych_up.c]: instead of the message could you use the anim check?  Also swords dance assums

File: test/battle/move_effect/psych_up.c [hunk 2]
```diff
@@ -1,4 +1,119 @@
...
+SINGLE_BATTLE_TEST("Psych Up displays the correct battlers when used by the opponent")
+{
+    GIVEN {
+        PLAYER(SPECIES_TORNADUS) { Speed(66); }
+        OPPONENT(SPECIES_LANDORUS) { Speed(99); }
+    } WHEN {
+        TURN { MOVE(player, MOVE_SWORDS_DANCE); MOVE(opponent, MOVE_CELEBRATE); }
+        TURN { MOVE(opponent, MOVE_PSYCH_UP); MOVE(player, MOVE_CELEBRATE); }
+    } SCENE {
+        MESSAGE("Tornadus used Swords Dance!");
```
Comment (AlexOn1ine) [inline test/battle/move_effect/psych_up.c]: also here
