### PR TITLE
Fixes ate type being ignored after checking summary screen

### LINKED ISSUE #6875: Move type changing abilities acquired with ability changing moves stops working after checking the mon summary
### Description

Example showing Tackle with Galvanize not doing super effective damage vs. a Water type and failing vs a Ghost type.
https://github.com/user-attachments/assets/4b2ebe2d-d702-41fe-8cfa-456ef395bd2d

Example showing Covet with Galvanize failing vs a Ghost type, and working when not checking the summary
https://discord.com/channels/419213663107416084/774393519569502268/1372865052809363549

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

a086d5f592a944fb97e6deb044cf67180e8f248d

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6875

I found an other bug but since it is just a visual issue I'm not really keen on fixing it. 

> // Bug: in battle, this only shows the dynamic type of battler in position 0

### CODE REVIEW

File: src/pokemon_summary_screen.c [hunk 1]
```diff
@@ -4305,8 +4305,12 @@ static void SetMoveTypeIcons(void)
         if (summary->moves[i] != MOVE_NONE)
         {
             type = GetMoveType(summary->moves[i]);
-            if (P_SHOW_DYNAMIC_TYPES)
-                type = CheckDynamicMoveType(mon, summary->moves[i], 0);
+            if (TRUE)
```
Comment (Bassoonian) [inline src/pokemon_summary_screen.c:4308]: Testing leftover?

File: src/pokemon_summary_screen.c [hunk 2]
```diff
@@ -4334,8 +4338,11 @@ static void SetNewMoveTypeIcon(void)
     u32 type = GetMoveType(sMonSummaryScreen->newMove);
     struct Pokemon *mon = &sMonSummaryScreen->currentMon;
 
-    if (P_SHOW_DYNAMIC_TYPES)
-        type = CheckDynamicMoveType(mon, sMonSummaryScreen->newMove, 0);
+    if (TRUE)
```
Comment (Bassoonian) [inline src/pokemon_summary_screen.c:4341]: Testing leftover?

File: src/pokemon_summary_screen.c (hunk 1 above)
Comment (AlexOn1ine) [inline src/pokemon_summary_screen.c:4308]:
```suggestion
            if (P_SHOW_DYNAMIC_TYPES)
```

**Comment by AlexOn1ine** [comment]
ready for re-review

File: src/battle_main.c [hunk 3]
```diff
@@ -5814,23 +5813,17 @@ bool32 TrySetAteType(u32 move, u32 battlerAtk, u32 attackerAbility)
...
 // Returns TYPE_NONE if type doesn't change.
-// NULL can be passed to ateBoost to avoid applying ate-ability boosts when opening the summary screen in-battle.
-u32 GetDynamicMoveType(struct Pokemon *mon, u32 move, u32 battler, u8 *ateBoost)
+u32 GetDynamicMoveType(struct Pokemon *mon, u32 move, u32 battler, enum MonState state)
 {
     u32 moveType = GetMoveType(move);
     u32 moveEffect = GetMoveEffect(move);
     u32 species, heldItem, holdEffect, ability, type1, type2, type3;
-    bool32 monInBattle = gMain.inBattle && gPartyMenu.menuType != PARTY_MENU_TYPE_IN_BATTLE;
+    bool32 monInBattle = state == MON_IN_BATTLE || state == MON_SUMMARY_SCREEN;
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply src/battle_main.c:5825]: the summary screen check is also in battle, it is just an alternative
```
    MON_SUMMARY_SCREEN, // MON_IN_BATTLE alternative To avoid setting setting the ate type global in the summary screen
```
Should I rename it?

**Review by hedara90 — APPROVED** [review]
