### PR TITLE
Fix Ion Deluge interaction with VoltAbsorb/LightRod

### LINKED ISSUE #3683: Ion Deluge triggers the users Lightning Rod/Volt Absorb
### Description

When a mon whose ability is Lightning Rod or Volt Absorb uses ion deluge their ability will suck in the move preventing it from activating.

For example if a volt absorb Lanturn uses ion deluge it will heal 25%.
What should happen is the ion deluge effect should be applied to the field that turn and all normal moves used after it will become electric type moves.

### Version

1.6.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

thelastmudkip

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3683

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -8324,7 +8289,7 @@ static bool32 IsAbilityAbsorbAffected(void)
     else
         moveType = gBattleMoves[gCurrentMove].type;
 
-    if (moveType == TYPE_ELECTRIC && GetBattlerAbility(gBattlerTarget) == ABILITY_VOLT_ABSORB)
+    if (moveType == TYPE_ELECTRIC && GetBattlerAbility(gBattlerTarget) == ability && gBattleMoves[gCurrentMove].effect != EFFECT_ION_DELUGE)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:8292]: Maybe target `MOVE_TARGET_ALL_BATTLERS` would be better instead of the effect so that it applies to all future moves with a similar effect?

Comment (DizzyEggg) [reply src/battle_script_commands.c:8292]: You're absolutely right, this also works for Electric Terrain which my fix didn't include.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Tests fail. I guess it's because it also needs to check for type?

Comment (DizzyEggg) [reply src/battle_script_commands.c]: Alright, should be good now

**Review by AlexOn1ine — APPROVED** [review]
