### PR TITLE
Adjustments for Eject Items / Mirror Herb / White Herb

### LINKED ISSUE #9499: Red Card and Eject Button should both activate if possible
### Description

Currently, only the fastest valid Red Card/Eject Button user activates the item, when it should pick the fastest which has one of the items, then the fastest that has the other item.

### Reproduction Steps

.

### Images / Video

_No response_

### Version

1.15.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Title 

Fixes #9499

### CODE REVIEW

File: src/battle_move_resolution.c [hunk 1]
```diff
@@ -3440,67 +3446,38 @@ static bool32 TryRedCard(enum BattlerId battlerAtk, enum BattlerId redCardBattle
...
     gLastUsedItem = gBattleMons[ejectButtonBattler].item;
     gBattleStruct->battlerState[ejectButtonBattler].usedEjectItem = TRUE;
     gSpecialStatuses[ejectButtonBattler].queuedSwitch = QUEUED_SWITCH_OPEN_PARTY_SCREEN;
-    BattleScriptCall(BattleScript_EjectItemActivates);
+    BattleScriptCall(BattleScript_EjectButtonActivates);
     gAiLogicData->ejectButtonSwitch = TRUE;
     return TRUE;
 }
 
 static enum MoveEndResult MoveEndCardButton(void)
```
Comment (AlexOn1ine) [inline src/battle_move_resolution.c:3461]: I'm not sure if those are still handled in one block (so based on speed for both items) or split into 2 moveend

Comment (PhallenTree) [reply src/battle_move_resolution.c:3461]: There are tests in the Battle Mechanics thread which show that this is how it's handled in SV. On a side note, I've figured out a good way to fix #9499 (on upcoming)

File: include/battle.h [hunk 2]
```diff
@@ -650,7 +650,7 @@ struct BattleStruct
     struct LostItem itemLost[MAX_BATTLE_TRAINERS][PARTY_SIZE];  // Pokemon that had items consumed or stolen (two bytes per party member per side)
     u8 blunderPolicy:1; // should blunder policy activate
     u8 swapDamageCategory:1; // Photon Geyser, Shell Side Arm, Light That Burns the Sky
-    u8 unused2:1;
+    u8 redCardActivated :1;
```
Comment (PhallenTree) [inline include/battle.h:652]:
```suggestion
    u8 redCardActivated:1;
```

File: src/battle_move_resolution.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_move_resolution.c:3461]: Isn't this what this pr already does?

They will both activate in the same step based on speed.

File: src/battle_move_resolution.c [hunk 3]
```diff
@@ -3458,49 +3464,21 @@ static bool32 TryEjectButton(enum BattlerId battlerAtk, u32 ejectButtonBattler)
...
-        else if (ejectButtonBattlers & 1u << battler && TryEjectButton(gBattlerAttacker, battler))
-            result = MOVEEND_RESULT_RUN_SCRIPT;
-        else
-            continue;
+        if (TryRedCard(gBattlerAttacker, battler, gCurrentMove))
+            return MOVEEND_RESULT_RUN_SCRIPT;
 
-        break;
+        if (TryEjectButton(gBattlerAttacker, battler))
+            return MOVEEND_RESULT_RUN_SCRIPT;
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Should still keep
```
if (battler == gBattlerAttacker)
   continue;
```

File: src/battle_move_resolution.c (hunk 1 above)
Comment (PhallenTree) [reply src/battle_move_resolution.c:3461]: Upon looking at the code, I'm not sure why the corresponding Known Failing test isn't passing

Comment (AlexOn1ine) [reply src/battle_move_resolution.c:3461]: will investigate

Comment (PhallenTree) [reply src/battle_move_resolution.c:3461]: The test is "Eject Button will activate before Red Card if holder is faster"

Comment (AlexOn1ine) [reply src/battle_move_resolution.c:3461]:
```diff
        PLAYER(SPECIES_WOBBUFFET) { Speed(20); }
        PLAYER(SPECIES_WOBBUFFET) { Speed(10); }
+        PLAYER(SPECIES_WOBBUFFET) { Speed(5); };
```
Started looking into `CanBattlerSwitch` and thought the function is broken lol. While I was rewriting it, I realized what is wrong.

**Comment by AlexOn1ine** [comment]
Ready for re-review.

I rewrote the function `CanBattlerSwitch` a bit.

File: src/battle_move_resolution.c [hunk 4]
```diff
@@ -3458,49 +3464,24 @@ static bool32 TryEjectButton(enum BattlerId battlerAtk, u32 ejectButtonBattler)
...
-
-    enum BattlerId battlers[MAX_BATTLERS_COUNT] = {0, 1, 2, 3};
-    SortBattlersBySpeed(battlers, FALSE);
+        enum BattlerId battler = gMoveResolutionBattlersBySpeed[gBattleStruct->eventState.moveEndBattler++];
 
-    for (enum BattlerId battlerDef = 0; battlerDef < gBattlersCount; battlerDef++)
-    {
-        enum BattlerId battler = battlers[battlerDef];
+        if (battler == gBattlerAttacker)
+           continue;
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
        if (battler == gBattlerAttacker)
            continue;
```

File: src/battle_move_resolution.c [hunk 5]
```diff
@@ -3417,11 +3421,14 @@ static bool32 HasAnyBattlerQueuedSwitch(void)
 static bool32 TryRedCard(enum BattlerId battlerAtk, enum BattlerId redCardBattler, enum Move move)
 {
     if (!IsBattlerAlive(redCardBattler)
+     || gBattleStruct->redCardActivated
      || !IsBattlerTurnDamaged(redCardBattler, EXCLUDING_SUBSTITUTES)
      || DoesSubstituteBlockMove(battlerAtk, redCardBattler, move)
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Is this condition still necessary? Doesn't the above one handle it already?
Should also make the move argument obsolete.

File: src/battle_move_resolution.c [hunk 6]
```diff
@@ -3762,72 +3713,55 @@ static enum MoveEndResult MoveEndThirdMoveBlock(void)
...
+        case HOLD_EFFECT_WHITE_HERB:
+            if (ItemBattleEffects(battler, 0, GetBattlerHoldEffect(battler), IsWhiteHerbActivation))
+                return MOVEEND_RESULT_RUN_SCRIPT;
+        case HOLD_EFFECT_EJECT_PACK:
+            if (TryEjectPack(gBattlerAttacker, battler))
+                return MOVEEND_RESULT_RUN_SCRIPT;
+        case HOLD_EFFECT_MIRROR_HERB:
+            if (ItemBattleEffects(battler, 0, GetBattlerHoldEffect(battler), IsMirrorHerbActivation))
+                return MOVEEND_RESULT_RUN_SCRIPT;
+        default:
```
Comment (PhallenTree) [inline src/battle_move_resolution.c:3751]:
```suggestion
        case HOLD_EFFECT_WHITE_HERB:
            if (ItemBattleEffects(battler, 0, holdEffect, IsWhiteHerbActivation))
                return MOVEEND_RESULT_RUN_SCRIPT;
            break;
        case HOLD_EFFECT_EJECT_PACK:
            if (TryEjectPack(gBattlerAttacker, battler))
                return MOVEEND_RESULT_RUN_SCRIPT;
            break;
        case HOLD_EFFECT_MIRROR_HERB:
            if (ItemBattleEffects(battler, 0, holdEffect, IsMirrorHerbActivation))
                return MOVEEND_RESULT_RUN_SCRIPT;
            break;
        default:
```
Both `break`s and redetermining hold effect.

File: src/battle_move_resolution.c [hunk 7]
```diff
@@ -3762,72 +3713,55 @@ static enum MoveEndResult MoveEndThirdMoveBlock(void)
...
-     && GetBattlerHoldEffect(battlerDef) == HOLD_EFFECT_EJECT_PACK
-     && IsBattlerAlive(battlerDef)
-     && CanBattlerSwitch(battlerDef)
-     && !gProtectStructs[battlerDef].disableEjectPack
-     && !(moveEffect == EFFECT_PARTING_SHOT && CanBattlerSwitch(battlerAtk)))
-        return TRUE;
-    return FALSE;
+    if (!gBattleMons[ejectPackBattler].volatiles.tryEjectPack
+     || HasAnyBattlerQueuedSwitch()
+     || GetBattlerHoldEffect(ejectPackBattler) != HOLD_EFFECT_EJECT_PACK
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: No need to check this anymore

File: src/battle_move_resolution.c [hunk 8]
```diff
@@ -3762,72 +3713,55 @@ static enum MoveEndResult MoveEndThirdMoveBlock(void)
...
+     || !IsBattlerAlive(ejectPackBattler)
+     || !CanBattlerSwitch(ejectPackBattler)
+     || gProtectStructs[ejectPackBattler].disableEjectPack
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: `disableEjectPack` can probably be removed, the queued switches PR already catches the specific case that this is meant to prevent.

File: src/battle_move_resolution.c (hunk 5 above)
Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: Oh ye no, this is fully redundant.

**Comment by AlexOn1ine** [comment]
ready for re-review.

File: src/battle_move_resolution.c [hunk 9]
```diff
@@ -3421,14 +3421,13 @@ static bool32 HasAnyBattlerQueuedSwitch(void)
 static bool32 TryRedCard(enum BattlerId battlerAtk, enum BattlerId redCardBattler, enum Move move)
 {
     if (!IsBattlerAlive(redCardBattler)
-     || gBattleStruct->redCardActivated
+     || gBattleStruct->battlerState[battlerAtk].redCardSwitched
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: This means that if Red Card fails due to Guard Dog, Dynamax (maybe also Ingrain and Suction Cups) it will continue activating other battlers' Red Cards

Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: Then I need to keep the old flag so 2 red cards are prevented on a spread move.

Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: also wouldn't the item be removed on guard dog, dynamax and suction cups?

Comment (PhallenTree) [reply src/battle_move_resolution.c]: Yes, Red Card would be removed and no switch would happen.

**Comment by AlexOn1ine** [comment]
revert the red card flag check change

**Comment by AlexOn1ine** [comment]
Looks like we need to use raw speed here https://github.com/rh-hideout/pokeemerald-expansion/pull/9818#issuecomment-4285567322

File: src/battle_move_resolution.c [hunk 10]
```diff
@@ -3421,14 +3421,13 @@ static bool32 HasAnyBattlerQueuedSwitch(void)
...
      || !IsBattlerTurnDamaged(redCardBattler, EXCLUDING_SUBSTITUTES)
      || DoesSubstituteBlockMove(battlerAtk, redCardBattler, move)
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Didn't remove this

File: src/battle_move_resolution.c
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Alignment

**Comment by PhallenTree** [comment]
> Looks like we need to use raw speed here [#9818 (comment)](https://github.com/rh-hideout/pokeemerald-expansion/pull/9818#issuecomment-4285567322)

Yea, feel free to do it if you want (there are probably a lot more cases that also currently order battlers with modifiers, but shouldn't or vice-versa)

File: src/battle_move_resolution.c (hunk 10 above)
Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: Since a single state is used for both Red Card and Eject Button we will always loop over all battlers. It's not an issue for Eject Button since we can use `HasAnyBattlerQueuedSwitch` to prevent other eject packs from activating.

I'm not sure how you would handle it without a flag. (Or at least without other changes. This is were I had the idea to set `gCurrentMove` to none if the user switched out so you could just check if it's none)

Comment (PhallenTree) [reply src/battle_move_resolution.c]: I meant DoesSubstituteBlockMove (which should be covered by IsBattlerTurnDamaged)

Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: oh oops, sorry.

**Comment by AlexOn1ine** [comment]
> > Looks like we need to use raw speed here [#9818 (comment)](https://github.com/rh-hideout/pokeemerald-expansion/pull/9818#issuecomment-4285567322)
> 
> Yea, feel free to do it if you want (there are probably a lot more cases that also currently order battlers with modifiers, but shouldn't or vice-versa)

Renamed `gMoveResolutionBattlersBySpeed` to `gBattlersByRawSpeed` and used that one also for magic bounce / magic coat.

**Review by PhallenTree — APPROVED** [review]
