### PR TITLE
Fixed curse + Protean interaction

### LINKED ISSUE #5662: Incorrect Protean Curse Behaviour
### Description

In the actual games, when a non ghost type Pokemon with the ability Protean uses Curse, the user afflicts themselves with the Curse condition. This is because the user first selects a target (itself), then changes its type, then activates the Curse that corresponds to its type. The end result is that a non ghost type Pokemon's curse with Protean will take the 50% HP Curse Damage AND afflict itself with Curse. This behavior is documented here: https://www.youtube.com/watch?v=nRfI3J0kI2o

This behavior is not currently implemented in pokeemerald-expansion and the aforementioned Curse User will instead get a +1 Atk, +1 Def boost, -1 Speed instead.

### Version

1.9.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Fixed incorrect Curse effect when used by Protean mons.
Added tests for Curse+Protean and Trick-or-Treat+Curse

## Issue(s) that this PR fixes

Fixes #5662 

## **Discord contact info**

hedara

### CODE REVIEW

File: test/battle/move_effect/curse.c [hunk 1]
```diff
@@ -34,3 +34,36 @@ SINGLE_BATTLE_TEST("Curse cuts the user's HP in half when used by Ghost-types")
...
+        PLAYER(SPECIES_KECLEON) { Ability(ABILITY_PROTEAN); }
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(player, MOVE_CURSE, target: player); }
+    } SCENE {
+        s32 playerMaxHP = GetMonData(&PLAYER_PARTY[0], MON_DATA_MAX_HP);
+        ABILITY_POPUP(player, ABILITY_PROTEAN);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_CURSE, player);
+        HP_BAR(player, damage: playerMaxHP / 2);
+        HP_BAR(player, damage: playerMaxHP / 4);
```
Comment (AlexOn1ine) [inline test/battle/move_effect/curse.c:50]: why is the player damaged twice?

Comment (hedara90) [reply test/battle/move_effect/curse.c:50]: End of turn Curse damage

Comment (AlexOn1ine) [reply test/battle/move_effect/curse.c:50]: why is it inflicted to the player and not opponent?
