### PR TITLE
Fixes Lock On

### LINKED ISSUE #9280: In Gen 5+, a battler can be affected by Lock-On from multiple targets
### Description

https://bulbapedia.bulbagarden.net/wiki/Lock-On_(move)
> Starting in [Generation V](https://bulbapedia.bulbagarden.net/wiki/Generation_V), multiple Pokémon can have the effect of Lock-On or Mind Reader on the same target.

script
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/data/battle_scripts_1.s#L2998-L3002

command
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/src/battle_script_commands.c#L8826-L8832

Only one attacker can have a lock-on status on a defender at a time (can't have multiple battlers assigned to battlerWithSureHit at the same time)
https://github.com/rh-hideout/pokeemerald-expansion/blob/3ea6bd18721ff53b52bd2d2fe2b493156388335f/src/battle_util.c#L10258-L10269

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #9280 and supersedes #9441

Handles Gen5+ only

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -8897,9 +8897,17 @@ static void Cmd_settypetorandomresistance(void)
...
-    gBattleMons[gBattlerTarget].volatiles.lockOn = 2;
-    gBattleMons[gBattlerTarget].volatiles.battlerWithSureHit = gBattlerAttacker;
-    gBattlescriptCurrInstr = cmd->nextInstr;
+
+    if (gBattleMons[gBattlerAttacker].volatiles.battlerWithSureHit == 0)
+    {
+        gBattleMons[gBattlerAttacker].volatiles.lockOn = 2;
+        gBattleMons[gBattlerAttacker].volatiles.battlerWithSureHit |= gBattlerTarget;
+        gBattlescriptCurrInstr = cmd->nextInstr;
+    }
```
Comment (PhallenTree) [inline src/battle_script_commands.c:8906]:
```suggestion
    if (gBattleMons[gBattlerAttacker].volatiles.lockOn == 0)
    {
        gBattleMons[gBattlerAttacker].volatiles.lockOn = 2;
        gBattleMons[gBattlerAttacker].volatiles.battlerWithSureHit = gBattlerTarget;
        gBattlescriptCurrInstr = cmd->nextInstr;
    }
```

File: src/battle_ai_main.c [hunk 2]
```diff
@@ -2321,7 +2321,7 @@ static s32 AI_CheckBadMove(enum BattlerId battlerAtk, enum BattlerId battlerDef,
         //TODO
         break;
     case EFFECT_LOCK_ON:
-        if (gBattleMons[battlerDef].volatiles.lockOn
+        if (gBattleMons[battlerAtk].volatiles.battlerWithSureHit & battlerDef
```
Comment (PhallenTree) [inline src/battle_ai_main.c]:
```suggestion
        if ((gBattleMons[battlerAtk].lockOn && gBattleMons[battlerAtk].volatiles.battlerWithSureHit & battlerDef)
```
The same for all other checks of this type.

File: src/battle_ai_util.c [hunk 3]
```diff
@@ -2177,10 +2177,8 @@ bool32 ShouldTryOHKO(enum BattlerId battlerAtk, enum BattlerId battlerDef, enum
     if (!DoesBattlerIgnoreAbilityChecks(battlerAtk, atkAbility, move) && defAbility == ABILITY_STURDY)
         return FALSE;
 
-    if (((gBattleMons[battlerDef].volatiles.lockOn
-        && gBattleMons[battlerDef].volatiles.battlerWithSureHit == battlerAtk)
-        || atkAbility == ABILITY_NO_GUARD || defAbility == ABILITY_NO_GUARD)
-        && gBattleMons[battlerAtk].level >= gBattleMons[battlerDef].level)
+    bool32 sureHit = (gBattleMons[battlerDef].volatiles.battlerWithSureHit & battlerAtk) || atkAbility == ABILITY_NO_GUARD || defAbility == ABILITY_NO_GUARD;
```
Comment (PhallenTree) [inline src/battle_ai_util.c]:
```suggestion
    bool32 sureHit = (gBattleMons[battlerAtk].lockOn && gBattleMons[battlerAtk].volatiles.battlerWithSureHit == battlerDef) || atkAbility == ABILITY_NO_GUARD || defAbility == ABILITY_NO_GUARD;
```
This one had the wrong order (battlerAtk, battlerDef)

**Comment by AlexOn1ine** [comment]
Sorry, I messed up. It has been a minute since I worked with a bitmask. It should obviously be 
```
gBattleMons[gBattlerAttacker].volatiles.battlerWithSureHit |= 1u << gBattlerTarget;
```
and then check
```
gBattleMons[battlerAtk].volatiles.battlerWithSureHit & 1u << battlerDef;
```

> I don't understand why you're trying make it like a bitfield


I think a `bitmask` is overall cleaner because 
1. you aren't dependent on the timer. You can just clear the `sureHit` value which means we don't have to care about cleaning it up when the user leaves the field 
2. because you only need to check one value instead of two. To be fair if implemented correctly you would only need the timer since you can only lock in onto one mom so this doesn't really count. I still overall think this is still better even without this argument

>  (so that a mon can Lock On to multiple battlers, which isn't how it works in Gen 5+), reminder that when the target is battler 0, battlerWithSureHit is set to 0 so it's not a good idea to check that.

```
gBattleMons[gBattlerAttacker].volatiles.battlerWithSureHit == 0
```
If the implementation was done correctly this would check if any bit is flipped to handle the possible failure

/edit: The alternative would be to do `battler + 1` and `battler - 1`. I prefer the `bitmask` but would be fine with this one as well. Though I think both are superior to the previous check. I can also just revert and check for the timer. Not really married to any implementation in this case.

**Comment by PhallenTree** [comment]
> I think a `bitmask` is overall cleaner because
> 
> 1. you aren't dependent on the timer. You can just clear the `sureHit` value which means we don't have to care about cleaning it up when the user leaves the field
> 2. because you only need to check one value instead of two. To be fair if implemented correctly you would only need the timer since you can only lock in onto one mom so this doesn't really count. I still overall think this is still better even without this argument

Feel free to use it or the +1 method.

**Comment by AlexOn1ine** [comment]
Ready for review again. An additional test was added to make sure it doesn't break for battler 0
```
Lock-On skips the accuracy check for 2 turns (Opponent uses Lock-On)
```
