### PR TITLE
Fix Smack Down anim + move anim tests

### LINKED ISSUE #4754: If the Pokemon don't obedience sometimes move background scrolling won't end
### Description

not sure the cause of the trigger

### Version

1.8.4 (Latest release)

### Upcoming/master Version

upcoming

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #4754

Turns out the issue wasn't related to obedience, but to how many times the Smack Down move was used. I was able to get the issue to happen exactly after 13th use.

I also added a way to check the move animations in tests(that is if they crash/softlock) with `gBattleTestRunnerState->forceMoveAnim = TRUE;`
With that we should be able to check all of the move animations now(with appropriate tests).

### CODE REVIEW

File: test/battle/move_animations/smack_down.c [hunk 1]
```diff
@@ -0,0 +1,25 @@
+#include "global.h"
+#include "test/battle.h"
+
+SINGLE_BATTLE_TEST("Move Animation Test: Smack Down works when used 15 times in a row")
+{
+    gBattleTestRunnerState->forceMoveAnim = TRUE;
```
Comment (AsparagusEduardo) [inline test/battle/move_animations/smack_down.c:6]: I think it would probably be good to add a macro for this. `FORCE_MOVE_ANIM` maybe?

File: test/battle/move_animations/smack_down.c [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+        {
+            TURN { MOVE(player, MOVE_SMACK_DOWN); MOVE(opponent, MOVE_HELPING_HAND); } // Helping Hand, so there's no anim on the opponent's side.
+        }
+    } SCENE {
+        for (j = 0; j < nTurns; j++)
+        {
+            ANIMATION(ANIM_TYPE_MOVE, MOVE_SMACK_DOWN, player);
+        }
+    } THEN {
+        gBattleTestRunnerState->forceMoveAnim = FALSE;
```
Comment (AsparagusEduardo) [inline test/battle/move_animations/smack_down.c:23]: And to complement the potential macro above, this could automatically be set to `FALSE` at the end of the test, so that you only need to add a single line per test that you want to force move animations.

Comment (DizzyEggg) [reply test/battle/move_animations/smack_down.c:23]: Hmm, not sure if that would be feasible. I can do `FORCE_MOVE_ANIM `, but without putting the whole `THEN` there

Comment (AsparagusEduardo) [reply test/battle/move_animations/smack_down.c]: Better than how it was earlier at least ^^;

**Review by AsparagusEduardo — APPROVED** [review]
