### PR TITLE
Fixed multi battle forced switches

### LINKED ISSUE #5842: Forced switchout moves causes issues in multi-battles
### Description

If the opponent uses forced switchout moves in a multi battle, the player side party might get the order messed up where the player/partner mons appear in the wrong slots of the party screen.
This causes a hardlock when all mons on the player side are knocked out and the player can't select their mon that's on the partner side of the party screen.
Screenshot_45
Steven multi battle, Metang belongs to Steven, Bulbasaur to player.
Screenshot_44
Custom battle, Swellow belongs to the trainer.
Discovered by Shahar.

### Version

1.10.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by hedara90**
## Description

The fix from upstream was not applicable to the expansion codebase, so I had to redo it from scratch.
The issue laid in `SwitchPartyOrderInGameMulti` using `i` instead of the actual value from `gBattleStruct->monToSwitchIntoId` like it was supposed to.
Also moved the declaration of `i` to the loop where it's used.

## Issue(s) that this PR fixes

Fixes #5842 

## **Discord contact info**

hedara

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -12204,12 +12203,12 @@ static void Cmd_forcerandomswitch(void)
                 || (gBattleTypeFlags & BATTLE_TYPE_RECORDED_LINK && gBattleTypeFlags & BATTLE_TYPE_BATTLE_TOWER)
                 || (gBattleTypeFlags & BATTLE_TYPE_RECORDED_LINK && gBattleTypeFlags & BATTLE_TYPE_MULTI))
             {
-                SwitchPartyOrderLinkMulti(gBattlerTarget, i, 0);
-                SwitchPartyOrderLinkMulti(BATTLE_PARTNER(gBattlerTarget), i, 1);
+                SwitchPartyOrderLinkMulti(gBattlerTarget, *(gBattleStruct->monToSwitchIntoId + gBattlerTarget), 0);
+                SwitchPartyOrderLinkMulti(BATTLE_PARTNER(gBattlerTarget), *(gBattleStruct->monToSwitchIntoId + gBattlerTarget), 1);
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:12207]:
```suggestion
                SwitchPartyOrderLinkMulti(gBattlerTarget, gBattleStruct->monToSwitchIntoId[gBattlerTarget], 0);
                SwitchPartyOrderLinkMulti(BATTLE_PARTNER(gBattlerTarget), gBattleStruct->monToSwitchIntoId[gBattlerTarget], 1);
```

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -12204,12 +12203,12 @@ static void Cmd_forcerandomswitch(void)
...
             }
 
             if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER)
-                SwitchPartyOrderInGameMulti(gBattlerTarget, i);
+                SwitchPartyOrderInGameMulti(gBattlerTarget, *(gBattleStruct->monToSwitchIntoId + gBattlerTarget));
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:12211]:
```suggestion
                SwitchPartyOrderInGameMulti(gBattlerTarget, gBattleStruct->monToSwitchIntoId[gBattlerTarget]);
```

**Review by AlexOn1ine — COMMENTED** [review]
for readability

**Comment by hedara90** [comment]
Suggestions applied

**Review by Bassoonian — APPROVED** [review]
