### PR TITLE
Misc battle engine changes

### LINKED ISSUE #8815: jumpiflastuseditemberry refers to gLastUsedItem instead of gBattleStruct->flingItem
### Description

Fling will execute `setlastuseditem`
https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/data/battle_scripts_1.s#L634-L657

This preserves the flung item in a variable, as well as sets gLastUsedItem so that the item can be referenced in STRINGID_PKMNFLUNG
https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/src/battle_script_commands.c#L14134-L14140

However, jumpiflastuseditemberry refers to gLastUsedItem
https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/src/battle_script_commands.c#L15581-L15588

This poses a problem as gLastUsedItem can be modified in some other commands beforehand
https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/data/battle_scripts_1.s#L642-L656

(not comprehensive list)
https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/src/battle_script_commands.c#L1800-L1819

https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/src/battle_script_commands.c#L2422-L2427
https://github.com/rh-hideout/pokeemerald-expansion/blob/2183fa748a641d157019456daf35a9f4bcb2195e/src/battle_script_commands.c#L2449-L2456

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #8856: Gen 6+ Nature Power effect is unimplemented
### Description

From Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Nature_Power_(move)#Generation_VI
> Generation VI
Nature Power now targets an adjacent Pokémon rather than the user (even if the move it would turn into affects multiple Pokémon). This allows single-target moves called by Nature Power to target an ally, which was not previously possible.

There's no config for that here
https://github.com/rh-hideout/pokeemerald-expansion/blob/1c4099f9c396bdbb90ea348fd5d13fb9d81d0850/src/data/moves_info.h#L7219-L7230

I also checked CancelerCallSubmove to be sure, and I don't think there's any handling there
https://github.com/rh-hideout/pokeemerald-expansion/blob/1c4099f9c396bdbb90ea348fd5d13fb9d81d0850/src/battle_util.c#L2508-L2567

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

alex's move target failure PR #8696 (see commit hash)

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Closes #8856
Closes #8815

Also removed some redundant magnitude code and moved Shell Trap closer to where it should be (not sure if this is the exact timing). Will make it easier to refactor `MOVEEND_UPDATE_LAST_MOVES` which we might want to do potentially.

### CODE REVIEW

File: test/battle/move_effect/shell_trap.c [hunk 1]
```diff
@@ -279,3 +279,25 @@ DOUBLE_BATTLE_TEST("Shell Trap does not trigger when hit into Substitute")
         ANIMATION(ANIM_TYPE_MOVE, MOVE_SHELL_TRAP, playerLeft);
     }
 }
+
+DOUBLE_BATTLE_TEST("Tar Shot activates on both opposing Targets")
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/shell_trap.c]: Is this for tar shot or shell trap?

Comment (AlexOn1ine) [reply test/battle/move_effect/shell_trap.c]: fixed

**Comment by Bassoonian** [comment]
Not passing tests

**Comment by AlexOn1ine** [comment]
> Not passing tests

reverted last commit. needs more attention

**Review by Bassoonian — APPROVED** [review]
