### PR TITLE
Fixes Dancer triggering if the move's user didn't act

### LINKED ISSUE #4495: Dancer Ability Gets Proc-ed Through Flinches
### Description

GIF attached, description:
Double battle vs 2 oricorios, both with the ability Dancer.
Persian uses Fake Out into Fire-Oricorio.
Psychic-Oricorio uses Quiver Dance, Fire-Oricorio's Dancer _tries_ to proc, but text displays that he flinched (correct behavior, i think)
Fire-Oricorio selected Revelation Dance as move to use, but was flinched by Fake Out. Text displays that fire-oricorio flinched, but Psychic-Oricorio's Dancer procs and it uses Revelation Dance, even though Fire-Oricorio flinched (incorrect behavior, Psychic-Oricorio's Dancer should not have proc-ed).

I am not sure if similar things would happen for other things that would cause a Pokemons move to fail for a given reason (sleep, paralysis, disable, taunt, etc) but this is the behavior in the case of flinching.

dancerflinchbug

### Version

1.8.1

### Upcoming/master Version

_No response_

### Discord contact info

iriv24#8479

### PR DESCRIPTION
**Pull request by PhallenTree**
Fixes Dancer triggering if the original user of the move flinched, was paralyzed or frozen. Added tests for this and for checking if the order of Dancer triggering is correct (slowest to fastest).

## Issue(s) that this PR fixes
Fixes #4495 

## Feature(s) this PR does NOT handle:
I'm not sure if Dancer still triggers every time it should, specifically if there are cases where it should trigger but gHitmarker doesn't include HITMARKER_ATTACKSTRING_PRINTED

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -6260,7 +6260,16 @@ static void Cmd_moveend(void)
...
+                bool8 turnOnHitmarker = FALSE;
 
+                for (battler = 0; battler < MAX_BATTLERS_COUNT; battler++)
+                    if (gSpecialStatuses[battler].dancerUsedMove)
+                    {
+                        // in case a battler fails to act on a Dancer proc
+                        turnOnHitmarker = TRUE;
+                        break;
+                    }
+
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:6272]:
```suggestion
                for (battler = 0; battler < MAX_BATTLERS_COUNT; battler++)
                {
                    if (gSpecialStatuses[battler].dancerUsedMove)
                    {
                        // in case a battler fails to act on a Dancer proc
                        turnOnHitmarker = TRUE;
                        break;
                    }
                }
                
```

File: test/battle/ability/dancer.c [hunk 2]
```diff
@@ -53,3 +53,74 @@ DOUBLE_BATTLE_TEST("Dancer can copy Teeter Dance and confuse both opposing targe
...
+            ABILITY_POPUP(opponent, ABILITY_DANCER);
+            ANIMATION(ANIM_TYPE_MOVE, MOVE_DRAGON_DANCE, opponent);
+        }
+    }
+}
+
+DOUBLE_BATTLE_TEST("Dancer still triggers if another dancer flinches")
+{
+    GIVEN {
+        ASSUME(gMovesInfo[MOVE_DRAGON_DANCE].danceMove == TRUE);
```
Comment (AlexOn1ine) [inline test/battle/ability/dancer.c:103]:
```suggestion
        ASSUME(MoveHasAdditionalEffectWithChance(MOVE_FAKE_OUT, MOVE_EFFECT_FLINCH, 100));
        ASSUME(gMovesInfo[MOVE_DRAGON_DANCE].danceMove == TRUE);
```

File: test/battle/ability/dancer.c [hunk 3]
```diff
@@ -53,3 +53,74 @@ DOUBLE_BATTLE_TEST("Dancer can copy Teeter Dance and confuse both opposing targe
...
+        ABILITY_POPUP(opponentLeft, ABILITY_DANCER);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_DRAGON_DANCE, opponentLeft);
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, opponentLeft);
+    }
+}
+
+SINGLE_BATTLE_TEST("Dancer doesn't trigger if the original user flinches")
+{
+    GIVEN {
+        ASSUME(gMovesInfo[MOVE_DRAGON_DANCE].danceMove == TRUE);
```
Comment (AlexOn1ine) [inline test/battle/ability/dancer.c:85]:
```suggestion
        ASSUME(MoveHasAdditionalEffectWithChance(MOVE_FAKE_OUT, MOVE_EFFECT_FLINCH, 100));
        ASSUME(gMovesInfo[MOVE_DRAGON_DANCE].danceMove == TRUE);
```

**Review by AlexOn1ine — COMMENTED** [review]
We are trying to use u32's for functions when we add new code.

**Review by AlexOn1ine — APPROVED** [review]
