### PR TITLE
Fix incorrect "last to move" check for Analytic, Snatch, and Magic Coat

### LINKED ISSUE #8512: Incorrect Analytic check
### Description

Analytic is currently checks if the attacker's action occurs in position `gBattlersCount - 1` (which would generally be the last), but this fails to account for:

- Instruct (which if not used last, as long as the target of Instruct acts last, will boost the move used);
- Empty slots, for example in 1v2/2v1 battles, or when a battler faints and the trainer has no replacement for that battler. (Snatch and Magic Coat also have this problem on their failure conditions)

```
    case ABILITY_ANALYTIC:
        if (GetBattlerTurnOrderNum(battlerAtk) == gBattlersCount - 1 && move != MOVE_FUTURE_SIGHT && move != MOVE_DOOM_DESIRE)
           modifier = uq4_12_multiply(modifier, UQ_4_12(1.3));
        break;
```

[jpwiki](https://wiki.xn--rckteqa2e.com/wiki/%E3%82%A2%E3%83%8A%E3%83%A9%E3%82%A4%E3%82%BA) additionally has the following interactions that are worth adding tests for:

> If a Pokémon with Analytic acts last in a turn in which Tatsugiri's turn is skipped due to the effect of Commander, the following applies:
> 1. At the start of that turn, if Tatsugiri chooses a move, but activates Commander before mon with Analytic acts, Analyze will activate if Tatsugiri was scheduled to act before Analytic. If it was scheduled to act after, it will not activate.
> 2. If you don't select a move at the start of the turn because Tatsugiri is already combined, Analytic will still boost even if the combination is broken by the time the mon with Analytic's action is performed. The speed relationship with Tatsugiri is not taken into account.

> If a Pokémon that was scheduled to act after Analytic faints and the Pokémon with Analytic ends up acting last, the boost doesn't occur until Generation 8. In Generation 9 , the boost occurs.

### Reproduction Steps

.

### Images / Video

_No response_

### Version

1.14.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by moostoet**
## Description

This PR fixes an issue where Analytic, Snatch, and Magic Coat incorrectly determine whether a battler is the "last to move" in a turn.

### The Problem

The previous implementation checked if a battler's action occurred at position `gBattlersCount - 1` (or `gCurrentTurnActionNumber == gBattlersCount - 1`). This approach fails to account for:

1. **Empty slots in doubles** - When a Pokemon faints and has no replacement, its slot becomes empty but `gBattlersCount` remains unchanged
2. **1v2 or 2v1 battles** - Similar issue where not all slots are filled
3. **Non-move actions** - Actions like switching or using items shouldn't count when determining "last to move"

For example, in a double battle where one Pokemon faints:
- 4 battler slots exist (`gBattlersCount = 4`)
- Only 3 Pokemon remain active
- A Pokemon at turn order position 2 would incorrectly think it's not last (since 2 != 3)
- But if position 3 is an empty/absent slot, position 2 IS actually last to move

### The Solution

Added a new helper function `IsLastMonToMove(u32 battler)` in `src/battle_script_commands.c` that properly determines if a battler is last to move by:

1. Getting the battler's position in turn order
2. Iterating through all subsequent positions
3. Skipping battlers marked as absent (`gAbsentBattlerFlags`)
4. Checking if any remaining battler will use a move (`B_ACTION_USE_MOVE`)
5. Returning `TRUE` only if no other battler after it will use a move

This function is now used by:
- **Analytic** ability (`src/battle_util.c`)
- **Magic Coat** (`src/battle_script_commands.c`) - Fails if user moves last (nothing to reflect)
- **Snatch** (`src/battle_script_commands.c`) - Fails if user moves last (nothing to steal)
- **Protect-likes** (`src/battle_script_commands.c`) 

### Tests Added

- `test/battle/ability/analytic.c` - Two new double battle tests verifying Analytic correctly activates/doesn't activate with empty slots
- `test/battle/move_effect/snatch.c` - Tests for basic functionality, failure when last, and success with empty partner slot
- `test/battle/move_effect/magic_coat.c` - Tests for failure when last and success with empty partner slot
- `test/battle/move_effect/protect.c`

## Issue(s) that this PR fixes

Fixes #8512

## Discord contact info

viridian.

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -2848,6 +2848,26 @@ u32 GetBattlerTurnOrderNum(u32 battler)
...
 }
 
+// Returns TRUE if no other battler after this one in turn order will use a move
+bool32 IsLastMonToMove(u32 battler)
+{
+    u32 i;
+    u32 battlerTurnOrderNum = GetBattlerTurnOrderNum(battler);
+
+    if (battlerTurnOrderNum >= gBattlersCount)
+        return TRUE;
```
Comment (PhallenTree) [inline src/battle_script_commands.c]:
```suggestion
    if (battlerTurnOrderNum >= gBattlersCount - 1)
        return TRUE;
```

File: test/battle/ability/analytic.c [hunk 2]
```diff
@@ -20,9 +20,59 @@ SINGLE_BATTLE_TEST("Analytic increases the power of moves by 30% if it's the las
...
+DOUBLE_BATTLE_TEST("Analytic activates correctly with empty slot after fainting", s16 damage)
+{
+    u32 speed;
+
+    PARAMETRIZE { speed = 50; }
+    PARAMETRIZE { speed = 5; }
+
+    GIVEN {
+        PLAYER(SPECIES_MAGNEMITE) { Ability(ABILITY_ANALYTIC); Speed(speed); }
+        PLAYER(SPECIES_WYNAUT) { HP(1); Speed(25); }
```
Comment (PhallenTree) [inline test/battle/ability/analytic.c]:
```suggestion
        PLAYER(SPECIES_WYNAUT) { HP(1); Speed(1); }
```

File: test/battle/ability/analytic.c [hunk 3]
```diff
@@ -20,9 +20,59 @@ SINGLE_BATTLE_TEST("Analytic increases the power of moves by 30% if it's the las
...
+DOUBLE_BATTLE_TEST("Analytic does not activate when not moving last with empty slot", s16 damage)
+{
+    u32 speed;
+
+    PARAMETRIZE { speed = 50; }
+    PARAMETRIZE { speed = 15; }
+
+    GIVEN {
+        PLAYER(SPECIES_MAGNEMITE) { Ability(ABILITY_ANALYTIC); Speed(speed); }
+        PLAYER(SPECIES_WYNAUT) { HP(1); Speed(25); }
```
Comment (PhallenTree) [inline test/battle/ability/analytic.c]:
```suggestion
        PLAYER(SPECIES_WYNAUT) { HP(1); Speed(1); }
```

File: test/battle/move_effect/magic_coat.c [hunk 4]
```diff
@@ -33,6 +33,43 @@ SINGLE_BATTLE_TEST("Magic Coat prints the correct message when bouncing back a m
...
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_MAGIC_COAT); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponent);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_MAGIC_COAT, player);
+    }
+}
+
+DOUBLE_BATTLE_TEST("Magic Coat works when partner slot is empty after fainting")
```
Comment (PhallenTree) [inline test/battle/move_effect/magic_coat.c]: This test should probably instead check that it doesn't activate when the only "slower battler" is the fainted ally.

File: test/battle/move_effect/protect.c [hunk 5]
```diff
@@ -356,6 +356,42 @@ SINGLE_BATTLE_TEST("Protect: Multi-hit moves don't hit a protected target and fa
...
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_PROTECT); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponent);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_PROTECT, player);
+    }
+}
+
+DOUBLE_BATTLE_TEST("Protect works when partner slot is empty after fainting")
```
Comment (PhallenTree) [inline test/battle/move_effect/protect.c]: This test should probably instead check that it doesn't activate when the only "slower battler" is the fainted ally.

File: test/battle/move_effect/snatch.c [hunk 6]
```diff
@@ -1,4 +1,66 @@
...
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_SNATCH); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_CELEBRATE, opponent);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_SNATCH, player);
+    }
+}
+
+DOUBLE_BATTLE_TEST("Snatch works when partner slot is empty after fainting")
```
Comment (PhallenTree) [inline test/battle/move_effect/snatch.c]: This test should probably instead check that it doesn't activate when the only "slower battler" is the fainted ally.

Comment (moostoet) [reply test/battle/move_effect/snatch.c]: Resolved

**Comment by moostoet** [comment]
@PhallenTree Resolved the outstanding issues, please feel free to re-review

File: test/battle/ability/analytic.c [hunk 7]
```diff
@@ -20,9 +20,59 @@ SINGLE_BATTLE_TEST("Analytic increases the power of moves by 30% if it's the las
...
+    PARAMETRIZE { speed = 50; }
+    PARAMETRIZE { speed = 5; }
+
+    GIVEN {
+        PLAYER(SPECIES_MAGNEMITE) { Ability(ABILITY_ANALYTIC); Speed(speed); }
+        PLAYER(SPECIES_WYNAUT) { HP(1); Speed(1); }
+        OPPONENT(SPECIES_WOBBUFFET) { Speed(20); }
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponentLeft, MOVE_TACKLE, target: playerRight); }
```
Comment (PhallenTree) [inline test/battle/ability/analytic.c]:
```suggestion
        TURN { MOVE(opponentLeft, MOVE_SCRATCH, target: playerRight); }
```

File: test/battle/ability/analytic.c [hunk 8]
```diff
@@ -20,9 +20,59 @@ SINGLE_BATTLE_TEST("Analytic increases the power of moves by 30% if it's the las
...
+    PARAMETRIZE { speed = 50; }
+    PARAMETRIZE { speed = 15; }
+
+    GIVEN {
+        PLAYER(SPECIES_MAGNEMITE) { Ability(ABILITY_ANALYTIC); Speed(speed); }
+        PLAYER(SPECIES_WYNAUT) { HP(1); Speed(1); }
+        OPPONENT(SPECIES_WOBBUFFET) { Speed(20); }
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponentLeft, MOVE_TACKLE, target: playerRight); }
```
Comment (PhallenTree) [inline test/battle/ability/analytic.c]:
```suggestion
        TURN { MOVE(opponentLeft, MOVE_SCRATCH, target: playerRight); }
```

File: test/battle/move_effect/snatch.c [hunk 9]
```diff
@@ -1,4 +1,64 @@
...
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponentLeft, MOVE_TACKLE, target: playerRight); }
+        TURN {
+            MOVE(opponentLeft, MOVE_CELEBRATE);
+            MOVE(opponentRight, MOVE_CELEBRATE);
+            MOVE(playerLeft, MOVE_SNATCH);
+        }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, opponentLeft);
```
Comment (PhallenTree) [inline test/battle/move_effect/snatch.c]:
```suggestion
        TURN { MOVE(opponentLeft, MOVE_SCRATCH, target: playerRight); }
        TURN {
            MOVE(opponentLeft, MOVE_CELEBRATE);
            MOVE(opponentRight, MOVE_CELEBRATE);
            MOVE(playerLeft, MOVE_SNATCH);
        }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SCRATCH, opponentLeft);
```

File: test/battle/move_effect/protect.c [hunk 10]
```diff
@@ -356,6 +356,42 @@ SINGLE_BATTLE_TEST("Protect: Multi-hit moves don't hit a protected target and fa
...
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponentLeft, MOVE_TACKLE, target: playerRight); }
+        TURN {
+            MOVE(opponentLeft, MOVE_CELEBRATE);
+            MOVE(opponentRight, MOVE_CELEBRATE);
+            MOVE(playerLeft, MOVE_PROTECT);
+        }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, opponentLeft);
```
Comment (PhallenTree) [inline test/battle/move_effect/protect.c]:
```suggestion
        TURN { MOVE(opponentLeft, MOVE_SCRATCH, target: playerRight); }
        TURN {
            MOVE(opponentLeft, MOVE_CELEBRATE);
            MOVE(opponentRight, MOVE_CELEBRATE);
            MOVE(playerLeft, MOVE_PROTECT);
        }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SCRATCH, opponentLeft);
```

File: test/battle/move_effect/magic_coat.c [hunk 11]
```diff
@@ -33,6 +33,42 @@ SINGLE_BATTLE_TEST("Magic Coat prints the correct message when bouncing back a m
...
+        OPPONENT(SPECIES_WYNAUT) { Speed(10); }
+    } WHEN {
+        TURN { MOVE(opponentLeft, MOVE_TACKLE, target: playerRight); }
+        TURN {
+            MOVE(opponentLeft, MOVE_CELEBRATE);
+            MOVE(opponentRight, MOVE_CELEBRATE);
+            MOVE(playerLeft, MOVE_MAGIC_COAT);
+        }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, opponentLeft);
```
Comment (PhallenTree) [inline test/battle/move_effect/magic_coat.c]:
```suggestion
        TURN { MOVE(opponentLeft, MOVE_SCRATCH, target: playerRight); }
        TURN {
            MOVE(opponentLeft, MOVE_CELEBRATE);
            MOVE(opponentRight, MOVE_CELEBRATE);
            MOVE(playerLeft, MOVE_MAGIC_COAT);
        }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SCRATCH, opponentLeft);
```

**Comment by AlexOn1ine** [comment]
@moostoet could you move the new function to `battle_util.c`?

**Comment by moostoet** [comment]
@AlexOn1ine done!
