### PR TITLE
Fix AI's right slot switching-in too early

### LINKED ISSUE #4656: In a Double Battle, the AI's right slot switches in early
### Description

In a scenario where either of the AI's Pokemon have fainted, if the player's right slot Pokemon has also fainted, the AI will switch in their right slot before the player is prompted to switch in their post-KO Pokemon, giving the player an advantage.

### Version

upcoming (Edge)

### Upcoming/master Version

06cbc9a1625bc4cecdcc62d96ae546c009f7ced8

### Discord contact info

Special K#8400

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #4656

I didn't have to do much, because the code functionality for this is already coded! In link battles, everyone chooses their switches and then the mons are switched-in, so this functionality is now also added for trainer double battles.

I created a new config, but can rename/delete it if you guys feel it's unnecessary. 

I also got rid of the `Link` label in scripts, since it'll no longer be used just for link battles.
Note: Please squash when merging
Before:
before

After:
after

### CODE REVIEW

File: include/config/battle.h [hunk 1]
```diff
@@ -49,17 +49,18 @@
...
+#define B_SLEEP_TURNS                   GEN_LATEST // In Gen5+, sleep lasts for 1-3 turns instead of 2-5 turns.
+#define B_TAUNT_TURNS                   GEN_LATEST // In Gen5+, Taunt lasts 3 turns if the user acts before the target, or 4 turns if the target acted before the user. In Gen3, taunt lasts 2 turns and in Gen 4, 3-5 turns.
+#define B_SPORT_TURNS                   GEN_LATEST // In Gen6+, Water/Mud Sport last 5 turns, even if the user switches out.
+#define B_MEGA_EVO_TURN_ORDER           GEN_LATEST // In Gen7, a Pokémon's Speed after Mega Evolution is used to determine turn order, not its Speed before.
+#define B_RECALC_TURN_AFTER_ACTIONS     GEN_LATEST // In Gen8, switching/using a move affects the current turn's order of actions, better known as dynamic speed.
+#define B_FAINT_SWITCH_IN               GEN_LATEST // In Gen4+, sending out a new Pokémon after the previous one fainted happens at the end of the turn. Before, it would happen after each action.
+#define B_FAIR_MULTI_SWITCH_IN_DOUBLES  FALSE       // In double trainer battles pokemon are switched at the same time, that is the player doesn't know the trainer's pokemon before they switch theirs.
```
Comment (pkLucid) [inline include/config/battle.h:63]: Any reason it is set to false? Also are we sure we need to config this? Our doubles are already not gen3 compatible.

Comment (AlexOn1ine) [inline include/config/battle.h:63]: Any reason this is set to false? Also are we sure we need a config for this since our gen3 double battles are already not gen3 compatible.

Comment (DizzyEggg) [reply include/config/battle.h:63]: Oops, this should be set to true lmao. I can get rid of the config

**Review by AlexOn1ine — APPROVED** [review]
