### PR TITLE
Fixes Protective Pads preventing Poison Touch activation

### LINKED ISSUE #9210: Protective Pads vs. Punching Glove/Long Reach tests
### Behavior Description

According to [jpwiki](https://wiki.xn--rckteqa2e.com/wiki/%E3%81%BC%E3%81%86%E3%81%94%E3%83%91%E3%83%83%E3%83%88#%E8%A9%B3%E7%B4%B0%E3%81%AA%E4%BB%95%E6%A7%98), Protective Pads doesn't prevent the following contact-related effects from activating, while Punching Glove/Long Reach do.
This is handled in expansion by the functions `CanBattlerAvoidContactEffects` (which checks Protective Pads) and `IsMoveMakingContact`, but there are missing tests for the different effects taking effect or not.

List of effects not prevented by Protective Pads, but prevented by Punching Glove/Long Reach:
- Fluffy halving damage from contact moves;
- Tough Claws boosting damage of contact moves;
- Unseen Fist ignoring protection when using a contact move;
- Poison Touch poisoning a target damaged using a contact move;
- Pickpocket stealing an item from the attacker when it uses a contact move;

### Images / Video

.

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by PhallenTree**
- Fixes Protective Pads preventing Poison Touch from activating. [Source](https://wiki.ポケモン.com/wiki/%E3%81%BC%E3%81%86%E3%81%94%E3%83%91%E3%83%83%E3%83%88#%E8%A9%B3%E7%B4%B0%E3%81%AA%E4%BB%95%E6%A7%98)
- Fixes Long Reach being ignored when determining if move makes contact for Fluffy.
- Adds Protective Pads vs. Punching Glove/Long Reach tests (see linked issue for more details).

## Issue(s) that this PR fixes
Fixes #9210

## Feature(s) this PR does NOT handle:
Doesn't add missing Unseen Fist/Tough Claws tests except the Protective Pads vs. Punching Gloves one.

## Discord contact info
PhallenTree

### CODE REVIEW

File: test/battle/ability/fluffy.c [hunk 1]
```diff
@@ -8,6 +8,7 @@ ASSUMPTIONS
     ASSUME(MoveMakesContact(MOVE_SCRATCH));
     ASSUME(MoveMakesContact(MOVE_FIRE_PUNCH));
     ASSUME(GetMoveType(MOVE_FIRE_PUNCH) == TYPE_FIRE);
+    ASSUME(MoveMakesContact(MOVE_THUNDER_PUNCH));
```
Comment (AsparagusEduardo) [inline test/battle/ability/fluffy.c]: I would only add to the assumptions block if every test in the file requires the assume, which doesn't seem to be the case here
