### PR TITLE
Fix Pickpocket moveend target checks and Thief/Covet handoff

### LINKED ISSUE #8769: Pickpocket moveend erroneously references gBattlerTarget
### Description

The pickpocket moveend checks if the move made contact with gBattlerTarget and if the move had an effect against gBattlerTarget. The problem is that the moveend happens after MOVEEND_NEXT_TARGET, where gBattlerTarget is unpredictable for multi-target moves
https://github.com/rh-hideout/pokeemerald-expansion/blob/cded31fa7f492a443627f9b64676b1090e58a93a/src/battle_move_resolution.c#L1490-L1498

The check really should be happening here in the loop
https://github.com/rh-hideout/pokeemerald-expansion/blob/cded31fa7f492a443627f9b64676b1090e58a93a/src/battle_move_resolution.c#L1502-L1513

(There are some other moveends that use gBattlerTarget, but they only deal with single target effects. MoveEnd_ItemEffectsAttacker2 might pose an issue, but I haven't really looked at it)
https://github.com/rh-hideout/pokeemerald-expansion/blob/cded31fa7f492a443627f9b64676b1090e58a93a/src/battle_move_resolution.c#L1076-L1087

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description

- Fix Pickpocket’s moveend logic to check contact/effect per target, avoiding incorrect spread‑move activations.
- Also handle the pending stolen item from Thief/Covet so Pickpocket can resolve correctly when the attacker’s item is assigned later in moveend.

> **[_Bulba_](https://bulbapedia.bulbagarden.net/wiki/Pickpocket_(Ability))**
> Pickpocket activates after Magician and the Sticky Barb, and after Thief and Covet steal a held item. 

## Issue(s) that this PR fixes
Fixes #8769

### CODE REVIEW

File: test/battle/ability/pickpocket.c [hunk 1]
```diff
@@ -1,4 +1,337 @@
...
+        ABILITY_POPUP(opponent, ABILITY_PICKPOCKET);
+        ABILITY_POPUP(player, ABILITY_STICKY_HOLD);
+        MESSAGE("Grimer's item cannot be removed!");
+    } THEN {
+        EXPECT(opponent->item == ITEM_NONE);
+        EXPECT(player->item == ITEM_MAGOST_BERRY);
+    }
+}
+
+SINGLE_BATTLE_TEST("Pickpocket cannot steal restricted held items")
```
Comment (AlexOn1ine) [inline test/battle/ability/pickpocket.c:119]: since we are testing the picketpocket behavior I think it is enough to check just one item that is restricted. Basically we are not checking if item is restricted but if picketpocket can steal such an item or not.

File: test/battle/ability/pickpocket.c [hunk 2]
```diff
@@ -1,4 +1,337 @@
...
+        EXPECT(opponent->item == ITEM_SHELL_BELL);
+        EXPECT(player->item == ITEM_NONE);
+    }
+}
+
+SINGLE_BATTLE_TEST("Pickpocket does not prevent King's Rock or Razor Fang flinches")
+{
+    u16 item;
+    PARAMETRIZE { item = ITEM_KINGS_ROCK; }
+    PARAMETRIZE { item = ITEM_RAZOR_FANG; }
```
Comment (AlexOn1ine) [inline test/battle/ability/pickpocket.c]: probably fine to just check one item since they have the same effect
