### PR TITLE
Multiple bugfixes (mostly Dancer/called moves)

### LINKED ISSUE #8237: Determine correct conditions for Tar Shot failing
### Description

The battle script for tar shot. This uses the command cantarshotwork to determine if tar shot can work
https://github.com/rh-hideout/pokeemerald-expansion/blob/2373f0283bb50b9248cfc8c6c46db4be6b8881dc/data/battle_scripts_1.s#L773-L777

cantarshotwork command definition:
https://github.com/rh-hideout/pokeemerald-expansion/blob/2373f0283bb50b9248cfc8c6c46db4be6b8881dc/asm/macros/battle_script.inc#L1739-L1742

BS_CanTarShotWork:
https://github.com/rh-hideout/pokeemerald-expansion/blob/2373f0283bb50b9248cfc8c6c46db4be6b8881dc/src/battle_script_commands.c#L15724-L15733

If tar shot hasn't been set AND the target's speed stat stage is less than the max stat stage (min stat stage with contrary), then tar shot can work. This means that if tar shot has been set, then the speed lowering effect won't proc. Also, tar shot won't count as failing if the target's speed stat stage is at 0 (12 with contrary) because of the incorrect CompareStat check.

This seems to contradict what Bulbapedia says: https://bulbapedia.bulbagarden.net/wiki/Tar_Shot_(move)
> Tar Shot will not double the effectiveness of Fire-type moves used on a target that is already under the effect of Tar Shot (but may still lower its Speed).

The correct behaviour should be investigated

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
- Fixes Weather abilities not activating when Delta Stream changes the weather;
- Fixes Tar Shot checks to determine whether the animation should be played (account for Terastallization and make move only fail if target's speed can't be reduced and target can't get the Tar Shot effect);
- Fixes Dancer activating on missed moves;
- Fixes Dancer only checking for one target being affected by the move (potentially caused Dancer to not activate in some situations);
- Fixes Dancer-called moves potentially activating Life Orb even when failing to affect any battler;
- Fixes Mold Breaker flag not being reset when a move calls a different move (example: Sleep Talk -> Sunsteel Strike would not set the Mold Breaker flag despite Sunsteel Strike ignoring abilities);
- Removed `MOVE_RESULT_MISSED` result flag being set if a stat change can't happen (gave it to status moves that may rely on it when they can't boost a stat);

## Issue(s) that this PR fixes
Fixes #8237

## Discord contact info
PhallenTree

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -10419,6 +10416,11 @@ void ClearDamageCalcResults(void)
     gBattleStruct->calculatedSpreadMoveAccuracy = FALSE;
     gBattleStruct->printedStrongWindsWeakenedAttack = FALSE;
     gBattleStruct->numSpreadTargets = 0;
+    gBattleScripting.savedDmg = 0;
+    if (gCurrentMove != MOVE_NONE)
+        gBattleStruct->moldBreakerActive = IsMoldBreakerTypeAbility(gBattlerAttacker, GetBattlerAbility(gBattlerAttacker)) || MoveIgnoresTargetAbility(gCurrentMove);
+    else
+        gBattleStruct->moldBreakerActive = FALSE;
```
Comment (AlexOn1ine) [inline src/battle_util.c:10423]: damn, this is much better.

**Comment by AlexOn1ine** [comment]
I think the Mold Breaker reset flag can also be removed from `MOVEEND_CLEAR_BITS`?
