### PR TITLE
Fixes Substitute triggering Stamina and Eject Button on crash damage

### LINKED ISSUE #3659: High Jump Kick Crash and Eject Button
### Description

A Pokemon holding Eject Button, getting a High Jump Kick Crash, will activate its own Eject Button.

In my case, I used a Pokemon with Protect and said behaviour happened.

### Version

upcoming (Edge)

### Upcoming Version

77ae9e3

### Discord contact info

._.terra._.

### LINKED ISSUE #3667: Stamina and Substitute
### Description

A Pokemon with Stamina can activate it's own ability by using Substitute.

### Version

upcoming (Edge)

### Upcoming Version

77ae9e3

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #3667
Fixes #3659

### CODE REVIEW

**Review by Bassoonian — APPROVED** [review]

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -5858,9 +5858,9 @@ static void Cmd_moveend(void)
                     u8 battler = battlers[i];
                     // Attacker is the damage-dealer, battler is mon to be switched out
                     if (IsBattlerAlive(battler)
+                      && gBattlerAttacker != battler
                       && GetBattlerHoldEffect(battler, TRUE) == HOLD_EFFECT_EJECT_BUTTON
-                      && !DoesSubstituteBlockMove(gBattlerAttacker, battler, gCurrentMove)
-                      && (gSpecialStatuses[battler].physicalDmg != 0 || gSpecialStatuses[battler].specialDmg != 0)
+                      && TARGET_TURN_DAMAGED
```
Comment (ghoulslash) [inline src/battle_script_commands.c:5863]: is this correct? TARGET_TURN_DAMAGED will check gBattlerTarget and not the `batter` loop index

Comment (AlexOn1ine) [reply src/battle_script_commands.c:5863]: oh, you are right. sorry :grimacing:
