### PR TITLE
Ability Shield allows for ability activation when obtained and Trick cleanup

### LINKED ISSUE #8564: Trick doesn't seem to set unburden for the target, even if it lost an item
### Description

It's clearly not checking whether to set or reset the target's unburden state, only the attacker: https://github.com/rh-hideout/pokeemerald-expansion/blob/38519b66e3a266f2aeb95d33a104817d601149fb/src/battle_script_commands.c#L12290-L12305

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
Adds Ability Shield allowing to activate suppressed abilities when obtained by a move (assuming that Thief/Symbiosis activating might allow for this also). From [smogon research thread](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-10780426)
Update Trick/Switcheroo to have the attacker's held item updated at the same time as the target's.

Other changes:
- Fixed Symbiosis in MoveEnd overwriting `gBattlerAttacker`;
- Fixed Trick/Switcheroo being prevented by the user's Sticky Hold (according to jpwiki, only the target's Sticky Hold prevents it);
- Fixes Trick/Switcheroo never changing target's Unburden flag;
- Removed `BS_TryAbsorbToxicSpikesOnFaint` (was already handled in #8128);
- Allow newly obtained items via Trick/Switcheroo to activate;
- Clear Unburden flag when changing abilities from Unburden.

## Issue(s) that this PR fixes
Fixes #8564

## Discord contact info
PhallenTree

### CODE REVIEW

**Comment by Cle-bit** [comment]
Pay attention to the modification of #8516, including the Ai section. Sorry about that.

File: src/battle_util.c [hunk 1]
```diff
@@ -12019,6 +12019,9 @@ static u32 GetMeFirstMove(void)
 
 void RemoveAbilityFlags(u32 battler)
 {
+    if (gBattleMons[battler].ability == ABILITY_UNBURDEN)
+        gBattleMons[battler].volatiles.unburdenActive = FALSE;
```
Comment (AlexOn1ine) [inline src/battle_util.c]: Is this for when the ability is switched, we want to clear unburden boost because we don't know if the item has been lost (if there is no item already)?

Comment (PhallenTree) [reply src/battle_util.c]: This is for when a battler is about to switch Unburden for a different ability (maybe it doesn't need the ability check?)

Comment (AlexOn1ine) [reply src/battle_util.c]: hm, if you are checking the raw ability anyways then probably not needed?
