### PR TITLE
Fixes AI not seeing primal weather and partner absorbing abilities

### LINKED ISSUE #6930: `GetWeatherDamageModifier` doesn't handle Primal Rain making Fire moves fail
### Description

Got a report from EI where an expected switchin was wrong because the AI doesn't see Fire type attacks failing (and thus dealing 0 damage) in Primal Rain.

Checked out `GetWeatherDamageModifier`, which is the function that handles weather-based damage modulation, and the only rain reference is for scaling up water and down fire, with no specific handling for this (or any other) niche weather. The same applies to Desolate Land not shutting off Water moves in the calc.

EDIT: Also doesn't seem to be handling for Delta Stream stopping damage from all types that are SE against flying

### Reproduction Steps

This field is mandatory now?! Consider this a protest

### Images / Video

_No response_

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6930

### CODE REVIEW

File: src/battle_ai_util.c [hunk 1]
```diff
@@ -434,6 +434,19 @@ bool32 IsDamageMoveUnusable(u32 battlerAtk, u32 battlerDef, u32 move, u32 moveTy
     if (CanAbilityAbsorbMove(battlerAtk, battlerDef, aiData->abilities[battlerDef], move, moveType, ABILITY_CHECK_TRIGGER))
         return TRUE;
 
+    u32 partnerAbility = aiData->abilities[BATTLE_PARTNER(battlerDef)];
+    if ((partnerAbility == ABILITY_LIGHTNING_ROD && moveType == TYPE_ELECTRIC)
```
Comment (AlexOn1ine) [inline src/battle_ai_util.c:438]:
```suggestion
    // Limited to Lighning Rod and Storm Drain because otherwise the AI would consider Water Absorb, etc...
    if ((partnerAbility == ABILITY_LIGHTNING_ROD && moveType == TYPE_ELECTRIC)
```

File: test/battle/ai/ai.c [hunk 2]
```diff
@@ -914,3 +914,30 @@ SINGLE_BATTLE_TEST("AI correctly records used moves")
...
+        OPPONENT(SPECIES_BLASTOISE) { Moves(MOVE_HYDRO_PUMP, MOVE_POUND); }
+    } WHEN {
+        TURN { MOVE(player, MOVE_SCRATCH); EXPECT_MOVE(opponent, MOVE_POUND); }
+    }
+}
+
+AI_DOUBLE_BATTLE_TEST("AI sees opposing drain ability")
+{
+    GIVEN {
+        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_CHECK_VIABILITY | AI_FLAG_TRY_TO_FAINT | AI_FLAG_OMNISCIENT);
```
Comment (Pawkkie) [inline test/battle/ai/ai.c:933]: Need typing assumptions, good otherwise :)

**Review by Pawkkie — CHANGES_REQUESTED** [review]

**Comment by Pawkkie** [comment]
I merged your other PR so there's now a conflict here, it's just accommodating the new test, sorry for the hassle!

**Comment by AlexOn1ine** [comment]
> I merged your other PR so there's now a conflict here, it's just accommodating the new test, sorry for the hassle!

fixed

**Review by Pawkkie — APPROVED** [review]
