### PR TITLE
Fix dns color transition not applying weather blending

### LINKED ISSUE #7016: visual bugs with DNS and fake RTC when warping between maps
### Description

when warping from one map to another, if fake RTC is enables, somehting is worng with the fade in/out. the issue seems mroe common, or possibly exlusively, during parts of the day/night cycle where the light is transiitoning between light and dark (i.e. morning and evening). occasionally when warping, after fading out, the screen flashed back to unfaded before transitioning to the destination map. warping into shade weather also shows an error where the light level brightens slightly after being in the new map for a second or two. the timing and occurence of these issues is soemwhat sporadic, but happens often with fake RTC at the aforementioned times of day. apologies if the explanation is not clear, hopefully the gifs dmeonstrate the issue clearly. these are two separate symtpoms, and I am assuming it is the same root cause. 

### Reproduction Steps

on. a clean project enable fake RTC in configs, set time to evening (make sure clock is started at new game or thtrough debug set wall clock), warp or go through any door that does a fade out/in (possibly go back and forth several times)

### Images / Video

Image
Image

### Version

upcoming (Edge)

### Upcoming/master Version

5dd45a047979f4b075c7c8f6689de72e21d91183

### Discord contact info

mrleaky666

### PR DESCRIPTION
**Pull request by FosterProgramming**
Maps with some weather effect like PetalburgWoods with weather_shade would not apply their effects properly when dns was active. It would apply it on map transition but after that, when time has passed to update the color palette, it would not apply the weather effect. This PR makes sure the weather effect is properly applied when DNS is updating the color palette.

## Media
In #7016, you can see a video of the woods suddenly becoming brighter when the palette update. I made a video recreating the situation in this commit where ut's teh evening and the screen become darker when the color transition happen:

https://github.com/user-attachments/assets/2140e52e-c524-40de-874e-4fff35c1dcc7

## Issue(s) that this PR fixes
Fixes #7016 and #7176 

## Things to note in the release changelog:
- DNS colors should apply properly in maps with weather effects that modify colors (please report any issue you may still find)

## Discord contact info
Jamie (foster_harmony)

### CODE REVIEW

File: src/overworld.c [hunk 1]
```diff
@@ -1716,8 +1716,7 @@ static void OverworldBasic(void)
          || bld0[1] != bld1[1]
          || bld0[2] != bld1[2])
         {
-           UpdateAltBgPalettes(PALETTES_BG);
-           UpdatePalettesWithTime(PALETTES_ALL);
+            ApplyWeatherColorMapIfIdle(gWeatherPtr->colorMapIndex);
```
Comment (Bassoonian) [inline src/overworld.c]:
```suggestion
           ApplyWeatherColorMapIfIdle(gWeatherPtr->colorMapIndex);
```

**Comment by Jaizu** [comment]
Shouldnt bug-fixes be ported to merrp branches too? If you are going to take such a big system like dns and followers the least u could do is to backport fixes/improvements to the original branches.
Even better, just PR to her branches and be in sync with it?

**Comment by AlexOn1ine** [comment]
> Shouldnt bug-fixes be ported to merrp branches too? If you are going to take such a big system like dns and followers the least u could do is to backport fixes/improvements to the original branches. Even better, just PR to her branches and be in sync with it?

Yeah, ideally.

**Comment by FosterProgramming** [comment]
> Shouldnt bug-fixes be ported to merrp branches too? If you are going to take such a big system like dns and followers the least u could do is to backport fixes/improvements to the original branches. Even better, just PR to her branches and be in sync with it?

I don't mind pushing my fixes to the feature branches but when looking at a bug, it can be difficult to know if it comes from the branch or of it's expansion specific. (Like I fixed another dns bug around the same time I worked on this one that was just a regression from some other expansion changes)
What do you think is the best way to track changes that need to be backported? Make special labels for it? Add comments to the issue?
