### PR TITLE
Fix berry tree spawning with max yield when OW_BERRY_ALWAYS_WATERABLE is active

### LINKED ISSUE #8965: Newgame overly generous berry trees using OW_BERRY_ALWAYS_WATERABLE
### Description

Newgame calls PlantBerryTree which goes to 
...
    if (OW_BERRY_ALWAYS_WATERABLE)
       	    tree->berryYield = GetBerryInfo(berry)->maxYield;
...

This is meant to happen so that you get max yield unless the moisture drops. However when it's called in newgame, it means all the existing oran trees in the game yield their maximum berries, which I assume is unintended

### Reproduction Steps

_No response_

### Images / Video

_No response_

### Version

1.14.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
When  OW_BERRY_ALWAYS_WATERABLE is active start at max yield when planted and lose yield over time if they are not watered. This cause issues where the tree created in later stage through script (like in enw_game.inc) would stay at max yield forever. This tries to give script generated trees a simulated amount of yield

## Issue(s) that this PR fixes
Fixes #8965

## Discord contact info
Jamie

### CODE REVIEW

**Comment by Bassoonian** [comment]
I'm confused if this is truly a bugfix, trees created at a later stage (as in the new game) are intended to remain at max yield by design (in vanilla Emerald too), otherwise they would wither and regrow and you'd encounter berries at random stages whenever you enter a new route

**Comment by FosterProgramming** [comment]
> I'm confused if this is truly a bugfix, trees created at a later stage (as in the new game) are intended to remain at max yield by design (in vanilla Emerald too), otherwise they would wither and regrow and you'd encounter berries at random stages whenever you enter a new route

In vanilla emerald, a tree spawned in the new game will spawn as if it had not been watered at min yield
This simply recreates this behavior for a different config. They are still prevented from withering because of the stopGrowth flag

File: src/berry.c [hunk 1]
```diff
@@ -1961,8 +1962,15 @@ void PlantBerryTree(u8 id, u8 berry, u8 stage, bool8 allowGrowth)
     tree->stage = stage;
     tree->moistureLevel = 100;
     if (OW_BERRY_ALWAYS_WATERABLE)
-        tree->berryYield = GetBerryInfo(berry)->maxYield;
-    if (stage == BERRY_STAGE_BERRIES)
+    {
+        // We simulate a tree having grwon without water
```
Comment (Bassoonian) [inline src/berry.c]:
```suggestion
        // We simulate a tree having grown without water
```

**Comment by luuma** [comment]
Sorry just before this gets closed can we use it to fix something I just spotted in src/berry.c also:
static const u8 sBerryMutations has a duplicate for the mutations that create a kelpsy berry

**Comment by FosterProgramming** [comment]
> Sorry just before this gets closed can we use it to fix something I just spotted in src/berry.c also: static const u8 sBerryMutations has a duplicate for the mutations that create a kelpsy berry

Done
