### PR TITLE
Fixes Rage Fist counter increment

### LINKED ISSUE #7566: Rage Fist issue
### Description

Hitting a Rage Fist user with Draining Kiss makes it gain 2 stacks of Rage Fist. 

### Reproduction Steps

Start a fight with a Draining Kiss Mon vs Rage Fist Annihilape. Draining Kiss it and let it Rage Fist you. Track the damage with a Damage Calculator and you should notice that the damage is off.

### Images / Video

_No response_

### Version

1.12.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7566

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -2635,6 +2635,7 @@ static void Cmd_healthbarupdate(void)
 static void Cmd_datahpupdate(void)
 {
     CMD_ARGS(u8 battler);
+    bool32 isPassiveDamageOrHealing = gHitMarker & HITMARKER_PASSIVE_DAMAGE;
```
Comment (Bassoonian) [inline src/battle_script_commands.c:2638]: If the hitmarker is also used for healing, could we maybe update its name accordingly too?

Comment (AlexOn1ine) [reply src/battle_script_commands.c:2638]: I'm planning to split `datahpupdate` into 2 functions, one for passive damage / healing, one for move damage so no. 

also it should be a pret change

Comment (AlexOn1ine) [reply src/battle_script_commands.c:2638]: we could rename it specifically in master but I'm not sure why since it has been inherited from pret.

Comment (Bassoonian) [reply src/battle_script_commands.c:2638]: I'm fine with pushing for a rename in pret, didn't know it was already present there

File: test/battle/move_effect/rage_fist.c [hunk 2]
```diff
@@ -342,3 +342,28 @@ SINGLE_BATTLE_TEST("Rage Fist doesn't get increased power if Substitute is hit")
...
+
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_GIGA_DRAIN, opponent);
+        HP_BAR(player);
+
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_RAGE_FIST, player);
+        HP_BAR(opponent, captureDamage: &timesGotHit[1]);
+    } THEN {
+        EXPECT_MUL_EQ(timesGotHit[0], Q_4_12(2.0), timesGotHit[1]);
+    }
+}
```
Comment (Bassoonian) [inline test/battle/move_effect/rage_fist.c]:
```suggestion
}

```

File: test/battle/move_effect/rage_fist.c [hunk 3]
```diff
@@ -342,3 +342,28 @@ SINGLE_BATTLE_TEST("Rage Fist doesn't get increased power if Substitute is hit")
         EXPECT_EQ(timesGotHit[0], timesGotHit[1]);
     }
 }
+
+SINGLE_BATTLE_TEST("Rage Fist - X")
```
Comment (Bassoonian) [inline test/battle/move_effect/rage_fist.c:346]: This still needs an actual name

Comment (AlexOn1ine) [inline test/battle/move_effect/rage_fist.c:346]:
```suggestion
SINGLE_BATTLE_TEST("Rage Fist counter will be updated correctly after absorb move")
```

Comment (AlexOn1ine) [reply test/battle/move_effect/rage_fist.c:346]: made a suggestion
