### PR TITLE
Fixes activation order for a couple abilities

### LINKED ISSUE #6389: Toxic Chain blocks other secondary moves from happening
### Description

> [...]
> 
> So I hypothesize that Toxic Chain still activates at the same (or at least close to the same) event timing, but it sets a flag earlier in the checks done after move success that it will badly poison, and if that flag is set, it doesn't attempt to set any other non-volatile status at an earlier point (burn, freeze, poison, etc.).

Source: smogon

### Version

1.11.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #7466: Color Change should change type after multi hit moves complete
### Description

https://bulbapedia.bulbagarden.net/wiki/Color_Change_(Ability)
> Color Change now activates after the last hit of a multistrike move. 

order of moveends:
https://github.com/rh-hideout/pokeemerald-expansion/blob/4d31693005bf628bfe259a7be9f3f47f87b3f810/include/constants/battle_script_commands.h#L136-L154

MOVEEND_ABILITIES:
https://github.com/rh-hideout/pokeemerald-expansion/blob/4d31693005bf628bfe259a7be9f3f47f87b3f810/src/battle_script_commands.c#L6105-L6106

Color Change happens in ABILITYEFFECT_MOVE_END
https://github.com/rh-hideout/pokeemerald-expansion/blob/4d31693005bf628bfe259a7be9f3f47f87b3f810/src/battle_util.c#L4577-L4591

### Reproduction Steps

N/A, source code analysis

### Images / Video

_No response_

### Version

Upcoming (edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #7732
Fixes #6389
Fixes #7466

Fixes Toxic Chain, Color Change, Berserk and Anger Shell activation timings.

### CODE REVIEW

**Comment by Bassoonian** [comment]
Is this meant to target upcoming?

**Comment by AlexOn1ine** [comment]
> Is this meant to target upcoming?

Ye, It's a bit to much for a bugfix imo.

File: include/battle.h [hunk 1]
```diff
@@ -901,7 +903,7 @@ struct BattleScripting
     s32 savedDmg;
     u16 savedMoveEffect; // For moves hitting multiple targets.
     u16 moveEffect;
-    u16 multihitMoveEffect;
+    u16 unused_0x30;
```
Comment (Bassoonian) [inline include/battle.h:907]: Any reason we don't just delete this? Maybe move ``abilityPopupOverwrite`` here?

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -962,6 +962,26 @@ static const struct PickupItem sPickupTable[] =
...
+    }
+    if (gBattleStruct->savedTargetCount > 0)
+    {
+        // #if TESTING
+        // Test_ExitWithResult(TEST_RESULT_ERROR, "savedTargetCount is greater than 0! More calls to SaveBattlerTarget than RestoreBattlerTarget!");
+        // #else
+        DebugPrintfLevel(MGBA_LOG_WARN, "savedTargetCount is greater than 0! More calls to SaveBattlerTarget than RestoreBattlerTarget!");
+        // #endif
+    }
+}
```
Comment (Bassoonian) [inline src/battle_script_commands.c:983]: Leftover code

Comment (AlexOn1ine) [reply src/battle_script_commands.c:983]: This should be correct now, I think. There was code leftover previously but I removed it in the last commit

File: include/battle.h (hunk 1 above)
Comment (AlexOn1ine) [reply include/battle.h:907]: It needs to be aligned because of scripting defines in `constants/battle.h`. It can be removed but I don't want to mess up counting bytes. We can clean up the struct later after #7249 is merged.

File: src/battle_script_commands.c (hunk 2 above)
Comment (Bassoonian) [reply src/battle_script_commands.c:983]: There's still commented out code and a DebugPrintf though, which we don't really have elsewhere in the repo as far as I'm aware

Comment (AlexOn1ine) [reply src/battle_script_commands.c:983]: The code was added by ghoul so I don't want to remove it without their permission. I think it doesn't compile tests so it was commented out.

**Comment by AlexOn1ine** [comment]
drafting since I found an other inaccuracy

**Comment by AlexOn1ine** [comment]
Mirror Herb order was wrong. 

Ready for review!

**Comment by Bassoonian** [comment]
Conflicts

**Comment by AlexOn1ine** [comment]
conflicts solved

**Review by Bassoonian — APPROVED** [review]
