### PR TITLE
Adds Glaive Rush, fixes for Plasma Fists and Relic Song 

### LINKED ISSUE #2494: MOVE_GLAIVE_RUSH Effect

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Closes  #2494

Fixes for Plasma Fists and Relic Song including tests.

### CODE REVIEW

**Review by Skeli789 — CHANGES_REQUESTED** [review]

File: src/battle_main.c [hunk 1]
```diff
@@ -4975,6 +4975,7 @@ static void TurnValuesCleanUp(bool8 var0)
             gBattleMons[i].status2 &= ~STATUS2_SUBSTITUTE;
 
         gSpecialStatuses[i].parentalBondState = PARENTAL_BOND_OFF;
+        gStatuses4[i] &= ~STATUS4_GLEIVE_RUSH;
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply src/battle_main.c:4978]: Just to make sure I understand it, it is cleared once the user used a different move? E.g. if the user moves second, opponent will still do double damage.

Also seems like both showdown dex and smogon are wrong again. Both have it until next turn. Don't know what the actual implementation is though.

[the remark this answers is not in the document]
Comment (Skeli789) [reply src/battle_main.c:4978]: > E.g. if the user moves second, opponent will still do double damage.

Correct

> Both have it until next turn.

Both say "until the **user's next turn**". You should test ingame if it's cleared if the user is unable to act due to being asleep, for instance.

File: data/battle_scripts_1.s [hunk 2]
```diff
@@ -440,6 +440,11 @@ gBattleScriptsForMoveEffects::
 	.4byte BattleScript_EffectSyrupBomb               @ EFFECT_SYRUP_BOMB
 	.4byte BattleScript_EffectHit                     @ EFFECT_IVY_CUDGEL
 	.4byte BattleScript_EffectMaxMove                 @ EFFECT_MAX_MOVE
+	.4byte BattleScript_EffectGlaiveRush              @ EFFECT_GLAIVE_RUSH
+
+BattleScript_EffectGlaiveRush::
+	setglaiverush
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply data/battle_scripts_1.s:448]: Should be fixed.

File: src/battle_main.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply src/battle_main.c]: I can't test ingame but according to Showdown the flag is still removed if the user is unable to move. 

Also not 100% sure about this but I followed Destiny Bond and also remove the flag if the user tries to flee or use an item.

File: data/battle_scripts_1.s (hunk 2 above)
[the remark this answers is not in the document]
Comment (Skeli789) [reply data/battle_scripts_1.s:448]: Did you test to ensure the effect is not set when the move has no effect?

File: data/scripts/debug.inc [hunk 3]
```diff
@@ -14,6 +14,7 @@ Debug_CheatStart::
 	setflag FLAG_RESCUED_BIRCH
 	setflag FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE
 	setflag FLAG_ADVENTURE_STARTED
+	setflag FLAG_BADGE08_GET
```
Comment (Skeli789) [inline data/scripts/debug.inc:17]: Intentional change?

File: data/battle_scripts_1.s (hunk 2 above)
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply data/battle_scripts_1.s:448]: No but should be fine now :sweat_smile:

Thanks for noticing these!

File: data/scripts/debug.inc (hunk 3 above)
Comment (AlexOn1ine) [reply data/scripts/debug.inc:17]: Yeah, it's needed for testing because of obedience but I didn't want to make a lone PR for it.

File: data/battle_scripts_1.s [hunk 4]
```diff
@@ -440,6 +440,17 @@ gBattleScriptsForMoveEffects::
 	.4byte BattleScript_EffectSyrupBomb               @ EFFECT_SYRUP_BOMB
 	.4byte BattleScript_EffectHit                     @ EFFECT_IVY_CUDGEL
 	.4byte BattleScript_EffectMaxMove                 @ EFFECT_MAX_MOVE
+	.4byte BattleScript_EffectGlaiveRush              @ EFFECT_GLAIVE_RUSH
+
+BattleScript_EffectGlaiveRush::
+	call BattleScript_EffectHit_Ret
+	jumpifhalfword CMP_COMMON_BITS, gMoveResultFlags, MOVE_RESULT_DOESNT_AFFECT_FOE, BattleScript_GlaiveRushNoEffect
```
Comment (Skeli789) [inline data/battle_scripts_1.s:447]: No need to make a new battle script, just jump to the relevant part of EffectHit

Comment (Skeli789) [reply data/battle_scripts_1.s:447]: Yup, looks better. You could even just jump to the battle script of `tryfaintmon BS_TARGET` in `EffectHit` and save a line of code.

Comment (Skeli789) [reply data/battle_scripts_1.s:447]: Yeah, uou can just add a new label in the EffectHit battle script at that point and jump to there

Comment (AlexOn1ine) [reply data/battle_scripts_1.s:447]: Question, would there be any harm in moving `seteffectwithchance` to `BattleScript_EffectHit_Ret`? Not every BS that uses `BattleScript_EffectHit_Ret` has `seteffectwithchance` in them but most do. That would clean up a lot of lines.

Comment (AlexOn1ine) [reply data/battle_scripts_1.s]: Weren't that many lines in the end but it still looks better.

File: data/scripts/debug.inc (hunk 3 above)
Comment (AlexOn1ine) [reply data/scripts/debug.inc]: Removed it from this PR since a different PR was merged that has it lol

File: data/battle_scripts_1.s (hunk 4 above)
Comment (Skeli789) [reply data/battle_scripts_1.s]: Much better, looks like you're done if your tests all pass :)

Comment (AlexOn1ine) [reply data/battle_scripts_1.s]: Yeah, all pass :sweat_smile: 

Thank you for you help!

**Review by DizzyEggg — DISMISSED** [review]

File: data/battle_scripts_1.s [hunk 5]
```diff
@@ -3353,7 +3358,6 @@ BattleScript_EffectPoisonHit:
 
 BattleScript_EffectAbsorb::
 	call BattleScript_EffectHit_Ret
-	seteffectwithchance
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply data/battle_scripts_1.s:3356]: Will do

[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply data/battle_scripts_1.s:3356]: Unrelated to `seteffectwithchance` but I found a bug in the first move I was writing the tests for. Should I fix it alongside the tests in this PR or make a new one?

File: test/battle/move_effect/glaive_rush.c [hunk 6]
```diff
@@ -0,0 +1,143 @@
+#include "global.h"
+#include "test/battle.h"
+
+ASSUMPTIONS
+{
+    ASSUME(gBattleMoves[MOVE_GLAIVE_RUSH].effect == EFFECT_GLAIVE_RUSH);
+}
+
+SINGLE_BATTLE_TEST("xx If Glaive Rush is successful moves targeted at the user do not check accuracy")
```
[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply test/battle/move_effect/glaive_rush.c]: fixed

File: data/battle_scripts_1.s (hunk 5 above)
[the remark this answers is not in the document]
Comment (DizzyEggg) [reply data/battle_scripts_1.s:3356]: Yes, please do

[the remark this answers is not in the document]
Comment (AlexOn1ine) [reply data/battle_scripts_1.s:3356]: Added tests (a lot were already there).

Also fixed Plasma Fists and Relic Song.

File: src/battle_script_commands.c [hunk 7]
```diff
@@ -16283,3 +16258,41 @@ void BS_TrySetOctolock(void)
...
+        gBattlescriptCurrInstr = cmd->nextInstr;
+}
+
+void BS_ApplyPlasmaFists(void)
+{
+    NATIVE_ARGS();
+
+    u8 i;
+    for (i = 0; i < gBattlersCount; i++)
+        gStatuses4[i] |= STATUS4_PLASMA_FISTS;
```
Comment (Skeli789) [inline src/battle_script_commands.c:16295]: I can see you just moved the existing code, but whoever did it originally handled it in a weird way. Plasma Fists really should set an Ion Deluge (a field effect like Gravity and Fairy Lock) with a timer of 1 that's decremented at the end of the turn. It shouldn't be attached to the battlers on the field as a status.

**Review by Skeli789 — CHANGES_REQUESTED** [review]

File: src/battle_script_commands.c (hunk 7 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c:16295]: Makes sense. I'll change it to a field effect.

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: `STATUS_FIELD_ION_DELUGE` was already present for the move so I used it for Plasma Fists as well.

Comment (Skeli789) [reply src/battle_script_commands.c]: Looks better

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: Great. Thx again!

File: test/battle/move_effect/flinch_status.c [hunk 8]
```diff
@@ -0,0 +1,61 @@
+#include "global.h"
+#include "test/battle.h"
+
+ASSUMPTIONS
+{
+    ASSUME(gBattleMoves[MOVE_THUNDER_FANG].effect == EFFECT_FLINCH_STATUS);
+    ASSUME(gBattleMoves[MOVE_ICE_FANG].effect == EFFECT_FLINCH_STATUS);
+    ASSUME(gBattleMoves[MOVE_FIRE_FANG].effect == EFFECT_FLINCH_STATUS);
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/flinch_status.c:8]: Single review for this test: Assumes for the status.

Comment (AlexOn1ine) [reply test/battle/move_effect/flinch_status.c:10]: added

**Review by Bassoonian — APPROVED** [review]
