### PR TITLE
Fix pc turning on/off animation not working in battle frontier

### LINKED ISSUE #8047: some PCs dont animate when you click on them
### Description

PCs that use a "off" mettatile besides the one in "gTileset_Building" don;t animate when you press a on them. form what I cna tell, the chekc perfomred by function "static bool32 IsBuildingPCTile(u32 tileId)" gets confused because battles  tents (maybe other examples) use their off metatile from the secondary tileset rather than thr building primary. 

it's simple to just change it to the general metattile, or add a more broad check to the aformenentioned funciton, however these probably are not "correct" soltuions to whatveer may have originally casued this, since according to my records it has been in expansion for quite a while 

### Reproduction Steps

try a PC in any battle tent, the screern does not do flicker ainimation when it tunrs on

### Images / Video

Image

### Version

upcoming (Edge)

### Upcoming/master Version

776a2e762bf8d14ccdd700016b83f3091df43ef9

### Discord contact info

mrleaky666

### PR DESCRIPTION
**Pull request by FosterProgramming**
I replaced the code to detect if a pc is in front of the player from something that only look for a specific pc tile to something that looks at the MB_PC metatile behavior

## Media

https://github.com/user-attachments/assets/77e290bf-5957-443d-bd6b-d1d3ede8b7f4

## Issue(s) that this PR fixes
Fixes #8047

## Discord contact info
Jamie

### CODE REVIEW

File: src/field_specials.c [hunk 1]
```diff
@@ -984,7 +985,7 @@ void FieldShowRegionMap(void)
 
 static bool32 IsBuildingPCTile(u32 tileId)
 {
-    return gMapHeader.mapLayout->primaryTileset == &gTileset_Building && (tileId == METATILE_Building_PC_On || tileId == METATILE_Building_PC_Off);
+    return (UNPACK_BEHAVIOR(GetMetatileAttributesById(tileId)) == MB_PC);
```
Comment (mrgriffin) [inline src/field_specials.c]: I'm not 100% sure, but I think `MetatileBehavior_IsPC` might do this?
E: Ah, not quite. It just does the `== MB_PC` part. But I suspect there's a more idiomatic function to get the behavior?

Comment (FosterProgramming) [reply src/field_specials.c]: MetatileBehavior_IsPC takes an metatileBehavior as an argument not a metatileID
I tried with MetatileBehavior_IsPC at first and it didn't work.
I could rewrite the functions to get the behavior and pass a behavior but I went with this solution because we already had a tileID
Edit: My bad, I see what you mean now,so I'm updating the code

Comment (FosterProgramming) [reply src/field_specials.c]: Fixed

File: src/field_specials.c [hunk 2]
```diff
@@ -60,6 +61,7 @@
 #include "constants/field_specials.h"
 #include "constants/items.h"
 #include "constants/heal_locations.h"
+#include "constants/metatile_behaviors.h"
```
Comment (mrgriffin) [inline src/field_specials.c]: I thiiink this might be unnecessary?

**Review by mrgriffin — APPROVED** [review]
ty!

I'm shocked that there's not some sort of `GetMetatileBehaviorOf(u32 tileId)` function! So `UNPACK_BEHAVIOR` it is :grin:
