### PR TITLE
Fix emergency exit not triggering properly during wild battles

### LINKED ISSUE #7955: Emergency Exit may not cause opponent Pokémon to flee
### Description

Emergency exit is checked in MOVEEND_EMERGENCY_EXIT:
https://github.com/rh-hideout/pokeemerald-expansion/blob/7e98dffc51a2df8b4b1347644176a2dbf93cf9c3/src/battle_script_commands.c#L6651-L6665

EmergencyExitCanBeTriggered:
https://github.com/rh-hideout/pokeemerald-expansion/blob/7e98dffc51a2df8b4b1347644176a2dbf93cf9c3/src/battle_script_commands.c#L1070-L1082

`&& (CanBattlerSwitch(battler) || !(gBattleTypeFlags & BATTLE_TYPE_TRAINER))`
This checks if there are other alive mons which the battler can switch into. However, there's also a check that allows emergency exit to work unconditionally if it's not a trainer battle, so that wild Pokémon can flee.

`&& CountUsablePartyMons(battler) > 0`
However, the above check will prevent such logic from actually triggering. This function is more or less equivalent to CanBattlerSwitch, where it checks if there are other mons that can be switched into that aren't already on the field.
https://github.com/rh-hideout/pokeemerald-expansion/blob/7e98dffc51a2df8b4b1347644176a2dbf93cf9c3/src/battle_ai_util.c#L4290-L4320

In a wild battle, there are no other Pokémon to switch into, so this check will always fail. Thus, Emergency Exit is unable to cause wild Pokémon to flee.

### Reproduction Steps

N/A, source code analysis

### Images / Video

_No response_

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
I simply removed the `CountUsablePartyMons(battler) > 0` condition because it returns the same result as `CanBattlerSwitch(battler)` but didn't have a ( OR in wild battle)
I also made sure player would flee if triggering emergency exit in wild battle. This is the behavior described on Bulbapedia and I've seen a reddit thread confirming the behavior.
The logic is duplicated in end move and end turn so I also duplicated the tests for each "condition"

## Issue(s) that this PR fixes
Fixes  #7955

## Things to note in the release changelog:
- Emergency exit and Wimp out now makes enemy and player pokemon flee during wild battles

## Discord contact info
Jamie

### CODE REVIEW

File: test/battle/ability/emergency_exit.c [hunk 1]
```diff
@@ -108,3 +108,70 @@ SINGLE_BATTLE_TEST("Emergency Exit activates when taking residual damage and fal
         ABILITY_POPUP(opponent, ABILITY_EMERGENCY_EXIT);
     }
 }
+
+//We do these tests separately for residual damage and move damage because they are handled separately in the code
```
Comment (AlexOn1ine) [inline test/battle/ability/emergency_exit.c]: The comment is not needed since this generally applies to a lot of things in the battle engine.

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -1079,7 +1079,6 @@ bool32 EmergencyExitCanBeTriggered(u32 battler)
      && HadMoreThanHalfHpNowDoesnt(battler)
      && (CanBattlerSwitch(battler) || !(gBattleTypeFlags & BATTLE_TYPE_TRAINER))
      && !(gBattleTypeFlags & BATTLE_TYPE_ARENA)
-     && CountUsablePartyMons(battler) > 0
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:1082]: Non blocking but if you move out the `IsBattlerTurnDamaged(battler)` so 
```
if (IsBattlerTurnDamaged(battler) && EmergencyExitCanBeTriggered(i))
```

This function can be used for both end turn end move end. If you want to do that I would move the function to `battle_util.c`

Non blocking though so the pr can be merged
