### PR TITLE
Fix Protosynthesis stat boosts ignoring speed drops 

### LINKED ISSUE #7738: Sticky Web Protosynthesis Interaction
### Description

If a Flutter Mane with highest stat Speed switches into a field with sun + sticky web, it still gets a Protosynthesis Speed Boost. Intended interaction is to account for the Speed Drop and boost it's Special Attack instead

### Reproduction Steps

See description / video. Make sure to make the Flutter Mane Timid to confirm it's highest stat being Speed.

### Images / Video

https://replay.p

https://github.com/user-attachments/assets/1f5549f9-7ae1-4236-8464-176e64a9e8a2

okemonshowdown.com/gen9customgame-2442028346-s6yil6kqgnjv1eva7595pylhoabp7ebpw

### Version

1.13.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by moostoet**
## Description
Details:

1) Cause
- Both Protosynthesis and Quark Drive picked their boost target via `GetHighestStatId`, which only inspects raw stats (`gBattleMons[battler].attack`, `.speed`, etc.) and never applies stage modifiers. After Sticky Web/Icy Wind lowered Speed, Flutter Mane’s raw Speed still exceeded Sp. Atk, so the ability kept boosting Speed regardless of stat changes.
- Because the boost decision never re-evaluated when weather/terrain re-enabled the abilities, Neutralizing Gas exiting the field still restored the old Speed boost even if Speed was now lower than Sp. Atk.

2) Fix
- Added `GetParadoxHighestStatId` that multiplies each stat by `gStatStageRatios[statStage]` before determining the maximum:
```c
     static u32 GetStatValueWithStages(u32 battler, u32 stat)
{
    u32 statValue;

    switch (stat)
    {
    case STAT_ATK:
        statValue = gBattleMons[battler].attack;
        break;
    case STAT_DEF:
        statValue = gBattleMons[battler].defense;
        break;
    case STAT_SPATK:
        statValue = gBattleMons[battler].spAttack;
        break;
    case STAT_SPDEF:
        statValue = gBattleMons[battler].spDefense;
        break;
    case STAT_SPEED:
        statValue = gBattleMons[battler].speed;
        break;
    default:
        return 0;
    }

    statValue *= gStatStageRatios[gBattleMons[battler].statStages[stat]][0];
    statValue /= gStatStageRatios[gBattleMons[battler].statStages[stat]][1];

    return statValue;
}

u32 GetParadoxHighestStatId(u32 battler)
{
    u32 highestId = STAT_ATK;
    u32 highestStat = GetStatValueWithStages(battler, STAT_ATK);

    for (u32 stat = STAT_DEF; stat < NUM_STATS; stat++)
    {
        if (stat == STAT_SPEED)
            continue;

        u32 statValue = GetStatValueWithStages(battler, stat);
        if (statValue > highestStat)
        {
            highestStat = statValue;
            highestId = stat;
        }
    }

    u32 speed = GetStatValueWithStages(battler, STAT_SPEED);
    if (speed > highestStat)
        highestId = STAT_SPEED;

    return highestId;
}
```
- Replaced every Protosynthesis/Quark Drive lookup with the new helper: activation scripts (`BattleScript_ProtosynthesisActivates` / `BattleScript_QuarkDriveActivates`), damage/survival modifiers in `CalcAttackStat`/`CalcDefenseStat`, and `GetBattlerTotalSpeedStat` so speed turn order reflects the correct boosted stat.
- Weather/terrain activation now buffers the recalculated stat before showing the popup, guaranteeing correct messaging.

3) Other
- Wrote regression tests (`Protosynthesis accounts for Sticky Web`, `Protosynthesis switches to boosting Sp. Atk after Speed is lowered`, and `Protosynthesis recalculates the boosted stat after Neutralizing Gas leaves the field`) to catch any regressions in Neutralizing Gas/Sticky Web interactions

## Media
  N/A

## Issue(s) that this PR fixes
  Fixes #7738.

## Feature(s) this PR does NOT handle:
  N/A

## Things to note in the release changelog:
  - Protosynthesis and Quark Drive now recalculate their boosted stat when Speed is lowered or Neutralizing Gas temporarily disables the ability.

## Discord contact info
viridian.

### CODE REVIEW

**Comment by PhallenTree** [comment]
With the changes from this PR, if you drop the Speed of a mon that has activated QD/Protosynthesis stating that speed would be boosted, it would then change to boost a different stat if it's no longer the highest stat. If this isn't intended, might be better to store the stat when the ability is first activated.
For example, 200 speed 199 attack mon activates QD -> says Speed is increased -> gets Speed lowered by Icy Wind -> now is boosting Attack because Speed was recalculated and determined to be lower than Attack.

**Comment by moostoet** [comment]
> With the changes from this PR, if you drop the Speed of a mon that has activated QD/Protosynthesis stating that speed would be boosted, it would then change to boost a different stat if it's no longer the highest stat. If this isn't intended, might be better to store the stat when the ability is first activated. For example, 200 speed 199 attack mon activates QD -> says Speed is increased -> gets speed lowered by Icy Wind -> now is boosting attack because speed is recalculated to be lower.

 To my knowledge it should determine the stat to boost at the moment the ability activates, and not re-activate or change the stat to boost unless something like NGas re-triggers it. In the case of Sticky Web it lowers speed before the ability activates. Going to take a second look at this when I'm back home to make some changes to the code to take this into account because it shouldn't be recalculating on a whim like that

**Comment by moostoet** [comment]
@PhallenTree - I fixed the logic of Protosynthesis and QD retaining the initial stat boost. I misinterpreted Alex's comment as not being a statement of fact which is why I accidentally implemented the wrong thing 😅

File: include/battle.h [hunk 1]
```diff
@@ -135,6 +135,7 @@ struct DisableStruct
     u8 octolockedBy:3;
     u8 tryEjectPack:1;
     u8 padding:4;
+    u8 paradoxBoostedStat;
```
Comment (PhallenTree) [inline include/battle.h]:
```suggestion
    u8 paradoxBoostedStat:4;
```
Probably doesn't need more than 4 bits.

File: src/battle_util.c [hunk 2]
```diff
@@ -5550,6 +5571,113 @@ bool32 CanBeParalyzed(u32 battlerAtk, u32 battlerDef, u32 abilityDef)
...
+{
+    if (gBattleMons[battler].ability == ABILITY_PROTOSYNTHESIS)
+        gDisableStructs[battler].paradoxBoostedStat = 0;
+}
+
+static void ResetParadoxTerrainStat(u32 battler)
+{
+    if (gBattleMons[battler].ability == ABILITY_QUARK_DRIVE)
+        gDisableStructs[battler].paradoxBoostedStat = 0;
+}
```
Comment (PhallenTree) [inline src/battle_util.c:5658]: These shouldn't reset if QD/Proto were activated due to a Booster Energy.

Comment (moostoet) [reply src/battle_util.c:5658]: Correct, will implement

Comment (moostoet) [reply src/battle_util.c:5658]: @PhallenTree These changes were implemented.

Comment (AlexOn1ine) [reply src/battle_util.c:5658]: Is there a reason `gBattleMons[battler].ability` is used instead of `GetBattlerAbility`?

Comment (moostoet) [reply src/battle_util.c:5658]: Nope - I refactored it to use that, thanks!

File: src/battle_util.c [hunk 3]
```diff
@@ -5550,6 +5571,115 @@ bool32 CanBeParalyzed(u32 battlerAtk, u32 battlerDef, u32 abilityDef)
...
+     && !gDisableStructs[battler].boosterEnergyActivated)
+        gDisableStructs[battler].paradoxBoostedStat = 0;
+}
+
+u32 UpdateParadoxBoostedStat(u32 battler)
+{
+    u32 statId = GetParadoxHighestStatId(battler);
+    gDisableStructs[battler].paradoxBoostedStat = statId;
+    return statId;
+}
```
Comment (AlexOn1ine) [inline src/battle_util.c]: This probably doesn't need to be a function. `gDisableStructs[battler].paradoxBoostedStat` can be moved to `GetParadoxHighestStatId`?

Or it could go to `GetParadoxBoostedStatId`?

File: src/battle_util.c [hunk 4]
```diff
@@ -204,6 +204,9 @@ static const struct BattleWeatherInfo sBattleWeatherInfo[BATTLE_WEATHER_COUNT] =
     },
 };
 
+static void ResetParadoxWeatherStat(u32 battler);
+static void ResetParadoxTerrainStat(u32 battler);
```
Comment (AlexOn1ine) [inline src/battle_util.c]: should go to the top of the file

File: src/battle_util.c (hunk 2 above)
Comment (moostoet) [reply src/battle_util.c:5658]: @AlexOn1ine On second thought I had a deeper look into `GetBattlerAbility` and did find a reason for me to use `gBattleMons[battler].ability`:

- If weather expires while Neutralizing Gas is up, `GetBattlerAbility(battler)` returns `ABILITY_NONE` because NGas is in effect, so the condition in `ResetParadoxWeatherStat()` is false and `gDisableStructs[player].paradoxBoostedStat` never resets

Thoughts on this?

File: src/battle_util.c (hunk 4 above)
Comment (moostoet) [reply src/battle_util.c]: Done

File: src/battle_util.c (hunk 3 above)
Comment (moostoet) [reply src/battle_util.c]: Done

File: src/battle_util.c (hunk 2 above)
Comment (AlexOn1ine) [reply src/battle_util.c:5658]: @PhallenTree I think then the direct ability call is correct?

Comment (PhallenTree) [reply src/battle_util.c:5658]: Actually I don't think the ability check is needed at all. Either `gDisableStructs[battler].paradoxBoostedStat` is already 0 or we want to set it to 0 because it wasn't activated by Booster Energy and the weather/terrain changed.

Comment (AlexOn1ine) [reply src/battle_util.c:5658]: Ah right.

@moostoet you can just remove the functions and set the fields both to 0 in the corresponding loops.

I can merge afterwards. Also conflicts.

Comment (moostoet) [reply src/battle_util.c:5658]: I pushed the changes as requested. @AlexOn1ine @PhallenTree

Comment (moostoet) [reply src/battle_util.c:5658]: Also fixed the conflict (one-liner)

**Review by AlexOn1ine — APPROVED** [review]
