### PR TITLE
Fixes intimidate missing timing during a mega evo / switch

### LINKED ISSUE #6320: Niche Intimidate missing timing
### Description

Some niche sequencing can cause Intimidate to miss it's timing.

- Mega Evolve into a Pokemon with Intimidate (Mega Manectric)
- Use a Hit Escape Move (Flip Turn) into a target that survives the hit
- Choose another Intimidate Pokemon to switch by the Hit Escape Move
- The last Intimidate will not activate.

https://github.com/user-attachments/assets/2cd09b6a-6e6a-4243-bd44-8e90876e2ad7

### Version

1.10.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6320

### CODE REVIEW

File: src/battle_main.c [hunk 1]
```diff
@@ -3259,6 +3259,9 @@ void SwitchInClearSetData(u32 battler)
     gCurrentMove = MOVE_NONE;
     gBattleStruct->arenaTurnCounter = 0xFF;
 
+    // Restore struct memeber so replacement does not miss timing
```
Comment (Bassoonian) [inline src/battle_main.c:3262]:
```suggestion
    // Restore struct member so replacement does not miss timing
```

**Review by Bassoonian — APPROVED** [review]
