### PR TITLE
Fixes Tera Shell activating on moves that have no effect on target

### LINKED ISSUE #6270: Tera Shell activates if Terapagos is immune
### Description

Correct behavior should be no Tera Shell activation
```
SINGLE_BATTLE_TEST("Tera Shell respects immunity")
{
    KNOWN_FAILING;
    GIVEN {
        PLAYER(SPECIES_TERAPAGOS_TERASTAL) { Ability(ABILITY_TERA_SHELL); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(opponent, MOVE_SHADOW_BALL); }
    } SCENE {
        NONE_OF {
            ABILITY_POPUP(player, ABILITY_TERA_SHELL);
            ANIMATION(ANIM_TYPE_MOVE, MOVE_SHADOW_BALL, opponent);
        }
    }
}
```

### Version

1.10.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6270

Additional removed some duplicate code and some minor calc optimization by passing an ability argument instead of calcing. Technically same should be made for attacker ability but that is for an other day.

### CODE REVIEW

File: test/battle/ability/tera_shell.c [hunk 1]
```diff
@@ -97,3 +97,19 @@ DOUBLE_BATTLE_TEST("Tera Shell only makes the first hit against Terapagos from a
         NOT MESSAGE("It's not very effective…");
     }
 }
+
+SINGLE_BATTLE_TEST("Tera Shell respects immunity")
+{
+    // KNOWN_FAILING;
```
Comment (Bassoonian) [inline test/battle/ability/tera_shell.c:103]: This comment doesn't need to stay, does it?

Comment (AlexOn1ine) [reply test/battle/ability/tera_shell.c]: removed

**Review by Bassoonian — APPROVED** [review]
