### PR TITLE
Fixes Liquid Ooze dmg not blocked by Magic Guard

### LINKED ISSUE #8023: Missing Magic Guard check for Liquid Oooze absorb
### Description

Fix:
```diff
 BattleScript_EffectAbsorbLiquidOoze::
        call BattleScript_AbilityPopUpTarget
+       jumpifability BS_ATTACKER, ABILITY_MAGIC_GUARD, BattleScript_EffectAbsorbEnd
        goto BattleScript_EffectAbsorb
 
 BattleScript_EffectAbsorb::
@@ -2561,6 +2562,7 @@ BattleScript_EffectAbsorb::
        printfromtable gAbsorbDrainStringIds
        waitmessage B_WAIT_TIME_LONG
        tryfaintmon BS_ATTACKER
+BattleScript_EffectAbsorbEnd:
        return
```

### Reproduction Steps

code

### Images / Video

_No response_

### Version

1.13.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #8023

### CODE REVIEW

File: test/battle/ability/liquid_ooze.c [hunk 1]
```diff
@@ -187,3 +187,34 @@ SINGLE_BATTLE_TEST("Liquid Ooze does not cause Dream Eater users to lose HP inst
         EXPECT_LT(damage, 0); // Negative damage = Heal
     }
 }
+
+SINGLE_BATTLE_TEST("Liquid Ooze hp lose from Absorb is blocked by Magic Guard")
```
Comment (Bassoonian) [inline test/battle/ability/liquid_ooze.c]:
```suggestion
SINGLE_BATTLE_TEST("Liquid Ooze HP loss from Absorb is blocked by Magic Guard")
```

File: test/battle/ability/liquid_ooze.c [hunk 2]
```diff
@@ -187,3 +187,34 @@ SINGLE_BATTLE_TEST("Liquid Ooze does not cause Dream Eater users to lose HP inst
...
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_ABSORB, player);
+        HP_BAR(opponent);
+        NONE_OF {
+            HP_BAR(player);
+            MESSAGE("Wobbuffet sucked up the liquid ooze!");
+        }
+    }
+}
+
+SINGLE_BATTLE_TEST("Liquid Ooze hp lose from Leech Seed is blocked by Magic Guard")
```
Comment (Bassoonian) [inline test/battle/ability/liquid_ooze.c]:
```suggestion
SINGLE_BATTLE_TEST("Liquid Ooze HP loss from Leech Seed is blocked by Magic Guard")
```

**Review by hedara90 — APPROVED** [review]
