### PR TITLE
Fixes Disguise + Counter/Mirror Coat/Metal Burst + Disguise tests

### LINKED ISSUE #8487: Disguise with Counter/Mirror Coat/Metal Burst
### Description

According to [jpwiki](https://wiki.xn--rckteqa2e.com/wiki/%E3%81%B0%E3%81%91%E3%81%AE%E3%81%8B%E3%82%8F), when Disguise blocks a move, any Counter/Mirror Coat/Metal Burst should counter for 1 damage (at least since Gen 8). We don't currently have a very good way to do this, since the equivalent for `gProtectStructs[battler].physicalDmg`/`gProtectStructs[battler].specialDmg` likely has a value of 0, which would be why it would deal 1 damage.

Other Disguise interactions worth testing:
- Recoil moves that deal damage blocked by Disguise cause 0 recoil (same with absorption moves);
- Kee/Maranga berries do not activate in Gen 9 when damage is blocked by Disguise;
- Items affected by type effectiveness (Weakness berries, Enigma berry and Weakness Policy) do not activate;

### Reproduction Steps

.

### Images / Video

_No response_

### Version

1.14.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by PhallenTree**
Fixes Disguise + Counter/Mirror Coat/Metal Burst interaction by setting the values of `physicalDmg`/`specialDmg` to 1 + the damage dealt by the move.

Fixes Disguise activating Weakness berries.

Added Disguise tests (chose to add to their respective effect files instead of Disguise's file).

## Issue(s) that this PR fixes
Fixes #8487 (except Kee/Maranga tests, but those can be added later)

## Discord contact info
PhallenTree

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -11346,6 +11352,13 @@ static void Cmd_unused_0xA0(void)
 {
 }
 
+static void CalcCounterMirrorCoatMetalBurstDamage(u32 baseDamage, u32 percentMult)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: Maybe just `CalcReflectBackDamage`?

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -2371,18 +2377,19 @@ static void MoveDamageDataHpUpdate(u32 battler, u32 scriptBattler, const u8 *nex
...
-            return;
         }
+        return;
     }
     else if (DoesDisguiseBlockMove(battler, gCurrentMove))
     {
         // TODO: Convert this to a proper FORM_CHANGE type.
         gBattleScripting.battler = battler;
+        gBattleStruct->moveDamage[battler] = 0;
+        gBattleStruct->moveResultFlags[battler] &= ~(MOVE_RESULT_NOT_VERY_EFFECTIVE | MOVE_RESULT_SUPER_EFFECTIVE);
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:2392]: Wouldn't this cause issues with moveend?

Comment (AlexOn1ine) [reply src/battle_script_commands.c:2392]: ah, wait I see

File: src/battle_script_commands.c [hunk 3]
```diff
@@ -2453,6 +2438,27 @@ static void MoveDamageDataHpUpdate(u32 battler, u32 scriptBattler, const u8 *nex
...
     }
 
+    // Note: While physicalDmg/specialDmg below are only distinguished between for Counter/Mirror Coat,
+    //       they are used in combination as general damage trackers for other purposes.
+    if (IsBattleMovePhysical(gCurrentMove))
+    {
+        gProtectStructs[battler].physicalDmg = gBattleStruct->moveDamage[battler] + 1;
+        gSpecialStatuses[battler].physicalDmg = gBattleStruct->moveDamage[battler] + 1;
+        if (scriptBattler == BS_TARGET) // What's the point of this??? It will be always target
+            gProtectStructs[battler].physicalBattlerId = gBattlerAttacker;
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: could you maybe remove the else branch? At least I can't think of a reason why we need to check for target

Comment (PhallenTree) [reply src/battle_script_commands.c]: Done

File: test/battle/move_effect/mirror_coat.c [hunk 4]
```diff
@@ -1,4 +1,131 @@
...
+        }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_FOLLOW_ME, opponentRight);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROUND, opponentLeft);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_MIRROR_COAT, playerLeft);
+        HP_BAR(opponentRight);
+    }
+}
+
+DOUBLE_BATTLE_TEST("Mirror Coat fails if mon that damaged mirrorCoat user is no longer on the field")
```
Comment (AlexOn1ine) [inline test/battle/move_effect/mirror_coat.c]: I think this is only true for gen1-4. Since Gen5+ the attack is redirected to the partner.

Comment (PhallenTree) [reply test/battle/move_effect/mirror_coat.c]: I just copied Counter's tests, should both be removed?

Comment (AlexOn1ine) [reply test/battle/move_effect/mirror_coat.c]: no, I just wanted to bring it up lol

I would add a (Gen1-4) in the test description
