### PR TITLE
Fixed ACE_POKEMON_FUNCTIONALITY

### LINKED ISSUE #2333: [Critical] Trainer parties are currently broken.
Tested on dev_1.x branch
I think this might be happening due to some switch logic changed recently, I think he's switching out to his next pokémon + 1.
I changed the sParty_Rick to:
```
static const struct TrainerMonNoItemDefaultMoves sParty_Rick[] = {
    {
        .iv = 0,
        .lvl = 9,
        .species = SPECIES_WEEDLE,
    },
    {
        .iv = 0,
        .lvl = 9,
        .species = SPECIES_KAKUNA,
    },
    {
        .iv = 0,
        .lvl = 9,
        .species = SPECIES_CATERPIE,
    },
    {
        .iv = 0,
        .lvl = 9,
        .species = SPECIES_METAPOD,
    },
};
```

Gif:
mGBA_U0RCCbwGPn

Save:
[pokeemerald.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/9592434/pokeemerald.zip)

### PR DESCRIPTION
**Pull request by Porygon23**
EDITED by @AsparagusEduardo:
- Fixes #2333.

Original description
> Removed ACE_POKEMON_FUNCTIONALITY.

> For some reason, if this AI Flag was not turned on, this skipped over the functionality of choosing the next pokemon inline.
> Functionality works when this flag is enabled, but not when it is not...?

>Removing functionality for now. I will fix it with another pull request.

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
We should first try to fix it before removing it. It's not good looking leaving commented out code like this

File: include/constants/battle_ai.h [hunk 1]
```diff
@@ -56,7 +56,7 @@
 #define AI_FLAG_STALL                 (1 << 13)  // AI stalls battle and prefers secondary damage/trapping/etc. TODO not finished
 #define AI_FLAG_SCREENER              (1 << 14)  // AI prefers screening effects like reflect, mist, etc. TODO unfinished
 #define AI_FLAG_SMART_SWITCHING       (1 << 15)  // AI includes a lot more switching checks
-#define AI_FLAG_ACE_POKEMON           (1 << 16)  // AI has Ace Pokemon. The last Pokemon in the party will not used until last remaining.
+//#define AI_FLAG_ACE_POKEMON           (1 << 16)  // AI has Ace Pokemon. The last Pokemon in the party will not used until last remaining.
```
Comment (AsparagusEduardo) [inline include/constants/battle_ai.h:59]:
```suggestion
#define AI_FLAG_ACE_POKEMON           (1 << 16)  // AI has an Ace Pokemon. The last Pokemon in the party will not be used until it's the last one remaining.
```

File: src/battle_ai_switch_items.c [hunk 2]
```diff
@@ -109,9 +109,9 @@ static bool8 ShouldSwitchIfWonderGuard(void)
             continue;
         if (i == gBattlerPartyIndexes[gActiveBattler])
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:112]:
```suggestion
        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
```

File: src/battle_ai_switch_items.c [hunk 3]
```diff
@@ -109,9 +109,9 @@ static bool8 ShouldSwitchIfWonderGuard(void)
             continue;
         if (i == gBattlerPartyIndexes[gActiveBattler])
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
             && i == (CalculateEnemyPartyCount()-1))
-            continue;
+            continue;*/
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:114]:
```suggestion
            continue;
```

File: src/battle_ai_switch_items.c [hunk 4]
```diff
@@ -202,9 +202,9 @@ static bool8 FindMonThatAbsorbsOpponentsMove(void)
             continue;
         if (i == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:205]:
```suggestion
        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
```

File: src/battle_ai_switch_items.c [hunk 5]
```diff
@@ -202,9 +202,9 @@ static bool8 FindMonThatAbsorbsOpponentsMove(void)
             continue;
         if (i == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
             && i == (CalculateEnemyPartyCount()-1))
-            continue;
+            continue;*/
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:207]:
```suggestion
            continue;
```

File: src/battle_ai_switch_items.c [hunk 6]
```diff
@@ -283,9 +283,9 @@ static bool8 ShouldSwitchIfGameStatePrompt(void)
                     
                         for (i = firstId; i < lastId; i++)
                         {
-                            if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+                            /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:286]:
```suggestion
                            if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
```

File: src/battle_ai_switch_items.c [hunk 7]
```diff
@@ -283,9 +283,9 @@ static bool8 ShouldSwitchIfGameStatePrompt(void)
                     
                         for (i = firstId; i < lastId; i++)
                         {
-                            if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+                            /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
                                 && i == (CalculateEnemyPartyCount()-1))
-                                break;
+                                break;*/
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:288]:
```suggestion
                                break;
```

File: src/battle_ai_switch_items.c [hunk 8]
```diff
@@ -574,9 +574,9 @@ static bool8 FindMonWithFlagsAndSuperEffective(u16 flags, u8 moduloPercent)
             continue;
         if (i == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:577]:
```suggestion
        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
```

File: src/battle_ai_switch_items.c [hunk 9]
```diff
@@ -574,9 +574,9 @@ static bool8 FindMonWithFlagsAndSuperEffective(u16 flags, u8 moduloPercent)
             continue;
         if (i == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
             && i == (CalculateEnemyPartyCount()-1))
-            continue;
+            continue;*/
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:579]:
```suggestion
            continue;
```

File: src/battle_ai_switch_items.c [hunk 10]
```diff
@@ -666,9 +666,9 @@ bool32 ShouldSwitch(void)
             continue;
         if (i == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
             continue;
-        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
+        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:669]:
```suggestion
        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```

File: src/battle_ai_switch_items.c [hunk 11]
```diff
@@ -666,9 +666,9 @@ bool32 ShouldSwitch(void)
...
             && i == (CalculateEnemyPartyCount()-1))
-            continue;
+            continue;*/
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:671]:
```suggestion
            continue;
```

File: src/battle_ai_switch_items.c [hunk 12]
```diff
@@ -756,9 +756,9 @@ void AI_TrySwitchOrUseItem(void)
                             continue;
                         if (monToSwitchId == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
                             continue;
-                        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+                        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:759]:
```suggestion
                        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
```

File: src/battle_ai_switch_items.c [hunk 13]
```diff
@@ -756,9 +756,9 @@ void AI_TrySwitchOrUseItem(void)
                             continue;
                         if (monToSwitchId == *(gBattleStruct->monToSwitchIntoId + battlerIn2))
                             continue;
-                        if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+                        /*if (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
                             && monToSwitchId == (CalculateEnemyPartyCount()-1))
-                            continue;
+                            continue;*/
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:761]:
```suggestion
                            continue;
```

File: src/battle_ai_switch_items.c [hunk 14]
```diff
@@ -957,8 +957,8 @@ u8 GetMostSuitableMonToSwitchInto(void)
             || i == *(gBattleStruct->monToSwitchIntoId + battlerIn1)
             || i == *(gBattleStruct->monToSwitchIntoId + battlerIn2)
             || (GetMonAbility(&party[i]) == ABILITY_TRUANT && IsTruantMonVulnerable(gActiveBattler, opposingBattler)) // While not really invalid per say, not really wise to switch into this mon.
-            || (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
-                && i == (CalculateEnemyPartyCount()-1))) //Save Ace Pokemon for last
+            /*|| (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON 
+                && i == (CalculateEnemyPartyCount()-1))*/) //Save Ace Pokemon for last
```
Comment (AsparagusEduardo) [inline src/battle_ai_switch_items.c:961]:
```suggestion
            || ((AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON)
                && i == (CalculateEnemyPartyCount() - 1))) //Save Ace Pokemon for last
```

File: src/battle_controller_opponent.c [hunk 15]
```diff
@@ -1699,9 +1699,9 @@ static void OpponentHandleChoosePokemon(void)
                 if (GetMonData(&gEnemyParty[chosenMonId], MON_DATA_HP) != 0
                     && chosenMonId != gBattlerPartyIndexes[battler1]
                     && chosenMonId != gBattlerPartyIndexes[battler2]
-                    && (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
+                    /*&& (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
                         && (!(chosenMonId == (CalculateEnemyPartyCount()-1))
```
Comment (AsparagusEduardo) [inline src/battle_controller_opponent.c:1703]:
```suggestion
                    && (!(AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON)
                        || chosenMonId != CalculateEnemyPartyCount() - 1
```

File: src/battle_controller_opponent.c [hunk 16]
```diff
@@ -1699,9 +1699,9 @@ static void OpponentHandleChoosePokemon(void)
...
-                            || CountAIAliveNonEggMonsExcept(PARTY_SIZE) == pokemonInBattle)))
+                            || CountAIAliveNonEggMonsExcept(PARTY_SIZE) == pokemonInBattle))*/)
```
Comment (AsparagusEduardo) [inline src/battle_controller_opponent.c:1704]:
```suggestion
                            || CountAIAliveNonEggMonsExcept(PARTY_SIZE) == pokemonInBattle))
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: src/battle_controller_opponent.c [hunk 17]
```diff
@@ -1699,9 +1699,9 @@ static void OpponentHandleChoosePokemon(void)
                 if (GetMonData(&gEnemyParty[chosenMonId], MON_DATA_HP) != 0
                     && chosenMonId != gBattlerPartyIndexes[battler1]
                     && chosenMonId != gBattlerPartyIndexes[battler2]
-                    && (AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON
-                        && (!(chosenMonId == (CalculateEnemyPartyCount()-1))
-                            || CountAIAliveNonEggMonsExcept(PARTY_SIZE) == pokemonInBattle)))
+                    && (!(AI_THINKING_STRUCT->aiFlags & AI_FLAG_ACE_POKEMON)
+                        || chosenMonId != CalculateEnemyPartyCount() - 1
+                            || CountAIAliveNonEggMonsExcept(PARTY_SIZE) == pokemonInBattle))
```
Comment (AsparagusEduardo) [inline src/battle_controller_opponent.c:1704]:
```suggestion
                        || CountAIAliveNonEggMonsExcept(PARTY_SIZE) == pokemonInBattle))
```

**Review by AsparagusEduardo — APPROVED** [review]
