### PR TITLE
Fix Tranformed mon changing forms when fainting

### LINKED ISSUE #9103: Fainting after transforming permanently changes species to that of alternate form target
### Description

When a Pokemon in the player's party transforms into an enemy Pokemon in an alternate form (e.g., mega, primal, etc.) and subsequently faints, it will permanently become the species the target that it transformed into. I have observed the same for several mega evolutions, Aegislash blade form, Cramorant gulping form, and Mimikyu busted form. Transforming via ability (Imposter) or move (Transform) will yield the same result.

### Reproduction Steps

Allow an enemy Pokemon to transform into any alternate form, then send out a Ditto with Imposter to transform into the enemy Pokemon. Then, allow Ditto to faint. Finally, check your party menu. You should see that Ditto has been replaced with the species of the Pokemon it previously transformed into.

### Images / Video

https://github.com/user-attachments/assets/3a77d8c0-07e9-479e-96bb-ca049e3ee09f

### Version

1.14.2 (Latest release)

### Upcoming/master Version

d12929ffbd672e13f9cfe6a276c5ceb0110b6c07

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Issue(s) that this PR fixes
Fixes #9103

## Discord contact info
AsparagusEduardo

### CODE REVIEW

File: src/battle_main.c [hunk 1]
```diff
@@ -3304,8 +3304,10 @@ const u8* FaintClearSetData(u32 battler)
         gBattleMons[battler].statStages[i] = DEFAULT_STAT_STAGE;
 
     bool32 keepGastroAcid = gBattleMons[battler].volatiles.gastroAcid;
+    bool32 keepTransformed = gBattleMons[battler].volatiles.transformed;
     memset(&gBattleMons[battler].volatiles, 0, sizeof(struct Volatiles));
     gBattleMons[battler].volatiles.gastroAcid = keepGastroAcid; // Edge case: Keep Gastro Acid if pokemon's ability can have effect after fainting, for example Innards Out.
+    gBattleMons[battler].volatiles.transformed = keepTransformed; // Edge case: Keep Transformed status to prevent triggering FORM_CHANGE_FAINT on transformed mons.
```
Comment (AlexOn1ine) [inline src/battle_main.c:3310]: I wonder if both of those are spilled over to the next battler and we would need to clear them on switch in for the next battler

Comment (AsparagusEduardo) [reply src/battle_main.c:3310]: > I wonder if both of those are spilled over to the next battler and we would need to clear them on switch in for the next battler

I'm pretty sure they're being cleared in `SwitchInClearSetData` (called by `switchindataupdate`)

Comment (AlexOn1ine) [reply src/battle_main.c:3310]: Right, i forgor
