### PR TITLE
Illusion struct cleanup and many Illusion fixes

### LINKED ISSUE #5015: Illusion does not properly cancel when the user Terastalizes
### Description

Illusion is supposed to cancel with the usual message when the user Terastalizes, but currently the sprite is only replaced, name and sprite offsets are still using old values, along with the name.
Might be related to other Illusion issues like #4526. 
```
SINGLE_BATTLE_TEST("(TERA) Illusion breaks if the pokemon Terastalizes")
{
    KNOWN_FAILING;  // #5015                         
    u32 species;                      
    PARAMETRIZE { species = SPECIES_TERAPAGOS; }
    PARAMETRIZE { species = SPECIES_WOBBUFFET; }
    GIVEN {                                          
        PLAYER(SPECIES_ZOROARK) { TeraType(TYPE_DARK); }
        PLAYER(species);
        OPPONENT(SPECIES_WOBBUFFET);                                 
    } WHEN {
        TURN { MOVE(player, MOVE_CELEBRATE, gimmick: GIMMICK_TERA); }
    } SCENE {
        MESSAGE("Zoroark's Illusion wore off!");                                                                                            
    }
}
```
pokeemerald-test-2

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

hedara

### LINKED ISSUE #6611: Illusion is not taken into consideration when Terastallizing
### Description

- When a battler with Illusion Terastallizes, the mon displayed should still be the one that the battler is imitating. Currently it displays Zoroark, but still uses display values (name and sprite offsets) used by the mon that Zoroark should be imitating, as displayed on #5015.
- It's likely that after fixing this, when Zoroark is hit and the Illusion wears off, Zoroark may be displayed without the usual Terastallization effect.

The previously described issues may also occur with Dynamax, however I have not tested it.

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by PhallenTree**
- Adds an enum `IllusionState` that replaces the previously existing `set` and `on`. Removed `broken` and `partyId` as they don't have much of a purpose.

- Adds missing activations of Illusion when Illusion is no longer in effect (when `GetBattlerAbility` != Illusion) - Worry Seed, Gastro Acid and Neutralizing Gas (timing for the first 2 may be wrong).

https://github.com/user-attachments/assets/7d3db8c3-ad4d-4eb3-8958-815caef21d30

- Fixes Gimmicks resetting the sprite to Zoroark/the battler with Illusion.

https://github.com/user-attachments/assets/7ca41f6e-a583-4170-baef-08175052a3d6

- Fixes Terastallizing while disguised as Ogerpon/Terapagos not causing Illusion to fade (Bug: when the Illusion fades, Zoroark already has the Tera color applied to it).

https://github.com/user-attachments/assets/7a71fe90-192e-4a53-8e47-26bfa1b6ed75

- Fixes being able to Dynamax while disguised as Zacian, Zamazenta or Eternatus.

- Fixes KO Animation using the original species' (Zoroark/the battler with Illusion) animations instead of the animations of the mon visible.

- Fixes battler nickname in Ability Popups not accounting for Illusion correctly.

https://github.com/user-attachments/assets/067b8057-5783-45df-96f8-b7b34ce132b6

- Fixes Insomnia/Vital Spirit preventing sleep message potentially mentioning the wrong battler.

## Issue(s) that this PR fixes
Fixes #6611, fixes #5015

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -10334,18 +10334,44 @@ bool32 CanBattlerGetOrLoseItem(u32 battler, u16 itemId)
...
 
+u32 GetBattlerVisualSpecies(u32 battler)
+{
+    u32 illusionSpecies = GetIllusionMonSpecies(battler);
+    if (illusionSpecies != SPECIES_NONE)
+        return illusionSpecies;
+    return gBattleMons[battler].species;
+}
+
+bool32 TryClearIllusion(u32 battler, bool32 end3)
```
Comment (AlexOn1ine) [inline src/battle_util.c:10345]: There are a couple enums in the repo for running different scripts. any change one could be used here?

**Review by AlexOn1ine — APPROVED** [review]
