### PR TITLE
Fix target cancelling not working properly with z-move

### LINKED ISSUE #6688: Bugs related to Z move and buttons in doubles matches
### Description

In the **doubles** battle, pokemon carries the Z crystal and clicks start to trigger the Z move. 
First, press **button A** to select the attack target, then press **button B**. At this point, press the **directional keys** (up, down, left, right) and discover a bug in the Z move（as shown in the video).

https://github.com/user-attachments/assets/7b2457d6-dba4-4748-b11a-03217dcb4e68

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
When canceling target while zmove is active, I make sure to disable z-move and when moving back to move selection

## Media
master:

https://github.com/user-attachments/assets/5efbd70a-44f7-4113-88c8-43637ad2e5a2

This commit:

https://github.com/user-attachments/assets/976a12a9-0539-4b92-9d10-5fcc582d74a5

## Issue(s) that this PR fixes
Fixes #6688

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_controller_player.c [hunk 1]
```diff
@@ -454,6 +454,12 @@ void HandleInputChooseTarget(u32 battler)
         PlaySE(SE_SELECT);
         gSprites[gBattlerSpriteIds[gMultiUsePlayerCursor]].callback = SpriteCB_HideAsMoveTarget;
         gBattlerControllerFuncs[battler] = HandleInputChooseMove;
+        if (gBattleStruct->gimmick.playerSelect == 1 && gBattleStruct->gimmick.usableGimmick[battler] == GIMMICK_Z_MOVE)
+        {
+            gBattleStruct->gimmick.playerSelect = 0;
+            gBattleStruct->zmove.viewing = TRUE;
```
Comment (AlexOn1ine) [inline src/battle_controller_player.c:460]: shouldn't this be set to false?

Comment (FosterProgramming) [reply src/battle_controller_player.c:460]: Looks a bit confusing, but when the function that is called after, look at the current zmove.viewing, inverts it and sets the right view (regular moves or z-move) so this is correct
