### PR TITLE
Fix for uncaught mon with terrain active

### LINKED ISSUE #7695: bug: catching uncaught mon with terrain active glitches rename message after dex info
### Description

when you catch a pokemon that is new to your dex, and the battle had a terrain active (misty/electric were the two i tested), after the dex info is displayed, the screen gets corrupted when you are asked if you want to rename your pokemon.

### Reproduction Steps

1) enter wild battle with terrain, via environment or move; 
2) catch the wild pokemon while the terrain is still active
3) after dex info is shown, the rename prompt screen gets corrupted

### Images / Video

Image

### Version

upcoming (Edge)

### Upcoming/master Version

04223403565cea2b11efce61ad3a36731343bd9a

### Discord contact info

khbsd

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #7695

The issue was that the game runs out of heap by the time the terrain's gfx are decompressed. `SetMultiuseSpriteTemplateToPokemon` requires less heap than `CreateMonPicSprite`, so it works.

terrain

Though I guess we could do something(debug printf message?) when trying to decompress .smol without necessary heap.

### CODE REVIEW

**Comment by hedara90** [comment]
We could add another error case to the compression error reporter, though that is a hard crash.

File: src/pokedex.c [hunk 1]
```diff
@@ -4021,8 +4022,8 @@ static void HighlightSubmenuScreenSelectBarItem(u8 a, u16 b)
 #define tPalTimer      data[2]
 #define tMonSpriteId   data[3]
 #define tIsShiny       data[13]
-#define tPersonalityLo data[14]
-#define tPersonalityHi data[15]
+#define tPersonalityLo 14
+#define tPersonalityHi 15
```
Comment (hedara90) [inline src/pokedex.c:4026]: Why was this changed?
It's a change from how the other data fields are used here.

Comment (DizzyEggg) [reply src/pokedex.c:4026]: So that I could use GetWordTaskArg
