### PR TITLE
Fix wrong palette for types sprites in hgss dex after catching mon

### LINKED ISSUE #8120: Wrong palette for Grass and Bug icons for newly caught Pokemon in the HGSS Dex
### Description

When catching a new Grass or Bug-type Pokemon with the HGSS Pokedex active, the palette for those types' icons is not correct

### Reproduction Steps

1. Enabled the HGSS Pokedex
2. Catch a previously uncaught Grass or Bug-type Pokemon

### Images / Video

Image

Image

### Version

upcoming (Edge)

### Upcoming/master Version

d95c6427b041bc8b5aa5f996c44665aecc96eff2

### Discord contact info

Frankfurter

### PR DESCRIPTION
**Pull request by FosterProgramming**
When showing hgss dex after capturing a mon
the caught mon would use palette slot 15 while the types sprites would use palette slots 13, 14 15
causing the wrong palette to load for some of the types
I changed the types sprites palettes to be 12, 13, 14 instead

## Media

master:

https://github.com/user-attachments/assets/e2f41f29-3848-47ce-9711-158d662789c5

this commit:

https://github.com/user-attachments/assets/ff9532f3-9f67-428a-b13c-47e35d05e54a

## Issue(s) that this PR fixes
Fixes #8120

## Discord contact info
Jamie

### CODE REVIEW

File: src/pokedex_plus_hgss.c [hunk 1]
```diff
@@ -4088,6 +4088,12 @@ static void UNUSED HighlightScreenSelectBarItem(u8 selectedScreen, u16 unused)
 #define tPersonalityLo data[14]
 #define tPersonalityHi data[15]
 
+// Types palettes need to be loaded at a different slot than anticipated by gTypesInfo
+// to avoid overlapping with caught mon sprite platte slot
+// Normarl type info palette slots: 13 , 14 and 15
+// Caugh mon palette slot: 15
```
Comment (Bassoonian) [inline src/pokedex_plus_hgss.c]:
```suggestion
// to avoid overlapping with caught mon sprite palatte slot
// Normal type info palette slots: 13 ,14 and 15
// Caught mon palette slot: 15
```

File: src/pokedex_plus_hgss.c [hunk 2]
```diff
@@ -4088,6 +4088,12 @@ static void UNUSED HighlightScreenSelectBarItem(u8 selectedScreen, u16 unused)
...
+#define TYPE_INFO_PALETTE_NUM_OFFSET 1
```
Comment (Bassoonian) [inline src/pokedex_plus_hgss.c]: Could we have this be ``- 1`` instead to make it more clear it's a negative offset? With the logic below being adapted to deal with this, of course

**Review by Bassoonian — APPROVED** [review]
