### PR TITLE
Fixes commander activation on a fainted mon

### LINKED ISSUE #6612: Ability commander bugs in double battles.
### Description

1. During a double battle, the initial releases were Tatsugiri and Cyclizar, and Cyclizar replaced Dondozo with Shed Tail. Ability Commander was successfully triggered, but at this point, Dondozo would freeze if attempting to use skills.

2.During a double battle, the first release were Tatsugiri and Dondozo, and ability Commander is successfully triggered. But if the enemy uses Dragon Tail (a forced replacement move?), it will get stuck.

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6612

### CODE REVIEW

File: test/battle/ability/commander.c [hunk 1]
```diff
@@ -421,3 +421,37 @@ DOUBLE_BATTLE_TEST("Commander Tatsugiri does not get hit by Dragon Darts when co
         NOT HP_BAR(playerLeft);
     }
 }
+
+DOUBLE_BATTLE_TEST("Commander will not activate if Donodozo fainted right before Tatsugiri came in")
```
Comment (Bassoonian) [inline test/battle/ability/commander.c:425]:
```suggestion
DOUBLE_BATTLE_TEST("Commander will not activate if Dondozo fainted right before Tatsugiri came in")
```

File: test/battle/ability/commander.c [hunk 2]
```diff
@@ -421,3 +421,37 @@ DOUBLE_BATTLE_TEST("Commander Tatsugiri does not get hit by Dragon Darts when co
...
+        OPPONENT(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(opponentRight, MOVE_TACKLE, target: playerRight); MOVE(playerLeft, MOVE_SHED_TAIL); SEND_OUT(playerLeft, 2); SEND_OUT(playerRight, 3); }
+    } SCENE {
+        NOT ABILITY_POPUP(playerLeft, ABILITY_COMMANDER);
+    }
+}
+
+DOUBLE_BATTLE_TEST("Commander prevent Donozo from switch out by Dragon Tail")
```
Comment (Bassoonian) [inline test/battle/ability/commander.c:441]:
```suggestion
DOUBLE_BATTLE_TEST("Commander prevent Dondozo from switch out by Dragon Tail")
```

**Review by Bassoonian — APPROVED** [review]
