### PR TITLE
Fixes Rapid Spin and target defrost not being blocked by Sheer Force

### LINKED ISSUE #9248: Gen 9 Rapid Spin's effects are blocked by Sheer Force
### Description

Up until Gen 8, Rapid Spin's effect wasn't blocked by Sheer Force. The Speed boost added in Gen 8 was blocked by Sheer Force.
In Gen 9, both effects are blocked by Sheer Force.
Therefore, it's possible the timing of Rapid Spin removing hazards has changed.
Source: [jpwiki](https://wiki.xn--rckteqa2e.com/wiki/%E3%81%93%E3%81%86%E3%81%9D%E3%81%8F%E3%82%B9%E3%83%94%E3%83%B3)

### Reproduction Steps

.

### Images / Video

_No response_

### Version

1.14.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by PhallenTree**
Fixes Rapid Spin's blowing away hazards/certain statuses and target defrost (by moves that can burn only) not being blocked by Sheer Force and rearranged moveend order for these.

Also reorders Pickpocket and Eject Pack activations.

Sources: [Defrost](https://wiki.xn--rckteqa2e.com/wiki/%E3%81%93%E3%81%8A%E3%82%8A_(%E7%8A%B6%E6%85%8B%E7%95%B0%E5%B8%B8)#%E7%9B%B8%E6%89%8B%E3%82%92%E5%9B%9E%E5%BE%A9), [Rapid Spin](https://wiki.xn--rckteqa2e.com/wiki/%E3%81%93%E3%81%86%E3%81%9D%E3%81%8F%E3%82%B9%E3%83%94%E3%83%B3#%E6%8A%80%E3%81%AE%E4%BB%95%E6%A7%98)

## Issue(s) that this PR fixes
Fixes #9248

## Feature(s) this PR does NOT handle:
Doesn't handle Gen 8 behavior where Sheer Force + Rapid Spin only prevents the speed boost.

## Discord contact info
PhallenTree

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -11650,11 +11650,11 @@ static bool32 CanAbilityPreventStatLoss(enum Ability abilityDef)
     return FALSE;
 }
 
-bool32 CanBurnHitThaw(enum Move move)
+bool32 CanBurnHitThaw(enum Ability abilityAtk, enum Move move)
 {
     u8 i;
 
-    if (GetConfig(CONFIG_BURN_HIT_THAW) >= GEN_6)
+    if (GetConfig(CONFIG_BURN_HIT_THAW) >= GEN_6 && abilityAtk != ABILITY_SHEER_FORCE)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:11657]: Does that mean a Fire Move that has an additional burn effect, isn't blocked by Sheer Force but a non fire move that has the burn effect would be blocked?

Comment (PhallenTree) [reply src/battle_script_commands.c:11657]: Yes, that's what jpwiki says

File: src/battle_move_resolution.c [hunk 2]
```diff
@@ -2864,6 +2829,71 @@ static enum MoveEndResult MoveEndMultihitMove(void)
...
+        if (gBattleMons[battler].status1 & STATUS1_FREEZE
+         && IsBattlerTurnDamaged(battler)
+         && IsBattlerAlive(battler)
+         && GetBattleMoveType(gCurrentMove) == TYPE_FIRE)
+        {
+            gBattleScripting.battler = battler;
+            gBattleMons[battler].status1 &= ~STATUS1_FREEZE;
+            BtlController_EmitSetMonData(battler, B_COMM_TO_CONTROLLER, REQUEST_STATUS_BATTLE, 0, sizeof(gBattleMons[battler].status1), &gBattleMons[battler].status1);
+            MarkBattlerForControllerExec(battler);
+            BattleScriptCall(BattleScript_DefrostedViaFireMove);
```
Comment (AlexOn1ine) [inline src/battle_move_resolution.c]: I think the code is identical so we could you a function in this case? 
```C
static void DefrostTarget(enum BattlerId battler, u32 status)
{
    gBattleScripting.battler = battler;
    gBattleMons[battler].status1 &= ~status;
    BtlController_EmitSetMonData(battler, B_COMM_TO_CONTROLLER, REQUEST_STATUS_BATTLE, 0, sizeof(gBattleMons[battler].status1), &gBattleMons[battler].status1);
    MarkBattlerForControllerExec(battler);
    BattleScriptCall(BattleScript_DefrostedViaFireMove);
}
```

**Review by AlexOn1ine — APPROVED** [review]
