### PR TITLE
Fix substitute follower appearing with dead party

### LINKED ISSUE #9013: B_FLAG_NO_WHITEOUT and HealPlayerParty desync: follower pokemon is replaced with substitute doll after battle
### Description

NOTE: Tested with 1.13, dont know if this exists for 1.14

See the reproduction steps for a description.

Basically, there is a de-sync involved with scripted losses when `HealPlayerParty` is called. I think ideally, what's supposed to happen is that after the battle, a substitute doll is not supposed to come out. When the player loses, `ReturnToFieldLocal` (which is called before `HealPlayerParty`) does `UpdateFollowingPokemon`. Then, if the player walks around, then at this point, the `ReturnToFieldLocal` sets a substitute doll, so that's what we see. But then, if a player does another `ReturnToFieldLocal` call by reloading the map (easiest: opening some menu), the follower data is set correctly.

I [fixed it in my hack](https://github.com/magical-ice-winged-otter/islandgame3/commit/bb313cbe85b5fb64423c41550583b2a35d5cc7d9#diff-dcf69379dc1632054ee142ffde1654c1c89bd7d709495e2533c749691c088cd0) by simply adding `UpdateFollowingPokemon` at the end of `HealPlayerParty`, but I don't really know if that's the proper fix to submit to expansion.

### Reproduction Steps

Walk up to some trainer with your follower pokemon out, and have the below script run.
```poryscript
script SomeScript {
setflag(FLAG_NO_WHITEOUT)
trainerbattle_no_intro(<SOME_TRAINER>, <SOME_DEFEATED_TEXT>)
....
// Later down the line, heal the player party. NOTE: in order to reproduce properly, you need to actually lose.
special(HealPlayerParty)
```
Walk away, and you will see the substitute doll, when instead we should see the 1st followable pokemon in the party.

### Images / Video

Buggy version: https://github.com/user-attachments/assets/21d07819-4600-4542-aa7f-39d330454261
After the fix: https://github.com/user-attachments/assets/879d5e8d-e38c-49fb-afea-441577d93edc

### Version

1.13.0

### Upcoming/master Version

_No response_

### Discord contact info

accelgor

### PR DESCRIPTION
**Pull request by FosterProgramming**
The function that picks a follower from the alive mons in your party can return empty party slots creating the substitute

Video were recorded on upcoming because it was easier to set up tests there

## Media
upcoming:

https://github.com/user-attachments/assets/a81e8a6e-2c5f-4f5e-83e1-57c73b3c4710

after this commit:

https://github.com/user-attachments/assets/a78a74fc-b549-4baa-ac7e-a1fc6282db16

## Issue(s) that this PR fixes
Fixes #9013

## Discord contact info
Jamie

### CODE REVIEW

File: src/event_object_movement.c [hunk 1]
```diff
@@ -1968,7 +1968,7 @@ u8 CreateVirtualObject(u16 graphicsId, u8 virtualObjId, s16 x, s16 y, u8 elevati
 struct Pokemon *GetFirstLiveMon(void)
 {
     u32 i;
-    for (i = 0; i < PARTY_SIZE; i++)
+    for (i = 0; i < gPlayerPartyCount; i++)
```
Comment (AlexOn1ine) [inline src/event_object_movement.c]: Are we sure this will always hold the correct value? Wouldn't it be more safe to skip empty slots (checking for species none)?

Comment (FosterProgramming) [reply src/event_object_movement.c]: PR fixed
