### PR TITLE
Fix tests failing with `B_FRIENDSHIP_BOOST` being `TRUE`

### LINKED ISSUE #6238: Setting B_FRIENDSHIP_BOOST to TRUE causes certain tests to fail.
### Description

The actual effects tested in the test still work correctly, but the numbers the tests are expecting do not appear, so they will inherently fail.

- Contrary raises a stat after using a move which would normally lower it: Growl 2/2.
- Hyper Training increases stats without affecting IVs.
- AI will only use Dream Eater if target is asleep
- Booster Energy increases special defense by 30% if it is the highest stat
- Revelation Dance becomes Normal type if used by a Typeless Pokemon due to Roost
- Sword of Ruin reduces Defense if opposing mon's ability doesn't match.
- AI sees increased base power of Smelling Salt
- canhypertrain/hypertrain affect MON_DATA_HYPER_TRAINED_* and recalculate stats.
- AI sees increased base power of Facade.

### Version

1.10.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

wildvenonat

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Sets friendship to 0 during tests.

## Issue(s) that this PR fixes
Fixes #6238

## Discord contact info
AsparagusEduardo

### CODE REVIEW

File: test/test_runner_battle.c [hunk 1]
```diff
@@ -1563,6 +1563,12 @@ void OpenPokemon(u32 sourceLine, u32 side, u32 species)
     data = MOVE_NONE;
     for (i = 0; i < MAX_MON_MOVES; i++)
         SetMonData(DATA.currentMon, MON_DATA_MOVE1 + i, &data);
+    data = 0;
+    if (B_FRIENDSHIP_BOOST) {
```
Comment (hedara90) [inline test/test_runner_battle.c]:
```suggestion
    if (B_FRIENDSHIP_BOOST)
    {
```

**Review by hedara90 — APPROVED** [review]
