### PR TITLE
Fix gems activating for moves that don't deal type damage

### LINKED ISSUE #6785: Gem will activate for moves that don't deal type damage
### Description

Just no check at all, so stuff like counter and seismic toss will trigger a gem
https://github.com/rh-hideout/pokeemerald-expansion/blob/7c4fb51/src/battle_main.c#L6076-L6081

No check at the gem activation stage either
https://github.com/rh-hideout/pokeemerald-expansion/blob/7c4fb51/src/battle_script_commands.c#L2201-L2211

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by spindrift64**
Gems do not activate for no type damage moves such as Counter/Psywave/Super Fang.

## Description
Check for base power of the move used. Moves that would trigger the bug have 1 base power.

## Issue(s) that this PR fixes
Fixes #6785

## **Discord contact info**
spindrift64

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -2203,6 +2204,7 @@ static void Cmd_adjustdamage(void)
         && !(gHitMarker & HITMARKER_UNABLE_TO_USE_MOVE)
         && gBattleMons[gBattlerAttacker].item
         && moveEffect != EFFECT_PLEDGE
+        && movePower > 1
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:2207]: Could you move the pledge check to the other part of the gem activation because this might lead to some incorrect results otherwise and I believe you don't need to add the power check here.

File: test/battle/hold_effect/gems.c [hunk 2]
```diff
@@ -87,3 +87,20 @@ SINGLE_BATTLE_TEST("Gem is consumed if the move type is changed")
         ANIMATION(ANIM_TYPE_MOVE, MOVE_FEINT_ATTACK, player);
     }
 }
+
+SINGLE_BATTLE_TEST("Gem is not consumed if a no type damage move is used") //ie. Counter, Psywave, Super Fang. All these moves have 1 base power.
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) { Item(ITEM_PSYCHIC_GEM); };
```
Comment (AlexOn1ine) [inline test/battle/hold_effect/gems.c:94]: @spindrift64 could you also add an assume here that psywave has 1 base power?

File: test/battle/hold_effect/gems.c [hunk 3]
```diff
@@ -87,3 +87,20 @@ SINGLE_BATTLE_TEST("Gem is consumed if the move type is changed")
...
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN {
+            MOVE(player, MOVE_PSYWAVE);
+        }
```
Comment (AlexOn1ine) [inline test/battle/hold_effect/gems.c:99]:
```suggestion
        TURN { MOVE(player, MOVE_PSYWAVE); }
```

Comment (AlexOn1ine) [reply test/battle/hold_effect/gems.c:99]: if it is just one move, you can do it on one line.

**Review by AlexOn1ine — APPROVED** [review]

File: src/battle_main.c [hunk 4]
```diff
@@ -6074,7 +6074,10 @@ void SetTypeBeforeUsingMove(u32 move, u32 battler)
         gBattleStruct->dynamicMoveType = TYPE_ELECTRIC | F_DYNAMIC_TYPE_SET;
 
     // Check if a gem should activate.
-    if (holdEffect == HOLD_EFFECT_GEMS && GetBattleMoveType(move) == ItemId_GetSecondaryId(heldItem))
+    if (holdEffect == HOLD_EFFECT_GEMS
+        && GetBattleMoveType(move) == ItemId_GetSecondaryId(heldItem)
+        && GetMoveEffect(move) != EFFECT_PLEDGE
+        && GetMovePower(move) > 1)
```
Comment (AlexOn1ine) [inline src/battle_main.c:6080]: @spindrift64 we have to change this to only `ohko` moves. Everything else seems to trigger gems but give no boost. Do you want to make the pr?

Comment (AlexOn1ine) [reply src/battle_main.c:6080]: struggle already isn't affected by gems but the check should be moved over as well. Ideally there would be only one entry point but does need a small refactor. I noticed it a couple times that it isn't ideally handled.

Comment (AlexOn1ine) [reply src/battle_main.c:6080]: They activate for moves with one power besides ohko moves but don't increase the dmg (which was previously already correct)

Comment (spindrift64) [reply src/battle_main.c:6080]: I see, I'll work on this soon
