### PR TITLE
Fixed Z-Moves+Obedience bugged behavior

### LINKED ISSUE #3333: Z-Moves and Disobedience break battles
### Description

https://discord.com/channels/419213663107416084/774393519569502268/1145308711657676810

> if you use a z-move when your mon doesn't obey you and ignore your orders, it causes various issues. 

This ticket is a placeholder so we don't forget it, but needs to be fleshed out later.

### Version

1.5.3 (Default)

### Upcoming Version

_No response_

### Discord contact info

aaghat

### PR DESCRIPTION
**Pull request by hedara90**
Made it so that the Z-Move animation doesn't play when the battler doesn't obey, and doesn't "waste" the Z-Move activation.

## Description

Used 3 bits in the `BattleStruct` to store the obedience result.
The obedience check is then moved to before the battler has done anything in the turn and the Z-Move activation can then check for obedience.
Z-Move flags for the battler are then cleared in order to not interfere with the next turn.

## Images

https://github.com/user-attachments/assets/8dfc7308-c71c-42fa-bbde-85ba254ee84c

## Issue(s) that this PR fixes

Fixes #3333 

## **Discord contact info**

hedara

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -8347,7 +8345,7 @@ u8 IsMonDisobedient(void)
     if (BattlerHasAi(gBattlerAttacker))
         return 0;
 
-    if (IsBattlerModernFatefulEncounter(gBattlerAttacker)) // only false if illegal Mew or Deoxys
+    if (TRUE) // This used to be a check to see if the mon in question was a fateful encounter (Mew or Deoxys)
```
Comment (AlexOn1ine) [inline src/battle_util.c:8348]: I don't think this is necessary. It is just legacy code that we don't need to support.

File: src/battle_util.c [hunk 2]
```diff
@@ -8347,7 +8345,7 @@ u8 IsMonDisobedient(void)
...
     {
         if (gBattleTypeFlags & BATTLE_TYPE_INGAME_PARTNER && GetBattlerPosition(gBattlerAttacker) == B_POSITION_PLAYER_RIGHT)
```
Comment (AlexOn1ine) [inline src/battle_util.c:8350]: Why not check everything in the new function? The check in this function seems redundant. I would move the full check to before the battler does anything so it isn't scattered around.

File: src/battle_util.c [hunk 3]
```diff
@@ -8379,7 +8377,7 @@ u8 IsMonDisobedient(void)
     }
 
     if (B_OBEDIENCE_MECHANICS >= GEN_8
-     && !IsOtherTrainer(gBattleMons[gBattlerAttacker].otId, gBattleMons[gBattlerAttacker].otName))
+        && !IsOtherTrainer(gBattleMons[gBattlerAttacker].otId, gBattleMons[gBattlerAttacker].otName))
```
Comment (AlexOn1ine) [inline src/battle_util.c:8380]: We are trying to use the the first formatting instead of what it was just change into. At least for new stuff.

File: src/battle_util.c (hunk 2 above)
Comment (hedara90) [reply src/battle_util.c:8350]: Now that you mention it, yea.
I think I started with this approach when I thought I only had 1 bit to use in `SpecialStatus`

**Comment by hedara90** [comment]
Redid the implementation.
Ready again.

**Comment by AlexOn1ine** [comment]
> Redid the implementation. Ready again.

looks great, thx. will review later

**Review by AlexOn1ine — APPROVED** [review]
