### PR TITLE
Fix AI wrongly thinking it strikes first with priority even if player is using priority themselves

### LINKED ISSUE #6255: AI persistently chooses Sucker Punch even if opposing mon has faster priority
### Description

This bug happened in the following scenario:

**Enemy (AI) team:**

- Grapploct with Sucker Punch.

**Our (Player) team:**

- Floatzel on low HP (think 9/84 HP) with Aqua Jet

The scenario played out like this:

- Floatzel used Aqua Jet in order to chip Grapploct.
- Grapploct technically sees fast kill with Sucker Punch (seeing Floatzel on low HP as well), and chooses it. At this point, Floatzel uses Aqua Jet **first** (in the case of priority ties, speed is checked to see who goes first), and the AI should see that it cannot use +1 priority moves.
- In the following turn, Floatzel uses Aqua Jet again, and the AI tries using Sucker Punch again, despite seeing that it failed last turn.

### Version

upcoming (Edge)

### Upcoming/master Version

e29e1c6ca7a387acca4ff69247f5284fee44024d

### Discord contact info

viridian.

### PR DESCRIPTION
**Pull request by moostoet**
## Description
In the previous iteration of `AI_WhoStrikesFirst`, the code performed a check like this:

```c
if (GetMovePriority(battlerAI, moveConsidered) > 0)
        return AI_IS_FASTER;
```

This incorrectly assumes that the AI is always faster if the battle move's priority is above `0`. This did not take into account whether the player's predicted move was a priority move, and as such, would faultily use moves like `Sucker Punch` even if it the enemy has `Aqua Jet` with a higher speed stat.

The updated code now checks the player's predicted move through `AI_DATA->lastUsedMove[battler]` to see if the predicted move's priority is higher or lower than the AI's considered move. The rest of the checks stay the same, as this code simply fixes the faulty check.

## Issue(s) that this PR fixes
Fixes #6255 

## **Discord contact info**
viridian.

### CODE REVIEW

**Comment by moostoet** [comment]
Just to note: The function name `GetMovePriority` becomes `GetBattleMovePriority` in `upcoming`, so this should be taken into account when merging one to the other. `GetMovePriority` was refactored into a function simply taking `moveId` as an argument.

File: src/battle_ai_util.c [hunk 1]
```diff
@@ -1094,8 +1094,15 @@ s32 AI_WhoStrikesFirst(u32 battlerAI, u32 battler, u32 moveConsidered)
     u32 abilityAI = AI_DATA->abilities[battlerAI];
     u32 abilityPlayer = AI_DATA->abilities[battler];
 
-    if (GetMovePriority(battlerAI, moveConsidered) > 0)
+    u32 predictedMove = AI_DATA->lastUsedMove[battler];
```
Comment (Pawkkie) [inline src/battle_ai_util.c:1097]: Could you add a comment here that just says "Update for move prediction" or some equivalent so I know to come back to this when I get that PR'd? :)

**Review by Pawkkie — CHANGES_REQUESTED** [review]
Could you please write a test to confirm this is working as intended? :)

File: src/battle_ai_util.c (hunk 1 above)
Comment (moostoet) [reply src/battle_ai_util.c:1097]: Will do! Writing tests for it now as well.

**Comment by moostoet** [comment]
Test was written to confirm it works as intended.

**Review by Pawkkie — APPROVED** [review]
