### PR TITLE
Fixes Opportunist accumulating stat changes

### LINKED ISSUE #3477: Opportunist accumulates stat stages
### Description

Opportunist does not clear the stat stages it applies, so when it activates repeatedly the stat stages are additive. Demonstrated in the following GIFs: Swagger + Howl results in a +5 Attack for the Opportunist user; Flatter + Growth results in +1 Attack and +3 Sp. Atk; copying Howl three times results in +1 Attack, then +2, then +3;
swaggerbug
flatterbug
opportunistrise

### Version

upcoming (Edge)

### Upcoming Version

8eb10796e7e56cd9c2c950a9f80a787eb825987f

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
## Issue(s) that this PR fixes
Fixes #3477

## **People who collaborated with me in this PR**
@ZnogyroP

### CODE REVIEW

File: test/battle/ability/opportunist.c [hunk 1]
```diff
@@ -101,6 +101,24 @@ DOUBLE_BATTLE_TEST("Opportunist raises Attack only once when partner has Intimid
     }
 }
 
+SINGLE_BATTLE_TEST("Opportunist does not accumulate opposing mons stat changes")
```
Comment (Bassoonian) [inline test/battle/ability/opportunist.c:104]:
```suggestion
SINGLE_BATTLE_TEST("Opportunist does not accumulate opposing mon's stat changes")
```

**Review by Bassoonian — APPROVED** [review]
