### PR TITLE
Fix Mold Breaker-like abilities, AI Move Accuracy function, Fury Cutter with Parental Bond

### LINKED ISSUE #4956: Fury Cutter/Parental Bond interaction may be broken
### Description

https://discord.com/channels/419213663107416084/774393519569502268/1261145494365929523

### Version

1.8.5 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### LINKED ISSUE #5019: AI_SetMoveAccuracy wrong defender ability
### Description

See https://github.com/rh-hideout/pokeemerald-expansion/blob/aac6ebd3d72162e3131f71fa2f5c395d3da7e311/src/battle_ai_main.c#L401

### Version

1.8.5 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
Fixes GetBattlerAbility potentially checking the wrong battler's action in doubles, causing Mold Breaker-like abilities to not ignore the target's ability.

Fixes AI_SetMoveAccuracy using battlerAtk's ability as abilityDef.

Fixes Fury Cutter counter getting incremented on the second hit of Parental Bond instead of the first.
Adds a test for this.

## Issue(s) that this PR fixes
Fixes #5019, fixes #4956

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: test/battle/move_effect/fury_cutter.c [hunk 1]
```diff
@@ -36,3 +36,27 @@ SINGLE_BATTLE_TEST("Fury Cutter power doubles with each use, up to 160 power")
...
     }
 }
+
+SINGLE_BATTLE_TEST("Fury Cutter counter is the same for both hits of Parental Bond")
+{
+    s16 damage[4];
+
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_PARENTAL_BOND); }
+        OPPONENT(SPECIES_LINOONE) { HP(900); }
```
Comment (AlexOn1ine) [inline test/battle/move_effect/fury_cutter.c:46]: Could you use Regirock or something similar with a high defense to avoid specifying the HP stat?

**Review by AlexOn1ine — APPROVED** [review]
