### PR TITLE
Fix max move message against semi invulnerable target

### LINKED ISSUE #6406: Max move failing does not have a proper move used message
### Description

Using a max move when the target is semi-invulnerable can make the move fail, as in vanilla SWSH.
However, there is no associated message "XXX used Max-xxx" in expansion's current implementation. The battle message merely adds up to "But it failed!" without giving more information about what failed.

Image

Also tested in double battles.

Steps to reproduce: 
1- make an opponent able to dynamax by setting the dynamax level in trainers.party. 
2- run the trainer battle et make sure the opponent does not use max-guard
3- use a two-turns move that give the semi-invulnerable status (fly, dive, bounce, dig...) 
4- witness

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

Nopinou#8678

### PR DESCRIPTION
**Pull request by FosterProgramming**
I also simplified the way protect is handled in some accuracycheck calls

## Media
master:

https://github.com/user-attachments/assets/e46a2c17-1a99-4e6d-a613-840a2290d240

this commit:

https://github.com/user-attachments/assets/8ef3a5e2-3364-4af3-9a92-25036ea9a60f

## Issue(s) that this PR fixes
Fixes #6406

## Discord contact info
Jamie

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Is this a max move message only issue?

File: test/battle/gimmick/dynamax.c [hunk 1]
```diff
@@ -1671,5 +1671,19 @@ SINGLE_BATTLE_TEST("Dynamax: Destiny Bond fails if a dynamaxed battler is presen
     }
 }
 
+SINGLE_BATTLE_TEST("Dynamax: max move against semi-invulnerable target")
```
Comment (AlexOn1ine) [inline test/battle/gimmick/dynamax.c]:
```suggestion
SINGLE_BATTLE_TEST("Dynamax: max move against semi-invulnerable target prints the correct message")
```
since it's vague what is tested

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -1370,8 +1370,23 @@ static void AccuracyCheck(bool32 recalcDragonDarts, const u8 *nextInstr, const u
...
+            }
             gBattlescriptCurrInstr = failInstr;
-        else if (!JumpIfMoveAffectedByProtect(gCurrentMove, gBattlerTarget, TRUE, failInstr))
+        }
+        else if (IsBattlerProtected(gBattlerAttacker, gBattlerTarget, gCurrentMove))
+        {
+            gBattleStruct->moveResultFlags[gBattlerTarget] |= MOVE_RESULT_MISSED;
+            gBattleStruct->missStringId[gBattlerTarget] = gBattleCommunication[MISS_TYPE] = B_MSG_PROTECTED;
+            gLastLandedMoves[gBattlerTarget] = 0;
+            gLastHitByType[gBattlerTarget] = 0;
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:1386]: ~~why are those reset?~~ Oh, I see because they are also reset during the other protect part, hm

**Comment by FosterProgramming** [comment]
> Is this a max move message only issue?
I don't know, I simply fixed what was reported. 
The result message code is a bit messy and there is probably value in making a list of all possible strings and conditions then refactor into something cleaner but documenting it thoroughly is a lot of effort

**Comment by AlexOn1ine** [comment]
> > Is this a max move message only issue?
> > I don't know, I simply fixed what was reported.

k, I'll merge if you solve conflicts. 

We should probably open an issue to investigate the regular message though.
