### PR TITLE
Move Target failure follow up

### LINKED ISSUE #8960: Spit Up Refactor
### Description

Spit up hasn't been fully modernized. 

### Reproduction Steps

code

### Images / Video

_No response_

### Version

1.14.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #8960

#8696 follow up

This fixes some regressions that were caused by the move target failure. Specifically for Spit Up and Swallow, but some messages were also played incorrectly (Magnitude and Fickle Beam). Then a Beat Up Gen2,3,4 change and a bunch of clean up.

### CODE REVIEW

**Comment by Bassoonian** [comment]
Tests not passing

File: src/battle_move_resolution.c [hunk 1]
```diff
@@ -1239,7 +1237,7 @@ static bool32 IsTargetingSelfAndAlly(u32 battlerAtk, u32 battlerDef)
             gBattleStruct->moveResultFlags[battlerDef] = MOVE_RESULT_NO_EFFECT;
         return skipFailure;
     }
-    return checkFailure; // In Gen3 the user checks it's own failure. Unclear because no such moves exists
```
Comment (AlexOn1ine) [inline src/battle_move_resolution.c:1211]: removed the comments because no move exists like that in gen3 so we can't prove it.

**Comment by AlexOn1ine** [comment]
should hopefully be good now

File: data/battle_scripts_1.s [hunk 2]
```diff
@@ -3010,12 +3000,15 @@ BattleScript_EffectPainSplit::
...
+BattleScript_SnoreMessage::
 	printstring STRINGID_PKMNFASTASLEEP
 	waitmessage B_WAIT_TIME_LONG
 	statusanimation BS_ATTACKER
+    return
+
+BattleScript_EffectSnore::
+	attackcanceler
+	jumpifhalfword CMP_EQUAL, gChosenMove, MOVE_SLEEP_TALK, BattleScript_DoSnore
 BattleScript_DoSnore::
```
Comment (PhallenTree) [inline data/battle_scripts_1.s]: This doesn't do anything?

File: src/battle_move_resolution.c [hunk 3]
```diff
@@ -1088,6 +1096,32 @@ static enum CancelerResult CancelerCharging(struct BattleContext *ctx)
...
+        gBattleStruct->fickleBeamBoosted = RandomPercentage(RNG_FICKLE_BEAM, 30);
+        if (gBattleStruct->fickleBeamBoosted)
+        {
+            BattleScriptCall(BattleScript_FickleBeamMessage);
+            return CANCELER_RESULT_BREAK;
+        }
+        break;
+    case EFFECT_SNORE:
+        BattleScriptCall(BattleScript_SnoreMessage);
+        return CANCELER_RESULT_BREAK;
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Since this happens after `CANCELER_ATTACKSTRING` this causes the messages to be printed in this order: "Mon used Snore!" then "Mon is fast asleep!" when it should be the other way around
My guess is that in the games the fast asleep message is printed in `CANCELER_ASLEEP_OR_FROZEN` but it doesn't end the move for Snore and Sleep Talk

File: data/battle_scripts_1.s (hunk 2 above)
Comment (AlexOn1ine) [reply data/battle_scripts_1.s]: forgot to remove

File: src/battle_move_resolution.c (hunk 3 above)
Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: oh ye, will fix. I think this was already broken lol

**Comment by AlexOn1ine** [comment]
ready for re-review. 

Sorry for the force push. Messed up the last 2 commits a bit.

File: src/battle_move_resolution.c [hunk 4]
```diff
@@ -1088,6 +1101,29 @@ static enum CancelerResult CancelerCharging(struct BattleContext *ctx)
     return result;
 }
 
+static enum CancelerResult CancelerMoveSpecificMessage(struct BattleContext *ctx)
+{
+    switch(GetMoveEffect(ctx->move))
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
    switch (GetMoveEffect(ctx->move))
```

File: src/battle_move_resolution.c [hunk 5]
```diff
@@ -1598,11 +1632,11 @@ enum CancelerResult DoAttackCanceler(void)
     while (gBattleStruct->eventState.atkCanceler < CANCELER_END && result == CANCELER_RESULT_SUCCESS)
     {
         result = sMoveSuccessOrderCancelers[gBattleStruct->eventState.atkCanceler](&ctx);
-        gBattleStruct->unableToUseMove = (result == CANCELER_RESULT_FAILURE);
         if (result != CANCELER_RESULT_PAUSE)
             gBattleStruct->eventState.atkCanceler++;
     }
 
+    gBattleStruct->unableToUseMove = (result == CANCELER_RESULT_FAILURE);
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
    if (result == CANCELER_RESULT_FAILURE)
        gBattleStruct->unableToUseMove = TRUE;
```

File: test/battle/move_effect/stockpile.c [hunk 6]
```diff
@@ -272,3 +272,42 @@ DOUBLE_BATTLE_TEST("Stockpile's Def and Sp. Def boost is lost after using Spit U
...
+    } WHEN {
+        TURN { MOVE(player, MOVE_STOCKPILE); }
+        TURN { MOVE(opponent, MOVE_PROTECT); MOVE(player, MOVE_SPIT_UP); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_STOCKPILE, player);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_PROTECT, opponent);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_SPIT_UP, player);
+    } THEN {
+        EXPECT_EQ(player->statStages[STAT_DEF], DEFAULT_STAT_STAGE );
+        EXPECT_EQ(player->statStages[STAT_SPDEF], DEFAULT_STAT_STAGE );
```
Comment (PhallenTree) [inline test/battle/move_effect/stockpile.c]:
```suggestion
        EXPECT_EQ(player->statStages[STAT_DEF], DEFAULT_STAT_STAGE);
        EXPECT_EQ(player->statStages[STAT_SPDEF], DEFAULT_STAT_STAGE);
```

File: test/battle/move_effect/stockpile.c [hunk 7]
```diff
@@ -272,3 +272,42 @@ DOUBLE_BATTLE_TEST("Stockpile's Def and Sp. Def boost is lost after using Spit U
...
+        TURN { MOVE(player, MOVE_STOCKPILE); }
+        TURN { MOVE(opponent, MOVE_ELECTRIFY); MOVE(player, MOVE_SPIT_UP); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_STOCKPILE, player);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_ELECTRIFY, opponent);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_SPIT_UP, player);
+        ABILITY_POPUP(opponent, ABILITY_LIGHTNING_ROD);
+    } THEN {
+        EXPECT_EQ(player->statStages[STAT_DEF], DEFAULT_STAT_STAGE );
+        EXPECT_EQ(player->statStages[STAT_SPDEF], DEFAULT_STAT_STAGE );
```
Comment (PhallenTree) [inline test/battle/move_effect/stockpile.c]:
```suggestion
        EXPECT_EQ(player->statStages[STAT_DEF], DEFAULT_STAT_STAGE);
        EXPECT_EQ(player->statStages[STAT_SPDEF], DEFAULT_STAT_STAGE);
```
