### PR TITLE
Random Pyramid Encounter fixes

### LINKED ISSUE #3791: BATTLE_PYRAMID_RANDOM_ENCOUNTERS does not include Gen 9 Pokemon
### Description

Due to the use of `species = Random() % FORMS_START;` and the definition of gen 9 Pokemon following the forms, they are not included within this range.

### Version

1.7.0 (Default)

### Upcoming Version

_No response_

### Discord contact info

zatsoo

### LINKED ISSUE #4325: Game freezes on Battle Pyramid Ecounter
### Description

If `BATTLE_PYRAMID_RANDOM_ENCOUNTERS` is set to true the game freezes right before an encounter

### Version

1.8.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4325
Fixes #3791

Credits:
Jasper for the base species check idea
ghoulslash for fixing the freeze

### CODE REVIEW

File: src/battle_pyramid.c [hunk 1]
```diff
@@ -1401,27 +1401,32 @@ void GenerateBattlePyramidWildMon(void)
...
     id = GetMonData(&gEnemyParty[0], MON_DATA_SPECIES, NULL) - 1;   // index in table (0-11) -> higher index is lower probability
     bstLim = 450 + (25*round) + (5*id);                             // higher BST limit for 'rarer' wild mon rolls
 
     while (1)
     {
-        species = Random() % FORMS_START;
+        species = Random() % NUM_SPECIES;
+
+        // check if base species
+        if (!GET_BASE_SPECIES_ID(species))
```
Comment (ghoulslash) [inline src/battle_pyramid.c:1419]: doesn't GET_BASE_SPECIES_ID return a species ID? So shouldn't this be `if (GET_BASE_SPECIES_ID(species) != species)` ?

File: src/battle_pyramid.c [hunk 2]
```diff
@@ -1401,27 +1401,32 @@ void GenerateBattlePyramidWildMon(void)
...
     id = GetMonData(&gEnemyParty[0], MON_DATA_SPECIES, NULL) - 1;   // index in table (0-11) -> higher index is lower probability
     bstLim = 450 + (25*round) + (5*id);                             // higher BST limit for 'rarer' wild mon rolls
 
     while (1)
     {
-        species = Random() % FORMS_START;
+        species = Random() % NUM_SPECIES;
+
+        // check if base species
+        if (GET_BASE_SPECIES_ID(species) != species)
```
Comment (AsparagusEduardo) [inline src/battle_pyramid.c:1419]: Maybe we should introduce `IS_BASE_SPECIES_ID`. I've been thinking about it for a while now, but I didn't know where it could be used lol

Comment (AlexOn1ine) [reply src/battle_pyramid.c:1419]: maybe in the future? not sure if it is worth it here.

**Review by ghoulslash — APPROVED** [review]
