### PR TITLE
Fix mapjson failing with long map/layout names

### LINKED ISSUE #9372: upcoming mapjson doesn't support map with names too long
### Description

 self explanatory

### Reproduction Steps

_No response_

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Issue(s) that this PR fixes
Fixes #9372

## Discord contact info
Jamie

### CODE REVIEW

File: tools/mapjson/mapjson.cpp [hunk 1]
```diff
@@ -863,16 +869,21 @@ string generate_layouts_constants_text(Json layouts_data) {
...
+    vector<string> filtered_layout_defines;
+    int max_length = 0;
     for (auto &layout : required_layout_defines) {
         auto it = find(defined_layouts.begin(), defined_layouts.end(), layout);
         if (it == defined_layouts.end()) {
-            text << "#define " << layout << string(50 - layout.length(), ' ')
-                 //<< "(" << map_id_num << " | (" << json_to_string(required_map_id[1]) << " << 8)),\n";
-                 << "0xFFFF\n";
+            filtered_layout_defines.push_back(layout);
+            if (layout.length() > max_length)
```
Comment (hedara90) [inline tools/mapjson/mapjson.cpp:878]: This generates a warning:
```
warning: comparison of integer expressions of different signedness
```
`max_length` should be `size_t` to match return type of `std::string::length`

**Comment by FosterProgramming** [comment]
PR updated
