### PR TITLE
Fixes Symbiosis not triggering when a weakness berry was consumed

### LINKED ISSUE #6585: Symbiosis doesn't seem to proc after a weakness berry is consumed
### Description

`berryReduced` set in damage calc
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/src/battle_util.c#L10334-L10337

`damagecalc` happens before `attackanimation`
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/data/battle_scripts_1.s#L2800-L2803
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/data/battle_scripts_1.s#L2820-L2821

Starting from `attackanimation`
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/src/battle_script_commands.c#L2383-L2388

Calls `TryActivateWeakenessBerry`
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/src/battle_script_commands.c#L2337-L2377

Sets `berryReduced` to `FALSE`
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/src/battle_script_commands.c#L2321-L2325

`MOVEEND_SYMBIOSIS` is checked waaaaaay after the above code
https://github.com/rh-hideout/pokeemerald-expansion/blob/3d8b912087e5e49db5999911dfd526bb511dd895/src/battle_script_commands.c#L7314-L7319

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6585

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -6187,14 +6186,16 @@ static bool32 TryKnockOffBattleScript(u32 battlerDef)
...
 
-#define SYMBIOSIS_CHECK(battler, ally)                             \
-    GetBattlerAbility(ally) == ABILITY_SYMBIOSIS                   \
-    && gBattleMons[battler].item == ITEM_NONE                      \
-    && gBattleMons[ally].item != ITEM_NONE                         \
-    && CanBattlerGetOrLoseItem(battler, gBattleMons[ally].item)    \
-    && CanBattlerGetOrLoseItem(ally, gBattleMons[ally].item)       \
-    && IsBattlerAlive(battler)                                     \
-    && IsBattlerAlive(ally)
+static inline bool32 TryTriggerSymbioses(u32 battler, u32 ally)
```
Comment (Bassoonian) [inline src/battle_script_commands.c:6189]: Any reason you're using the plural here now? Also in the other function

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: sleepiness

fixed

**Review by Bassoonian — APPROVED** [review]
