### PR TITLE
Fix tera tint not applying on activation

### LINKED ISSUE #7804: Tera'd mons don't appear tera'd until they switch out and swap back in
### Description

Title. The tinge that they get draped in doesn't show up until they reenter the field.

### Reproduction Steps

Have enemy tera and see, have it switch out with smart ai, and switch back in later.

### Images / Video

Image

### Version

1.13.1 (Latest release)

### Upcoming/master Version

Latest Master

### Discord contact info

Jordan

### PR DESCRIPTION
**Pull request by FosterProgramming**
I copied the tint effect from the on switch-code. It ends up being a partial reversion of the changes done in #7613 but the issues from #7613 doesn't occur anymore (probably because tera animations have been reqorked since according to Linathan)

## Media
master:

https://github.com/user-attachments/assets/f319aa9f-836b-40a1-a5a0-09b083f262c8

this commit:

https://github.com/user-attachments/assets/605ea361-7162-4b0e-9520-6b9b4f6e29f1

## Issue(s) that this PR fixes
Fixes #7804

## Discord contact info
Jamie

### CODE REVIEW

File: src/battle_gfx_sfx_util.c [hunk 1]
```diff
@@ -998,6 +998,13 @@ void HandleSpeciesGfxDataChange(u8 battlerAtk, u8 battlerDef, bool32 megaEvo, bo
         CpuCopy32(gPlttBufferFaded + paletteOffset, gPlttBufferUnfaded + paletteOffset, PLTT_SIZEOF(16));
     }
 
+    // Terastallization's tint
+    if (GetActiveGimmick(battlerAtk) == GIMMICK_TERA)
+    {
+        BlendPalette(paletteOffset, 16, 8, GetTeraTypeRGB(GetBattlerTeraType(battlerAtk)));
+        CpuCopy32(gPlttBufferFaded + paletteOffset, gPlttBufferUnfaded + paletteOffset, PLTT_SIZEOF(16));
+    }
```
Comment (PhallenTree) [inline src/battle_gfx_sfx_util.c]: Doing it this way also unfixes #6811, could you do it as a function argument like `megaEvo` instead of checking the active gimmick?

**Comment by FosterProgramming** [comment]
A lot of changes: I rebased on top of master to include another transform bugfix then I slightly refactor HandleSpeciesGfxDataChange to use only one variable to determine the type of change instead of `megaEvo` and `trackEnemyPersonality` which were not clear on their roles.
I also updated Animtask_transformmon and animtask_hideswapsprite to reflect those changes. 
hideswapsprite was copied from transformmon but had unused conditionnal branches that I removed


https://github.com/user-attachments/assets/738abca7-3cad-4863-9c05-edb6365732ea

**Review by PhallenTree — APPROVED** [review]
