### PR TITLE
Fix Magician Life orb recoil when stealing

### LINKED ISSUE #3678: Magician stealing a life orb deals self damage
### Description

When attacking an opposing mon holding a life orb magician steal the life orb, does not boost damage but does cause recoil.

What should have happened is magician steals the life orb but does not boost the damage and does not receive recoil.

Video Demonstration: [MagicianLifeOrbBug.zip](https://github.com/rh-hideout/pokeemerald-expansion/files/13628891/MagicianLifeOrbBug.zip)

### Version

1.6.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

thelastmudkip

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3678 with test

### CODE REVIEW

File: test/battle/ability/magician.c [hunk 1]
```diff
@@ -0,0 +1,30 @@
+#include "global.h"
+#include "test/battle.h"
+
+SINGLE_BATTLE_TEST("Magician does not get self-damage recoil after stealing Life Orb")
+{
+    GIVEN {
+        ASSUME(gItems[ITEM_LIFE_ORB].holdEffect == HOLD_EFFECT_LIFE_ORB);
+        ASSUME(gBattleMoves[MOVE_TACKLE].power != 0);
+        ASSUME(P_GEN_6_POKEMON == TRUE);
```
Comment (AlexOn1ine) [inline test/battle/ability/magician.c:9]: Edu changed it so that pokemon gen assumes are no longer needed. Maybe they can clarify on how it works.

Comment (AsparagusEduardo) [reply test/battle/ability/magician.c:9]: `PLAYER` and `OPPONENT` essentially check for `IsSpeciesEnabled`. If it returns FALSE, the test automatically ends as `ASSUMPTION_FAIL` with a message that says that the species was disabled.

Comment (DizzyEggg) [reply test/battle/ability/magician.c]: That's a great change! I removed the assume

**Review by AlexOn1ine — APPROVED** [review]
