### PR TITLE
Fix Berserk gene issue in double battles

### LINKED ISSUE #3180: Berserk Gene issue in Double Battle
### Description

In Double Battles, the confusion effect of Berserk Gene applies to the Pokemon in slot 2. 
Testing with a Spinda with Own Tempo in Slot 2, the confusion is avoided with no ability Pop Up. A Spinda with Own Tempo in Slot 1 (and Berserk Gene) has Own Tempo ability pop up, followed by a string of <Pokemon B Ability> prevented confusion.

### Version

1.5.0

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3180

With tests

### CODE REVIEW

File: test/battle/hold_effect/berserk_gene.c [hunk 1]
```diff
@@ -30,6 +30,32 @@ SINGLE_BATTLE_TEST("Berserk Gene sharply raises attack at the start of battle",
     }
 }
 
+DOUBLE_BATTLE_TEST("Berserk Gene sharply raises attack at the start of a double battle", s16 damage)
+{
+    u16 useItem;
+    PARAMETRIZE { useItem = FALSE; }
+    PARAMETRIZE { useItem = TRUE; }
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/berserk_gene.c:37]:
```suggestion
    u16 item;
    PARAMETRIZE { item = ITEM_NONE; }
    PARAMETRIZE { item = ITEM_BERSERK_GENE; }
```

File: test/battle/hold_effect/berserk_gene.c [hunk 2]
```diff
@@ -83,6 +109,45 @@ SINGLE_BATTLE_TEST("Berserk Gene does not confuse a Pokemon with Own Tempo but s
...
 }
 
+DOUBLE_BATTLE_TEST("Berserk Gene does not confuse a Pokemon with Own Tempo but still raises attack sharply in a double battle", s16 damage)
+{
+    u16 useItem;
+    bool8 slowbroPosLeft = FALSE;
+
+    PARAMETRIZE { useItem = FALSE; }
+    PARAMETRIZE { useItem = TRUE; slowbroPosLeft = TRUE; }
+    PARAMETRIZE { useItem = TRUE; slowbroPosLeft = FALSE; }
```
Comment (AsparagusEduardo) [inline test/battle/hold_effect/berserk_gene.c:119]:
```suggestion
    u16 item;
    bool8 positionLeft = FALSE;

    PARAMETRIZE { item = ITEM_NONE; }
    PARAMETRIZE { item = ITEM_BERSERK_GENE; positionLeft = TRUE; }
    PARAMETRIZE { item = ITEM_BERSERK_GENE; positionLeft = FALSE; }
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

**Comment by DizzyEggg** [comment]
Review changes done

**Review by AsparagusEduardo — APPROVED** [review]
