### PR TITLE
Fix Transform fail conditions with gen-specific checks

### LINKED ISSUE #9055: Transform shouldn't work if the user is transformed in gen 5+
### Description

https://bulbapedia.bulbagarden.net/wiki/Transform_(move)#Transformation_conditions
Bulbapedia says transform cannot execute if the user is transformed. There is no such check in transformdataexecution or the battle script
https://github.com/rh-hideout/pokeemerald-expansion/blob/c3b462a1397b9dea82882d336b1c77209c6d53bd/src/battle_script_commands.c#L8485-L8497
https://github.com/rh-hideout/pokeemerald-expansion/blob/c3b462a1397b9dea82882d336b1c77209c6d53bd/data/battle_scripts_1.s#L2797-L2809

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Issue(s) that this PR fixes
Closes #9055

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -11264,7 +11264,8 @@ static void Cmd_transformdataexecution(void)
 
     gChosenMove = MOVE_UNAVAILABLE;
     gBattlescriptCurrInstr = cmd->nextInstr;
-    if (gBattleMons[gBattlerTarget].volatiles.transformed
+    if ((B_UPDATED_MOVE_FLAGS >= GEN_5 && gBattleMons[gBattlerAttacker].volatiles.transformed)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: we usually use `B_UPDATED_MOVE_FLAGS` for constant data in `moves_info`. 

Could you create a new config? Something like `B_TRANSFORM`

**Comment by grintoul1** [comment]
Conflicts

**Comment by Cle-bit** [comment]
There are still some details that need to be revised

**Comment by AsparagusEduardo** [comment]
I believe new battle configs should have tests for them

**Comment by Cle-bit** [comment]
> I believe new battle configs should have tests for them

Get it!

**Comment by Cle-bit** [comment]
Ready for review IoI

**Comment by AlexOn1ine** [comment]
@Cle-bit could you solve conflicts again? :sweat_smile:

**Comment by Cle-bit** [comment]
> @Cle-bit could you solve conflicts again? 😅

Ah, I'll do it later👀
