### PR TITLE
Tauros forms stat fixes + Electrode-H evo item fix

### LINKED ISSUE #3940: Paldean Tauros has wrong base stats
### Description

All breeds of Paldean Tauros are currently using the same TAUROS_MISC_INFO define which contains the base form's stats, but the Paldean form is supposed to have different base stats.

### Version

1.7.1 (Default)

### Upcoming Version

_No response_

### Discord contact info

moo66

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes  #3940

### CODE REVIEW

File: src/data/pokemon/species_info/gen_1.h [hunk 1]
```diff
@@ -10188,6 +10182,12 @@ const struct SpeciesInfo gSpeciesInfoGen1[] =
 
     [SPECIES_TAUROS] =
     {
+        .baseHP        = 75,
+        .baseAttack    = 100,
+        .baseDefense   = 95,
+        .baseSpeed     = 110,
+        .baseSpAttack  = 40,
+        .baseSpDefense = 70,
         TAUROS_MISC_INFO,
```
Comment (Bassoonian) [inline src/data/pokemon/species_info/gen_1.h:10191]: `TAUROS_MISC_INFO` should precede all else, if I'm not mistaken

Comment (AlexOn1ine) [reply src/data/pokemon/species_info/gen_1.h]: fixed
