### PR TITLE
Fixes Mycelium Might and Lagging Tail adjusting prio incorrectly

### LINKED ISSUE #6866: Mycelium Might will be ignored if neutralizing gas mon switches out
### Description

When Weezing switches out, `Mycelium Might` will be ignored when recalculating turn order. Meaning the user isn't going to be last in the priority bracket.

### Version

1.11.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6866

### CODE REVIEW

File: src/battle_main.c [hunk 1]
```diff
@@ -4820,7 +4824,11 @@ s32 GetBattleMovePriority(u32 battler, u32 ability, u32 move)
...
         return GetMovePriority(MOVE_MAX_GUARD);
 
-    if (ability == ABILITY_GALE_WINGS
+    if (gProtectStructs[battler].quash)
+    {
+        priority = -8;
+    }
+    else if (ability == ABILITY_GALE_WINGS
         && (GetGenConfig(GEN_CONFIG_GALE_WINGS) < GEN_7 || IsBattlerAtMaxHp(battler))
         && GetMoveType(move) == TYPE_FLYING)
```
Comment (Bassoonian) [inline src/battle_main.c]:
```suggestion
    else if (ability == ABILITY_GALE_WINGS
          && (GetGenConfig(GEN_CONFIG_GALE_WINGS) < GEN_7 || IsBattlerAtMaxHp(battler))
          && GetMoveType(move) == TYPE_FLYING)
```
