### PR TITLE
Reimplemented Mimicry

### LINKED ISSUE #2472: Mimicry may be broken
Just had a battle in which the opposing Pokemon set up Electric Terrain, then when the Galarian Stunfisk came in, it said "Stunfisk changed into the Electric type" and froze, music still running.

### PR DESCRIPTION
**Pull request by LOuroboros**
# Description
About a year ago I implemented Mimicry, an ability that changes the user's type based on the active field terrain.
I can't say that I like some of the decisions I took, so I just removed it and reimplemented it.
As far as I tested, it's all working, but extra testing is always welcomed.
Closes #2472.

## **Discord contact info**
Lunos#4026

### CODE REVIEW

**Comment by ghoulslash** [comment]
This should be redone to be included in the ABILITYEFFECT_ON_TERRAIN case

**Comment by LOuroboros** [comment]
> This should be redone to be included in the ABILITYEFFECT_ON_TERRAIN case

Working on it. It works for the most part, *but* the game freezes after `BattleScript_MimicryActivates_End3` finishes executing, for some reason.

I've been looking at the code to see if I could figure out what's going on, but I can't really spot anything wrong per se 🤔 

```diff
diff --git a/asm/macros/battle_script.inc b/asm/macros/battle_script.inc
index 2089c99f6..396d04c7b 100644
--- a/asm/macros/battle_script.inc
+++ b/asm/macros/battle_script.inc
@@ -2038,10 +2038,6 @@
 	various \battler, VARIOUS_ACTIVATE_TERRAIN_CHANGE_ABILITIES
 	.endm
 
-	.macro applymimicry battler:req
-	various \battler, VARIOUS_APPLY_MIMICRY
-	.endm
-
 @ helpful macros
 	.macro setstatchanger stat:req, stages:req, down:req
 	setbyte sSTATCHANGER, \stat | \stages << 3 | \down << 7
diff --git a/data/battle_scripts_1.s b/data/battle_scripts_1.s
index 21f424fe1..bc6bbbeb4 100644
--- a/data/battle_scripts_1.s
+++ b/data/battle_scripts_1.s
@@ -2526,26 +2526,8 @@ BattleScript_EffectPsychicTerrain:
 	playanimation BS_ATTACKER, B_ANIM_RESTORE_BG
 	call BattleScript_ActivateTerrainAbilities
 	call BattleScript_TerrainSeedLoop
-	call BattleScript_TryToApplyMimicry
 	goto BattleScript_MoveEnd
 
-BattleScript_TryToApplyMimicry:
-	savetarget
-	setbyte gBattlerTarget, 0
-BattleScript_TryToApplyMimicry_Loop:
-	jumpifword CMP_NOT_EQUAL, gFieldStatuses, STATUS_FIELD_TERRAIN_ANY, BattleScript_TryToApplyMimicry_Increment
-	jumpifability BS_TARGET, ABILITY_MIMICRY, BattleScript_TryToApplyMimicry_Effect
-BattleScript_TryToApplyMimicry_Effect:
-	pause B_WAIT_TIME_SHORT
-	call BattleScript_AbilityPopUp
-	applymimicry BS_TARGET
-	printstring STRINGID_BATTLERTYPECHANGEDTO
-	waitmessage B_WAIT_TIME_SHORT
-BattleScript_TryToApplyMimicry_Increment:
-	addbyte gBattlerTarget, 1
-	jumpifbytenotequal gBattlerTarget, gBattlersCount, BattleScript_TryToApplyMimicry_Loop
-	return
-
 BattleScript_EffectTopsyTurvy:
 	attackcanceler
 	attackstring
@@ -6732,6 +6714,7 @@ BattleScript_OverworldTerrain::
 	printfromtable gTerrainStringIds
 	waitmessage B_WAIT_TIME_LONG
 	playanimation BS_SCRIPTING, B_ANIM_RESTORE_BG
+	call BattleScript_ActivateTerrainAbilities
 	end3
 
 BattleScript_SideStatusWoreOff::
diff --git a/include/battle.h b/include/battle.h
index 8242d91d4..1b3928cae 100644
--- a/include/battle.h
+++ b/include/battle.h
@@ -192,6 +192,7 @@ struct SpecialStatus
     u8 dancerUsedMove:1;
     u8 dancerOriginalTarget:3;
     // End of byte
+    u8 mimicryDone:1;
 };
 
 struct SideTimer
diff --git a/include/constants/battle_script_commands.h b/include/constants/battle_script_commands.h
index e295609e0..a13423bcb 100644
--- a/include/constants/battle_script_commands.h
+++ b/include/constants/battle_script_commands.h
@@ -216,46 +216,44 @@
 #define VARIOUS_JUMP_IF_WEATHER_AFFECTED            125
 #define VARIOUS_JUMP_IF_LEAF_GUARD_PROTECTED        126
 #define VARIOUS_SET_ATTACKER_STICKY_WEB_USER        127
-#define VARIOUS_TRY_TO_APPLY_MIMICRY                128
-#define VARIOUS_PHOTON_GEYSER_CHECK                 129
-#define VARIOUS_SHELL_SIDE_ARM_CHECK                130
-#define VARIOUS_TRY_NO_RETREAT                      131
-#define VARIOUS_TRY_TAR_SHOT                        132
-#define VARIOUS_CAN_TAR_SHOT_WORK                   133
-#define VARIOUS_CHECK_POLTERGEIST                   134
-#define VARIOUS_SET_OCTOLOCK                        135
-#define VARIOUS_CUT_1_3_HP_RAISE_STATS              136
-#define VARIOUS_TRY_END_NEUTRALIZING_GAS            137
-#define VARIOUS_JUMP_IF_UNDER_200                   138
-#define VARIOUS_SET_SKY_DROP                        139
-#define VARIOUS_CLEAR_SKY_DROP                      140
-#define VARIOUS_SKY_DROP_YAWN                       141
-#define VARIOUS_JUMP_IF_CANT_FLING                  142
-#define VARIOUS_JUMP_IF_HOLD_EFFECT                 143
-#define VARIOUS_CURE_CERTAIN_STATUSES               144
-#define VARIOUS_TRY_RESET_NEGATIVE_STAT_STAGES      145
-#define VARIOUS_JUMP_IF_LAST_USED_ITEM_BERRY        146
-#define VARIOUS_JUMP_IF_LAST_USED_ITEM_HOLD_EFFECT  147
-#define VARIOUS_SAVE_BATTLER_ITEM                   148
-#define VARIOUS_RESTORE_BATTLER_ITEM                149
-#define VARIOUS_BATTLER_ITEM_TO_LAST_USED_ITEM      150
-#define VARIOUS_SET_BEAK_BLAST                      151
-#define VARIOUS_SWAP_SIDE_STATUSES                  152
-#define VARIOUS_SET_Z_EFFECT                        153
-#define VARIOUS_TRY_SYMBIOSIS                       154
-#define VARIOUS_CAN_TELEPORT                        155
-#define VARIOUS_GET_BATTLER_SIDE                    156
-#define VARIOUS_CHECK_PARENTAL_BOND_COUNTER         157
-#define VARIOUS_SWAP_STATS                          158
-#define VARIOUS_JUMP_IF_ROD                         159
-#define VARIOUS_JUMP_IF_ABSORB                      160
-#define VARIOUS_JUMP_IF_MOTOR                       161
-#define VARIOUS_TEATIME_INVUL                       162
-#define VARIOUS_TEATIME_TARGETS                     163
-#define VARIOUS_TRY_WIND_RIDER_POWER                164
-#define VARIOUS_ACTIVATE_WEATHER_CHANGE_ABILITIES   165
-#define VARIOUS_ACTIVATE_TERRAIN_CHANGE_ABILITIES   166
-#define VARIOUS_APPLY_MIMICRY                       167
+#define VARIOUS_PHOTON_GEYSER_CHECK                 128
+#define VARIOUS_SHELL_SIDE_ARM_CHECK                129
+#define VARIOUS_TRY_NO_RETREAT                      130
+#define VARIOUS_TRY_TAR_SHOT                        131
+#define VARIOUS_CAN_TAR_SHOT_WORK                   132
+#define VARIOUS_CHECK_POLTERGEIST                   133
+#define VARIOUS_SET_OCTOLOCK                        134
+#define VARIOUS_CUT_1_3_HP_RAISE_STATS              135
+#define VARIOUS_TRY_END_NEUTRALIZING_GAS            136
+#define VARIOUS_JUMP_IF_UNDER_200                   137
+#define VARIOUS_SET_SKY_DROP                        138
+#define VARIOUS_CLEAR_SKY_DROP                      139
+#define VARIOUS_SKY_DROP_YAWN                       140
+#define VARIOUS_JUMP_IF_CANT_FLING                  141
+#define VARIOUS_JUMP_IF_HOLD_EFFECT                 142
+#define VARIOUS_CURE_CERTAIN_STATUSES               143
+#define VARIOUS_TRY_RESET_NEGATIVE_STAT_STAGES      144
+#define VARIOUS_JUMP_IF_LAST_USED_ITEM_BERRY        145
+#define VARIOUS_JUMP_IF_LAST_USED_ITEM_HOLD_EFFECT  146
+#define VARIOUS_SAVE_BATTLER_ITEM                   147
+#define VARIOUS_RESTORE_BATTLER_ITEM                148
+#define VARIOUS_BATTLER_ITEM_TO_LAST_USED_ITEM      149
+#define VARIOUS_SET_BEAK_BLAST                      150
+#define VARIOUS_SWAP_SIDE_STATUSES                  151
+#define VARIOUS_SET_Z_EFFECT                        152
+#define VARIOUS_TRY_SYMBIOSIS                       153
+#define VARIOUS_CAN_TELEPORT                        154
+#define VARIOUS_GET_BATTLER_SIDE                    155
+#define VARIOUS_CHECK_PARENTAL_BOND_COUNTER         156
+#define VARIOUS_SWAP_STATS                          157
+#define VARIOUS_JUMP_IF_ROD                         158
+#define VARIOUS_JUMP_IF_ABSORB                      159
+#define VARIOUS_JUMP_IF_MOTOR                       160
+#define VARIOUS_TEATIME_INVUL                       161
+#define VARIOUS_TEATIME_TARGETS                     162
+#define VARIOUS_TRY_WIND_RIDER_POWER                163
+#define VARIOUS_ACTIVATE_WEATHER_CHANGE_ABILITIES   164
+#define VARIOUS_ACTIVATE_TERRAIN_CHANGE_ABILITIES   165
 
 // Cmd_manipulatedamage
 #define DMG_CHANGE_SIGN            0
diff --git a/src/battle_script_commands.c b/src/battle_script_commands.c
index 9c85cd407..560d11373 100644
--- a/src/battle_script_commands.c
+++ b/src/battle_script_commands.c
@@ -10209,9 +10209,6 @@ static void Cmd_various(void)
         gBattlescriptCurrInstr += 3;
         AbilityBattleEffects(ABILITYEFFECT_ON_TERRAIN, gActiveBattler, 0, 0, 0);
         return;
-    case VARIOUS_APPLY_MIMICRY:
-        ChangeTypeBasedOnTerrain(gActiveBattler);
-        break;
     } // End of switch (gBattlescriptCurrInstr[2])
 
     gBattlescriptCurrInstr += 3;
diff --git a/src/battle_util.c b/src/battle_util.c
index 85f9e73bf..1da05a1da 100644
--- a/src/battle_util.c
+++ b/src/battle_util.c
@@ -4297,28 +4297,25 @@ static u8 ForewarnChooseMove(u32 battler)
 
 void ChangeTypeBasedOnTerrain(u8 battlerId)
 {
-    u16 moveType, move;
+    u8 battlerType;
     u16 terrainFlags = VarGet(VAR_TERRAIN) & STATUS_FIELD_TERRAIN_ANY;
 
     if (terrainFlags && gFieldStatuses & STATUS_FIELD_TERRAIN_ANY)
         gFieldStatuses = terrainFlags | STATUS_FIELD_TERRAIN_PERMANENT; // terrain is permanent
 
-    GET_MOVE_TYPE(move, moveType);
-    {
-        if (gFieldStatuses & STATUS_FIELD_ELECTRIC_TERRAIN)
-            moveType = TYPE_ELECTRIC;
-        else if (gFieldStatuses & STATUS_FIELD_GRASSY_TERRAIN)
-            moveType = TYPE_GRASS;
-        else if (gFieldStatuses & STATUS_FIELD_MISTY_TERRAIN)
-            moveType = TYPE_FAIRY;
-        else if (gFieldStatuses & STATUS_FIELD_PSYCHIC_TERRAIN)
-            moveType = TYPE_PSYCHIC;
-        else // failsafe
-            moveType = gSpeciesInfo[battlerId].type1;
-    }
-    SET_BATTLER_TYPE(battlerId, moveType);
+    if (gFieldStatuses & STATUS_FIELD_ELECTRIC_TERRAIN)
+        battlerType = TYPE_ELECTRIC;
+    else if (gFieldStatuses & STATUS_FIELD_GRASSY_TERRAIN)
+        battlerType = TYPE_GRASS;
+    else if (gFieldStatuses & STATUS_FIELD_MISTY_TERRAIN)
+        battlerType = TYPE_FAIRY;
+    else if (gFieldStatuses & STATUS_FIELD_PSYCHIC_TERRAIN)
+        battlerType = TYPE_PSYCHIC;
+    else // failsafe
+        battlerType = gSpeciesInfo[battlerId].type1;
+    SET_BATTLER_TYPE(battlerId, battlerType);
     PREPARE_MON_NICK_WITH_PREFIX_BUFFER(gBattleTextBuff1, battlerId, gBattlerPartyIndexes[battlerId])
-    PREPARE_TYPE_BUFFER(gBattleTextBuff2, moveType);
+    PREPARE_TYPE_BUFFER(gBattleTextBuff2, battlerType);
 }
 
 u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 moveArg)
@@ -4821,15 +4818,6 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
                 effect++;
             }
             break;
-        case ABILITY_MIMICRY:
-            if (gFieldStatuses & STATUS_FIELD_TERRAIN_ANY && !gSpecialStatuses[battler].switchInAbilityDone)
-            {
-                ChangeTypeBasedOnTerrain(battler);
-                BattleScriptPushCursorAndCallback(BattleScript_MimicryActivates_End3);
-                gSpecialStatuses[battler].switchInAbilityDone = TRUE;
-                effect++;
-            }
-            break;
         case ABILITY_PROTOSYNTHESIS:
             if (!gSpecialStatuses[battler].switchInAbilityDone && gBattleWeather & B_WEATHER_SUN)
             {
@@ -6227,6 +6215,15 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
         battler = gBattlerAbility = gBattlerAttacker = gBattleScripting.battler;
         switch (GetBattlerAbility(battler))
         {
+        case ABILITY_MIMICRY:
+            if (!gSpecialStatuses[battler].mimicryDone)
+            {
+                gSpecialStatuses[battler].mimicryDone = TRUE;
+                ChangeTypeBasedOnTerrain(battler);
+                BattleScriptPushCursorAndCallback(BattleScript_MimicryActivates_End3);
+                effect++;
+            }
+            break;
         case ABILITY_QUARK_DRIVE:
             if (IsBattlerTerrainAffected(battler, STATUS_FIELD_ELECTRIC_TERRAIN))
             {
diff --git a/src/data/pokemon/species_info.h b/src/data/pokemon/species_info.h
index 95ccf90aa..4eac73517 100644
--- a/src/data/pokemon/species_info.h
+++ b/src/data/pokemon/species_info.h
@@ -1006,7 +1006,7 @@ const struct SpeciesInfo gSpeciesInfo[] =
         .growthRate = GROWTH_MEDIUM_SLOW,
         .eggGroup1 = EGG_GROUP_MONSTER,
         .eggGroup2 = EGG_GROUP_DRAGON,
-        .abilities = {ABILITY_BLAZE, ABILITY_NONE, ABILITY_SOLAR_POWER},
+        .abilities = {ABILITY_MIMICRY, ABILITY_NONE, ABILITY_SOLAR_POWER},
         .bodyColor = BODY_COLOR_RED,
         .noFlip = FALSE,
     },
```

**Comment by LOuroboros** [comment]
Alright, solved the issue and made some extra changes involving the new `ABILITYEFFECT`s since it's all tied to Mimicry.

File: src/battle_util.c [hunk 1]
```diff
@@ -2118,6 +2067,17 @@ u32 GetBattlerFriendshipScore(u8 battlerId)
     return GetMonFriendshipScore(&party[gBattlerPartyIndexes[battlerId]]);
 }
 
+static void TryToRevertMimicry(void)
+{
+    u8 i;
```
Comment (ghoulslash) [inline src/battle_util.c:2072]: u32 i;

File: src/battle_util.c [hunk 2]
```diff
@@ -4335,6 +4295,28 @@ static u8 ForewarnChooseMove(u32 battler)
     Free(data);
 }
 
+void ChangeTypeBasedOnTerrain(u8 battlerId)
```
Comment (ghoulslash) [inline src/battle_util.c:4298]: I suggest making this return a `bool32`, and the failsafe option should return `FALSE`

File: src/battle_util.c [hunk 3]
```diff
@@ -6236,12 +6202,22 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
         }
         break;
     case ABILITYEFFECT_ON_TERRAIN:  // For ability effects that activate when the field terrain changes.
-        battler = gBattlerAbility = gBattlerAttacker = gBattleScripting.battler;
+        battler = gBattlerAbility = gBattleScripting.battler;
         switch (GetBattlerAbility(battler))
         {
+        case ABILITY_MIMICRY:
+            if (!gSpecialStatuses[battler].terrainAbilityDone)
```
Comment (ghoulslash) [inline src/battle_util.c:6209]: I suggest: `if (!gSpecialStatuses[battler].terrainAbilityDone && ChangeTypeBasedOnTerrain(battler))` so if there's no active terrain, mimicry won't activate

**Review by ghoulslash — CHANGES_REQUESTED** [review]

File: src/battle_util.c (hunk 2 above)
Comment (LOuroboros) [reply src/battle_util.c:4298]: Uh, sure, I guess. It feels kinda weird to me, but 🤷 
```c
bool8 ChangeTypeBasedOnTerrain(u8 battlerId)
{
    u8 battlerType;
    u16 terrainFlags = VarGet(VAR_TERRAIN) & STATUS_FIELD_TERRAIN_ANY;

    if (terrainFlags && gFieldStatuses & STATUS_FIELD_TERRAIN_ANY)
        gFieldStatuses = terrainFlags | STATUS_FIELD_TERRAIN_PERMANENT; // terrain is permanent

    if (gFieldStatuses & STATUS_FIELD_ELECTRIC_TERRAIN)
        battlerType = TYPE_ELECTRIC;
    else if (gFieldStatuses & STATUS_FIELD_GRASSY_TERRAIN)
        battlerType = TYPE_GRASS;
    else if (gFieldStatuses & STATUS_FIELD_MISTY_TERRAIN)
        battlerType = TYPE_FAIRY;
    else if (gFieldStatuses & STATUS_FIELD_PSYCHIC_TERRAIN)
        battlerType = TYPE_PSYCHIC;
    else // failsafe
        return FALSE;
    SET_BATTLER_TYPE(battlerId, battlerType);
    PREPARE_TYPE_BUFFER(gBattleTextBuff1, battlerType);
}
```

File: src/battle_util.c (hunk 3 above)
Comment (LOuroboros) [reply src/battle_util.c:6209]: Same as above. Will push, but it feels weird to have 2 calls to the function together, one for a check and the other one to execute an operation.

File: src/battle_util.c [hunk 4]
```diff
@@ -4335,6 +4295,30 @@ static u8 ForewarnChooseMove(u32 battler)
     Free(data);
 }
 
+bool8 ChangeTypeBasedOnTerrain(u8 battlerId)
+{
+    u8 battlerType;
+    u16 terrainFlags = VarGet(VAR_TERRAIN) & STATUS_FIELD_TERRAIN_ANY;
```
Comment (ghoulslash) [inline src/battle_util.c:4301]: I'm confused what this is doing. VAR_TERRAIN is only used for setting terrain at the start of battle. We only need to check `gFieldStatuses & <flag>`, so lines 4301-4305 look like they can be removed

Comment (LOuroboros) [reply src/battle_util.c:4301]: It's for checking the permanent mode of the field statuses. It was straight up copy-pasted and adapted from the checks inside the `case ABILITYEFFECT_SWITCH_IN_TERRAIN` of `AbilityBattleEffects` :eyes:

Comment (ghoulslash) [reply src/battle_util.c:4301]: But why does permanence matter? If we're calling this function the terrain has changed to something so we don't care if it's permanent or not

Comment (LOuroboros) [reply src/battle_util.c:4301]: I wasn't sure if it was needed or not tbh. It's just something I took into consideration, like "Oh, I should make the function compatible with that, right?" or something. I'll go check if the ability still works for overworld terrains after removing those lines.

Comment (LOuroboros) [reply src/battle_util.c:4301]: Scratch that, I'll need to do further testing and looking into. I was sure everything was working correctly, but it's not. The ability doesn't trigger for terrain-inducing overworld weather conditions. I'll look into it either later or tomorrow, I'm just too tired right now.

Comment (ghoulslash) [reply src/battle_util.c:4301]: should be able to just tack on `tryactivatechangeabilities` loop at the end of `BattleScript_TerrainSeedLoop` I would think

Comment (LOuroboros) [reply src/battle_util.c:4301]: Do you mean a `call BattleScript_ActivateSwitchInAbilities` in `BattleScript_TerrainSeedLoop_NextBattler` before the `return`? Will do :eyes:

I also noticed that I forgot to include to activate the `ABILITYEFFECT_ON_WEATHER` on `Cmd_switchineffects` so I did that as well, and added activations for them at `TryDoEventsBeforeFirstTurn` too, in the same loop used by the activation of `ABILITYEFFECT_ON_SWITCHIN` :eyes:

**Comment by LOuroboros** [comment]
Ready for another review :eyes:

File: src/battle_script_commands.c [hunk 5]
```diff
@@ -6785,9 +6785,11 @@ static void Cmd_switchineffects(void)
...
 
         if (AbilityBattleEffects(ABILITYEFFECT_ON_SWITCHIN, gActiveBattler, 0, 0, 0)
-            || ItemBattleEffects(ITEMEFFECT_ON_SWITCH_IN, gActiveBattler, FALSE)
-            || AbilityBattleEffects(ABILITYEFFECT_TRACE2, 0, 0, 0, 0)
-            || AbilityBattleEffects(ABILITYEFFECT_WEATHER_FORM, 0, 0, 0, 0))
+         || (gBattleWeather & B_WEATHER_ANY && WEATHER_HAS_EFFECT && AbilityBattleEffects(ABILITYEFFECT_ON_WEATHER, gActiveBattler, 0, 0, 0))
+         || (gFieldStatuses & STATUS_FIELD_TERRAIN_ANY && AbilityBattleEffects(ABILITYEFFECT_ON_TERRAIN, gActiveBattler, 0, 0, 0))
+         || ItemBattleEffects(ITEMEFFECT_ON_SWITCH_IN, gActiveBattler, FALSE)
+         || AbilityBattleEffects(ABILITYEFFECT_TRACE2, 0, 0, 0, 0)
+         || AbilityBattleEffects(ABILITYEFFECT_WEATHER_FORM, 0, 0, 0, 0))
```
Comment (ghoulslash) [inline src/battle_script_commands.c:6792]: `ABILITYEFFECT_WEATHER_FORM` and `ABILITYEFFECT_ON_WEATHER` is redundant. I recommend merging the two

File: src/battle_util.c [hunk 6]
```diff
@@ -6209,7 +6173,7 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
         }
         break;
     case ABILITYEFFECT_ON_WEATHER: // For ability effects that activate when the battle weather changes.
-        battler = gBattlerAbility = gBattlerAttacker = gBattleScripting.battler;
+        battler = gBattlerAbility = gBattleScripting.battler;
         switch (GetBattlerAbility(battler))
```
Comment (ghoulslash) [inline src/battle_util.c:6177]: I think these will need a `weatherAbilityDone` check. Looking at the code, it seems like if you switch in a mon with Protosynthesis when sun is active it would constantly trigger.

**Review by ghoulslash — CHANGES_REQUESTED** [review]

File: src/battle_util.c (hunk 6 above)
Comment (LOuroboros) [reply src/battle_util.c:6177]: > I think these will need a weatherAbilityDone check. Looking at the code, it seems like if you switch in a mon with Protosynthesis when sun is active it would constantly trigger.

I actually tested that earlier with Castform's form change, and it didn't trigger a loop.

I tested the activation on the first turn, and also the activation after a switch out, @ghoulslash#3839.

In fact, that's exactly why I brought up earlier on the Discord server how it's weird that I need a `terrainAbilityDone` for terrain abilities to prevent them from getting stuck in a loop, while weather abilities work just fine :eyes:

I'll re-test with Protosynthesis and apply the change if it's truly needed though.

Comment (ghoulslash) [reply src/battle_util.c:6177]: I assume that's because `TryWeatherFormChange` would return 0 if there's no form change to do, so no script would execute. The 'weatherAbilityDone' isn't needed if every ability check has its own 'check' to make sure the associated script wouldn't run.

File: src/battle_main.c [hunk 7]
```diff
@@ -3720,6 +3720,10 @@ static void TryDoEventsBeforeFirstTurn(void)
         gBattlerAttacker = gBattlerByTurnOrder[gBattleStruct->switchInAbilitiesCounter++];
         if (AbilityBattleEffects(ABILITYEFFECT_ON_SWITCHIN, gBattlerAttacker, 0, 0, 0) != 0)
             return;
+        if (gBattleWeather & B_WEATHER_ANY && WEATHER_HAS_EFFECT && AbilityBattleEffects(ABILITYEFFECT_ON_WEATHER, gActiveBattler, 0, 0, 0) != 0)
```
[the remark this answers is not in the document]
Comment (ghoulslash) [reply src/battle_main.c:3723]: sure they can. if another mon has electric surge for example, it will call `tryactivateterrainchangeabilities` which would trigger mimicry, for example

[the remark this answers is not in the document]
Comment (LOuroboros) [reply src/battle_main.c:3723]: I'm talking about instances in which a Pokémon with those abiliies is sent out on the very first turn and the conditions match.

Feel free to test it out yourself by cloning the branch I'm PR'ing here if you don't believe me, though I can record a video too.

I assigned Mimicry as Charmander's ability, removed the check for `ABILITYEFFECT_ON_TERRAIN` here and entered a battle while the Rain Thunderstorm weather was active in the overworld.

What happened? Mimicry wasn't activated when the battle began, after the Electric Terrain was invoked.

The exact same thing happened with Protosynthesis. I assigned it as Charmander's ability, removed the check that uses `ABILITYEFFECT_ON_WEATHER` and entered a battle while the `WEATHER_DROUGHT` was in effect.

What happened? Charmander couldn't activate Protosynthesis.

File: src/battle_util.c [hunk 8]
```diff
@@ -6226,8 +6157,9 @@ u8 AbilityBattleEffects(u8 caseID, u8 battler, u16 ability, u8 special, u16 move
             }
             break;
         case ABILITY_PROTOSYNTHESIS:
-            if (IsBattlerWeatherAffected(battler, B_WEATHER_SUN))
+            if (!gSpecialStatuses[battler].terrainAbilityDone && IsBattlerWeatherAffected(battler, B_WEATHER_SUN))
```
Comment (ghoulslash) [inline src/battle_util.c:6160]: `.weatherAbilityDone`

**Review by ghoulslash — CHANGES_REQUESTED** [review]

**Review by ghoulslash — APPROVED** [review]
