### PR TITLE
Fixes Ally Switch cancelling partner's moves targeting that side of the field

### LINKED ISSUE #6646: Ally Switch makes self-targeting status moves used by partner fail
### Description

Reported by malad1211 on Discord.
Test to verify behaviour:
```C
DOUBLE_BATTLE_TEST("Ally Switch doesn't make self-targeting status moves fail")
{
    GIVEN {
        ASSUME(gMovesInfo[MOVE_HARDEN].target == MOVE_TARGET_USER);
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WYNAUT);
        OPPONENT(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WYNAUT);
    } WHEN {
        TURN { MOVE(playerLeft, MOVE_ALLY_SWITCH); MOVE(playerRight, MOVE_HARDEN); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ALLY_SWITCH, playerLeft);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_HARDEN, playerLeft);
    }
}
```

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
- Fixes moves failing after Ally Switch if the Attacker is the ally of the battler that used Ally Switch and if they target a battler on the same side of the field (changed so that only moves that did not originally target the user, but target the user after Ally Switch fail).
- Fixes Acupressure failing regardless of target if Ally Switch was used by their partner.
- Fixes Snipe Shot, Propeller Tail and Stalwart redirecting moves for some battlers when they shouldn't (after Ally Switch).

## Issue(s) that this PR fixes
Fixes #6646

## **People who collaborated with me in this PR**
@hedara90 made the Ally Switch test in #6646

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: src/battle_anim_effects_1.c [hunk 1]
```diff
@@ -6938,9 +6938,12 @@ static void AnimTask_AllySwitchDataSwap(u8 taskId)
     TrySwapWishBattlerIds(battlerAtk, battlerPartner);
 
     // For Snipe Shot and abilities Stalwart/Propeller Tail - keep the original target.
-    for (i = 0; i < MAX_BATTLERS_COUNT; i++)
+    for (i = 0; i < gBattlersCount; i++)
     {
         u16 ability = GetBattlerAbility(i);
+        if (IsBattlerAlly(i, battlerAtk))
```
Comment (PhallenTree) [inline src/battle_anim_effects_1.c:6944]:
```suggestion
        // if not targeting a slot that got switched, continue
        if (!IsBattlerAlly(gBattleStruct->moveTarget[i], battlerAtk))
```

**Review by AlexOn1ine — APPROVED** [review]
