### PR TITLE
Fix Instruct Missing Checks for Focus Punch, Beak Blast, Shell Trap, and Sky Drop

### LINKED ISSUE #9148: Instruct is missing checks for focus punch, beak blast, shell trap (and possibly sky drop + others)
### Description

https://bulbapedia.bulbagarden.net/wiki/Instruct_(move)
> Instruct will fail if [...] the target is in the middle of [Bide](https://bulbapedia.bulbagarden.net/wiki/Bide_(move)), [Focus Punch](https://bulbapedia.bulbagarden.net/wiki/Focus_Punch_(move)), [Beak Blast](https://bulbapedia.bulbagarden.net/wiki/Beak_Blast_(move)), [Shell Trap](https://bulbapedia.bulbagarden.net/wiki/Shell_Trap_(move)) [...]; the target has been picked up by [Sky Drop](https://bulbapedia.bulbagarden.net/wiki/Sky_Drop_(move)) (even if one of the Pokémon has [No Guard](https://bulbapedia.bulbagarden.net/wiki/No_Guard_(Ability)));

Nothing seems to be here. The sky drop one I'm not sure about because its gLastMoves might be cleared anyway but I haven't looked at the sky drop code at all before
https://github.com/rh-hideout/pokeemerald-expansion/blob/63fc5bf0fe47331c1cc8d318bf5b4d818699a581/src/battle_script_commands.c#L14099-L14113

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description
- Test `Beak Blast doesn't burn if the target is protected` (#8713 )used Instruct to construct an “Instructed Protect-like move while preparing Beak Blast” scenario. After the fix Instruct correctly fails in the middle of Beak Blast(so that setup path is basically impossible?)

## Issue(s) that this PR fixes
Fixes #9148

### CODE REVIEW

File: test/battle/move_effect/beak_blast.c [hunk 1]
```diff
@@ -178,6 +178,7 @@ DOUBLE_BATTLE_TEST("Beak Blast doesn't burn if the target is protected")
     PARAMETRIZE { move = MOVE_BURNING_BULWARK; }
     PARAMETRIZE { move = MOVE_SILK_TRAP; }
 
+    KNOWN_FAILING;
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/beak_blast.c]: I don't like the idea of accepting a bugfix that introduces a new bug knowingly.

Comment (AlexOn1ine) [reply test/battle/move_effect/beak_blast.c]: That's not a new bug. Cle-bit pointed out that this might be a faulty tests.

Comment (AsparagusEduardo) [reply test/battle/move_effect/beak_blast.c]: > That's not a new bug. Cle-bit pointed out that this might be a faulty tests.

Sorry, I didn't fully read the description.

Comment (Cle-bit) [reply test/battle/move_effect/beak_blast.c]: I don't know if to change it to TO_DO_BATTLE_TEST or delete the test (if there is no feasible setup path?)

Comment (hedara90) [reply test/battle/move_effect/beak_blast.c]: Can't a Dancer setup be used instead?
Beak Blast setup.
Dancer Protects
Dancer partner uses a dance move on Beak Blaster
Dancer procs and Dancer uses same Dance move on Beak Blaster

Comment (Cle-bit) [reply test/battle/move_effect/beak_blast.c]: > Can't a Dancer setup be used instead? Beak Blast setup. Dancer Protects Dancer partner uses a dance move on Beak Blaster Dancer procs and Dancer uses same Dance move on Beak Blaster

This setup is not equivalent to the original case, because it protects the contact attacker (the Dancer) rather than the Beak Blast user, while the initial test depended on the Beak Blast user being both in Beak Blast’s setup state and under a Protect-like effect in the same turn.

Comment (hedara90) [reply test/battle/move_effect/beak_blast.c]: Oh, I read it the wrong way around then.
Shouldn't just Mat Block work then?
It protects the entire side from Physical and Special moves.

Comment (Cle-bit) [reply test/battle/move_effect/beak_blast.c]: > Oh, I read it the wrong way around then. Shouldn't just Mat Block work then? It protects the entire side from Physical and Special moves.

Yeah, this might work!

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -1136,6 +1136,19 @@ static inline bool32 IsBattlerUsingBeakBlast(u32 battler)
     return !HasBattlerActedThisTurn(battler);
 }
 
+static inline bool32 IsInstructBannedChargingMove(u32 battler)
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:1139]: Those moves aren't really banned, right? Instruct is just being prevented when charging?

Comment (Cle-bit) [reply src/battle_script_commands.c:1139]: > Those moves aren't really banned, right? Instruct is just being prevented when charging?

Those moves([Focus Punch](https://bulbapedia.bulbagarden.net/wiki/Focus_Punch_(move)), [Beak Blast](https://bulbapedia.bulbagarden.net/wiki/Beak_Blast_(move)), [Shell Trap](https://bulbapedia.bulbagarden.net/wiki/Shell_Trap_(move))) are Instruct-banned after execution.
I add a separate guard to prevent Instruct during their charging.

Comment (Cle-bit) [reply src/battle_script_commands.c:1139]: The Bide test passing is not caused by the new `gBattleMons[gBattlerTarget].volatiles.bideTurns != 0 `check, because it already passed before this change via `IsMoveInstructBanned(move)`. During Bide, `gLastPrintedMoves[target]` is MOVE_BIDE, and MOVE_BIDE has `.instructBanned = TRUE`.

Comment (AlexOn1ine) [reply src/battle_script_commands.c:1139]: I see!

Comment (Cle-bit) [reply src/battle_script_commands.c:1139]: I tested if `.instructBanned` is set to `FALSE`, the test fails without `gBattleMons[gBattlerTarget].volatiles.bideTurns != 0`; once that check is added, the test passes.
