### PR TITLE
Zen Mode Fix: Removes start battle form change and adds switch-out form change

### LINKED ISSUE #9303: Zen Mode implementation is incorrect
### Description

Discovered by FIQ. Discussed in the Battle Mechanics Discussion thread.

Zen Mode currently does not match with what's on cart.
* Zen Mode does not activate at the start of battle. It only activates during End-Turn events.
* Zen Mode reverts Darmanitan back to its Standard Form when swapped out, regardless if its HP is below 50% or not.

### Reproduction Steps

Enter a battle with a Darmanitan with the ability Zen Mode and it's 50% HP or below.

### Images / Video

* https://discordapp.com/channels/419213663107416084/1368163973366681712/1475205340604666079
* https://discordapp.com/channels/419213663107416084/1368163973366681712/1475208880505094318

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

linathan

### PR DESCRIPTION
**Pull request by LinathanZel**
Title

## Description
This PR fixes `ABILITY_ZEN_MODE` to match on cartridge behavior.
* Zen Mode will only activate and change form to Zen Mode Form if Darmanitan is at 50% HP or below at the end of turn.
* Zen Mode will change Darmanitan to Standard Mode Form if swapped out, regardless of the conditions for Zen Mode are met.
* New battle messages: `Zen Mode triggered!` and `Zen Mode ended!`

Additionally, tests were modified for Zen Mode:
* Removed `Zen Mode switches Darmanitan's form when HP is half or less before the first turn`
* Added `Zen Mode switches Darmanitan's form to Standard when swapped out`

## Media

https://github.com/user-attachments/assets/87bbc694-0742-4e89-8858-f07276db91f0

## Issue(s) that this PR fixes
Fixes #9303

## Discord contact info
linathan

### CODE REVIEW

**Comment by LinathanZel** [comment]
Ready for review!

File: src/battle_end_turn.c [hunk 1]
```diff
@@ -1328,6 +1328,15 @@ static bool32 HandleEndTurnFormChange(enum BattlerId battler)
             BattleScriptExecute(BattleScript_PowerConstruct);
         else if (ability == ABILITY_HUNGER_SWITCH)
             BattleScriptExecute(BattleScript_BattlerFormChangeEnd3NoPopup);
+        else if (ability == ABILITY_ZEN_MODE)
```
Comment (AlexOn1ine) [inline src/battle_end_turn.c]: could you turn this if block into a switch?

File: src/battle_message.c [hunk 2]
```diff
@@ -899,6 +899,8 @@ const u8 *const gBattleStringsTable[STRINGID_COUNT] =
     [STRINGID_PKMNANGRY]                            = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} is angry!"),
     [STRINGID_PKMNEATING]                           = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} is eating!"),
     [STRINGID_PKMNDISGUISEWASBUSTED]                = COMPOUND_STRING("{B_SCR_NAME_WITH_PREFIX}'s disguise was busted!"),
+    [STRINGID_ZENMODETRIGGERED]                     = COMPOUND_STRING("Zen Mode triggered!"),
+    [STRINGID_ZENMODEENDED]                         = COMPOUND_STRING("Zen Mode ended!"),
```
Comment (AlexOn1ine) [inline src/battle_message.c]:
```suggestion
    [STRINGID_ZENMODETRIGGERED]                     = COMPOUND_STRING("{B_SCR_ABILITY} triggered!"),
    [STRINGID_ZENMODEENDED]                         = COMPOUND_STRING("{B_SCR_ABILITY} ended!"),
```

File: src/battle_end_turn.c [hunk 3]
```diff
@@ -1324,12 +1324,26 @@ static bool32 HandleEndTurnFormChange(enum BattlerId battler)
     {
         gBattleScripting.battler = battler;
         gBattleScripting.abilityPopupOverwrite = ability; // To prevent the new form's ability from pop up
-        if (ability == ABILITY_POWER_CONSTRUCT) // Special animation
+        switch (ability)
+        {
+        case ABILITY_POWER_CONSTRUCT: // Special animation
```
Comment (AlexOn1ine) [inline src/battle_end_turn.c]:
```suggestion
        case ABILITY_POWER_CONSTRUCT:
```
should probably remove this comment at this point. It's clear from the code and the default mentions there is a default

File: src/battle_end_turn.c [hunk 4]
```diff
@@ -1324,12 +1324,26 @@ static bool32 HandleEndTurnFormChange(enum BattlerId battler)
...
             BattleScriptExecute(BattleScript_PowerConstruct);
-        else if (ability == ABILITY_HUNGER_SWITCH)
+            break;
+        case ABILITY_HUNGER_SWITCH:
             BattleScriptExecute(BattleScript_BattlerFormChangeEnd3NoPopup);
-        else
+            break;
+        case ABILITY_ZEN_MODE:
+            if (gBattleMons[battler].species == SPECIES_DARMANITAN_ZEN
+                || gBattleMons[battler].species == SPECIES_DARMANITAN_GALAR_ZEN)
```
Comment (AlexOn1ine) [inline src/battle_end_turn.c]:
```suggestion
            if (gBattleMons[battler].species == SPECIES_DARMANITAN_ZEN
           || gBattleMons[battler].species == SPECIES_DARMANITAN_GALAR_ZEN)
```
usually this is the alignment we are using.
