### PR TITLE
Fixes Spectral Thief stealing boost at the wrong time

### LINKED ISSUE #6191: Spectral Thief should steal the target's stat boosts before dealing damage
### Description

Title

### Version

1.10.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6191

### CODE REVIEW

File: include/constants/battle.h [hunk 1]
```diff
@@ -388,34 +388,33 @@
...
+#define MOVE_EFFECT_ION_DELUGE          79
+#define MOVE_EFFECT_AROMATHERAPY        80 // No functionality yet
+#define MOVE_EFFECT_HAZE                81
+#define MOVE_EFFECT_LEECH_SEED          82
+#define MOVE_EFFECT_REFLECT             83
+#define MOVE_EFFECT_LIGHT_SCREEN        84
+#define MOVE_EFFECT_SALT_CURE           85
+#define MOVE_EFFECT_EERIE_SPELL         86
 
 #define NUM_MOVE_EFFECTS                88
```
Comment (Pawkkie) [inline include/constants/battle.h:419]:
```suggestion
#define NUM_MOVE_EFFECTS                87
```

File: test/battle/move_effect/spectral_thief.c [hunk 2]
```diff
@@ -0,0 +1,52 @@
+#include "global.h"
+#include "test/battle.h"
+
+SINGLE_BATTLE_TEST("Spectral Thies steals opponents boost before attacking", s16 damage)
```
Comment (Pawkkie) [inline test/battle/move_effect/spectral_thief.c:4]:
```suggestion
SINGLE_BATTLE_TEST("Spectral Thief steals opponents boost before attacking", s16 damage)
```

File: test/battle/move_effect/spectral_thief.c [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        if (move == MOVE_SWORDS_DANCE)
+            MESSAGE("The opposing Wobbuffet stole the target's boosted stats!");
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_SPECTRAL_THIEF, opponent);
+        HP_BAR(player, captureDamage: &results[i].damage);
+    } FINALLY {
+        EXPECT_MUL_EQ(results[0].damage, Q_4_12(2.0), results[1].damage);
+    }
+}
+
+SINGLE_BATTLE_TEST("Spectral Thies can't steals opponents boost if target is immune")
```
Comment (Pawkkie) [inline test/battle/move_effect/spectral_thief.c:32]:
```suggestion
SINGLE_BATTLE_TEST("Spectral Thief can't steal opponent's boost if target is immune")
```

**Review by Pawkkie — CHANGES_REQUESTED** [review]

**Comment by AlexOn1ine** [comment]
review addressed

**Review by Pawkkie — APPROVED** [review]
