### PR TITLE
Gulp missile not triggering on faint fix and added form change type

### LINKED ISSUE #4143: Gulp Missile doesn't trigger on KO
### Description

Title. Gulp Missile's activation currently checks for IsBattlerAlive, meaning that it doesn't trigger if the Gulp Missiler is knocked out. This is contradictory to canon behaviour as per [this post](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8285893). 

### Version

1.7.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by BlueAnthem37510**
As above

## Description
The bug was being caused by transformed cramorant being changed back to it's normal form after fainting but before the ability triggered, so similar to how Illusion works on faint, I added a battlescript to run before the faint resets cramorant's form.

In src/battle_util.c I removed some repeating code that gulp missile had. It had a TO DO noted on it for adding a form change type so I've added FORM_CHANGE_END_MOVE for this. I'm not confident I have implemented this in the correct way, but it does work.

## Images

test-ezgif com-video-to-gif-converter

## Issue(s) that this PR fixes

Fixes #4143

### CODE REVIEW

File: include/constants/battle_script_commands.h [hunk 1]
```diff
@@ -237,6 +237,7 @@
 #define VARIOUS_STORE_HEALING_WISH                   145
 #define VARIOUS_HIT_SWITCH_TARGET_FAILED             146
 #define VARIOUS_TRY_REVIVAL_BLESSING                 147
+#define VARIOUS_TRY_ACTIVATE_GULP_MISSILE            148
```
Comment (AlexOn1ine) [inline include/constants/battle_script_commands.h:240]: Instead of a various could you use a callnative? For examples you can check all the callnatives at the end of the `battle_script_commands.h` file. 

Generally we try to phase out variouses.

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -8969,6 +8969,41 @@ static void Cmd_various(void)
         }
         break;
     }
+    case VARIOUS_TRY_ACTIVATE_GULP_MISSILE: 
+    {
+        VARIOUS_ARGS();
+
+        u16 battlerAbility = GetBattlerAbility(battler);
+        if (battlerAbility == ABILITY_GULP_MISSILE){
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:8977]: bracket on new line

File: src/battle_script_commands.c [hunk 3]
```diff
@@ -8969,6 +8969,41 @@ static void Cmd_various(void)
...
+                if (GetBattlerAbility(gBattlerAttacker) != ABILITY_MAGIC_GUARD)
+                {
+                    gBattleMoveDamage = GetNonDynamaxMaxHP(gBattlerAttacker) / 4;
+                    if (gBattleMoveDamage == 0)
+                        gBattleMoveDamage = 1;
+                }
+                 
+                BattleScriptPushCursor();
+                                                              
+                switch(gBattleMons[gBattlerTarget].species){
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:8992]: same here

File: test/battle/ability/gulp_missile.c [hunk 4]
```diff
@@ -117,8 +117,7 @@ SINGLE_BATTLE_TEST("(Gulp Missile) Cramorant in Gorging paralyzes the target if
 
 SINGLE_BATTLE_TEST("(Gulp Missile) triggers even if the user is fainted by opposing mon")
 {
-    // See: https://github.com/rh-hideout/pokeemerald-expansion/issues/4143
-    KNOWN_FAILING;
+    // See: https://github.com/rh-hideout/pokeemerald-expansion/issues/4143
```
Comment (AlexOn1ine) [inline test/battle/ability/gulp_missile.c:120]: since you fixed the issue the comment isn't needed anymore

File: src/battle_util.c [hunk 5]
```diff
@@ -5583,35 +5583,29 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
...
-                        if (gBattleMoveDamage == 0)
-                            gBattleMoveDamage = 1;
+                    
+                    switch(gBattleMons[gBattlerTarget].species){
+                        case SPECIES_CRAMORANT_GORGING:             
+                            TryBattleFormChange(battler, FORM_CHANGE_END_MOVE);                                        
+                            gBattlescriptCurrInstr = BattleScript_GulpMissileGorging; break;
+                        case SPECIES_CRAMORANT_GULPING: default:           
+                            TryBattleFormChange(battler, FORM_CHANGE_END_MOVE);                                            
+                            gBattlescriptCurrInstr = BattleScript_GulpMissileGulping; break;
```
Comment (AlexOn1ine) [inline src/battle_util.c:5605]: some formatting issue across the block

**Review by AlexOn1ine — CHANGES_REQUESTED** [review]
A couple issues with formatting but looks good otherwise.

File: include/constants/form_change_types.h [hunk 6]
```diff
@@ -120,4 +120,8 @@
 // param1: status
 #define FORM_CHANGE_STATUS                      20
 
+// Form change that activates after move is used.
+//Only used for activating gulp missile
+#define FORM_CHANGE_END_MOVE                     21
```
Comment (AsparagusEduardo) [inline include/constants/form_change_types.h:125]: I think `FORM_CHANGE_HIT_BY_MOVE` would be more apt.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: src/battle_script_commands.c [hunk 7]
```diff
@@ -16864,38 +16864,39 @@ void BS_TryGulpMissile(void)
 void BS_TryActivateGulpMissile(void)
 {
     NATIVE_ARGS();
-    
-    if (GetBattlerAbility(gBattlerTarget) == ABILITY_GULP_MISSILE)
+
+    if (GetBattlerAbility(gBattlerTarget) == ABILITY_GULP_MISSILE
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:16868]: small nitpick but since the ability check takes the most cycles it makes more sense to check it as the last thing in the condition since it is more likely it will fail long before that.

File: src/battle_script_commands.c [hunk 8]
```diff
@@ -16861,6 +16861,44 @@ void BS_TryGulpMissile(void)
 }
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:16863]: extra blank line

File: src/battle_script_commands.c [hunk 9]
```diff
@@ -16861,6 +16861,44 @@ void BS_TryGulpMissile(void)
...
+        
+        BattleScriptPushCursor();                                                            
+        switch(gBattleMons[gBattlerTarget].species)
+        {
+            case SPECIES_CRAMORANT_GORGING:             
+                TryBattleFormChange(gBattlerTarget, FORM_CHANGE_HIT_BY_MOVE);
+                gBattlescriptCurrInstr = BattleScript_GulpMissileGorging; 
+                break;
+            case SPECIES_CRAMORANT_GULPING: 
+            default:
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:16889]: Any particular reason you added a default here?

**Review by AlexOn1ine — COMMENTED** [review]
sorry, a couple more things :sweat_smile:

File: src/battle_script_commands.c (hunk 9 above)
Comment (AsparagusEduardo) [reply src/battle_script_commands.c:16889]: Modern doesn't like switches without defaults

Comment (AlexOn1ine) [reply src/battle_script_commands.c:16888]: Shouldn't the default be a break in this case? Since if it defaults both given cases will be falls and it would be a bug if it starts a form change and goes to the gulp script. 

This could happen in a randomizer when a species other the Cramorant gets Gulp Missile as an ability

File: src/battle_util.c [hunk 10]
```diff
@@ -5583,35 +5583,31 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
...
+                        default:           
+                            TryBattleFormChange(battler, FORM_CHANGE_HIT_BY_MOVE);                                            
+                            gBattlescriptCurrInstr = BattleScript_GulpMissileGulping; 
+                            break;
                     }
-                    BattleScriptPushCursor();
-                    gBattlescriptCurrInstr = BattleScript_GulpMissileGulping;
-                    effect++;
-                }
+                    effect++;
```
Comment (AlexOn1ine) [inline src/battle_util.c:5610]: Can you move `effect++` to both switch cases,  `SPECIES_CRAMORANT_GORGING` and `SPECIES_CRAMORANT_GULPING`? The effect should only be increased if one of Cramorant species forms is correct otherwise it would be a bug.

File: src/battle_script_commands.c [hunk 11]
```diff
@@ -16860,6 +16860,43 @@ void BS_TryGulpMissile(void)
...
+            default:           
+                TryBattleFormChange(gBattlerTarget, FORM_CHANGE_HIT_BY_MOVE);
+                gBattlescriptCurrInstr = BattleScript_GulpMissileGulping; 
+                break;
+        } 
+    }          
+    else
+    {
+        gBattlescriptCurrInstr = cmd->nextInstr;
+    }
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:16897]: Can you replace the `break`'s with `return`'s, remove the else branch and just have the next instruction by itself at the end? This potentially eliminates a bug where the next instruction statement would be never reached.

**Review by AlexOn1ine — COMMENTED** [review]
I'm sorry, there are a couple more things I noticed :sweat_smile:

File: src/battle_script_commands.c (hunk 9 above)
Comment (AsparagusEduardo) [reply src/battle_script_commands.c:16888]: I think we could use this to have a generic "transformed when hit by move" so that it's not exclusively linked to Gulp Missile.

File: src/battle_script_commands.c [hunk 12]
```diff
@@ -16860,6 +16860,43 @@ void BS_TryGulpMissile(void)
...
+        
+        BattleScriptPushCursor();                                                            
+        switch(gBattleMons[gBattlerTarget].species)
+        {
+            case SPECIES_CRAMORANT_GORGING:             
+                TryBattleFormChange(gBattlerTarget, FORM_CHANGE_HIT_BY_MOVE);
+                gBattlescriptCurrInstr = BattleScript_GulpMissileGorging; 
+                break;
+            case SPECIES_CRAMORANT_GULPING: 
+            default:
```
Comment (AsparagusEduardo) [inline src/battle_script_commands.c:16888]: Removing whitespace
```suggestion
        BattleScriptPushCursor();
        switch(gBattleMons[gBattlerTarget].species)
        {
            case SPECIES_CRAMORANT_GORGING:
                TryBattleFormChange(gBattlerTarget, FORM_CHANGE_HIT_BY_MOVE);
                gBattlescriptCurrInstr = BattleScript_GulpMissileGorging; 
                break;
            case SPECIES_CRAMORANT_GULPING: 
            default:
```

File: src/battle_script_commands.c (hunk 11 above)
Comment (AsparagusEduardo) [inline src/battle_script_commands.c:16897]: Removing whitespace
```suggestion
                TryBattleFormChange(gBattlerTarget, FORM_CHANGE_HIT_BY_MOVE);
                gBattlescriptCurrInstr = BattleScript_GulpMissileGulping;
                break;
        }
    }
    else
    {
        gBattlescriptCurrInstr = cmd->nextInstr;
    }
```

File: src/battle_util.c [hunk 13]
```diff
@@ -5583,35 +5583,31 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
...
                     {
-                        gBattleMoveDamage = GetNonDynamaxMaxHP(gBattlerAttacker) / 4;
-                        if (gBattleMoveDamage == 0)
-                            gBattleMoveDamage = 1;
+                        case SPECIES_CRAMORANT_GORGING:             
+                            TryBattleFormChange(battler, FORM_CHANGE_HIT_BY_MOVE);                                        
+                            gBattlescriptCurrInstr = BattleScript_GulpMissileGorging; 
+                            break;
+                        case SPECIES_CRAMORANT_GULPING: 
+                        default:
```
Comment (AsparagusEduardo) [inline src/battle_util.c:5605]: Removing whitespace
```suggestion
                        case SPECIES_CRAMORANT_GORGING:
                            TryBattleFormChange(battler, FORM_CHANGE_HIT_BY_MOVE);
                            gBattlescriptCurrInstr = BattleScript_GulpMissileGorging;
                            break;
                        case SPECIES_CRAMORANT_GULPING: 
                        default:
```

File: src/battle_util.c [hunk 14]
```diff
@@ -5583,35 +5583,31 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
...
-                        gBattleMoveDamage = GetNonDynamaxMaxHP(gBattlerAttacker) / 4;
-                        if (gBattleMoveDamage == 0)
-                            gBattleMoveDamage = 1;
+                        case SPECIES_CRAMORANT_GORGING:             
+                            TryBattleFormChange(battler, FORM_CHANGE_HIT_BY_MOVE);                                        
+                            gBattlescriptCurrInstr = BattleScript_GulpMissileGorging; 
+                            break;
+                        case SPECIES_CRAMORANT_GULPING: 
+                        default:           
+                            TryBattleFormChange(battler, FORM_CHANGE_HIT_BY_MOVE);
```
Comment (AsparagusEduardo) [inline src/battle_util.c:5606]: Removing whitespace
```suggestion
                            TryBattleFormChange(battler, FORM_CHANGE_HIT_BY_MOVE);
```

File: src/data/pokemon/form_change_tables.h [hunk 15]
```diff
@@ -1098,6 +1098,7 @@ static const struct FormChange sSandacondaFormChangeTable[] =
 static const struct FormChange sCramorantFormChangeTable[] = {
     {FORM_CHANGE_BATTLE_HP_PERCENT, SPECIES_CRAMORANT_GULPING, ABILITY_GULP_MISSILE, HP_HIGHER_THAN,   50},
     {FORM_CHANGE_BATTLE_HP_PERCENT, SPECIES_CRAMORANT_GORGING, ABILITY_GULP_MISSILE, HP_LOWER_EQ_THAN, 50},
+    {FORM_CHANGE_HIT_BY_MOVE,       SPECIES_CRAMORANT, ABILITY_GULP_MISSILE},
```
Comment (AsparagusEduardo) [inline src/data/pokemon/form_change_tables.h:1101]:
```suggestion
    {FORM_CHANGE_BATTLE_HP_PERCENT, SPECIES_CRAMORANT_GULPING, ABILITY_GULP_MISSILE, HP_HIGHER_THAN,   50},
    {FORM_CHANGE_BATTLE_HP_PERCENT, SPECIES_CRAMORANT_GORGING, ABILITY_GULP_MISSILE, HP_LOWER_EQ_THAN, 50},
    {FORM_CHANGE_HIT_BY_MOVE,       SPECIES_CRAMORANT,         ABILITY_GULP_MISSILE},
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]
Whitespace and alignment corrections

**Review by AlexOn1ine — APPROVED** [review]
Can be merged from my side. Thanks Blue :thumbsup:

**Review by AsparagusEduardo — APPROVED** [review]
