### PR TITLE
fix entry hazards switch in issue #3207

### LINKED ISSUE #3207: Toxic Spikes don't function properly after a Pecha Berry activation.
### Description

Toxic Spikes seem to bug out if a Pokémon has its poison healed by a Pecha Berry on switch-in.

Once you've been healed by the Pecha Berry, if you switch in any other Pokémon afterwards, Toxic Spikes will not poison that Pokémon. (Judging by the nature of the bug, I'd assume an item like Lum Berry would work too.)

For clarity, here's a scenario where this bug would occur:

```
Turn 1:
* Opponent sets up 1 layer of Toxic Spikes

Turn 2:
* Player switches in Pokémon holding Pecha Berry.
* Pokémon gets poisoned but is immediately healed by Pecha Berry.

Turn 3:
* Player switches in Pokémon holding nothing.
* Pokémon does not get poisoned.

Turn 4:
* Player switches to another Pokémon holding nothing.
* Pokémon gets poisoned by the Toxic Spikes like normal.
```

Here's a video of this bug in action:

https://github.com/rh-hideout/pokeemerald-expansion/assets/77281351/11f1847c-5c26-4393-963a-7ab9841317c3

### Version

1.5.1 (Default)

### Upcoming Version

_No response_

### Discord contact info

sarnnn

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3207
Replaces #3275

Added test for fixed Toxic Spikes issue(and additional one which stemmed from the same bug).

The issue was that the side status for hazard damge was not properly set/cleared after every switch-in. I fixed it by placing it in the Disable Struct instead, which is by default cleared on fainting/switching. Also, this shouldn't have been a side status in the first place, since it affects individual battlers.

Edit: It also accidentally fixed one known failing test, nice

### CODE REVIEW

File: test/battle/move_effect/toxic_spikes.c [hunk 1]
```diff
@@ -208,3 +208,65 @@ SINGLE_BATTLE_TEST("Toxic Spikes are removed by Poison-types affected by Magnet
         NOT STATUS_ICON(opponent, poison: TRUE);
     }
 }
+
+SINGLE_BATTLE_TEST("Toxic Spikes inflicts poison on switch in after Pecha Berry's activation") // #3207
```
Comment (AsparagusEduardo) [inline test/battle/move_effect/toxic_spikes.c:212]: This test is essentially the same as `Pokemon can be further poisoned with Toxic spikes after a status healing hold effect was previously used` in `test/battle/hold_effect/cure_status.c` except with the sides reversed.

Please move this test over there and edit them both to march with the following:
- `PARAMETRIZE` for Lum and Pecha berries.
- Messages for both.
- Same test name, except with a ` - Player` and ` - Opponent` suffix.
- Removing the issue number.

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

**Comment by DizzyEggg** [comment]
Ready for review

**Review by AsparagusEduardo — APPROVED** [review]
