### PR TITLE
 Fix strength sap on substitute

### LINKED ISSUE #3357: Strength Sap + Substitute no HP Gain
### Description

Using Strength Sap while under substitute prints the wrong message and doesn't heal any HP

strengthsap_substitute

### Version

1.5.3 (Default)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3357
Replaces #3358

Ghoul's fix + tests

### CODE REVIEW

File: test/battle/move_effect/strength_sap.c [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+        MESSAGE("Foe Wobbuffet had its energy drained!");
+    } THEN {
+        EXPECT_EQ(results[i].hp * -1, atkStat);
+    }
+}
+
+// Same as above, but Substitute is used before Strength Sap.
+SINGLE_BATTLE_TEST("Strength Sap works exactly the same when attacker is behind substitute", s16 hp)
+{
+    u32 atkStat = 0;
```
Comment (Bassoonian) [inline test/battle/move_effect/strength_sap.c:36]:
```suggestion
    u32 atkStat;
```

**Review by Bassoonian — CHANGES_REQUESTED** [review]

File: test/battle/move_effect/strength_sap.c (hunk 1 above)
Comment (DizzyEggg) [reply test/battle/move_effect/strength_sap.c:36]: Why? This is just to make sure the variable is not initialized in case PARAMETRIZE misses it.

Comment (Bassoonian) [reply test/battle/move_effect/strength_sap.c:36]: As far as I'm aware in all the tests variables are just initialised as is, not without a default value. Feel free to correct me though, but it's a consistency thing (I think, at least!)

Comment (DizzyEggg) [reply test/battle/move_effect/strength_sap.c:36]: Nope, they're regular variables. I remember we had one Bug Bite test failing, because the variable wasn't initialized #3311.

Comment (Bassoonian) [reply test/battle/move_effect/strength_sap.c:36]: Oh, my bad then!

**Review by Bassoonian — APPROVED** [review]
