### PR TITLE
Fixes Knock Off / Ogerpon behavior

### LINKED ISSUE #9443: Knock Off does knock off Ogerpon masks from Ogerpon
### Description

> Knock Off cannot remove any of the Hearthflame, Wellspring, or Cornerstone Masks from Ogerpon.

The following tests passed.
But note that OGERON **did not** transform in the second test (I am not sure if this is correct).
```
SINGLE_BATTLE_TEST("Knock Off does knock off Ogerpon masks from Pokemon that don't actually use them")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET) { Item(ITEM_HEARTHFLAME_MASK); }
    } WHEN {
        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_KNOCK_OFF); }
    } SCENE {
        MESSAGE("Wobbuffet knocked off the opposing Wobbuffet's Hearthflame Mask!");
    } THEN {
        EXPECT(opponent->item == ITEM_NONE);
    }
}

SINGLE_BATTLE_TEST("Knock Off doesn't knock off Ogerpon masks from Ogerpon forms that actually use them")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_OGERPON) { Item(ITEM_HEARTHFLAME_MASK); }
    } WHEN {
        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_KNOCK_OFF); }
    } SCENE {
        NOT MESSAGE("Wobbuffet knocked off the opposing Ogerpon's Hearthflame Mask!");
    } THEN {
        EXPECT(opponent->item == ITEM_HEARTHFLAME_MASK);
    }
}
```
What was observed in the game was different(See the video below).
By the way, the following tests are missing:
> Knock Off cannot remove a Booster Energy from any Paradox Pokémon (**excluding Koraidon and Miraidon**), even if it hasn't consumed the item because its Ability triggered from the appropriate weather or terrain condition instead.

### Reproduction Steps

.

### Images / Video

Observed in the game:

https://github.com/user-attachments/assets/a5bafd02-164f-46c1-b2a4-2ad2a83d5f43

### Version

1.15.0 (Latest release)

### Upcoming/master Version

master

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #9443

### CODE REVIEW

File: test/battle/move_effect/knock_off.c
Comment (hedara90) [inline test/battle/move_effect/knock_off.c:1]: Could you add a test case for "Paradox Pokemon can't knock off Booster energy from non-Paradox mons"?

Comment (AlexOn1ine) [reply test/battle/move_effect/knock_off.c:1]: Like that?
```C
SINGLE_BATTLE_TEST("Knock Off used by a Paradox mon doesn't knock off a Paradox mon's Booster Energy")
{
    GIVEN {
        PLAYER(SPECIES_TORKOAL) { Ability(ABILITY_DROUGHT); }
        PLAYER(SPECIES_GREAT_TUSK);
        OPPONENT(SPECIES_GREAT_TUSK) { Item(ITEM_BOOSTER_ENERGY); }
    } WHEN {
        TURN { SWITCH(player, 1); }
        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_KNOCK_OFF); }
    } SCENE {
        NOT MESSAGE("Great Tust knocked off the opposing Great Tusk's Booster Energy!");
    } THEN {
        EXPECT(opponent->item == ITEM_BOOSTER_ENERGY);
    }
}
```

Comment (hedara90) [reply test/battle/move_effect/knock_off.c:1]: The target should be a Wobbuffet, Paradox mons can't Knock Off a non-Paradox mon's Booster Energy.

Comment (AlexOn1ine) [reply test/battle/move_effect/knock_off.c:1]: test added

File: test/battle/move_effect/knock_off.c [hunk 1]
```diff
@@ -437,3 +437,73 @@ SINGLE_BATTLE_TEST("Knock Off does not activate if the item was previously consu
...
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_CELEBRATE); MOVE(player, MOVE_KNOCK_OFF); }
+    } SCENE {
+        NOT MESSAGE("Wobbuffet knocked off the opposing Great Tusk's Booster Energy!");
+    } THEN {
+        EXPECT(opponent->item == ITEM_BOOSTER_ENERGY);
+    }
+}
+
+SINGLE_BATTLE_TEST("Knock Off used by a Paradox mon doesn't knock off a Paradox mon's Booster Energy")
```
Comment (hedara90) [inline test/battle/move_effect/knock_off.c]:
```suggestion
SINGLE_BATTLE_TEST("Knock Off used by a Paradox mon doesn't knock off a non-Paradox mon's Booster Energy")
```
