### PR TITLE
Fix cure status item effect not working properly in doubles

### LINKED ISSUE #7926: double battle healing status ineffective
### Description

using mon B's turn to heal mon A in a double batttel is inneffectvie; status continuees to affect mon, status indictaor remains until menuing, effect continues after indicator departs, subsequent attempt s to heal are denied. 

### Reproduction Steps

in a double battle wiht mon A poisoned, use an antiditoe during mon B's turn. it is consumed, yet the status indicator remains. poinson damage will occur. go to pokemeon menu; see that the indictaor has departed. progress another turn in combat to witness poisosn damage occurring. open debug menu to wintess that posion remains on the mon (secretly). attempt to use another antidote only to be denied. 

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

ca53ccb55e38c1b55c746e0de05a861c5918940d

### Discord contact info

mrleaky666

### PR DESCRIPTION
**Pull request by FosterProgramming**
Code was applying the effect to the item user instead of the item target
Refactored to better handle the separation between battler and non battler target.
Fixed inconsistent test where battler would die at the end of turn depending of the status condition parameter

## Issue(s) that this PR fixes
Fixes #7926

## Discord contact info
Jamie

### CODE REVIEW

File: test/battle/item_effect/cure_status.c [hunk 1]
```diff
@@ -31,6 +31,23 @@ SINGLE_BATTLE_TEST("Antidote heals a battler from being poisoned")
     }
 }
 
+DOUBLE_BATTLE_TEST("Antidote heals a battler from being poisoned (doubles)")
```
Comment (AlexOn1ine) [inline test/battle/item_effect/cure_status.c:34]: Could you add a test (or parametrize) that also tests playerLeft?

File: test/battle/item_effect/cure_status.c [hunk 2]
```diff
@@ -135,6 +152,31 @@ SINGLE_BATTLE_TEST("Full Heal heals a battler from any primary status")
     }
 }
 
+DOUBLE_BATTLE_TEST("Full Heal heals a battler from any primary status (doubles)")
```
Comment (AlexOn1ine) [inline test/battle/item_effect/cure_status.c:161]: It doesn't matter much but this could be a single battle tests since it just verifies if the Full Heal works. 

No need to change it though just something I noticed

Comment (FosterProgramming) [reply test/battle/item_effect/cure_status.c:161]: I mean that's the point, it verifies that full heal cures status when cross-used in a double battle. Same as the antidote test.

**Comment by FosterProgramming** [comment]
PR updated

File: test/battle/item_effect/cure_status.c (hunk 2 above)
Comment (AlexOn1ine) [reply test/battle/item_effect/cure_status.c:161]: Ah, I was a bit confused because the above test looked almost identical but I realize that it is using different items to heal

**Review by AlexOn1ine — APPROVED** [review]
