### PR TITLE
Fix Tera indicators

### LINKED ISSUE #4897: Tera Type Icon is wrong for the opponent and Stellar Type icon is on the wrong position
### Description

pokeemerald-test-3
pokeemerald-test-1

It is just a visual problem

### Version

1.8.4 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Bassoonian**
## Issue(s) that this PR fixes
Fixes #4897

## **Discord contact info**
bassoonian

### CODE REVIEW

File: src/data/graphics/gimmicks.h [hunk 1]
```diff
@@ -103,7 +103,7 @@ static const struct SpriteSheet sSpriteSheet_MegaIndicator = {sMegaIndicatorGfx,
 static const struct SpriteSheet sSpriteSheet_AlphaIndicator = {sAlphaIndicatorGfx, sizeof(sAlphaIndicatorGfx), TAG_ALPHA_INDICATOR_TILE};
 static const struct SpriteSheet sSpriteSheet_OmegaIndicator = {sOmegaIndicatorGfx, sizeof(sOmegaIndicatorGfx), TAG_OMEGA_INDICATOR_TILE};
 static const struct SpriteSheet sSpriteSheet_DynamaxIndicator = {sDynamaxIndicatorGfx, sizeof(sDynamaxIndicatorGfx), TAG_DYNAMAX_INDICATOR_TILE};
-static const struct SpriteSheet sTeraIndicatorSpriteSheets[NUMBER_OF_MON_TYPES + 1] =
+static const struct SpriteSheet sTeraIndicatorSpriteSheets[NUMBER_OF_MON_TYPES] =
 {
     {sNormalIndicatorGfx, sizeof(sNormalIndicatorGfx), TAG_NORMAL_INDICATOR_TILE},
```
Comment (AlexOn1ine) [inline src/data/graphics/gimmicks.h:108]: shouldn't it be solved by adding a dummy in this array as the first entry?

Comment (Bassoonian) [reply src/data/graphics/gimmicks.h:108]: I tried, but for some reason that absolutely shifted everything (it even started to look like the mega evolution icon)

Comment (AlexOn1ine) [reply src/data/graphics/gimmicks.h:108]: It could be that I am misunderstanding the issue though since I don't understand how decreasing it in `sTeraIndicatorSpriteSheets[GetBattlerTeraType(battler) - 1]` solves the problem.

Comment (AlexOn1ine) [reply src/data/graphics/gimmicks.h:108]: > I tried, but for some reason that absolutely shifted everything (it even started to look like the mega evolution icon)

Interesting. No idea why

**Comment by Bassoonian** [comment]
Updated with a cleaner fix by @AlexOn1ine

**Review by AlexOn1ine — APPROVED** [review]
