### PR TITLE
fixes Micle Berry not increasing accuracy on the next turn

### LINKED ISSUE #5149: Micle Berry Issues
### Description

Micle Berry seems to not work properly. It is supposed to multipliy the accuracy of the holder's **next** move by 1.2, which means the effect can carry on to the next turn (At least that's how I understand it to work, feel free to correct me if I am wrong). But the effect just wears off once the Turn ends, resulting in no effect.

Here is an example to demonstrate. Megahorns Accuracy boosted with Micle Berry is 102%, which means it should always hit with the Micle Berry effect. 

https://github.com/user-attachments/assets/caa3f8d1-755c-4cfe-a5f5-8682e601a2ff

### Version

1.9.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes  #5149

### CODE REVIEW

**Comment by Pawkkie** [comment]
I'm not sure this test is representative, as it passes for me on vanilla master without the change.

**Comment by AlexOn1ine** [comment]
> I'm not sure this test is representative, as it passes for me on vanilla master without the change.

oh hm, I'm not sure how else a test could be written. Though I'm pretty sure this fixes the issue

**Comment by Pawkkie** [comment]
Did some investigating, if you just hardcode the PASSES_RANDOMLY to the fixed percentages we want, the tests check the success rate appropriately.

That being said, this solution unfortunately doesn't fix the berry applying across turns. Here are my tests:
This first one, where the Berry affects the move used in the same turn, passes
```
SINGLE_BATTLE_TEST("Miscle Berry increases the accuracy of the next used move")
{
    GIVEN {
        ASSUME(gMovesInfo[MOVE_ROCK_SLIDE].accuracy == 90);
        PASSES_RANDOMLY(100, 100, RNG_ACCURACY);
        PLAYER(SPECIES_WOBBUFFET) { MaxHP(100); HP(26); Item(ITEM_MICLE_BERRY); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(opponent, MOVE_TACKLE); MOVE(player, MOVE_ROCK_SLIDE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, opponent);
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, player);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROCK_SLIDE, player);
    }
}
```
This one, which is the same one you have here with the PASSES_RANDOMLY change, fails
```
SINGLE_BATTLE_TEST("Miscle Berry increases the accuracy of the next used move across turns")
{
    GIVEN {
        ASSUME(gMovesInfo[MOVE_ROCK_SLIDE].accuracy == 90);
        PASSES_RANDOMLY(100, 100, RNG_ACCURACY);
        PLAYER(SPECIES_WOBBUFFET) { MaxHP(100); HP(26); Item(ITEM_MICLE_BERRY); }
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(opponent, MOVE_TACKLE); }
        TURN { MOVE(player, MOVE_ROCK_SLIDE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, opponent);
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, player);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROCK_SLIDE, player);
    }
}
```

**Comment by AlexOn1ine** [comment]
> That being said, this solution unfortunately doesn't fix the berry applying across turns. Here are my tests:
> This first one, where the Berry affects the move used in the same turn, passes

I think my test is flawed but as far as I understand it should not work across turn but for the next used move.

**Comment by Pawkkie** [comment]
That's poor phrasing on my part, it's the next move used across turns that I was talking about, that's the only case it seems to break in.

T1 Player Wobb Celebrate, opp Wobb tackle, berry procs.
T2 Player Wobb Rock Slide should have 108 accuracy from berry, can still miss.

**Comment by AlexOn1ine** [comment]
Fixed. The problem was that the protect struct got cleared each turn, I used a BattleStruct field instead. 

I'm not sure if the protect struct getting clear during ai calcs is optimal but it is out of scope for this pr so I added a comment for now

**Comment by AlexOn1ine** [comment]
drafting for now. I want to do it a little bit differently

**Comment by AlexOn1ine** [comment]
> drafting for now. I want to do it a little bit differently

Ready for review. Though didn't change anything except a typo.

File: test/battle/hold_effect/micle_berry.c [hunk 1]
```diff
@@ -64,3 +64,36 @@ SINGLE_BATTLE_TEST("Micle Berry raises the holder's accuracy by 1.2")
...
+        TURN { MOVE(opponent, MOVE_TACKLE); }
+        TURN { MOVE(player, MOVE_ROCK_SLIDE); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, opponent);
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, player);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_ROCK_SLIDE, player);
+    }
+}
+
+SINGLE_BATTLE_TEST("Miscle Berry increases the accuracy of the next used move")
```
Comment (Pawkkie) [inline test/battle/hold_effect/micle_berry.c:85]: There's a typo in the berry name, should be Micle. This would mean the two tests have identical names, so I'd suggest either going with the name I was using for the other test ("Micle Berry increases the accuracy of the next used move across turns")or coming up with something else that's representative :)

Amusingly that typo was also in the test I commented whoops I read the berry name wrong lol

**Review by Pawkkie — CHANGES_REQUESTED** [review]
Just one test typo, looks great otherwise!

File: test/battle/hold_effect/micle_berry.c (hunk 1 above)
Comment (AlexOn1ine) [reply test/battle/hold_effect/micle_berry.c]: pushed a suggestion

**Comment by AlexOn1ine** [comment]
I don't understand why this does not compile. It is fine on my end

**Comment by AsparagusEduardo** [comment]
Probably something in master has an issue

**Comment by AsparagusEduardo** [comment]
Nvm, nothing recent seems to have the issue

**Comment by AlexOn1ine** [comment]
merging in master fixed the problem whatever it was

**Review by Pawkkie — APPROVED** [review]
