### PR TITLE
Fixes Cotton Spore failing if one of the targets blocks it

### LINKED ISSUE #6177: Gen 6+ Cotton Spore behaves incorrectly on a target with Overcoat/Safety Goggles/Grass-type
### Description

Since Gen 6, Cotton Spore has been a powder move that targets both foes. 
Currently powder moves are blocked by Overcoat, Safety Goggles and Grass-types in `CANCELLER_POWDER_MOVE`, which only checks one target and then ends the action if sucessfully blocked. This means that Cotton Spore may be incorrectly blocked by a single target being immune to powder moves (even if the other is not), or both targets may have their speed reduced despite one of them being immune to powder moves.
Likely solution: Moving this handling to `ABILITYEFFECT_MOVES_BLOCK` or `CanAbilityBlockMove` should correctly block effects only on immune targets.

Also the move animation only displays one target being affected even if both are affected.

### Version

upcoming (Edge)

### Upcoming/master Version

https://github.com/rh-hideout/pokeemerald-expansion/commit/64c5113b239aafc14fa7bb74c28e32f3894853b1

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6177

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -12297,3 +12274,30 @@ bool32 HasWeatherEffect(void)
...
 }
+
+bool32 IsMovePowderBlocked(u32 battlerAtk, u32 battlerDef, u32 move)
+{
+    bool32 effect = FALSE;
+
+    if (IsPowderMove(move) && (battlerAtk != battlerDef))
+    {
+        if (B_POWDER_GRASS >= GEN_6
+            && (IS_BATTLER_OF_TYPE(battlerDef, TYPE_GRASS) || GetBattlerAbility(battlerDef) == ABILITY_OVERCOAT))
```
Comment (Bassoonian) [inline src/battle_util.c:12285]:
```suggestion
        if (B_POWDER_GRASS >= GEN_6
         && (IS_BATTLER_OF_TYPE(battlerDef, TYPE_GRASS) || GetBattlerAbility(battlerDef) == ABILITY_OVERCOAT))
```
