### PR TITLE
fix telekinesis not working

### LINKED ISSUE #3679: Telekensis is not applying lock on effect
### Description

Telekenesis is currently only functioning as magnet rise for the target. Telekinesis should also make it so moves with an accuracy check cannot miss the target.

### Version

1.6.2 (Default)

### Upcoming Version

_No response_

### Discord contact info

thelastmudkip

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3679

Also corrects the string used.

And fixes one Roost known failing.

### CODE REVIEW

File: test/battle/move_effect/telekinesis.c [hunk 1]
```diff
@@ -0,0 +1,70 @@
+#include "global.h"
+#include "test/battle.h"
+
+ASSUMPTIONS
+{
+    ASSUME(gBattleMoves[MOVE_TELEKINESIS].effect == EFFECT_TELEKINESIS);
+}
+
+SINGLE_BATTLE_TEST("Telekinesis makes the target unable to avoid any attacks made against it")
```
Comment (AlexOn1ine) [inline test/battle/move_effect/telekinesis.c:9]: Doesn't this test need a random check since it would always succeed in a test environment regardless of accuracy?

Comment (DizzyEggg) [reply test/battle/move_effect/telekinesis.c:9]: hit:false makes the move always miss. If you run the the test without the fix, it fails.

**Review by AlexOn1ine — APPROVED** [review]
