### PR TITLE
Refactor Beat Up handling for Gen 3/4 defaults, fix crit check, and expand test coverage

### LINKED ISSUE #8173: Gen3 Beat Up tests
### Behavior Description

Gen3 Beat Up still uses a script for each hit which might cause issues now that the engine uses a much more update multi hit mechanic. 

Ideally we would update the gen3 script when we have some tests that cover the basics. .

### Images / Video

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by moostoet**
## Description
- Precompute Beat Up party participants and species info for both config paths, reuse that data in the battle script command, and simplify the effect script to rely on the standard multi-hit flow.
- Fix the Beat Up critical check (`jumpifcriticalhit` --> `jumpifnotcriticalhit`) so damage is only doubled on actual crits instead of non-crits.
- Add Gen3/4 vs Gen5+ Beat Up test coverage

## Media
N/A

## Issue(s) that this PR fixes
Fixes #8173

## Feature(s) this PR does NOT handle:
- Beat Up's per-hit independent critical-chance behaviour remains TODO.

## Things to note in the release changelog:
- BUGFIX: Beat Up (`GEN =< 5`) now no longer doubles its damage on every non-critical hit
- Beat Up now precomputes eligible party members/strikers for consistent multi-hit resolution and expanded tests covering both pre-Gen5 and Gen5+ rules

## Discord contact info
viridian.

### CODE REVIEW

File: include/battle.h [hunk 1]
```diff
@@ -740,6 +740,7 @@ struct BattleStruct
     u8 skyDropTargets[MAX_BATTLERS_COUNT]; // For Sky Drop, to account for if multiple Pokemon use Sky Drop in a double battle.
     // When using a move which hits multiple opponents which is then bounced by a target, we need to make sure, the move hits both opponents, the one with bounce, and the one without.
     u16 beatUpSpecies[PARTY_SIZE];
+    u8 beatUpPartyIndexes[PARTY_SIZE];
```
Comment (AlexOn1ine) [inline include/battle.h]: couldn't you just use `beatUpSpecies` for both and assign species vs index depending on the config?

**Review by AlexOn1ine — COMMENTED** [review]
Would you be open to do more changes so we can remove the `BattleScript_EffectBeatUp` script entirely? I can walk you through them or make a patch.

File: src/battle_util.c [hunk 2]
```diff
@@ -9390,6 +9424,11 @@ s32 DoFixedDamageMoveCalc(struct DamageContext *ctx)
     case EFFECT_FINAL_GAMBIT:
         dmg = GetNonDynamaxHP(ctx->battlerAtk);
         break;
+    case EFFECT_BEAT_UP:
+        if (B_BEAT_UP >= GEN_5)
+            return INT32_MAX;
```
Comment (AlexOn1ine) [inline src/battle_util.c]: Since you are already checking this in `CalcBeatUpDamage` this isn't needed anymore.

File: src/battle_util.c [hunk 3]
```diff
@@ -2486,12 +2517,15 @@ static enum MoveCanceler CancelerMultihitMoves(void)
              && !GetMonData(&party[i], MON_DATA_IS_EGG)
              && !GetMonData(&party[i], MON_DATA_STATUS))
             {
-                gBattleStruct->beatUpSpecies[gBattleStruct->beatUpSlot++] = species;
+#if B_BEAT_UP >= GEN_5
+                gBattleStruct->beatUpSpecies[gMultiHitCounter] = species;
+#else
+                gBattleStruct->beatUpSpecies[gMultiHitCounter] = i;
+#endif
```
Comment (AlexOn1ine) [inline src/battle_util.c]: were we can we use regular non preproc if's

File: src/battle_util.c [hunk 4]
```diff
@@ -271,6 +271,35 @@ static u32 CalcBeatUpPower(void)
     return (GetSpeciesBaseAttack(species) / 10) + 5;
 }
 
+static s32 CalcBeatUpDamage(struct DamageContext *ctx)
+{
+#if B_BEAT_UP >= GEN_5
+    return INT32_MAX;
+#else
```
Comment (AlexOn1ine) [inline src/battle_util.c]: same here, should be a regular if check

File: src/battle_script_commands.c [hunk 5]
```diff
@@ -12590,48 +12590,44 @@ static void Cmd_trysetfutureattack(void)
...
-        u8 beforeLoop = gBattleCommunication[0];
-        for (;gBattleCommunication[0] < PARTY_SIZE; gBattleCommunication[0]++)
-        {
-            if (GetMonData(&party[gBattleCommunication[0]], MON_DATA_HP)
-                && GetMonData(&party[gBattleCommunication[0]], MON_DATA_SPECIES_OR_EGG) != SPECIES_NONE
-                && GetMonData(&party[gBattleCommunication[0]], MON_DATA_SPECIES_OR_EGG) != SPECIES_EGG
-                && !GetMonData(&party[gBattleCommunication[0]], MON_DATA_STATUS))
-                break;
-        }
+#if B_BEAT_UP < GEN_5
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: you shouldn't need to hide this code block behind a config since this script isn't used for gen5+

**Review by AlexOn1ine — COMMENTED** [review]
looks good. a few more things and then it should be ready

File: src/battle_util.c (hunk 3 above)
Comment (moostoet) [reply src/battle_util.c]: Done

File: src/battle_util.c (hunk 4 above)
Comment (moostoet) [reply src/battle_util.c]: Done

File: src/battle_script_commands.c (hunk 5 above)
Comment (moostoet) [reply src/battle_script_commands.c]: Fixed

File: src/battle_util.c (hunk 2 above)
Comment (moostoet) [reply src/battle_util.c]: It’s still needed because `INT32_MAX` is just a sentinel out of `CalcBeatUpDamage`. Without the early return in `DoFixedDamageMoveCalc` the fixed‑damage logic would still run (like clearing moveResultFlags that carry type effectiveness). 
 
For Gen5+ Beat Up we want the normal damage path to handle effectiveness and messaging, so we bail out immediately when we see the sentinel to avoid wiping those flags.

Comment (AlexOn1ine) [reply src/battle_util.c]: Oh right, there is just a bit redundancy but I guess that's fine.

**Comment by AlexOn1ine** [comment]
@moostoet I took the libery to make some changes if it's okay :face_with_peeking_eye:

* Made a "with gen" config that allows us to test all the changes at run time for any gen
* Simplified `Cmd_trydobeatup` a little more since we already calculated everything
* Removed some static vars (was there a reason they were declared as static?)
* Also removed some of the bounds checking. I don't think it's useful there. If there is something, tests would tell us it if some reads are wrong in this case. 
 
Patch: [beat_up.patch](https://github.com/user-attachments/files/23696446/beat_up.patch)

Sorry I didn't want to bother you even more.
