### PR TITLE
Fix Snatch stealing snatched moves

### LINKED ISSUE #8349: Snatch can steal a snatched move
### Description

From Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Snatch_(move)
> Snatch no longer steals moves that were stolen by another Pokémon's Snatch on the same turn.

Snatch triggers in attackcanceler here:
https://github.com/rh-hideout/pokeemerald-expansion/blob/9fde188033cd8551fc7ee753e13e3a03767ee3e2/src/battle_script_commands.c#L1250-L1261

Nothing prevents snatch from triggering multiple times per turn. `stealMove` is only set in the above snippet and the following locations (apart from the ProtectStruct clear at end of turn):
https://github.com/rh-hideout/pokeemerald-expansion/blob/9fde188033cd8551fc7ee753e13e3a03767ee3e2/src/battle_main.c#L3339
https://github.com/rh-hideout/pokeemerald-expansion/blob/9fde188033cd8551fc7ee753e13e3a03767ee3e2/src/battle_script_commands.c#L13180

Nothing happens in snatchsetbattlers either: https://github.com/rh-hideout/pokeemerald-expansion/blob/9fde188033cd8551fc7ee753e13e3a03767ee3e2/data/battle_scripts_1.s#L5750
https://github.com/rh-hideout/pokeemerald-expansion/blob/9fde188033cd8551fc7ee753e13e3a03767ee3e2/src/battle_script_commands.c#L13523-L13536

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by moostoet**
## Description

Fixes an issue where Snatch could steal a move that was already snatched by another Pokémon in the same turn during double battles.

In Gen 3-4, if multiple Pokémon used Snatch, the stolen move would be passed along to each successive Snatch user (slowest user gets the effect). Starting in Gen 5, Snatch no longer steals moves that were already stolen by another Pokémon's Snatch on the same turn.

This PR adds the `B_SNATCH` configuration option to control this behavior based on generation settings.

### Changes:
- Added `B_SNATCH` config option in `include/config/battle.h` (defaults to `GEN_LATEST`)
  - When set to Gen 5+, Snatch cannot steal a move that was already snatched this turn
  - When set to Gen 4 or earlier, multiple Snatch users can chain-steal the same move
- Updated snatch check in `Cmd_attackcanceler` (`src/battle_script_commands.c`) to respect the config
- Added tests for Snatch behavior in `test/battle/move_effect/snatch.c`:
  - Snatch steals stat-boosting moves from the opponent
  - Snatch does not steal non-snatchable moves
  - Snatch does not steal a move that was already snatched this turn (Gen 5+)
  - Snatch steals from the correct target when multiple snatchable moves are used

## Issue(s) that this PR fixes

Fixes #8349

## Discord contact info

viridian.

### CODE REVIEW

**Comment by AlexOn1ine** [comment]
Wasn't this a generational change?

**Comment by moostoet** [comment]
@AlexOn1ine Yeah, I was working on that right after I posted it because I overlooked it. It's in there now though! 😅

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -1250,7 +1250,9 @@ static void Cmd_attackcanceler(void)
     u32 i;
     for (i = 0; i < gBattlersCount; i++)
```
Comment (PhallenTree) [inline src/battle_script_commands.c]:
```suggestion
    for (i = 0; i < gCurrentTurnActionNumber; i++)
```
Small optimization (only check battlers that have already acted)

File: test/battle/move_effect/snatch.c [hunk 2]
```diff
@@ -1,4 +1,111 @@
 #include "global.h"
 #include "test/battle.h"
 
-TO_DO_BATTLE_TEST("TODO: Write Snatch (Move Effect) test titles")
+ASSUMPTIONS
+{
+    ASSUME(GetMoveEffect(MOVE_SNATCH) == EFFECT_SNATCH);
+    ASSUME(MoveCanBeSnatched(MOVE_SWORDS_DANCE) == TRUE);
```
Comment (PhallenTree) [inline test/battle/move_effect/snatch.c:7]:
```suggestion
    ASSUME(MoveCanBeSnatched(MOVE_SWORDS_DANCE) == TRUE);
    ASSUME(GetMoveEffect(MOVE_SWORDS_DANCE) == EFFECT_ATTACK_UP_2);
    ASSUME(MoveCanBeSnatched(MOVE_CELEBRATE) == FALSE);
```
Since the tests check Swords Dance boosts

File: src/battle_script_commands.c (hunk 1 above)
Comment (PhallenTree) [inline src/battle_script_commands.c]:
```suggestion
    for (i = 0; i < gCurrentTurnActionNumber; i++)
```
Small optimization, no need to check battlers that have not acted yet.

**Comment by moostoet** [comment]
@PhallenTree I implemented your suggestions 👍

**Comment by AlexOn1ine** [comment]
@PhallenTree is this ready to go?

**Comment by PhallenTree** [comment]
> @PhallenTree is this ready to go?

There are conflicts, but yeah. Also you assigned this to yourself, so I assumed you'd also want to give a review.

**Comment by AlexOn1ine** [comment]
> > @PhallenTree is this ready to go?
> 
> There are conflicts, but yeah. Also you assigned this to yourself, so I assumed you'd also want to give a review.

Oh, I only assigned it because I didn't want it to be merged in the last release cycle. Though I forgot we have labels for that.

@moostoet conflicts

**Review by AlexOn1ine — APPROVED** [review]
