### PR TITLE
Fix mirage tower ceiling crumble color

### LINKED ISSUE #6566: mirage tower crumbling animation bug
### Description

when mirage tower crumbles, the animation uses the wrogn graphics. at least as of 1.9.4, the dust crumbling on the screen where you revceive fossils appears in the 'transparecy magenta' color. starting with 1.11.1, the animaiton of the tower itself crumbling on the route map also appears incorrect; using some shade of green and ohter garbage. 

to reproduce: take a fossil from the top floor of mirage tower (debug warp 24.97), watch cutscene.

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

mrleaky666

### PR DESCRIPTION
**Pull request by FosterProgramming**
Normally, the ceiling crumble sprites don't use their own palette and just use colors that are part of the player palette. I'm not sure why but at some point in expansion life, this turned the sprite purple. To fix this, I simply load the already existing palette file. This does not match the original color in vanilla emerald which was more green-ish but it arguably looks better

## Media
Master:

https://github.com/user-attachments/assets/0ef09af9-4577-4c4d-92d2-b18960667f9f

This commit:

https://github.com/user-attachments/assets/3f76d6c6-efdd-449e-8b92-6ec843264ae7

## Issue(s) that this PR fixes
Fixes #6566

## Discord contact info
Jamie

### CODE REVIEW

File: src/mirage_tower.c [hunk 1]
```diff
@@ -98,6 +98,12 @@ static const struct SpriteSheet sCeilingCrumbleSpriteSheets[] =
     {}
 };
 
+static const struct SpritePalette sCeilingCrumbleSpritePalettes[] =
+{
+    {sMirageTowerCrumbles_Palette,     TAG_CEILING_CRUMBLE},
+    {},
```
Comment (Bassoonian) [inline src/mirage_tower.c]: Is this bit necessary? I'm fine with it if it is, though it may perhaps require a comment? Just thinking out loud

Comment (FosterProgramming) [reply src/mirage_tower.c]: Like, is there a better way to load the palette? I'm not really experience with graphics code, I copied some palette loading code from somewhere else and it worked

Comment (hedara90) [reply src/mirage_tower.c]: You can do a `LoadSpritePaletteWithTag(sMirageTowerCrumbles_Palette, TAG_CEILING_CRUMBLE);`

**Comment by FosterProgramming** [comment]
I updated the way I load the palette and it works fine. Ready for review

**Comment by hedara90** [comment]
Correct me if I'm wrong, but immediately after this animation plays, the player is warped to another map.
So it doesn't matter that the palette is never explicitly freed, it's implicitly freed with the warp.
