### PR TITLE
Fixes Dragon Tail using the effect twice during a Parental Bond attack

### LINKED ISSUE #5600: Dragon Tail behaes incorrectly with Parental Bond
### Description

When Dragon Tail is used by a pokemon with Parental Bond, it's currently switching out the targeted pokemon after the first hit, then it hits the newly sent out opponent with `MOVE_NONE`.
Intended behavior is that Dragon Tail hits twice, then the target is switched out. This is verified on cartridge in Gen 7.

https://github.com/user-attachments/assets/70f2fc84-b914-452f-b99e-b5a2db20a270

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

ad16fa76f20ed2507ca9cc2a3bffcf282e2dbd21

### Discord contact info

hedara

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #5600

### CODE REVIEW

File: test/battle/ability/parental_bond.c [hunk 1]
```diff
@@ -286,6 +286,26 @@ SINGLE_BATTLE_TEST("Parental Bond Snore strikes twice while asleep")
     }
 }
 
+SINGLE_BATTLE_TEST("Parental Bond will block hit switch target effects before the second hit")
```
Comment (AsparagusEduardo) [inline test/battle/ability/parental_bond.c:289]:
```suggestion
SINGLE_BATTLE_TEST("Parental Bond only triggers Dragon Tail's target switch out on the second hit")
```

**Review by AsparagusEduardo — CHANGES_REQUESTED** [review]

File: test/battle/ability/parental_bond.c (hunk 1 above)
Comment (AlexOn1ine) [reply test/battle/ability/parental_bond.c]: You can just commit and merge test name changes

Comment (AsparagusEduardo) [reply test/battle/ability/parental_bond.c]: Is that ok for your PRs? I didn't do it because I wanted the suggestions to go through you first before merging.

Comment (AlexOn1ine) [reply test/battle/ability/parental_bond.c]: If it is just comment changes I don't mind. I'm not good at making descriptions so I'm sure the suggestion is better then anything I came up with

Comment (AlexOn1ine) [reply test/battle/ability/parental_bond.c]: Ye, speaking for myself here, not others :sweat_smile:

**Review by AsparagusEduardo — APPROVED** [review]
