### PR TITLE
Fixes UB in Cmd_averagestats

### LINKED ISSUE #5000: Cmd_averagestats has UB
### Description

https://discord.com/channels/419213663107416084/774393519569502268/1263628135417774081

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #5000

Fix provided by @mrgriffin

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -15669,17 +15669,26 @@ static void Cmd_swapstatstages(void)
...
 
+static u16 *GetBattlerStat(struct BattlePokemon *battler, u32 stat)
+{
+    switch (stat)
+    {
+    case STAT_ATK:   return &battler->attack;
+    case STAT_DEF:   return &battler->defense;
+    case STAT_SPATK: return &battler->spAttack;
+    case STAT_SPDEF: return &battler->spDefense;
+    default: return NULL;
```
Comment (Bassoonian) [inline src/battle_script_commands.c:15680]: Shouldn't this `return` be aligned with the others?

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: fixed

**Review by Bassoonian — APPROVED** [review]
