### PR TITLE
Fixed Battle AI debug screen shiny sprites

### LINKED ISSUE #3920: Battle AI debug screen has shiny sprites
### Description

Front sprites in the AI debug screen are shiny, even if the Pokémon in question is not

### Version

upcoming (Edge)

### Upcoming Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by fdeblasio**
## Description
Switched gBattleMons.isShiny to GetMonData(mon,  MON_DATA_IS_SHINY). There might be a cleaner way to do it, though

## Images
test-1

## Issue(s) that this PR fixes
Fixes #3920

## **Discord contact info**
Frankfurter0

### CODE REVIEW

File: src/battle_debug.c [hunk 1]
```diff
@@ -800,8 +800,15 @@ static void Task_ShowAiPoints(u8 taskId)
                 data->spriteIds.aiIconSpriteIds[i] = 0xFF;
             }
         }
+
+        struct Pokemon *mon;
+        if (GetBattlerSide(data->aiBattlerId) == B_SIDE_PLAYER)
+            mon = &gPlayerParty[gBattlerPartyIndexes[data->aiBattlerId]];
+        else
+            mon = &gEnemyParty[gBattlerPartyIndexes[data->aiBattlerId]];
```
Comment (AlexOn1ine) [inline src/battle_debug.c:808]: I think there is a function / macro to get a side mon.

Comment (fdeblasio) [reply src/battle_debug.c]: You're right! `GetBattlerParty`
