### PR TITLE
Fix AI hold effect considerations

### LINKED ISSUE #6122: IsMonGrounded does not check for magic room correctly
### Description

Updated Code:
```bool32 IsMonGrounded(u16 heldItemEffect, u32 ability, u8 type1, u8 type2)
{
    // List that makes mon not grounded
    if (!(gFieldStatuses & STATUS_FIELD_GRAVITY) && !(heldItemEffect == HOLD_EFFECT_IRON_BALL && !(ability == ABILITY_KLUTZ || gFieldStatuses & STATUS_FIELD_MAGIC_ROOM))
        && (type1 == TYPE_FLYING || type2 == TYPE_FLYING || ability == ABILITY_LEVITATE
        || (heldItemEffect == HOLD_EFFECT_AIR_BALLOON && ability != ABILITY_KLUTZ && !gFieldStatuses & STATUS_FIELD_MAGIC_ROOM)))
        return FALSE;
    else
        return TRUE;
}
```

### Version

1.10.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

SShadowzLmao#3643

### PR DESCRIPTION
**Pull request by Pawkkie**
## Description
This started as adding Magic Room to `IsMonGrounded`, but I did a search for `ABILITY_KLUTZ` and found a bunch of cases where a quick boolean function would shorten up conditionals. This PR addresses that initial mishandling, while also applying the same thorough item checks everywhere it's applicable and introducing `IsBattlerItemEnabled` for use in the future.

## Issue(s) that this PR fixes
Closes #6122 

## **Discord contact info**
@Pawkkie

### CODE REVIEW

File: src/battle_ai_util.c [hunk 1]
```diff
@@ -4141,3 +4131,12 @@ void IncreaseSubstituteMoveScore(u32 battlerAtk, u32 battlerDef, u32 move, s32 *
     if (AI_DATA->hpPercents[battlerAtk] > 70)
         ADJUST_SCORE_PTR(WEAK_EFFECT);
 }
+
+bool32 IsBattlerItemEnabled(u32 battler)
+{
+    if (gFieldStatuses & STATUS_FIELD_MAGIC_ROOM
+        || (gBattleMons[battler].ability == ABILITY_KLUTZ && !(gStatuses3[battler] & STATUS3_GASTRO_ACID) && !(gStatuses3[battler] & STATUS3_EMBARGO)
+        && !(AI_THINKING_STRUCT->aiFlags[battler] & AI_FLAG_NEGATE_UNAWARE)))
```
Comment (AlexOn1ine) [inline src/battle_ai_util.c:4139]: Since you are using a function, could you modify the check so it looks a bit cleaner? E,g, status check could be extracted with an early return.

Comment (Pawkkie) [reply src/battle_ai_util.c]: Done and pushed :)

**Review by AlexOn1ine — APPROVED** [review]
