### PR TITLE
createmon uses enum Pokeball instead of Item

### LINKED ISSUE #9268: Expose BALL_ constants to event_scripts.s for givemon
### Description

Since #5560 `givemon` has changed:
```diff
-givemon SPECIES_PIPLUP, 15, ball=ITEM_CHERISH_BALL
+givemon SPECIES_PIPLUP, 15, ball=BALL_CHERISH
```
But you can't write the latter because the `BALL_x` constants are defined in `include/pokeball.h` which isn't available in scripts. We need to migrate `enum Pokeball` to `include/constants/pokeball.h` (or something like that) and include it in `data/event_scripts.s`.

This wasn't noticed until now because `ITEM_x_BALL == BALL_x` for all balls we currently support, except Strange Ball. If you try to `givemon` with `ITEM_STRANGE_BALL` you get a Poké Ball instead.

[Reported by ttime100](https://discord.com/channels/419213663107416084/1077168246555430962/1473751861205929984).

### Reproduction Steps

```
givemon SPECIES_PIPLUP, 15, ball=ITEM_STRANGE_BALL
```
Notice that Piplup is in a Poké Ball, not a Strange Ball.

### Images / Video

_No response_

### Version

1.14.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by FosterProgramming**
## Issue(s) that this PR fixes
Fixes #9268

## Things to note in the release changelog:
- Balls data in when using createmon and givemon now expect enum Pokeball instead of struct Item
- Running the migration script python3 migration_scripts/1.15/givemon_balls_typechange.py should update your script file automatically. If you have ball items not present in expansion in your project, you may need to edit the item_to_ball array in migration_scripts/1.15/trainer_party_ball_type_change.py to run the script

## Discord contact info
Jamie

### CODE REVIEW

**Comment by FosterProgramming** [comment]
PR updated and added a migration script.
This is the example file to test migration script but please write your own to cover stuff I may have forgotten:
```
givemon SPECIES_WOBBUFFET, 100, item=ITEM_LEFTOVERS, ball=ITEM_MASTER_BALL, nature=NATURE_BOLD, abilityNum=2, gender=MON_MALE, hpEv=1, atkEv=2, defEv=3, speedEv=4, spAtkEv=5, spDefEv=6, hpIv=7, atkIv=8, defIv=9, speedIv=10, spAtkIv=11, spDefIv=12, move1=MOVE_SCRATCH, move2=MOVE_SPLASH, move3=MOVE_CELEBRATE, move4=MOVE_EXPLOSION, shinyMode=SHINY_MODE_ALWAYS, gmaxFactor=TRUE, teraType=TYPE_FIRE, dmaxLevel=7;
createmon 1, 0, SPECIES_WOBBUFFET, 100, ITEM_CHERISH_BALL, ITEM_SAFARI_BALL
createmon 1, 2, SPECIES_WOBBUFFET, 100, move1=MOVE_SCRATCH, move2=MOVE_SPLASH, move3=MOVE_NONE, move4=MOVE_NONE, ball=ITEM_GREAT_BALL;
givemon SPECIES_WOBBUFFET, 100, ITEM_POKE_BALL, ITEM_ULTRA_BALL
```

File: include/constants/pokeball.h [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+    BALL_DREAM = 22,
+    BALL_SAFARI = 23,
+    BALL_SPORT = 24,
+    BALL_PARK = 25,
+    BALL_BEAST = 26,
+    BALL_CHERISH = 27,
+    POKEBALL_COUNT
+};
+
+#endif // GUARD_CONSTANTS_POKEBALL_H
```
Comment (AlexOn1ine) [inline include/constants/pokeball.h]:
```suggestion
#endif // GUARD_CONSTANTS_POKEBALL_H

```
