### PR TITLE
Fix Present heal miss-flag handling and enforce Telepathy blocking

### LINKED ISSUE #9151: Present on a wonder guard or telepathy pokemon where present heals the pokemon won't reset the miss flag
### Description

Present script runs typecalc
https://github.com/rh-hideout/pokeemerald-expansion/blob/63fc5bf0fe47331c1cc8d318bf5b4d818699a581/data/battle_scripts_1.s#L3286-L3290

In typecalc, eventually get down to wonder guard and telepathy check. if those abilities trigger, move result flags are set with MOVE_RESULT_MISSED
https://github.com/rh-hideout/pokeemerald-expansion/blob/63fc5bf0fe47331c1cc8d318bf5b4d818699a581/src/battle_util.c#L8474-L8475
https://github.com/rh-hideout/pokeemerald-expansion/blob/63fc5bf0fe47331c1cc8d318bf5b4d818699a581/src/battle_util.c#L8536-L8548

in presentdamagecalculation, if it turns out to heal, move result flags are cleared. However, only MOVE_RESULT_DOESNT_AFFECT_FOE is cleared (and not MOVE_RESULT_MISSED). so the move will still count as being missed, which will affect the myriad of moveend checks that call IsBattlerUnaffectedByMove (check for MOVE_RESULT_NO_EFFECT)
https://github.com/rh-hideout/pokeemerald-expansion/blob/63fc5bf0fe47331c1cc8d318bf5b4d818699a581/src/battle_script_commands.c#L9165-L9167
https://github.com/rh-hideout/pokeemerald-expansion/blob/63fc5bf0fe47331c1cc8d318bf5b4d818699a581/src/battle_script_commands.c#L9201-L9214

(previously, it would prevent the heal from working, but because of the recent datahpupdate refactor it'll still heal)

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description

- Fixes Present heal outcomes could retain stale miss/no-effect state after Wonder Guard/Telepathy-related typecalc handling.
- [Bulba](https://bulbapedia.bulbagarden.net/wiki/Present_(move)): If Present is used on an ally with Telepathy, Present will always be blocked, even if it would have healed the target.

## Issue(s) that this PR fixes
Fixes #9151

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -12087,6 +12087,7 @@ static void Cmd_presentdamagecalculation(void)
     CMD_ARGS();
 
     u32 rand = RandomUniform(RNG_PRESENT, 0, 0xFF);
+    bool32 blockedByTelepathy = GetBattlerAbility(gBattlerTarget) == ABILITY_TELEPATHY && gBattlerTarget == BATTLE_PARTNER(gBattlerAttacker);
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: I would just move this statement directly into the if else statement. It's short enough.

Comment (Cle-bit) [reply src/battle_script_commands.c]: Ok!

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -12119,13 +12119,17 @@ static void Cmd_presentdamagecalculation(void)
     {
         gBattlescriptCurrInstr = BattleScript_HitFromCritCalc;
     }
+    else if (GetBattlerAbility(gBattlerTarget) == ABILITY_TELEPATHY && gBattlerTarget == BATTLE_PARTNER(gBattlerAttacker))
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]:
```suggestion
    else if (gBattlerTarget == BATTLE_PARTNER(gBattlerAttacker) && GetBattlerAbility(gBattlerTarget) == ABILITY_TELEPATHY)
```
@Cle-bit I took the liberty to make this change. It's a minor optimization since `GetBattlerAbility` is more costly and isn't run when target isn't partner in this case.
