### PR TITLE
Fix field abilities activating when an other mon switches in

### LINKED ISSUE #8740: Weather/Terrain abilities activate upon any switch in
### Description

Whenever any Pokemon switches in, all Pokemon with weather and terrain abilities present on the field activate their abilities.

### Reproduction Steps

Have Pokemon with weather/terrain abilities (such as Drought, Drizzle, Grassy Surge, Psychic Terrain, etc.) present on the field and swap out a Pokemon.

### Images / Video

https://github.com/user-attachments/assets/ef718be2-473f-489f-a314-361f8e39ba7a

https://github.com/user-attachments/assets/2403ea01-6096-47ec-8f9c-6749debd4273

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

linathan

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes  #8740

Regression from  #8128

### CODE REVIEW

**Comment by Bassoonian** [comment]
Shouldn't this be in master?

**Comment by AlexOn1ine** [comment]
> Shouldn't this be in master?

It's not in master yet. Though I need to think about this. Drafting.

**Comment by AlexOn1ine** [comment]
I remember what happened now. In my initial draft I didn't pass the flag `gBattleStruct->battlerState[battler].switchIn` but rather skipped the iteration. 
```C
            while (gBattleStruct->eventState.battlerSwitchIn < FIRST_EVENT_BLOCK_COUNT)
            {
                if (!gBattleStruct->battlerState[battler].switchIn)
                    continue;
                if (FirstEventBlockEvents(&calcValues))
                    return TRUE;
            }
```
I think this is a much better solution but this caused several bugs and I can't remember anymore what it was and I don't want to redo since I might come across the same roadblocks. 

So ready for review!

File: test/battle/ability/quark_drive.c [hunk 1]
```diff
@@ -236,3 +236,23 @@ SINGLE_BATTLE_TEST("Quark Drive doesn't activate for a transformed battler")
...
+        TURN {}
+        TURN {}
+        TURN {}
+        TURN {}
+        TURN {}
+        TURN {}
+        TURN { SWITCH(opponentLeft, 2); }
+    } SCENE {
+    }
+}
```
Comment (AlexOn1ine) [inline test/battle/ability/quark_drive.c]:
```suggestion
```

**Comment by PhallenTree** [comment]
> I think this is a much better solution but this caused several bugs and I can't remember anymore what it was and I don't want to redo since I might come across the same roadblocks.

Probably some abilities that activate when other battlers switch-in as well, like Trace.

**Comment by grintoul1** [comment]
Conflicts

**Comment by AlexOn1ine** [comment]
conflicts resolved!

File: src/battle_util.c
Comment (grintoul1) [inline src/battle_util.c]:
```suggestion
            u32 weather = (GetConfig(CONFIG_SNOW_WARNING) >= GEN_9 ? BATTLE_WEATHER_SNOW : BATTLE_WEATHER_HAIL);
            if (TryChangeBattleWeather(battler, weather, gLastUsedAbility))
            {
                BattleScriptCall(BattleScript_WeatherAbilityActivates);
                effect++;
            }
            else if (gBattleWeather & B_WEATHER_PRIMAL_ANY && HasWeatherEffect())
            {
                BattleScriptCall(BattleScript_BlockedByPrimalWeather);
                effect++;
            }
```

Comment (grintoul1) [reply src/battle_util.c]: Running `TryChangeBattleWeather` twice results in `gBattleWeather = sBattleWeatherInfo[battleWeatherId].flag` being set in the first run, therefore in the second `if (gBattleWeather & sBattleWeatherInfo[battleWeatherId].flag)` passes leading to `return FALSE;` preventing the battle script being called

Comment (grintoul1) [reply src/battle_util.c]: That suggestion has not come through as intended.
Original:
```
        case ABILITY_SNOW_WARNING:
            if (!shouldAbilityTrigger)
                break;
            if (GetConfig(CONFIG_SNOW_WARNING) >= GEN_9 && TryChangeBattleWeather(battler, BATTLE_WEATHER_SNOW, gLastUsedAbility))
            {
                u32 weather = (GetConfig(CONFIG_SNOW_WARNING) >= GEN_9 ? BATTLE_WEATHER_SNOW : BATTLE_WEATHER_HAIL);
                if (TryChangeBattleWeather(battler, weather, gLastUsedAbility))
                {
                    BattleScriptCall(BattleScript_WeatherAbilityActivates);
                    effect++;
                }
                else if (gBattleWeather & B_WEATHER_PRIMAL_ANY && HasWeatherEffect())
                {
                    BattleScriptCall(BattleScript_BlockedByPrimalWeather);
                    effect++;
                }
            }
            break;
```
Changed:
```
        case ABILITY_SNOW_WARNING:
            if (!shouldAbilityTrigger)
                break;
            u32 weather = (GetConfig(CONFIG_SNOW_WARNING) >= GEN_9 ? BATTLE_WEATHER_SNOW : BATTLE_WEATHER_HAIL);
            if (TryChangeBattleWeather(battler, weather, gLastUsedAbility))
            {
                BattleScriptCall(BattleScript_WeatherAbilityActivates);
                effect++;
            }
            else if (gBattleWeather & B_WEATHER_PRIMAL_ANY && HasWeatherEffect())
            {
                BattleScriptCall(BattleScript_BlockedByPrimalWeather);
                effect++;
            }
            break;
```

File: test/battle/ability/quark_drive.c (hunk 1 above)
Comment (grintoul1) [reply test/battle/ability/quark_drive.c]: This test is also still in the changes

File: src/battle_util.c [hunk 2]
```diff
@@ -4617,6 +4623,9 @@ u32 AbilityBattleEffects(enum AbilityEffect caseID, u32 battler, enum Ability ab
             }
             break;
         case ABILITY_SNOW_WARNING:
+            if (!shouldAbilityTrigger)
+                break;
+            if (GetConfig(CONFIG_SNOW_WARNING) >= GEN_9 && TryChangeBattleWeather(battler, BATTLE_WEATHER_SNOW, gLastUsedAbility))
```
Comment (AlexOn1ine) [inline src/battle_util.c]:
```suggestion
```

File: test/battle/ability/quark_drive.c (hunk 1 above)
Comment (AlexOn1ine) [inline test/battle/ability/quark_drive.c]:
```suggestion
```
