### PR TITLE
Fix Commander cleanup after Volt Switch switch-in

### LINKED ISSUE #9137: Tatsugiri Commander Invincibility Bug
### Description

If Tatsugiri is inside of Dondozo because of Commander, then Dondozo is killed via Volt Switch, Tatsugiri emerges but appears to still be invincible and in its commander state (it cannot attack or be hit with an attack). KOing a future Pokemon (like the Seadra that comes in next) will reset Tatsugiri to be able to be hit again. 

A video is provided showcasing the issue.

### Reproduction Steps

Knock out a Dondozo with a commander Tatsugiri using Volt Switch

### Images / Video

https://youtu.be/TbEpuSbNsFw

### Version

1.14.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

FranklyNathan

### PR DESCRIPTION
**Pull request by Cle-bit**
## Issue(s) that this PR fixes
Fixes #9137

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -7389,6 +7389,15 @@ static void Cmd_switchindataupdate(void)
...
 
+    if (gBattleStruct->battlerState[battler].commanderSpecies != SPECIES_NONE)
+    {
+        u32 partner = BATTLE_PARTNER(battler);
+        gBattleStruct->battlerState[battler].commanderSpecies = SPECIES_NONE;
+        gBattleStruct->battlerState[partner].commandingDondozo = FALSE;
+        if (IsBattlerAlive(partner))
+            gBattleMons[partner].volatiles.semiInvulnerable = STATE_NONE;
+    }
+
```
Comment (PhallenTree) [inline src/battle_script_commands.c]: This should probably be handled in `FaintClearSetData` if possible, otherwise Tatsugiri is still invulnerable on the same turn that Volt Switch was used

**Comment by PhallenTree** [comment]
```
FAILED tests:
  - test/battle/ability/commander.c:395: Matched HP_BAR - Commander Tatsugiri does not get hit by Dragon Darts when a commanded Dondozo faints.
  - test/battle/ability/commander.c:376: Matched MESSAGE - Commander Tatsugiri does not attack if Dondozo faints the same turn it's switched in.
  - test/battle/ai/ai_switching.c:1731: Expected 1.0 passes/successes, observed 0.0 - AI will not choose to switch out Dondozo with Commander Tatsugiri (50/50).
```
For the first test, not clearing `gBattleStruct->battlerState[partner].commandingDondozo` and checking it wherever Dragon Darts switches targets would fix the test, but also it shouldn't fail in upcoming thanks to #8696.
For the second test, not clearing `gBattleStruct->battlerState[partner].commandingDondozo` would fix it (it gets automatically cleared at the end of the turn).
I'm not experienced enough with AI code to help solve the third one, but I'd recommend watching the test to see if the behavior is correct.

**Comment by Cle-bit** [comment]
Thank you, PhallenTree. I am trying to fix it :D

**Comment by Cle-bit** [comment]
`Commander Tatsugiri does not get hit by Dragon Darts when a commanded Dondozo faints` passed on upcoming, but AI testing still failed.
image

**Comment by Cle-bit** [comment]
GIF 2026-2-7 0-36-20
To be honest, I didn't see the problem (please correct me if I'm wrong)

**Comment by PhallenTree** [comment]
I'm not sure what's wrong, but if you remove the line `PASSES_RANDOMLY(100, 100);`, it should give you an idea why the test is failing.

**Comment by Cle-bit** [comment]
image
I found the problem.
Finally... the test has passed.

**Comment by Cle-bit** [comment]
I'm not sure if `Commander Tatsugiri does not get hit by Dragon Darts when a commanded Dondozo faints.`needs to be fixed? Still marked as `KNOWN_FAILING;`. Because it passed on upcoming due to #8696 .

**Comment by PhallenTree** [comment]
It's fine, since in upcoming it will pass.
