### PR TITLE
Fix some move animations leaking VRAM and freeing already freed tags

### LINKED ISSUE #6537: Prismatic Laser and Poltergeist sprite tile memory leak
### Description

Prismatic Laser loads 9 spritesheet: https://github.com/rh-hideout/pokeemerald-expansion/blob/master/data/battle_anim_scripts.s#L11855-L11864
But there are only 8 total slots for spritesheet tags to free at the end: https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/battle_anim.c#L32
Solution: increase the count to 9

Poltergeist creates an item sprite: https://github.com/rh-hideout/pokeemerald-expansion/blob/master/data/battle_anim_scripts.s#L14639

Which needs to be explicitly freed with `unloadspritegfx ANIM_TAG_ITEM_BAG` (like with Covet)

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

luckytyphlosion

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Fixes some move animations not freeing everything they allocate.
Fixes some Z-Move animations using `unloadsppritegfx` to free tags that are not loaded at that point.
Adds a new check to the move animation tests to count allocations and frees in move animations to make sure they match.

## Issue(s) that this PR fixes

Fixes #6537 

## Discord contact info

hedara

### CODE REVIEW

File: src/sprite.c [hunk 1]
```diff
@@ -28,6 +28,8 @@
 
 #if T_SHOULD_RUN_MOVE_ANIM
 EWRAM_DATA bool32 gLoadFail = FALSE;
+EWRAM_DATA bool32 gCountAllocs = FALSE;
```
Comment (AlexOn1ine) [inline src/sprite.c:31]: Any reason not to use `bool8`?

Comment (hedara90) [reply src/sprite.c:31]: This code is only present in tests, so I went for a miniscule performace upgrade at the cost of a miniscule EWRAM increase.

**Comment by hedara90** [comment]
Conflicts resolved.
