### PR TITLE
Magic Bounce / Magic Coat/ Snatch refactor

### LINKED ISSUE #9500: Magic Bounce / Magic Coat against targets opposing field moves
### Description

On moves that target the opposing field only the fastest magic coat / magic bounce will activate. 

### Reproduction Steps

.

### Images / Video

_No response_

### Version

1.15.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
## Description
Slight Magic Coat / Magic Bounce refactor / bugfix. Uses ~~canceler~~moveend now since the previous implementation didn't handle 2 opposing Magic Bounce/Coat users

Fixes #9500

### CODE REVIEW

File: test/battle/move_effect/parting_shot.c [hunk 1]
```diff
@@ -69,37 +69,37 @@ SINGLE_BATTLE_TEST("Parting Shot: Hyper Cutter blocks Attack drop but still swit
...
-        OPPONENT(SPECIES_WYNAUT);
-    } WHEN {
-        TURN { MOVE(opponent, MOVE_MAGIC_COAT); MOVE(player, MOVE_PARTING_SHOT); SEND_OUT(opponent, 1); }
-    } THEN {
-        EXPECT_EQ(player->statStages[STAT_ATK], DEFAULT_STAT_STAGE - 1);
-        EXPECT_EQ(player->statStages[STAT_SPATK], DEFAULT_STAT_STAGE - 1);
-        EXPECT_EQ(opponent->species, SPECIES_WYNAUT);
-    }
-}
+// SINGLE_BATTLE_TEST("Parting Shot: Magic Coat bounces it and switches the target out")
```
Comment (AlexOn1ine) [inline test/battle/move_effect/parting_shot.c:72]: Those have been commented out. They will be fixed in the stat change refactor.

File: src/battle_move_resolution.c [hunk 2]
```diff
@@ -1900,6 +1904,45 @@ static enum CancelerResult CancelerNotFullyProtected(struct BattleCalcValues *cv
     return CANCELER_RESULT_SUCCESS;
 }
 
+static enum CancelerResult CancelerBouncedMove(struct BattleCalcValues *cv)
+{
+    if (gBattleStruct->bouncedMoveIsUsed)
+        return CANCELER_RESULT_SUCCESS;
+
+    u32 foundBouncer = FALSE;
+    for (enum BattlerId battler = 0; battler < gBattlersCount; battler++)
```
Comment (grintoul1) [inline src/battle_move_resolution.c]:
```suggestion
    for (enum BattlerId battler = B_BATTLER_0; battler < gBattlersCount; battler++)
```

File: src/battle_move_resolution.c [hunk 3]
```diff
@@ -1900,6 +1904,45 @@ static enum CancelerResult CancelerNotFullyProtected(struct BattleCalcValues *cv
     return CANCELER_RESULT_SUCCESS;
 }
 
+static enum CancelerResult CancelerBouncedMove(struct BattleCalcValues *cv)
+{
+    if (gBattleStruct->bouncedMoveIsUsed)
+        return CANCELER_RESULT_SUCCESS;
+
+    u32 foundBouncer = FALSE;
```
Comment (grintoul1) [inline src/battle_move_resolution.c]: Apologies may be knowledge gap on my part - is there a reason/benefit for not using a bool? or does it make zero difference

File: src/battle_move_resolution.c [hunk 4]
```diff
@@ -1900,6 +1904,45 @@ static enum CancelerResult CancelerNotFullyProtected(struct BattleCalcValues *cv
...
+            BattleScriptCall(BattleScript_MagicCoat);
+        }
+
+        if (foundBouncer)
+        {
+            gBattleStruct->targetBeforeBounce = gBattlerTarget;
+            gBattleStruct->battlerState[gBattlerAttacker].targetsDone[gBattlerTarget] = TRUE;
+            gBattleStruct->moveResultFlags[gBattlerTarget] |= MOVE_RESULT_DOESNT_AFFECT_FOE; // for moves that target the opposing field
+            gBattlerTarget = battler;
+            for (enum BattlerId i = 0; i < gBattlersCount; i++)
```
Comment (grintoul1) [inline src/battle_move_resolution.c]:
```suggestion
            for (enum BattlerId i = B_BATTLER_0; i < gBattlersCount; i++)
```

File: src/battle_move_resolution.c [hunk 5]
```diff
@@ -2751,28 +2795,23 @@ static enum MoveEndResult MoveEndNextTarget(void)
...
-            }
-        }
+    }
+
+    // Not sure if this is the correct placement
+    // Maybe tested agaist something like Eject Pack in doubles while there is a possible foe left
+    // E.g. Leer into Magic Bounce and valid target. When does Eject Pack activate?
+    if (gBattleStruct->bouncedMoveIsUsed)
+    {
+        for (enum BattlerId battler = 0; battler < gBattlersCount; battler++)
```
Comment (grintoul1) [inline src/battle_move_resolution.c]:
```suggestion
        for (enum BattlerId battler = B_BATTLER_0; battler < gBattlersCount; battler++)
```

File: src/battle_script_commands.c [hunk 6]
```diff
@@ -12813,14 +12794,23 @@ void BS_JumpIfBlockedBySoundproof(void)
...
+
     gBattleStruct->attackerBeforeBounce = gBattleScripting.battler = gBattlerAttacker;
     gBattlerAttacker = gBattlerTarget;
     gBattlerTarget = gBattleStruct->attackerBeforeBounce;
     ClearDamageCalcResults();
     gBattleStruct->eventState.atkCanceler = CANCELER_SET_TARGETS;
     gBattleStruct->eventState.atkCancelerBattler = 0;
 
-    gBattlescriptCurrInstr = cmd->nextInstr;
+    for (enum BattlerId i = 0; i < gBattlersCount; i++)
```
Comment (grintoul1) [inline src/battle_script_commands.c]:
```suggestion
    for (enum BattlerId i = B_BATTLER_0; i < gBattlersCount; i++)
```

File: test/battle/ability/magic_bounce.c [hunk 7]
```diff
@@ -124,6 +124,36 @@ DOUBLE_BATTLE_TEST("Magic Bounce bounces back moves hitting both foes at two foe
...
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_LEER, playerLeft);
+        MESSAGE("Abra's Leer was bounced back by the opposing Espeon's Magic Bounce!");
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_LEER, opponentLeft);
+        NOT MESSAGE("The opposing Espeon's Defense fell!");
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerLeft);
+        MESSAGE("Abra's Defense fell!");
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerRight);
+        MESSAGE("Kadabra's Defense fell!");
+
+        NOT MESSAGE("The opposing Natu's Defense fell!");
```
Comment (grintoul1) [inline test/battle/ability/magic_bounce.c]: Channeling my inner Hedara: is it possible to replace the `NOT MESSAGE` with `NOT ANIMATION` or similar?

File: src/battle_move_resolution.c [hunk 8]
```diff
@@ -1900,6 +1904,45 @@ static enum CancelerResult CancelerNotFullyProtected(struct BattleCalcValues *cv
...
+        }
+        else if (gSpecialStatuses[battler].magicCoatPending)
+        {
+            foundBouncer = TRUE;
+            gEffectBattler = battler;
+            gSpecialStatuses[battler].magicCoatPending = FALSE;
+            BattleScriptCall(BattleScript_MagicCoat);
+        }
+
+        if (foundBouncer)
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]:
```suggestion
        }
        else
        {
            continue;
        }
```
No need for the `foundBouncer` variable

File: src/battle_move_resolution.c [hunk 9]
```diff
@@ -1900,6 +1904,45 @@ static enum CancelerResult CancelerNotFullyProtected(struct BattleCalcValues *cv
     return CANCELER_RESULT_SUCCESS;
 }
 
+static enum CancelerResult CancelerBouncedMove(struct BattleCalcValues *cv)
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Technically I think the correct timing for this is after MoveEndNextTarget, since from Lin's testing, it first does the non-bounced move on all affected targets, then the battlers protected by Magic Coat/Magic Bounce bounce the move back, though this is a decent point to have `TARGET_OPPONENTS_FIELD` moves being bounced, since only 1 bounce activates.

https://discord.com/channels/419213663107416084/1368163973366681712/1420595325692805202

File: src/battle_move_resolution.c [hunk 10]
```diff
@@ -2751,28 +2795,23 @@ static enum MoveEndResult MoveEndNextTarget(void)
...
-                BattleScriptPush(GetMoveBattleScript(gCurrentMove));
-                gBattlescriptCurrInstr = BattleScript_FlushMessageBox;
-                return MOVEEND_RESULT_BREAK;
-            }
-        }
+    }
+
+    // Not sure if this is the correct placement
+    // Maybe tested agaist something like Eject Pack in doubles while there is a possible foe left
+    // E.g. Leer into Magic Bounce and valid target. When does Eject Pack activate?
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: Valid targets are affected by move -> Magic Bounce/Coat bounces the move for every target that could bounce the move -> Eject Pack activates
https://discord.com/channels/419213663107416084/1368163973366681712/1470954229391691960

File: src/battle_move_resolution.c (hunk 3 above)
Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: It should be a bool32 but functionally it makes no difference since both u32 and bool32 are a 32 bit unsigned integer. It's just for humans. (or maybe bool32 is a signed int? Idk)

File: test/battle/ability/magic_bounce.c (hunk 7 above)
Comment (AlexOn1ine) [reply test/battle/ability/magic_bounce.c]: should I just leave the animation checks?

Comment (grintoul1) [reply test/battle/ability/magic_bounce.c]: Could do, or a "not animation" for whichever position the Natu is having it's stat changed

**Comment by grintoul1** [comment]
@PhallenTree my comments are pretty much just style stuff. As you're far more experienced in this area are you happy for me to step back and let you be the approver from a technical perspective please?

**Comment by PhallenTree** [comment]
> @PhallenTree my comments are pretty much just style stuff. As you're far more experienced in this area are you happy for me to step back and let you be the approver from a technical perspective please?

Yea I will fully review this from now.

File: test/battle/ability/magic_bounce.c (hunk 7 above)
Comment (PhallenTree) [reply test/battle/ability/magic_bounce.c]: There's still a few of these using messages (like the Espeon one on the first line)

File: src/battle_script_commands.c (hunk 6 above)
Comment (PhallenTree) [reply src/battle_script_commands.c]: This wasn't changed

File: test/battle/ability/magic_bounce.c (hunk 7 above)
Comment (AlexOn1ine) [reply test/battle/ability/magic_bounce.c]: I think the Espeon one was the only one left.

**Comment by AlexOn1ine** [comment]
ready for re-review. also removed the now redundant callnative.

~~Also removed the stored battler variables. I think swapping should be fine at the end. /Edit: Actually it might not be fine :thinking:  The target can change. I'll revert that. /edit2: haven't pushed yet anyways~~

**Comment by AlexOn1ine** [comment]
Ended up using `saveattacker` and `savetarget` which actually revealed a possible bug with 2 opposing magic coat/bounce.

**Comment by AlexOn1ine** [comment]
ready for re-review.

File: src/battle_move_resolution.c [hunk 11]
```diff
@@ -2751,31 +2814,97 @@ static enum MoveEndResult MoveEndNextTarget(void)
...
+    if (gBattleStruct->bouncedMoveIsUsed)
+    {
+        RestoreAttacker();
+        RestoreTarget();
+        gBattleStruct->bouncedMoveIsUsed = FALSE;
+    }
+
+    if (gBattleStruct->magicBouncePending || gBattleStruct->magicCoatPending)
+    {
+        u8 battlersByRawSpeed[MAX_BATTLERS_COUNT] = {0,1,2,3};
```
Comment (PhallenTree) [inline src/battle_move_resolution.c]: I'd keep this as just `battlers` since it only orders whenever it's a hazard setting move

File: src/battle_script_commands.c [hunk 12]
```diff
@@ -11743,7 +11721,7 @@ void BS_SaveTarget(void)
 void BS_RestoreTarget(void)
```
Comment (PhallenTree) [inline src/battle_script_commands.c:11721]: Should use `RestoreTarget` function. Same thing in `BS_RestoreAttacker`

File: test/battle/move_effect/magic_coat.c [hunk 13]
```diff
@@ -98,6 +98,48 @@ DOUBLE_BATTLE_TEST("Magic Coat reflects hazards regardless of the user's positio
     }
 }
 
+DOUBLE_BATTLE_TEST("Magic Coat activates on the fastest opposing mon (raw speed)")
```
Comment (PhallenTree) [inline test/battle/move_effect/magic_coat.c]:
```suggestion
DOUBLE_BATTLE_TEST("Magic Coat activates on the fastest opposing mon for hazard setting moves (raw speed)")
```
