### PR TITLE
Fix incorrect player berry animation on opponent’s low-HP heal at battle start

### LINKED ISSUE #8898: Animation error when starting a battle with a low hp opponent that has a healing berry
### Description

Low priority since it can't really appear in normal gameplay, but if you start a test where the opponent has low hp and uses a healing berry, a player berry consumption animation will play incorrectly before the correct opponent animation plays.  It seems to be due to gBattlerAttacker not being set right away so when the itemremove script runs, it runs against the default battler 0, incorrectly removing from the player, before the berry's following low hp check makes it try again on the opponent.

### Reproduction Steps

```c
SINGLE_BATTLE_TEST("TESTItems can restore a battler's HP by a fixed amount (singles, player)")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET) { HP(1); MaxHP(400); Item(ITEM_ORAN_BERRY); }
    } WHEN {
        TURN {  }
    } SCENE {
        NONE_OF
        {
            ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, player);
        }
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, opponent);
    }
}
```

### Images / Video

_No response_

### Version

1.14.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

bassforte

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description

> Due to gBattlerAttacker not being set right away so when the itemremove script runs, it runs against the default battler 0.

## Issue(s) that this PR fixes
Fixes #8898

### CODE REVIEW

**Comment by grintoul1** [comment]
That's a strange test to have not passed!

**Comment by Cle-bit** [comment]
Let me take a look (this test was written by me..)

File: src/battle_main.c [hunk 1]
```diff
@@ -3890,6 +3890,7 @@ static void TryDoEventsBeforeFirstTurn(void)
         while (gBattleStruct->switchInBattlerCounter < gBattlersCount) // From fastest to slowest
         {
             u32 battler = gBattlerByTurnOrder[gBattleStruct->switchInBattlerCounter++];
+            gBattlerAttacker = battler;
```
Comment (AlexOn1ine) [inline src/battle_main.c:3893]: What does the additional assignment of `gBattlerAttacker` do here? Since the function `ItemBattleEffects` sets battler to scripting battler and `BattleScript_ItemHealHP_RemoveItem` uses only that.

Comment (AlexOn1ine) [reply src/battle_main.c:3893]: If a mon switches in due to eject button in the middle of move execution and has a berry, this assignment overwrites the current attacker so it should be avoided. 

In general unless it is the end of the turn mutations of `gBattlerAttacker` and `gBattlerTarget` are very bad. In cases we can't avoid it we use `save` and `restore` functions/macros for  attacker/target

Comment (Cle-bit) [reply src/battle_main.c:3893]: I see, this is a bit tricky

Comment (AlexOn1ine) [reply src/battle_main.c:3893]: do you know where the core issue is coming from?

Comment (Cle-bit) [reply src/battle_main.c:3893]: `BattleScript_ItemHealHP_RemoveItemEnd2` uses `BS_ATTACKER` while `ItemBattleEffects` only sets `gBattleScripting.battler`?

Comment (AlexOn1ine) [reply src/battle_main.c:3893]: Wait a minute. That's fine here. It's only the first turn anyways. Sorry, I should have looked more into the place you did it.

**Comment by AlexOn1ine** [comment]
@grintoul1 this should be merge ready

**Review by grintoul1 — APPROVED** [review]
