### PR TITLE
Last Respects effect + Fixed Supreme Overlord

### LINKED ISSUE #3035: Supreme Overlord's effect is wrong
Its current implementation has an "initial x1.2 boost", but according to [Anubis](https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/page-20#post-9421520), Supreme Overlord only gets an additional x0.1 boost per fainted battler.

EDIT: Additionally, it's supposed to use a faint counter that's independent from this ability, and it's also used by Last Respects

### PR DESCRIPTION
**Pull request by AsparagusEduardo**
## Description
Replaces #3037

Original description:
> SV introduced a variable for each side to count the amount of fainted Pokémon on that side. It caps at 100, and both Last Respects and Supreme Overlord use it.
However, but Supreme Overlord's effect caps at 5 and it's kept the same based on the value that the side counter was when the battler entered battle, meaning that a partner fainting while the ability's holder is also in won't affect its multiplier.

## Issue(s) that this PR fixes
Fixes #3035

## Feature(s) this PR does NOT handle:
Automatic test for checking the Last Respects' 100-time cap. The test runner doesn't support that many turns.

## **Discord contact info**
AsparagusEduardo

### CODE REVIEW

**Comment by AsparagusEduardo** [comment]
Converted to draft because I'm now realizing that it's meant to be based on currently fainted party members, not how many faints happened in the battle.

**Comment by AsparagusEduardo** [comment]
Converted to draft because I'm now realizing that Supreme Overlord it's meant to be based on currently fainted party members, not how many faints happened in the battle.

File: src/battle_util.c [hunk 1]
```diff
@@ -3958,23 +3958,14 @@ bool32 ChangeTypeBasedOnTerrain(u32 battler)
...
-    for (i = 0; i < PARTY_SIZE; i++)
-    {
-        if (GetMonData(&party[i], MON_DATA_SPECIES) != SPECIES_NONE
-         && !GetMonData(&party[i], MON_DATA_IS_EGG)
-         && GetMonData(&party[i], MON_DATA_HP) == 0)
-            modifier += (!appliedFirstBoost) ? UQ_4_12(0.2) : UQ_4_12(0.1);
-        appliedFirstBoost = TRUE;
-    }
+    for (i = 0; i < gBattleStruct->supremeOverlordCounter[battler]; i++)
+        modifier += UQ_4_12(0.1);
```
Comment (Skeli789) [inline src/battle_util.c:3968]: Would `modifier += UQ_4_12(0.1) * gBattleStruct->supremeOverlordCounter[battler]` not work?

File: src/battle_util.c [hunk 2]
```diff
@@ -8673,6 +8668,12 @@ static inline u32 CalcMoveBasePower(u32 move, u32 battlerAtk, u32 battlerDef, u3
         if (RandomPercentage(RNG_FICKLE_BEAM, 30))
             basePower *= 2;
         break;
+    case EFFECT_LAST_RESPECTS:
+        if (GetBattlerSide(battlerAtk) == B_SIDE_PLAYER)
+            basePower += (basePower * min(100, gBattleResults.playerFaintCounter));
+        else
+            basePower += (basePower * min(100, gBattleResults.opponentFaintCounter));
+        break;
```
Comment (Skeli789) [inline src/battle_util.c:8676]: To remove duplicate code, you can do something like:
```
u8 faintCounter = min(100, (GetBattlerSide(battlerAtk) == B_SIDE_PLAYER) ? gBattleResults.playerFaintCounter : gBattleResults.opponentFaintCounter)
basePower += basePower * faintCounter
```
```

**Review by Skeli789 — CHANGES_REQUESTED** [review]

File: src/battle_util.c (hunk 2 above)
Comment (AsparagusEduardo) [reply src/battle_util.c:8684]: Or maybe an inline function to get a side's faint counter 🤔

File: src/battle_util.c (hunk 1 above)
Comment (AsparagusEduardo) [reply src/battle_util.c:3968]: Yes, that's better. Will add it.

**Comment by AsparagusEduardo** [comment]
Ready for review

File: src/battle_util.c [hunk 3]
```diff
@@ -4611,12 +4605,24 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
...
-            if (!gSpecialStatuses[battler].switchInAbilityDone && CountUsablePartyMons(battler) < PARTY_SIZE)
+            if (!gSpecialStatuses[battler].switchInAbilityDone)
             {
+                struct Pokemon* party = GetBattlerParty(battler);
                 gSpecialStatuses[battler].switchInAbilityDone = TRUE;
-                gBattleStruct->supremeOverlordModifier[battler] = GetSupremeOverlordModifier(battler);
-                BattleScriptPushCursorAndCallback(BattleScript_SupremeOverlordActivates);
-                effect++;
+                j = 0;
+                for (i = 0; i < PARTY_SIZE; i++)
```
Comment (Skeli789) [inline src/battle_util.c:4613]: Why was this added? The pre-existing faint counter should be used.

**Review by Skeli789 — CHANGES_REQUESTED** [review]

File: src/battle_util.c (hunk 3 above)
Comment (AsparagusEduardo) [reply src/battle_util.c:4613]: It had been so long since I did research that I forgot that I assumed stuff based on Bulbapedia's description. It should've used the same counter as Last Respects.
https://www.smogon.com/forums/threads/scarlet-violet-battle-mechanics-research.3709545/post-9421520
Will fix it.

**Comment by AsparagusEduardo** [comment]
Finally, finally should be done.

File: src/battle_main.c [hunk 4]
```diff
@@ -3316,7 +3317,7 @@ const u8* FaintClearSetData(u32 battler)
 
     for (i = 0; i < gBattlersCount; i++)
     {
-        if (i != battler && GetBattlerSide(i) != GetBattlerSide(battler))
```
Comment (AlexOn1ine) [inline src/battle_main.c:3319]: Minor nitpick but maybe revert this change? I feel like having the function call makes it more clear what is happening and it isn't used anywhere else.

File: src/battle_main.c [hunk 5]
```diff
@@ -3316,7 +3317,7 @@ const u8* FaintClearSetData(u32 battler)
...
+        if (i != battler && GetBattlerSide(i) != battlerSide)
```
Comment (AlexOn1ine) [inline src/battle_main.c:3320]: Minor nitpick but maybe revert this change? I feel like having the function call makes it more clear what is happening and it isn't used anywhere else.

**Review by AlexOn1ine — APPROVED** [review]
