### PR TITLE
Fixes crash damage move against absorbing abilities

### LINKED ISSUE #5477: Supercell Slam not crashing on immunitiy abilities
### Description

According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Supercell_Slam_(move)) Supercell Slam should deal 50% Crash damage if the target has Volt Absorb or similar abilities. In my testings this did not happen though, Supercell Slam got absorbed without dealing any crash damage. 

### Version

1.9.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes https://github.com/rh-hideout/pokeemerald-expansion/issues/5477

### CODE REVIEW

**Comment by TerraPrograms** [comment]
I believe High Jump Kick vs Mimikyu with an active disguise is still broken and wouldn't cause recoil, at least according to my testing, could you double check that?

**Comment by hedara90** [comment]
Testing shows that using HJK (with scrappy) into Mimikyu breaks the disguise and doesn't deal crash damage.
But without Scrappy crash damage doesn't happen, while vs. a Gastly (without Disguise) it does suffer crash damage, so something is wrong.

**Comment by AlexOn1ine** [comment]
Should be fixed

**Comment by TerraPrograms** [comment]
Yeah looks good now.

File: test/battle/move_effect/recoil_if_miss.c [hunk 1]
```diff
@@ -98,3 +98,60 @@ SINGLE_BATTLE_TEST("Jump Kick's recoil happens after Spiky Shield damage and Pok
...
+        TURN { MOVE(player, MOVE_SUPERCELL_SLAM); }
+    } SCENE {
+        s32 maxHP = GetMonData(&PLAYER_PARTY[0], MON_DATA_MAX_HP);
+        ABILITY_POPUP(opponent, ABILITY_LIGHTNING_ROD);
+        MESSAGE("Wobbuffet kept going and crashed!");
+        HP_BAR(player, damage: maxHP / 2);
+    }
+}
+
+SINGLE_BATTLE_TEST("Recoil if miss: Jump Kick has 50% recoil if target is disguised")
```
Comment (hedara90) [inline test/battle/move_effect/recoil_if_miss.c:135]: Test title does not really describe what's tested.
But I can't come up with something better than "Disguise + HJK isn't borked".

Comment (AlexOn1ine) [reply test/battle/move_effect/recoil_if_miss.c:135]:
```
Jump Kick into a disguised target will fail and cause 50% of crash damage
```
?

Comment (hedara90) [reply test/battle/move_effect/recoil_if_miss.c:135]: That's not what happens though, there's not crash damage vs Disguise right now in expansion (I don't know what's supposed to happen)

Comment (AlexOn1ine) [reply test/battle/move_effect/recoil_if_miss.c:135]: It wasn't broken. I just introduced a regression by fixing a different issue.

Comment (AlexOn1ine) [reply test/battle/move_effect/recoil_if_miss.c:135]: The actual issue that is being fixed is crash damage into an immunity ability

Comment (hedara90) [reply test/battle/move_effect/recoil_if_miss.c:135]: Hitting HJK into Disguise does not cause crash damage (with Scrappy).

Comment (AlexOn1ine) [inline test/battle/move_effect/recoil_if_miss.c:135]:
```suggestion
SINGLE_BATTLE_TEST("Recoil if miss: Disguise doesn't prevent crash damage from Jump Kick into ghost types")
```

**Review by hedara90 — APPROVED** [review]
