### PR TITLE
Fix ASSUMPTIONS not working

### LINKED ISSUE #3043: Automatic Test ASSUMPTIONS block is not working
Swords Dance's effect is `EFFECT_ATTACK_UP_2`, but by accident I put `EFFECT_ATTACK_UP` in the assumption block and the test passed anyway.
imagen

Moving the assumption to inside of the `GIVEN` block correctly failed the assumption.
imagen

### PR DESCRIPTION
**Pull request by DizzyEggg**
Fixes #3043

Example output when `ASSUME` fails in `ASSUMPTION` block:

```
[0] Multi hit Moves hit the maximum amount with Skill Link: ASSUMPTION_FAIL
test/battle/move_effect/multi_hit.c:6: ASSUME failed
[0] Multi hit Moves hit twice 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit thrice 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit four times 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit four times 35 Percent of the time: ASSUMPTION_FAIL
[0] Multi hit Moves hit at least four times with Loaded Dice: ASSUMPTION_FAIL
[0] Multi hit Moves hit five times 50 Percent of the time with Loaded Dice: ASSUMPTION_FAIL
- Tests PASSED:        0
- ASSUMPTIONS_FAILED:  7
- Tests TOTAL:         7
```

### CODE REVIEW

File: test/test_runner.c [hunk 1]
```diff
@@ -88,7 +88,7 @@ static u32 AssignCostToRunner(void)
     u32 minCostProcess;
 
     if (gTestRunnerState.test->runner == &gAssumptionsRunner)
-        return TRUE;
+        return 0;
```
Comment (mrgriffin) [inline test/test_runner.c:91]: Ah, I think I see what I messed up—this code looks like it was expecting to return `TRUE` if the test should run on this runner, and `FALSE` if not; but somewhere along the way it changed to returning the process to run on instead.

The reason why you'd want to run the assumptions on every runner is that the tests which are covered by the assumptions run on an arbitrary set of runners. So I wonder if this should say `return gTestRunnerI;` so that the test runs on all the runners (at zero cost, because we've skipped `estimateCost` on line 98, which is also important for keeping all the `processCosts` in sync).

I think atm if we have no tests except:
- an `ASSUMPTIONS` block which fails
- two tests that rely on that block

Then if we `make check -j2` the second test will run even though it shouldn't because `ASSUMPTIONS` and the first test will run on runner 0, and just the second test will run on runner 1 (`skipFilename` never gets set, because the `ASSUMPTIONS` doesn't run on that runner).

Comment (DizzyEggg) [reply test/test_runner.c:91]: By atm you mean with or without this PR's changes?

Comment (mrgriffin) [reply test/test_runner.c:91]: With these changes. (It would be similar without, but swapping runners 0 and 1 because `return TRUE;` is really `return 1;`)

Comment (DizzyEggg) [reply test/test_runner.c:91]: I see. Now how to fix it : D

Comment (mrgriffin) [reply test/test_runner.c:91]: You'd have to double-check (or I can do it later when I'm home from work), but I think just replacing `return 0;` with `return gTestRunnerI;` ought to do it :crossed_fingers:

**Comment by AsparagusEduardo** [comment]
I applied the changes to current master and then changed:
```diff
ASSUMPTIONS
{
-   ASSUME(gBattleMoves[MOVE_BULLET_SEED].effect == EFFECT_MULTI_HIT);
+   ASSUME(gBattleMoves[MOVE_BULLET_SEED].effect == EFFECT_ABSORB);
}
```

image

File: test/test_runner.c (hunk 1 above)
Comment (AsparagusEduardo) [reply test/test_runner.c:91]: Looks like that worked (except with an extra `ASSUME failed`)

image

Comment (AsparagusEduardo) [reply test/test_runner.c:91]: Do we care about fixing this extra `ASSUME failed`?

**Review by AsparagusEduardo — APPROVED** [review]
Let's add the repeated assumption as a minor issue.
