### PR TITLE
Fix Iron Ball type effectiveness check

### LINKED ISSUE #6727: Iron Ball Resistances
### Description

Since Generation 5, Flying-Types take 1x damage from Ground Attacks regardless of their secondary typing. Source: Bulbapedia.

Currently it will look at its secondary typing and for example Corviknight with Iron Ball would be Weak to Earthquake when it shouldn't.

### Version

1.11.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by spindrift64**
fixed Iron Ball's type effectiveness mechanics

## Description
Added a unique type effectiveness check for Iron Ball to take into account the changes made in gen 5 forward.
Added a flag to toggle the gen 5 mechanics update of Iron Ball.
Added a test for Iron Ball's type effectiveness check.

## Issue(s) that this PR fixes
Fixes #6727

## **Discord contact info**
spindrift64

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -8844,7 +8844,7 @@ static bool32 IsBattlerGroundedInverseCheck(u32 battler, bool32 considerInverse)
 
 bool32 IsBattlerGrounded(u32 battler)
 {
-    return IsBattlerGroundedInverseCheck(battler, FALSE);
+    return IsBattlerGroundedInverseCheck(battler, FALSE, FALSE);
```
Comment (AlexOn1ine) [inline src/battle_util.c:8847]: can you please add enums + enum type checking for both false arguments? It hard to read code otherwise

File: src/battle_util.c [hunk 2]
```diff
@@ -8816,12 +8816,22 @@ bool32 IsBattlerProtected(u32 battlerAtk, u32 battlerDef, u32 move)
     return isProtected;
 }
 
-// Only called directly when calculating damage type effectiveness
-static bool32 IsBattlerGroundedInverseCheck(u32 battler, bool32 considerInverse)
+enum InverseBattleCheck {
+    CONSIDER_INVERSE_BATTLE,
+    NOT_INVERSE_BATTLE
+};
```
Comment (AlexOn1ine) [inline src/battle_util.c:8822]:
```suggestion
enum InverseBattleCheck 
{
    INVERSE_BATTLE,
    NOT_INVERSE_BATTLE
};
```

File: src/battle_util.c [hunk 3]
```diff
@@ -8816,12 +8816,22 @@ bool32 IsBattlerProtected(u32 battlerAtk, u32 battlerDef, u32 move)
...
+
+enum IronBallCheck {
+    ENABLE_IRON_BALL_CHECK,
+    IGNORE_IRON_BALL_CHECK
+};
```
Comment (AlexOn1ine) [inline src/battle_util.c:8827]:
```suggestion
enum IronBallCheck 
{
    CHECK_IRON_BALL
    IGNORE_IRON_BALL
};
```

File: test/battle/hold_effect/iron_ball.c [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+        OPPONENT(SPECIES_SKARMORY) { Item(ITEM_IRON_BALL); };
+    } WHEN {
+        TURN { MOVE(player, MOVE_EARTHQUAKE); };
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_EARTHQUAKE, player);
+        NONE_OF {
+            MESSAGE("It's super effective!");
+        }
+    }
+}
```
Comment (AlexOn1ine) [inline test/battle/hold_effect/iron_ball.c:22]: missing new line

File: src/battle_util.c [hunk 5]
```diff
@@ -8816,12 +8816,22 @@ bool32 IsBattlerProtected(u32 battlerAtk, u32 battlerDef, u32 move)
...
+
+// Only called directly when calculating damage type effectiveness, and Iron Ball's type effectiveness mechanics
+static bool32 IsBattlerGroundedInverseCheck(u32 battler, enum InverseBattleCheck considerInverse, enum IronBallCheck considerIronBallCheck)
```
Comment (AlexOn1ine) [inline src/battle_util.c:8830]:
```suggestion
static bool32 IsBattlerGroundedInverseCheck(u32 battler, enum InverseBattleCheck checkInverse, enum IronBallCheck checkIronBall)
```

**Comment by AlexOn1ine** [comment]
the enums are a bit verbose but looks good otherwise

File: test/battle/hold_effect/iron_ball.c (hunk 4 above)
Comment (spindrift64) [reply test/battle/hold_effect/iron_ball.c:22]: what line is missing?

Comment (AlexOn1ine) [inline test/battle/hold_effect/iron_ball.c:22]:
```suggestion
}

```

Comment (AlexOn1ine) [reply test/battle/hold_effect/iron_ball.c:22]: an extra line at the end of the file

**Comment by spindrift64** [comment]
should be good now
