### PR TITLE
Fix Costar not copying partner's critical hit boosts

### LINKED ISSUE #8381: Costar should copy partner's crit boosts
### Description

Costar is missing this effect. Should copy Focus Energy/Dragon Cheer volatiles and, although not in Gen 9, crit boosts obtained via G-Max Chi Strike.

### Reproduction Steps

.

### Images / Video

_No response_

### Version

1.13.3 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

PhallenTree

### PR DESCRIPTION
**Pull request by moostoet**
## Description

Costar now correctly copies critical hit boosts from its ally when switching in. Previously, Costar only copied stat stages but missed copying:
- Focus Energy volatile
- Dragon Cheer volatile
- G-Max Chi Strike bonus crit stages

This matches the expected behavior as documented on Bulbapedia and resolves the existing `TO_DO_BATTLE_TEST("Costar can copy an ally's critical hit ratio")`.

## Issue(s) that this PR fixes

Fixes #8381

## Discord contact info

viridian.

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -4144,6 +4144,10 @@ u32 AbilityBattleEffects(u32 caseID, u32 battler, u32 ability, u32 special, u32
                 gSpecialStatuses[battler].switchInAbilityDone = TRUE;
                 for (i = 0; i < NUM_BATTLE_STATS; i++)
                     gBattleMons[battler].statStages[i] = gBattleMons[BATTLE_PARTNER(battler)].statStages[i];
+                // Copy crit boosts (Focus Energy, Dragon Cheer, G-Max Chi Strike)
+                gBattleMons[battler].volatiles.focusEnergy = gBattleMons[BATTLE_PARTNER(battler)].volatiles.focusEnergy;
+                gBattleMons[battler].volatiles.dragonCheer = gBattleMons[BATTLE_PARTNER(battler)].volatiles.dragonCheer;
+                gBattleStruct->bonusCritStages[battler] = gBattleStruct->bonusCritStages[BATTLE_PARTNER(battler)];
```
Comment (AlexOn1ine) [inline src/battle_util.c]: Would you be open to change `bonusCritStages` to a battlemon volatile? Battlemon volatiles are cleared automatically when the mon switches out / faints so we don't need to care about that. As far as I can see we forgot to add it to the `FaintClearSetData` function

**Comment by PhallenTree** [comment]
The ability does not require the `CountBattlerStatIncreases` check according to jpwiki, it will even copy the partner's lowered stats.

**Comment by moostoet** [comment]
> The ability does not require the `CountBattlerStatIncreases` check according to jpwiki, it will even copy the partner's lowered stats.

@PhallenTree - I reworked the code to comply with this, as well as introducing a new test

File: src/battle_util.c (hunk 1 above)
Comment (moostoet) [reply src/battle_util.c]: @AlexOn1ine Yes, I just committed the changes, feel free to review 👍

File: src/battle_script_commands.c [hunk 2]
```diff
@@ -4059,8 +4059,8 @@ void SetMoveEffect(u32 battler, u32 effectBattler, bool32 primary, bool32 certai
         gBattlescriptCurrInstr = BattleScript_EffectMeanLookSide;
         break;
     case MOVE_EFFECT_CRIT_PLUS_SIDE:
-        gBattleStruct->bonusCritStages[gBattlerAttacker]++;
-        gBattleStruct->bonusCritStages[BATTLE_PARTNER(gBattlerAttacker)]++;
+        gBattleMons[gBattlerAttacker].volatiles.bonusCritStages++;
+        gBattleMons[BATTLE_PARTNER(gBattlerAttacker)].volatiles.bonusCritStages++;
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c]: Could you add a bound check for those so they don't overflow? At stage 3 it doesn't matter anymore if they are increased.

Comment (moostoet) [reply src/battle_script_commands.c]: @AlexOn1ine Added

**Comment by AlexOn1ine** [comment]
@PhallenTree is this ready to go?

**Comment by PhallenTree** [comment]
> @PhallenTree is this ready to go?

There are conflicts now, but yeah.
