### PR TITLE
Future Sight fixes

### LINKED ISSUE #4030: Future Sight issues
### Description

- When the attacker switches out after using Future Sight, the damage calculation uses the current active Pokemon's stats rather than the original Pokemon.
- Future sight does not consume items like Psychic Gem when the attacker is still in the field. (It is actually expected to happen that Future Sight ignores item boosts when the attacker switches, but not when it stays in.)
- Future Sight resolves after the enemy switches in a Pokemon when it should be the opposite. Example: https://replay.pokemonshowdown.com/gen9ou-2038561127 This is how it is supposed to work, whereas in the current expansion Version, Gholdengo would take Future Sight damage.

### Version

upcoming (Edge)

### Upcoming/master Version

58102e6

### Discord contact info

._.terra._.

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #4030

Damage for Future Sight calculation is now done outside of the normal calcs if the current battler is not the original Future Sight user. 

Feel free to ask for more specific tests.

### CODE REVIEW

File: src/battle_message.c [hunk 1]
```diff
@@ -231,6 +231,7 @@ static const u8 sText_PkmnBlewAwaySpikes[] = _("{B_ATK_NAME_WITH_PREFIX} blew aw
 static const u8 sText_PkmnFledFromBattle[] = _("{B_ATK_NAME_WITH_PREFIX} fled from\nbattle!");
 static const u8 sText_PkmnForesawAttack[] = _("{B_ATK_NAME_WITH_PREFIX} foresaw\nan attack!");
 static const u8 sText_PkmnTookAttack[] = _("{B_DEF_NAME_WITH_PREFIX} took the\n{B_BUFF1} attack!");
+static const u8 sText_FutureSightNoHit[] = _("{B_CURRENT_MOVE} did not hit because\nthe target is fainted.");
```
Comment (Bassoonian) [inline src/battle_message.c:234]: Is this authentic game text? The tone just feels more Showdowny than most other strings to me, but that could just be me haha

File: test/battle/move_effect/future_sight.c [hunk 2]
```diff
@@ -0,0 +1,133 @@
+#include "global.h"
+#include "test/battle.h"
+
+ASSUMPTIONS
+{
+    ASSUME(gMovesInfo[MOVE_SEED_FLARE].power == gMovesInfo[MOVE_FUTURE_SIGHT].power);
+}
+
+SINGLE_BATTLE_TEST("Future Sight uses the Attack stat of the original user without modifiers")
```
Comment (Bassoonian) [inline test/battle/move_effect/future_sight.c:9]: Shouldn't this be Special Attack? In which case we also need to check the category of both moves in the assumptions.

File: test/battle/move_effect/future_sight.c [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+        HP_BAR(opponent, captureDamage: &seedFlareDmg);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_FUTURE_SIGHT, player);
+        MESSAGE("Foe Regice took the Future Sight attack!");
+        HP_BAR(opponent, captureDamage: &futureSightDmg);
+    } THEN {
+        EXPECT_EQ(seedFlareDmg, futureSightDmg);
+    }
+}
+
+SINGLE_BATTLE_TEST("Future Sight is not boosted by Life Orb is original user is not on the field")
```
Comment (Bassoonian) [inline test/battle/move_effect/future_sight.c:39]:
```suggestion
SINGLE_BATTLE_TEST("Future Sight is not boosted by Life Orb if original user is not on the field")
```

File: test/battle/move_effect/future_sight.c [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_FUTURE_SIGHT, player);
+        MESSAGE("Foe Regice took the Future Sight attack!");
+        HP_BAR(opponent, captureDamage: &futureSightDmg);
+        NOT MESSAGE("Raichu was hurt by its Life Orb!");
+    } THEN {
+        EXPECT_EQ(seedFlareDmg, futureSightDmg);
+    }
+}
+
+SINGLE_BATTLE_TEST("Future Sight receives from STAB party mon")
```
Comment (Bassoonian) [inline test/battle/move_effect/future_sight.c:66]:
```suggestion
SINGLE_BATTLE_TEST("Future Sight receives STAB from party mon")
```
I think?

File: src/battle_message.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_message.c:234]: That is from showdown lol Idk the offical game freak string and it is is different.

File: test/battle/move_effect/future_sight.c (hunk 2 above)
Comment (AlexOn1ine) [reply test/battle/move_effect/future_sight.c:9]: yes

File: src/battle_message.c (hunk 1 above)
Comment (Bassoonian) [reply src/battle_message.c:234]: It's missing from the SV textdump, so we should really try to test this in-game before we add a non-vanilla string imo (unless others think it's non-blocking). This PR is good to go other than this though

Comment (AlexOn1ine) [reply src/battle_message.c]: I removed the string since there wasn't this are any other comparable string in the SV data. I didn't replace it with anything else because the `But failed` string seemed weird in this situation and since the set up is non trivial I don't want to bother anyone. Though it might worth an issue ticket. Maybe someone will test it.

**Comment by AlexOn1ine** [comment]
Ready for re-review.

File: include/battle_scripts.h [hunk 5]
```diff
@@ -86,6 +86,7 @@ extern const u8 BattleScript_WrapFree[];
 extern const u8 BattleScript_LeechSeedFree[];
 extern const u8 BattleScript_SpikesFree[];
 extern const u8 BattleScript_MonTookFutureAttack[];
+extern const u8 BattleScript_FutureAttackFail[];
```
Comment (Bassoonian) [inline include/battle_scripts.h:89]: I'm surprised this compiles because the string doesn't exist anymore, haha

File: include/battle.h [hunk 6]
```diff
@@ -278,7 +278,8 @@ struct FieldTimer
 struct WishFutureKnock
 {
     u8 futureSightCounter[MAX_BATTLERS_COUNT];
-    u8 futureSightAttacker[MAX_BATTLERS_COUNT];
+    u8 futureSightBattlerIndex[MAX_BATTLERS_COUNT];
+    u8 futureSightPartyIndex[MAX_BATTLERS_COUNT];
     u16 futureSightMove[MAX_BATTLERS_COUNT];
```
Comment (Bassoonian) [inline include/battle.h:283]: I may be mistaken, but wouldn't a slight reorder here realign it so we don't have three u8s and then a u16? Maybe the fact it's an array removes the need, but just a thought

File: src/battle_message.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_message.c]: fixed

File: include/battle_scripts.h (hunk 5 above)
Comment (AlexOn1ine) [reply include/battle_scripts.h]: fixed

**Review by Bassoonian — APPROVED** [review]
