### PR TITLE
Strength Sap fixes 

### LINKED ISSUE #9060: Attacker Strength Sap with magic guard takes damage vs target liquid ooze
### Description

There's just no check for magic guard if target has liquid ooze:
https://github.com/rh-hideout/pokeemerald-expansion/blob/c3b462a1397b9dea82882d336b1c77209c6d53bd/data/battle_scripts_1.s#L934-L956

### Reproduction Steps

code

### Images / Video

_No response_

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #9060

To upcoming because there are to many changes right now between upcoming and master. 

There is a contrary test that fails but I can't figure out why 
```
jumpifstat BS_TARGET, CMP_EQUAL, STAT_ATK, MIN_STAT_STAGE, BattleScript_StrengthSapPrintStatMessage
```
This line should prevent it from jumping but it goes into the branch regardless. If you remove the check the test passes again. I'm not sure if this might be some greater issue with the stat buff code.

### CODE REVIEW

File: test/battle/move_effect/strength_sap.c [hunk 1]
```diff
@@ -167,3 +168,65 @@ SINGLE_BATTLE_TEST("Strength Sap restores more HP if Big Root is held", s16 hp)
...
+        ABILITY_POPUP(player, ABILITY_LIQUID_OOZE);
+        NOT HP_BAR(opponent);
+    }
+}
+
+SINGLE_BATTLE_TEST("Strength Sap does not fail if target has Contrary and is at +6 Atk")
+{
+    GIVEN {
+        // No idea why this does not work the code checks for min stage but goes into the fail branch regardless.
+        // However this didn't work prior to the refactor either
```
Comment (PhallenTree) [inline test/battle/move_effect/strength_sap.c]: Use `jumpifstatignorecontrary` instead of `jumpifstat`

File: test/battle/move_effect/strength_sap.c [hunk 2]
```diff
@@ -167,3 +168,65 @@ SINGLE_BATTLE_TEST("Strength Sap restores more HP if Big Root is held", s16 hp)
         EXPECT_GT(abs(results[1].hp), abs(results[0].hp));
     }
 }
+
+SINGLE_BATTLE_TEST("Strength Sap will not drain users hp due to Uiquid Ooze")
```
Comment (PhallenTree) [inline test/battle/move_effect/strength_sap.c]:
```suggestion
SINGLE_BATTLE_TEST("Strength Sap will not drain users hp due to Liquid Ooze")
```

File: test/battle/move_effect/strength_sap.c [hunk 3]
```diff
@@ -141,6 +141,7 @@ SINGLE_BATTLE_TEST("Strength Sap fails if target is at -6 Atk")
     }
 }
 
+// Is the test description correct?
 TO_DO_BATTLE_TEST("Strength Sap doesn't fail if target has Contrary and is at +6 Atk, restoring HP based on +5 Atk")
```
Comment (PhallenTree) [inline test/battle/move_effect/strength_sap.c]: No, the HP restoring should be based on stat stage before Strength Sap's Attack drop/boost

File: src/battle_move_resolution.c [hunk 4]
```diff
@@ -1806,7 +1787,18 @@ static enum MoveEndResult MoveEndAbsorb(void)
...
         {
             s32 healAmount = gBattleStruct->passiveHpUpdate[gBattlerAttacker];
-            SetAbsorbScript(healAmount, moveEffect);
+            if (GetBattlerAbility(gBattlerTarget) == ABILITY_LIQUID_OOZE)
+            {
+                SetPassiveDamageAmount(gBattlerAttacker, healAmount);
+                gBattleCommunication[MULTISTRING_CHOOSER] = B_MSG_ABSORB_OOZE;
+                BattleScriptCall(BattleScript_EffectAbsorbLiquidOoze);
+            }
+            else if (!IsBattlerAtMaxHp(gBattlerAttacker))
```
Comment (AlexOn1ine) [inline src/battle_move_resolution.c]: the message might also not be played for other absorbing moves?

Comment (PhallenTree) [reply src/battle_move_resolution.c]: [jpwiki](https://wiki.xn--rckteqa2e.com/wiki/%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA:HP%E3%82%92%E5%90%B8%E5%8F%8E%E3%81%99%E3%82%8B%E3%82%8F%E3%81%96):

> Even if HP is already full, up until the fourth generation, the message "Sucked energy from target!" will be displayed. From the fifth generation onwards, this message is omitted.

So yeah it's no longer displayed when the user is at full HP.

Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: Should we make it general or exclude strength sap from the config? I assume if strength sap existed in gen3/4 it would also play the message regardless whether hp was drained or not.

Comment (PhallenTree) [reply src/battle_move_resolution.c]: It should be general, there are more moves introduced in Gen 5+ that this would apply to

Comment (AlexOn1ine) [reply src/battle_move_resolution.c]: config added

File: test/battle/move_effect/strength_sap.c [hunk 5]
```diff
@@ -167,3 +167,92 @@ SINGLE_BATTLE_TEST("Strength Sap restores more HP if Big Root is held", s16 hp)
...
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(opponent, MOVE_HEAL_BLOCK); MOVE(player, MOVE_STRENGTH_SAP); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_HEAL_BLOCK, opponent);
+        NOT ANIMATION(ANIM_TYPE_MOVE, MOVE_STRENGTH_SAP, player);
+    }
+}
+
+SINGLE_BATTLE_TEST("Strangth Sap will drain users HP if target has Liquid Ooze")
```
Comment (PhallenTree) [inline test/battle/move_effect/strength_sap.c]:
```suggestion
SINGLE_BATTLE_TEST("Strength Sap will drain users HP if target has Liquid Ooze")
```

File: test/battle/move_effect/strength_sap.c [hunk 6]
```diff
@@ -167,3 +167,92 @@ SINGLE_BATTLE_TEST("Strength Sap restores more HP if Big Root is held", s16 hp)
         EXPECT_GT(abs(results[1].hp), abs(results[0].hp));
     }
 }
+
+SINGLE_BATTLE_TEST("Strength Sap will not drain users hp due to Liquid Ooze")
```
Comment (PhallenTree) [inline test/battle/move_effect/strength_sap.c]: Should probably mention Magic Guard in this test's title

**Review by PhallenTree — COMMENTED** [review]
Upper Hand tests are failing (they use Draining Kiss, should set hp of Comfey to below 100% or use the new config with GEN_4)

**Comment by AlexOn1ine** [comment]
Fixed the tests. I just removed the messages for the upper hand. I think this should be fine since we are still checking the anim.

**Review by PhallenTree — APPROVED** [review]

**Review by hedara90 — APPROVED** [review]
