### PR TITLE
Change HP bar color calculation from pixel-width to actual values

### LINKED ISSUE #5776: Gen 5+ HP fraction calculation
### Description

The way the HP fractions are currently calculated for things like health bar color or critical health bleep can lead to unexpected results. For example, when a mon's health is between 20% and 21%, it gets rounded down to 20% and is incorrectly displayed as being on low health. This was fixed in Gen 5+.
image
image
image
Here's an example of a mon being at 20.5% health in Gen 3, 4, and 5.

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Kasenn**
## Description

In Gen 1-4, the HP bar color was calculated based on the pixel-width of the HP bar. Gen 5 onwards, GF changed the HP bar color calculation from pixel-width based to actual value-based. This updates the color calculation to that newer-gen standard.

The function `CalcBarFilledPixels` does a `return filledPixels;`, which is now completely unused, but I thought it best to leave it there in case of backwards-compatibility.

This is my first PR so hopefully I'm doing this right.

## Media
Example of HP bars before and after
image

Examples from Gen 3-6 as proof:
image
image
image
image

## Issue(s) that this PR fixes

Fixes #5776

## Discord contact info

kaseni

### CODE REVIEW

**Comment by FosterProgramming** [comment]
Adding scope pending because I'm not sure if it should be added as is or as a config

**Comment by AlexOn1ine** [comment]
> Adding scope pending because I'm not sure if it should be added as is or as a config

should be a config, set to `TRUE`

**Comment by Kasenn** [comment]
Cleaned up a bit and made it a config

File: src/battle_interface.c [hunk 1]
```diff
@@ -2064,22 +2064,35 @@ s32 MoveBattleBar(u8 battler, u8 healthboxSpriteId, u8 whichBar, u8 unused)
...
+    u8 level;
     u8 barElementId;
     u8 i;
+    s32 currValue, maxValue;
 
     switch (whichBar)
     {
     case HEALTH_BAR:
-        filledPixelsCount = CalcBarFilledPixels(gBattleSpritesDataPtr->battleBars[battler].maxValue,
+    #if B_HPBAR_COLOR_THRESHOLD < GEN_5
```
Comment (AlexOn1ine) [inline src/battle_interface.c]: You can use a regular if for configs if it isn't const data

Comment (Kasenn) [reply src/battle_interface.c]: I'm a bit confused, would it not be more efficient to preproc it? In any case, I updated it with another commit

Comment (AlexOn1ine) [reply src/battle_interface.c]: Right, since a preproc will be optimized out, it will always be more efficient. However the downside of a prerproc is that we get no compile errors if it's set to false. So a decision a long time ago was made that everything that can be a normal if should be a normal if.

In your case the compiler might even decide to optimize out it regardless since this condition will always be either true or false.

File: src/battle_interface.c [hunk 2]
```diff
@@ -2280,26 +2296,33 @@ u8 GetScaledHPFraction(s16 hp, s16 maxhp, u8 scale)
...
+        if (currValue > (maxValue * 50 / 100)) // more than 50 % hp
+            return HP_BAR_GREEN;
+        else if (currValue > (maxValue * 20 / 100)) // more than 20 % hp
+            return HP_BAR_YELLOW;
+        else if (currValue > 0)
+            return HP_BAR_RED; // 20 % or less
         else
-            result = HP_BAR_EMPTY;
+            return HP_BAR_EMPTY;
     }
```
Comment (AlexOn1ine) [inline src/battle_interface.c]: there is something incorrect here. I think the last curly bracket is wrong and the block needs to be one depth lower.

Comment (Kasenn) [reply src/battle_interface.c]: there was a small hiccup with the indentation, but it should be fixed now

File: src/battle_interface.c [hunk 3]
```diff
@@ -2064,22 +2064,38 @@ s32 MoveBattleBar(u8 battler, u8 healthboxSpriteId, u8 whichBar, u8 unused)
...
 
-        if (filledPixelsCount > (B_HEALTHBAR_PIXELS * 50 / 100)) // more than 50 % hp
+        maxValue  = gBattleSpritesDataPtr->battleBars[battler].maxValue;
+        currValue = gBattleSpritesDataPtr->battleBars[battler].currValue;
+    }
+
+        if (currValue > (maxValue * 50 / 100)) // more than 50 % hp
             barElementId = HEALTHBOX_GFX_HP_BAR_GREEN;
-        else if (filledPixelsCount > (B_HEALTHBAR_PIXELS * 20 / 100)) // more than 20% hp
+        else if (currValue > (maxValue * 20 / 100)) // more than 20 % hp
```
Comment (Bassoonian) [inline src/battle_interface.c]:
```suggestion
        else if (currValue > (maxValue * 20 / 100)) // more than 20% hp
```

File: src/battle_interface.c [hunk 4]
```diff
@@ -2064,22 +2064,38 @@ s32 MoveBattleBar(u8 battler, u8 healthboxSpriteId, u8 whichBar, u8 unused)
...
             barElementId = HEALTHBOX_GFX_HP_BAR_YELLOW;
         else
             barElementId = HEALTHBOX_GFX_HP_BAR_RED; // 20 % or less
```
Comment (Bassoonian) [inline src/battle_interface.c]:
```suggestion
            barElementId = HEALTHBOX_GFX_HP_BAR_RED; // 20% or less
```

File: src/battle_interface.c [hunk 5]
```diff
@@ -2064,22 +2064,38 @@ s32 MoveBattleBar(u8 battler, u8 healthboxSpriteId, u8 whichBar, u8 unused)
...
                             gBattleSpritesDataPtr->battleBars[battler].receivedValue,
                             &gBattleSpritesDataPtr->battleBars[battler].currValue,
                             array, B_HEALTHBAR_PIXELS / 8);
 
-        if (filledPixelsCount > (B_HEALTHBAR_PIXELS * 50 / 100)) // more than 50 % hp
+        maxValue  = gBattleSpritesDataPtr->battleBars[battler].maxValue;
+        currValue = gBattleSpritesDataPtr->battleBars[battler].currValue;
+    }
+
+        if (currValue > (maxValue * 50 / 100)) // more than 50 % hp
```
Comment (Bassoonian) [inline src/battle_interface.c]:
```suggestion
        if (currValue > (maxValue * 50 / 100)) // more than 50% hp
```

File: src/battle_interface.c [hunk 6]
```diff
@@ -2280,26 +2296,34 @@ u8 GetScaledHPFraction(s16 hp, s16 maxhp, u8 scale)
...
         else
-            result = HP_BAR_EMPTY;
-    }
+        {
+            currValue = hp;
+            maxValue = maxhp;
+        }
 
-    return result;
+        if (currValue > (maxValue * 50 / 100)) // more than 50 % hp
```
Comment (Bassoonian) [inline src/battle_interface.c]:
```suggestion
        if (currValue > (maxValue * 50 / 100)) // more than 50% hp
```

File: src/battle_interface.c [hunk 7]
```diff
@@ -2280,26 +2296,34 @@ u8 GetScaledHPFraction(s16 hp, s16 maxhp, u8 scale)
...
+            return HP_BAR_GREEN;
+        else if (currValue > (maxValue * 20 / 100)) // more than 20 % hp
```
Comment (Bassoonian) [inline src/battle_interface.c]:
```suggestion
        else if (currValue > (maxValue * 20 / 100)) // more than 20% hp
```

File: src/battle_interface.c [hunk 8]
```diff
@@ -2280,26 +2296,34 @@ u8 GetScaledHPFraction(s16 hp, s16 maxhp, u8 scale)
...
+            return HP_BAR_YELLOW;
+        else if (currValue > 0)
+            return HP_BAR_RED; // 20 % or less
```
Comment (Bassoonian) [inline src/battle_interface.c]:
```suggestion
            return HP_BAR_RED; // 20% or less
```

File: src/battle_interface.c [hunk 9]
```diff
@@ -2280,26 +2296,34 @@ u8 GetScaledHPFraction(s16 hp, s16 maxhp, u8 scale)
...
 {
-    u8 result;
+    s32 currValue, maxValue;
 
     if (hp == maxhp)
     {
-        result = HP_BAR_FULL;
+        return HP_BAR_FULL;
     }
     else
```
Comment (Bassoonian) [inline src/battle_interface.c:2309]: We don't need this ``else`` because we ``return`` anyway, so that allow you to reduce the indentation

File: src/battle_interface.c [hunk 10]
```diff
@@ -2280,26 +2296,34 @@ u8 GetScaledHPFraction(s16 hp, s16 maxhp, u8 scale)
...
 
-    return result;
+        if (currValue > (maxValue * 50 / 100)) // more than 50 % hp
+            return HP_BAR_GREEN;
+        else if (currValue > (maxValue * 20 / 100)) // more than 20 % hp
+            return HP_BAR_YELLOW;
+        else if (currValue > 0)
+            return HP_BAR_RED; // 20 % or less
+        else
+            return HP_BAR_EMPTY;
```
Comment (Bassoonian) [inline src/battle_interface.c]: The ``else`` here (and in the conditions) is technically also not needed, though less "harmful" than the ``else`` mentioned above

**Comment by Kasenn** [comment]
applied all the suggested changes (hopefully. the github ui is hard to follow at times so i'm not sure i got everything)

**Review by Bassoonian — APPROVED** [review]

**Comment by Kasenn** [comment]
@all-contributors please add @Kasenn for code
