### PR TITLE
Fixes timesGotHit not increasing on forced switch out

### LINKED ISSUE #6306: Potential Rage Fist bug
### Description

During a merge I noticed that long time ago I added a rage fist fix in my repo. However I don't remember what the purpose of it was and I forgot to port it at that time. The fix is in `Cmd_forcerandomswitch`
```
            // Rage Fist timesGotHit increase
            if (gBattlerAttacker != gBattlerTarget
                && gMovesInfo[gCurrentMove].category != DAMAGE_CATEGORY_STATUS
                && MoveResultHasEffect(gBattlerTarget)
                && IsBattlerTurnDamaged(gBattlerTarget))
            {
                gBattleStruct->timesGotHit[GetBattlerSide(gBattlerTarget)][gBattlerPartyIndexes[gBattlerTarget]]++;
            }
```
I assume that if a random mon is forced in, moveend does not properly go through `MOVEEND_NUM_HITS` and therefore needs additional handling. 
Generally though, It might be worth looking into a better solution then having it in `MOVEEND_NUM_HITS`. Maybe in `healthbarupdate` or `datahpupdate`. That might future proof it and avoid splitting. 

### Version

1.10.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by AlexOn1ine**
Fixes #6306

### CODE REVIEW

File: src/battle_script_commands.c [hunk 1]
```diff
@@ -2669,6 +2671,9 @@ static void Cmd_datahpupdate(void)
             BtlController_EmitSetMonData(battler, BUFFER_A, REQUEST_HP_BATTLE, 0, sizeof(gBattleMons[battler].hp), &gBattleMons[battler].hp);
             MarkBattlerForControllerExec(battler);
         }
+
+        if (gBattlerAttacker != gBattlerTarget && GetMoveCategory(gCurrentMove) != DAMAGE_CATEGORY_STATUS)
```
Comment (hedara90) [inline src/battle_script_commands.c:2675]: This needs to have the check for `IsBattlerTurnDamaged(gBattlerTarget)`, otherwise it will count hits against substitutes which it shouldn't.

**Review by hedara90 — COMMENTED** [review]
Also add test for the Substitute regression.
```C
SINGLE_BATTLE_TEST("Rage Fist doesn't get increased power if Substitute is hit")
{
    s16 timesGotHit[2];

    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(opponent, MOVE_RAGE_FIST); MOVE(player, MOVE_CELEBRATE); }
        TURN { MOVE(opponent, MOVE_SUBSTITUTE); MOVE(player, MOVE_TACKLE); }
        TURN { MOVE(opponent, MOVE_RAGE_FIST); MOVE(player, MOVE_CELEBRATE); }
    } SCENE {
        ANIMATION(ANIM_TYPE_MOVE, MOVE_RAGE_FIST, opponent);
        HP_BAR(player, captureDamage: &timesGotHit[0]);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_RAGE_FIST, opponent);
        HP_BAR(player, captureDamage: &timesGotHit[1]);
    } THEN {
        EXPECT_EQ(timesGotHit[0], timesGotHit[1]);
    }
}
```

File: src/battle_script_commands.c (hunk 1 above)
Comment (AlexOn1ine) [reply src/battle_script_commands.c:2675]: oh thx. I was trying to think of something that would need it but couldn't

Comment (AlexOn1ine) [reply src/battle_script_commands.c]: fixed

**Review by hedara90 — APPROVED** [review]
