### PR TITLE
Fixes Stalwart/Propeller Tail, Life Orb on confusion, Remove Status wrong battlescripts

### LINKED ISSUE #4907: Self-Confusion Damage incorrectly triggers Life Orb
### Description

# Testing Script

## data/scripts/debug.inc

```diff
Debug_EventScript_Script_1::
+	setflag FLAG_BADGE08_GET
+	setflag FLAG_BADGE07_GET
+	setflag FLAG_BADGE06_GET
+	setflag FLAG_BADGE05_GET
+	setflag FLAG_BADGE04_GET
+	setflag FLAG_BADGE03_GET
+	setflag FLAG_BADGE02_GET
+	setflag FLAG_BADGE01_GET
+       givemon SPECIES_SHUCKLE,100,0
+       trainerbattle_single TRAINER_SAWYER_1,Debug_FlagsNotSetBattleConfigMessage_Text,Debug_FlagsNotSetBattleConfigMessage_Text
+	release
	end
```

## src/data/trainers.party

```diff
=== TRAINER_SAWYER_1 ===
Name: SAWYER
Class: Hiker
Pic: Hiker
Gender: Male
Music: Hiker
Double Battle: No
AI: Check Bad Move / Try To Faint / Check Viability

+ /*
Geodude
Level: 21
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA / 0 SpD / 0 Spe
+ */
+ Growlithe @ Life Orb
+ Level: 1
+ - Outrage

```

# Repro
1) Run testing script
2) Use Sticky Web over and over
3) Wait for Growlithe to hit itself in confusion
4) Expected no Life Orb interaction, but it triggers when hit instead

# Video
https://github.com/rh-hideout/pokeemerald-expansion/assets/77138753/936b2d81-15ce-4305-b9a4-9785df7c14d1

Reported from [The Pit](<https://discord.com/channels/1247322603895656579/1257860631705686058>).

### Version

upcoming (Edge)

### Upcoming/master Version

[d1ca1f667f6fb4623197151a0565f7c56357d123](https://github.com/rh-hideout/pokeemerald-expansion/commit/7e167f0b3c9e23eba98f294622c5fc7967072820)

### Discord contact info

pkmnsnfrn

### PR DESCRIPTION
**Pull request by PhallenTree**
Fixes Stalwart and Propeller Tail not ignoring redirection from Storm Drain/Lightning Rod.
Adds a test for this.

Fixes Life Orb damaging its holder if it hits itself in confusion.

Fixes MoveEffectRemoveStatus (Sparkling Aria, Wake-Up Slap, ...) that cure Freeze/Frostbite using the other status' battlescript.

## Issue(s) that this PR fixes
Fixes #4907 

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: test/battle/ability/stalwart.c [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+{
+    u32 ability;
+    PARAMETRIZE { ability = ABILITY_STORM_DRAIN; }
+    PARAMETRIZE { ability = ABILITY_LIGHTNING_ROD; }
+    GIVEN {
+        ASSUME(gMovesInfo[MOVE_SPARK].type == TYPE_ELECTRIC);
+        ASSUME(gMovesInfo[MOVE_WATER_GUN].type == TYPE_WATER);
+        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_STALWART); }
+        PLAYER(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_RAICHU) { Ability(ability); }
```
Comment (AlexOn1ine) [inline test/battle/ability/stalwart.c:31]: could you parametrize the species here as well so storm drain is attached to a legal ability?

**Review by AlexOn1ine — APPROVED** [review]
