### PR TITLE
Fix Ability Shield exemption when Neutralizing Gas ends

### LINKED ISSUE #9259: Investigate Ability Shield exemption when Neutralizing Gas ends
### Description

[Bulba](https://bulbapedia.bulbagarden.net/wiki/Neutralizing_Gas_(Ability)):
> Neutralizing Gas suppresses the effects of Abilities of other Pokémon currently in battle that are not holding an **Ability Shield**.
> Once Neutralizing Gas is no longer applying, Abilities that activate when gained (i.e. Abilities that activate when a Pokémon is switched in, such as Intimidate) immediately pop up an activation message **regardless of whether they have already done so**, with the exceptions of Unnerve (which still applies but without displaying a message) and Imposter (which only activates when switched in, not when gained). 

The wiki case might be: a Pokémon triggers Intimidate, then Neutralizing Gas enters the field, and later the Neutralizing Gas user is knocked out, so Intimidate triggers again.

However, Neutralizing Gas only suppresses Abilities of active Pokémon that are not holding an Ability Shield.
So for a Pokémon holding Ability Shield:
- Its Ability is never suppressed, so the gas effectively doesn’t apply to it.
- If it was never suppressed, there is no “regain” moment when the gas ends.
- Therefore, when Neutralizing Gas ends, only Abilities that were actually suppressed should reactivate; Pokémon with Ability Shield are not in that group.

If the above analysis is correct, then the fix may be:
```
void BS_JumpIfAbilityCantBeReactivated(void)
{
    NATIVE_ARGS(u8 battler, const u8 *jumpInstr);
    u32 battler = GetBattlerForBattleScript(cmd->battler);
    u32 ability = gBattleMons[battler].ability;

+   if (GetBattlerHoldEffectIgnoreAbility(battler) == HOLD_EFFECT_ABILITY_SHIELD)
+   {
+       gBattlescriptCurrInstr = cmd->jumpInstr;
+       return;
+   }
```

### Reproduction Steps

Team Configuration
```
Arcanine-Hisui @ Ability Shield
Ability: Intimidate
Level: 50
Tera Type: Ghost
EVs: 244 HP / 36 Atk / 4 Def / 12 SpD / 212 Spe
Adamant Nature
IVs: 0 SpA
- Flare Blitz
- Rock Slide
- Extreme Speed
- Protect

Weezing @ Sitrus Berry
Ability: Neutralizing Gas
Level: 50
Tera Type: Grass
EVs: 252 HP / 68 Def / 4 SpA / 156 SpD / 28 Spe
Calm Nature
IVs: 0 Atk
- Sludge Bomb
- Will-O-Wisp
- Taunt
- Protect
```

### Images / Video

Image

### Version

1.14.3 (Latest release)

### Upcoming/master Version

master

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by Cle-bit**
## Description
See #9259 for details

## Issue(s) that this PR fixes
Closes #9259

### CODE REVIEW

File: test/battle/hold_effect/ability_shield.c [hunk 1]
```diff
@@ -35,6 +35,38 @@ SINGLE_BATTLE_TEST("Ability Shield protects against Neutralizing Gas")
...
 
+DOUBLE_BATTLE_TEST("Ability Shield prevents Intimidate from reactivating after Neutralizing Gas ends")
+{
+    GIVEN {
+        PLAYER(SPECIES_WOBBUFFET) { Speed(5); }
+        PLAYER(SPECIES_WYNAUT) { Speed(4); }
+        OPPONENT(SPECIES_KOFFING) { Ability(ABILITY_NEUTRALIZING_GAS); HP(1); Speed(1); }
+        OPPONENT(SPECIES_GYARADOS) { Ability(ABILITY_INTIMIDATE); Item(ITEM_ABILITY_SHIELD); Speed(3); }
+    } WHEN {
+        TURN { MOVE(playerLeft, MOVE_TACKLE, target: opponentLeft); }
```
Comment (PhallenTree) [inline test/battle/hold_effect/ability_shield.c]:
```suggestion
        TURN { MOVE(playerLeft, MOVE_SCRATCH, target: opponentLeft); }
```

File: test/battle/hold_effect/ability_shield.c [hunk 2]
```diff
@@ -35,6 +35,38 @@ SINGLE_BATTLE_TEST("Ability Shield protects against Neutralizing Gas")
...
+    } SCENE {
+        ABILITY_POPUP(opponentLeft, ABILITY_NEUTRALIZING_GAS);
+        MESSAGE("Neutralizing gas filled the area!");
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_HELD_ITEM_EFFECT, opponentRight);
+        MESSAGE("The opposing Gyarados's Ability is protected by the effects of its Ability Shield!");
+        ABILITY_POPUP(opponentRight, ABILITY_INTIMIDATE);
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerLeft);
+        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerRight);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerLeft);
```
Comment (PhallenTree) [inline test/battle/hold_effect/ability_shield.c]:
```suggestion
        ANIMATION(ANIM_TYPE_MOVE, MOVE_SCRATCH, playerLeft);
```

File: test/battle/hold_effect/ability_shield.c [hunk 3]
```diff
@@ -35,6 +35,38 @@ SINGLE_BATTLE_TEST("Ability Shield protects against Neutralizing Gas")
...
+        HP_BAR(opponentLeft);
+        MESSAGE("The effects of the neutralizing gas wore off!");
+        MESSAGE("The opposing Koffing fainted!");
+        NONE_OF {
+            ABILITY_POPUP(opponentRight, ABILITY_INTIMIDATE);
+            ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerLeft);
+            ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerRight);
+        }
```
Comment (PhallenTree) [inline test/battle/hold_effect/ability_shield.c]:
```suggestion
        NONE_OF {
            ABILITY_POPUP(opponentRight, ABILITY_INTIMIDATE);
            ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerLeft);
            ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_STATS_CHANGE, playerRight);
        }
        MESSAGE("The opposing Koffing fainted!");
```

File: test/battle/hold_effect/ability_shield.c (hunk 1 above)
Comment (Cle-bit) [reply test/battle/hold_effect/ability_shield.c]: Is this necessary?

Comment (PhallenTree) [reply test/battle/hold_effect/ability_shield.c]: In general, since Tackle has changed over generations (mostly Base Power and Accuracy) while Scratch hasn't, it's better to use Scratch in tests.

**Review by AlexOn1ine — APPROVED** [review]
