### PR TITLE
Fix AI seeing priority wrong for players choice lock

### LINKED ISSUE #7898: AI not seeing priority of choice locked move properly
### Description

Bug found in Emerald Imperium but found to be reproducible through tests in expansion. 
AI does not see the priority of the player’s attack properly when choice locked for switch in calculations. This is mainly relevant in 2 situations:

1) When the player locks themself into a priority move and has no other priority move in their set, the AI will see the damage of the choiced move correctly but not the priority. (https://www.youtube.com/live/ikh2cAHN4Pk?t=2293s)

2) When the player locks themself into a non-priority move and has a priority move in their set, the AI will see the damage of the choiced move correctly but think the player can still use its other priority moves to deal damage to it. (https://youtu.be/S4QcbUJN4pw?si=36u99XwyIUPgBOOn&t=5472)

### Reproduction Steps

For 1):
- Careful Kingambit with choice band clicks sucker punch on a dragapult. Should bait in Annihilape for fast kill drain punch, instead baits gengar for fast kill focus blast. 

For 2):
- Jolly Lycanroc with choice band clicks mighty cleave on ninetales. Should bait in Darmanitan Galar Zen for fast kill, instead baits Decidueye Hisui for slow kill as Darmanitan thinks it dies to accelerock. 
- This can be done by replacing Darmanitan with a 0 defense iv hasty pheromosa with close combat.

### Images / Video

_No response_

### Version

1.13.2 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

MaximeGr

### PR DESCRIPTION
**Pull request by MaximeGr00**
## Description

Fixed an issue where if the player was locked into a priority move, AI would not recognize the move as such if it was the player's only priority move as *bestPlayerMove and *bestPlayerPriorityMove were not getting updated in the iteration of the choiced move.
Fixed another issue where if the player was locked into a non-priority move with a priority move in its set, AI would not recognize that the player's only option was not a priority move as it would iterate GetMaxPriorityDamagePlayerCouldDealToSwitchin normally.
Wrote a test for this fix.

## Media

https://www.youtube.com/live/ikh2cAHN4Pk?si=K9llfbZdKYv60xrl&t=2293
First bug instance.
Careful Choice Band Kingambit is locked into sucker punch and should bait annihilape for fast revenge kill as it fast ohko gengar.
https://youtu.be/S4QcbUJN4pw?si=36u99XwyIUPgBOOn&t=5472
Second bug instance.
Jolly Choice Band Lycanroc is locked into Mighty Cleave and should bait Galarian Darmanitan Zen Mode for fast revenge kill as it can't click accelerock.

## Issue(s) that this PR fixes

Fixes #7898

## Contributions

@ghostyboyy97

## Discord contact info

MaximeGr

### CODE REVIEW

File: test/battle/ai/ai_switching.c [hunk 1]
```diff
@@ -1399,3 +1399,20 @@ AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_SWITCHING: Fake Out style moves won't confu
...
+        ASSUME(gItemsInfo[ITEM_CHOICE_BAND].holdEffect == HOLD_EFFECT_CHOICE_BAND);
+        AI_FLAGS(AI_FLAG_CHECK_BAD_MOVE | AI_FLAG_TRY_TO_FAINT | AI_FLAG_CHECK_VIABILITY | AI_FLAG_SMART_SWITCHING | AI_FLAG_SMART_MON_CHOICES | AI_FLAG_OMNISCIENT);
+        PLAYER(SPECIES_LYCANROC) { Speed(5); Moves(MOVE_ACCELEROCK, MOVE_MIGHTY_CLEAVE); Item(item); }
+        OPPONENT(SPECIES_WOBBUFFET) { Speed(4); HP(1); Moves(MOVE_TACKLE); }
+        OPPONENT(SPECIES_DECIDUEYE_HISUI) { Speed(4); Moves(MOVE_LEAF_BLADE); }
+        OPPONENT(SPECIES_PHEROMOSA) { Speed(6); HP(1); Moves(MOVE_EARTHQUAKE); }
+    } WHEN {
+        TURN { MOVE(player, MOVE_MIGHTY_CLEAVE); EXPECT_MOVE(opponent, MOVE_TACKLE); item == ITEM_NONE ? EXPECT_SEND_OUT(opponent, 1) : EXPECT_SEND_OUT(opponent, 2); }
+    }
+}
```
Comment (AlexOn1ine) [inline test/battle/ai/ai_switching.c]:
```suggestion
}

```
