### PR TITLE
Follower Object Event refactor

### LINKED ISSUE #5147: Swinub and Piloswine overworld followers have bugged palettes.
### Description

Currently Swinub and Piloswine have palette problems that are hypothesized to be caused by sharing PAL TAGS with weather related stuff as suggested by @SBird1337:

In `field_weather.h`:
```
#define TAG_WEATHER_START 0x1200
enum {
    GFXTAG_CLOUD = TAG_WEATHER_START,
    GFXTAG_FOG_H,
    GFXTAG_ASH,
    GFXTAG_FOG_D,
    GFXTAG_SANDSTORM,
    GFXTAG_BUBBLE,
    GFXTAG_RAIN,
};
enum {
    PALTAG_WEATHER = TAG_WEATHER_START,
    PALTAG_WEATHER_2
};
```
Which causes a screwup in `event_object_movement.c` when calling `LoadDynamicFollowerPalette`, with it mistakenly thinking that the palettes for the overworld mon have already been loaded (as I have understood it).

image
image

Tested on clean latest expansion.

### Version

1.9.0 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

sarnnn

### LINKED ISSUE #5683: OBJ_EVENT_GFX_SPECIES_SHINY does not entirely work
### Description

broken_shiny_OW
This looks like a shiny Unown-K to me.

Strangely, going in a full screen UI and reloading the whole OW displays the correct shiny OW. One thing I know to be broken as well but is not shown in the gif is the shiny OW in a map connection instead of a warp.

Steps to reproduce: add the following OBJ_EVENTS to InsideOfTruck's map.json:
{
      "graphics_id": "OBJ_EVENT_GFX_SPECIES(MAGIKARP)",
      "x": 1,
      "y": 1,
      "elevation": 3,
      "movement_type": "MOVEMENT_TYPE_WALK_IN_PLACE_DOWN",
      "movement_range_x": 0,
      "movement_range_y": 0,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "NULL",
      "flag": "0"
    },
    {
      "graphics_id": "OBJ_EVENT_GFX_SPECIES_SHINY(MAGIKARP)",
      "x": 2,
      "y": 1,
      "elevation": 3,
      "movement_type": "MOVEMENT_TYPE_WALK_IN_PLACE_DOWN",
      "movement_range_x": 0,
      "movement_range_y": 0,
      "trainer_type": "TRAINER_TYPE_NONE",
      "trainer_sight_or_berry_tree_id": "0",
      "script": "NULL",
      "flag": "0"
    }

While trying to fix it, I found a few things that seem strange to me:
- lines 1687 to 1691 are a duplicate of lines 1681 to 1685 in src/event_object_movement.c
- In TrySetupObjectEventSprite, graphicsId is used before checking if shiny and changing value
- #5394 made changes in CreateObjectGraphicsSprite that bring the behavior mentionned in the previous line

### Version

upcoming (Edge)

### Upcoming/master Version

_No response_

### Discord contact info

Nopinou#8678

### PR DESCRIPTION
**Pull request by hedara90**
## Description

Supersedes #6117 
Fixes shiny pokemon object events and adds the possibility to female forms if they exist, also with shiny.
Also fixes the Swinub OW palette tag collision with the weather.
Refactored how follower `graphicsId`s are calculated.
Now they are calculated by taking the species number and adding`1 << 13` to signify that it is an OW follower/object event.
Furthermore the bits `1 << 14` and `1 << 15` are used to signify if is shiny and female.

## Images

pokeemerald-9
pokeemerald-8
pokeemerald-7
pokeemerald-10

## Issue(s) that this PR fixes

Fixes #5683 , fixes #5147 

## **People who collaborated with me in this PR**

@AsparagusEduardo 

## Things to note in the release changelog:

- Fixes `OBJ_EVENT_GFX_SPECIES_SHINY`
- Adds `OBJ_EVENT_GFX_SPECIES_FEMALE` and `OBJ_EVENT_GFX_SPECIES_SHINY_FEMALE`

## **Discord contact info**

hedara

### CODE REVIEW

File: src/event_object_movement.c [hunk 1]
```diff
@@ -1812,13 +1806,20 @@ static void UNUSED MakeSpriteTemplateFromObjectEventTemplate(const struct Object
 
 // Loads information from graphicsId, with shininess separate
 // also can write palette tag to the template
-static u8 LoadDynamicFollowerPaletteFromGraphicsId(u16 graphicsId, bool8 shiny, struct SpriteTemplate *template)
+static u8 LoadDynamicFollowerPaletteFromGraphicsId(u16 graphicsId, struct SpriteTemplate *template)
```
Comment (AlexOn1ine) [inline src/event_object_movement.c:1809]:
```suggestion
static u32 LoadDynamicFollowerPaletteFromGraphicsId(u16 graphicsId, struct SpriteTemplate *template)
```

Comment (AlexOn1ine) [reply src/event_object_movement.c:1809]: not a review

File: src/event_object_movement.c [hunk 2]
```diff
@@ -2024,17 +1979,18 @@ static const struct ObjectEventGraphicsInfo *SpeciesToGraphicsInfo(u16 species,
 }
 
 // Find, or load, the palette for the specified pokemon info
-static u8 LoadDynamicFollowerPalette(u16 species, u8 form, bool32 shiny)
+static u8 LoadDynamicFollowerPalette(u32 species, bool32 shiny, bool32 female)
```
Comment (AlexOn1ine) [inline src/event_object_movement.c:1982]:
```suggestion
static u32 LoadDynamicFollowerPalette(u32 species, bool32 shiny, bool32 female)
```

**Review by AlexOn1ine — APPROVED** [review]
