### PR TITLE
Fix Instruct bypassing AtkCanceler, Entry Hazards targeting wrong side of the field if opponent fainted

### LINKED ISSUE #5259: Sticky web is placed on the wrong side after Explosion / Memento
Seems to be an issue with Hazards because other status moves seem to be fine. 
```
SINGLE_BATTLE_TEST("Sticky Web is placed on the wrong side after Explosion")
{
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_EXPLOSION); MOVE(opponent, MOVE_STICKY_WEB); SEND_OUT(player, 1);}
    } SCENE {
        HP_BAR(player, hp: 0);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_EXPLOSION, player);
        MESSAGE("Wobbuffet fainted!");
        ANIMATION(ANIM_TYPE_MOVE, MOVE_STICKY_WEB, opponent);
        MESSAGE("A sticky web spreads out on the ground around your team!");
   }
}
```
```
SINGLE_BATTLE_TEST("Sticky Web is placed on the wrong side after Memento")
{
    KNOWN_FAILING;
    GIVEN {
        PLAYER(SPECIES_WOBBUFFET);
        PLAYER(SPECIES_WOBBUFFET);
        OPPONENT(SPECIES_WOBBUFFET);
    } WHEN {
        TURN { MOVE(player, MOVE_MEMENTO); MOVE(opponent, MOVE_STICKY_WEB); SEND_OUT(player, 1); }
    } SCENE {
        HP_BAR(player, hp: 0);
        ANIMATION(ANIM_TYPE_MOVE, MOVE_MEMENTO, player);
        MESSAGE("Wobbuffet fainted!");
        ANIMATION(ANIM_TYPE_MOVE, MOVE_STICKY_WEB, opponent);
        MESSAGE("A sticky web spreads out on the ground around your team!");
    }
}
```

### Version

1.9.1 (Latest release)

### Upcoming/master Version

_No response_

### Discord contact info

_No response_

### PR DESCRIPTION
**Pull request by PhallenTree**
Fixes Instruct bypassing AtkCanceler checks (Instruct allowed the target to act while asleep, flinched, etc.) and its interaction with First Turn Only moves (Fake Out, First Impression, Mat Block). Also fixes Instruct's animation using the attacker and target of the called move.
Added some Instruct tests to confirm some interactions such as:

> A Pokémon can successfully be instructed to repeat a move when under the effect of [Torment](https://bulbapedia.bulbagarden.net/wiki/Torment_(move)) or to use a [status move](https://bulbapedia.bulbagarden.net/wiki/Status_move) while holding an [Assault Vest](https://bulbapedia.bulbagarden.net/wiki/Assault_Vest). When instructed to use [Fake Out](https://bulbapedia.bulbagarden.net/wiki/Fake_Out_(move)), [Mat Block](https://bulbapedia.bulbagarden.net/wiki/Mat_Block_(move)), or [First Impression](https://bulbapedia.bulbagarden.net/wiki/First_Impression_(move)), the target will attempt to use the move and PP will be deducted from it, but the move will fail. When instructed to use a move that would be prevented by [Disable](https://bulbapedia.bulbagarden.net/wiki/Disable_(move)), [Heal Block](https://bulbapedia.bulbagarden.net/wiki/Heal_Block_(move)), [Gravity](https://bulbapedia.bulbagarden.net/wiki/Gravity_(move)), [Throat Chop](https://bulbapedia.bulbagarden.net/wiki/Throat_Chop_(move)), [Taunt](https://bulbapedia.bulbagarden.net/wiki/Taunt_(move)), or [Imprison](https://bulbapedia.bulbagarden.net/wiki/Imprison_(move)), the target will attempt to use it, but the move will fail without PP being deducted.
> 
> The instructed move will target the same Pokémon slot as the previously used move, as long as a Pokémon is present in that slot.
> 
> Instructed moves retain their original priority, regardless of the priority of Instruct - for example, Quick Attack still fails in Psychic Terrain when Instruct is used at 0 priority to call it.

Fixes Entry Hazards being setup on the wrong side of the field if the opponent fainted before the entry hazards being setup (happened because it would cause it to target `battler = 2` or `battler = 3` in Singles)
Added the 2 tests from #5259.

Removes unused `BattleScript_AuroraVeilEnds` and `STRINGID_AURORAVEILENDS` (Aurora Veil uses `BattleScript_SideStatusWoreOff`)

## Issue(s) that this PR fixes
Fixes #5259 

## **Discord contact info**
PhallenTree

### CODE REVIEW

File: src/battle_util.c [hunk 1]
```diff
@@ -8304,7 +8304,7 @@ u32 GetMoveTarget(u16 move, u8 setTarget)
     case MOVE_TARGET_FOES_AND_ALLY:
     case MOVE_TARGET_OPPONENTS_FIELD:
         targetBattler = GetBattlerAtPosition(BATTLE_OPPOSITE(GetBattlerSide(gBattlerAttacker)));
-        if (!IsBattlerAlive(targetBattler))
+        if (!IsBattlerAlive(targetBattler) && gBattleTypeFlags & BATTLE_TYPE_DOUBLE)
             targetBattler ^= BIT_FLANK;
```
Comment (AlexOn1ine) [inline src/battle_util.c:8308]: how does this fix the hazard situation? Also wouldn't it be better to remove the battler check for `MOVE_TARGET_OPPONENTS_FIELD` since it targets the side?

Comment (PhallenTree) [reply src/battle_util.c]: The function `NoTargetPresent` (present in `attackcanceler`) was causing the issue. Since the target was not alive, it would try to redirect the move to the target's partner, which didn't exist in singles. Can't figure out why having a `gBattlerTarget = 2` would make it target its own side of the field, but it did.

For comparison, here's the current interaction: (the unlabeled parts are the start of `NoTargetPresent` and immediately after the check for the target not being alive)

pre_fix

And here's the fixed interaction: (I also needed to fix another part where it initially set the target to 2)

with_fix

I initially left the check in for `MOVE_TARGET_OPPONENTS_FIELD` since I thought it might affect the animation played, but now it doesn't check if the target is alive.

Comment (AlexOn1ine) [reply src/battle_util.c]: thx, I like the second fix more.

File: test/battle/move_effect/instruct.c [hunk 2]
```diff
@@ -0,0 +1,217 @@
...
+        OPPONENT(SPECIES_WOBBUFFET);
+        OPPONENT(SPECIES_WOBBUFFET);
+    } WHEN {
+        TURN { MOVE(playerRight, MOVE_TACKLE, target: opponentLeft); MOVE(playerLeft, MOVE_INSTRUCT, target: playerRight); }
+    } SCENE {
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerRight);
+        HP_BAR(opponentLeft);
+        NOT HP_BAR(opponentRight);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_INSTRUCT, playerRight);
+        ANIMATION(ANIM_TYPE_MOVE, MOVE_TACKLE, playerRight);
```
Comment (AlexOn1ine) [inline test/battle/move_effect/instruct.c:54]: I might be misunderstanding instruct but is it coming from `playerRight` and not `playerLeft` as specified in `TURN`?

Comment (PhallenTree) [reply test/battle/move_effect/instruct.c:54]: That's because `tryinstruct` occurs before the animation and changes the attacker and target to be that of the move called. I can make it so it actually comes from the one using the move if that's better

Comment (AlexOn1ine) [reply test/battle/move_effect/instruct.c:54]: Do you know how this is handled in vanilla?

Comment (PhallenTree) [reply test/battle/move_effect/instruct.c:54]: No I don't. My change was just gonna be: save the attacker, change the attacker to be the user of Instruct, play the move's animation, restore the attacker

Comment (AlexOn1ine) [reply test/battle/move_effect/instruct.c:54]: ye, then I would do the change since it is simple enough and avoids confusion.

Comment (AlexOn1ine) [reply test/battle/move_effect/instruct.c:54]: ye seems logical

File: src/battle_script_commands.c [hunk 3]
```diff
@@ -9957,22 +9957,22 @@ static void Cmd_various(void)
         else
         {
             gSpecialStatuses[gBattlerTarget].instructedChosenTarget = *(gBattleStruct->moveTarget + gBattlerTarget) | 0x4;
-            gBattlerAttacker = gBattlerTarget;
+            gBattleStruct->savedBattlerAttacker[gBattleStruct->savedAttackerCount++] = gBattlerTarget;
```
Comment (AlexOn1ine) [inline src/battle_script_commands.c:9960]: is it possible to stare attacker and target in the script before attackcancler?

File: data/battle_scripts_1.s [hunk 4]
```diff
@@ -1749,6 +1749,7 @@ BattleScript_CopycatFail:
 	ppreduce
 	goto BattleScript_ButItFailed
 
+@ restoreattacker and restoretarget are used to obtain attacker and target of the called move
```
Comment (AlexOn1ine) [inline data/battle_scripts_1.s:1752]: The comment is probably redundant since the tests already will avoid a regression.

File: src/battle_script_commands.c (hunk 3 above)
Comment (PhallenTree) [reply src/battle_script_commands.c]: I have an alternative that uses gEffectBattler instead of saving and restoring attacker/target, as long as that doesn't cause any problems

**Review by AlexOn1ine — APPROVED** [review]
Looks good!
